#!/usr/bin/env python3
"""Code-generator for ``c/src/srmech_class_registry.c`` (0.9.0rc202).

The NAME -> DESCRIPTOR resolve gate for ``srmech_run_class_method``: emit the
packaged ``[class]`` TOML descriptors (``srmech/cascade/catalogs/class_catalog/
*.toml``) as a ``const`` C data table so a bare-C host (no Python, no host-FS)
can resolve a class NAME (e.g. ``"Genome"``) to its descriptor text and run the
rc201 ``srmech_make_class_run`` object-model engine on it.

Why compiled-in (option b, the rc184 ``gen_tool_registry.py`` model): the four
shipped descriptors are static SSoT DATA, exactly like the tool registry. A
bare-C host needs the descriptor bytes with no interpreter and no filesystem, so
the cleanest C-honest resolve is a bounded compiled-in NAME->bytes table. (The
rc172 catalog-C registry indexes ATTESTED ROOTS, a different object; a host-FS
read would push the resolve LOGIC out of C — both rejected.) A ``register_class_
dir`` USER class is NOT compiled in: ``srmech_run_class_method`` returns
``NULL`` for an unknown name and the caller runs the pure ``run_class_method``
(rc103 inform-don't-limit; the engine already defers user classes anyway).

Determinism / order
-------------------
Descriptors are emitted sorted by ``[class].name`` (the same order
``srmech.dsl.list_classes`` yields), so the generated table is stable and the
idempotence guard (re-run -> no diff) holds.

Line endings
------------
Each descriptor is read with universal newlines and re-encoded UTF-8 with ``\n``
line terminators (the repo's canonical / CI-checkout form), so the baked bytes
are identical regardless of the dev machine's autocrlf setting. The engine
output is newline-independent (it emits method results + field state, never the
descriptor's ``doc``), so this is a determinism choice, not a correctness one.

Regenerate (rc346, `#T975` — DO NOT run this script by hand)::

    python3 tools/regen_all.py          # from docs/srmech/python

This is the one registry generator with NO srmech import at all — it reads
only the packaged ``[class]`` TOML bytes, so no tool-surface change can
stale it (verified at rc346: adding, editing and renaming ops all left its
output byte-identical). It still runs in the ordered pass because it is a
generated shipped file and ``--check`` must be able to answer "is this
stale?" for every such file, not for a remembered subset. Its declared
``consumes=(class_catalog_toml,)`` carries no inbound edge, so the topo
sort is free to place it anywhere; it lands last.

An idempotence test (re-run -> no diff) guards drift.
"""

from __future__ import annotations

import sys
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib as _toml
else:  # pragma: no cover — 3.10 dev-time generation
    import tomli as _toml  # type: ignore[no-redef]


def _class_name(toml_bytes: bytes, path: Path) -> str:
    """The ``[class].name`` of a packaged descriptor (the resolve KEY)."""
    desc = _toml.loads(toml_bytes.decode("utf-8"))
    section = desc.get("class")
    if not isinstance(section, dict) or not section.get("name"):
        raise ValueError(f"{path} is missing [class].name")
    return str(section["name"])


def _byte_array(ident: str, data: bytes) -> str:
    """A ``static const unsigned char ident[] = {...,0};`` brace-initialiser (a
    char array, NOT a string literal, so -Woverlength-strings never applies).
    NUL-terminated for defensive C string use; the table records the exact
    length EXCLUDING the NUL."""
    body = list(data) + [0]
    rows = []
    for off in range(0, len(body), 20):
        rows.append("    " + ", ".join(str(b) for b in body[off:off + 20]) + ",")
    return (f"static const unsigned char {ident}[] = {{\n"
            + "\n".join(rows) + "\n};")


def generate() -> str:
    here = Path(__file__).resolve()
    catalog_dir = (here.parent.parent.parent / "python" / "srmech"
                   / "cascade" / "catalogs" / "class_catalog")
    if not catalog_dir.is_dir():
        raise FileNotFoundError(f"class_catalog dir not found at {catalog_dir}")

    entries = []  # (name, lf_bytes)
    for toml_path in sorted(catalog_dir.glob("*.toml")):
        # Universal-newline read -> re-encode LF (the canonical / CI form).
        text = toml_path.read_text(encoding="utf-8")  # newline=None normalises
        lf_bytes = text.encode("utf-8")
        name = _class_name(lf_bytes, toml_path)
        entries.append((name, lf_bytes))
    entries.sort(key=lambda e: e[0])

    out = []
    w = out.append
    w("/* srmech_class_registry.c - GENERATED by c/tools/gen_class_registry.py.")
    w(" * DO NOT EDIT BY HAND. Regenerate with:")
    w(" *   python3 tools/regen_all.py            (from docs/srmech/python)")
    w(" *")
    w(" * rc347: this line named the raw generator plus a `>` redirect, which was")
    w(" * exactly trap 2 the runner removed - forget the redirect and the table")
    w(" * goes to the terminal, nothing changes, exit 0. The runner also fixes the")
    w(" * ORDER this file depends on. rc346 left it stale on purpose to keep its")
    w(" * own zero-delta signal clean; rc347 already moves these bytes.")
    w(" *")
    w(" * Source of truth: the .toml descriptors under")
    w(" * srmech/cascade/catalogs/class_catalog/ (the packaged DSL [class] descriptors).")
    w(" * The 0.9.0rc203 NAME->DESCRIPTOR resolve gate for")
    w(" * srmech_run_class_method - the shipped descriptors as a const data table so")
    w(" * a bare-C host resolves a class NAME to its descriptor text with no Python")
    w(" * and no filesystem (JPL-clean: const arrays, no dynamic init, no malloc).")
    w(" * The lookup accessor lives in srmech_make_class.c.")
    w(" *")
    w(f" * TOML-declared classes: {len(entries)} "
      f"({', '.join(n for n, _ in entries)}).")
    w(" *")
    # ASCII-ONLY: test_class_registry_codegen_rc202 pins the generated .c to
    # pure ASCII (MSVC-safe under /WX). No em-dashes, no smart quotes.
    w(" * This is the [class] DESCRIPTOR table, not srmech's class count.")
    w(" * rc298 (task 936) made describe()['classes'] capability-first, so it")
    w(" * reports MORE than this: a hand-coded domain class (CDRegister) has")
    w(" * no descriptor text to bake here, and reaches a bare-C host through")
    w(" * its own peers rather than through srmech_run_class_method. A NULL")
    w(" * from srmech_class_descriptor_lookup for such a name is correct,")
    w(" * not a gap.")
    w(" */")
    w("")
    w('#include "srmech.h"')
    w("")
    for idx, (_name, data) in enumerate(entries):
        w(_byte_array(f"cls_desc_{idx}", data))
    w("")
    w("const srmech_class_descriptor_t srmech_class_registry_table[] = {")
    for idx, (name, data) in enumerate(entries):
        # name is a [class].name — always a short ASCII bare identifier.
        w(f'    {{ "{name}", (const char *)cls_desc_{idx}, {len(data)}u }},')
    w("};")
    w("")
    w("const size_t srmech_class_registry_len =")
    w("    sizeof(srmech_class_registry_table) "
      "/ sizeof(srmech_class_registry_table[0]);")
    w("")
    return "\n".join(out)


if __name__ == "__main__":
    sys.path.insert(
        0, str(Path(__file__).resolve().parents[2] / "python" / "tools"))
    from codegen_manifest import require_regen_all

    require_regen_all("gen_class_registry")
    sys.stdout.write(generate())
