""".mcpb (Claude Desktop MCP Bundle) emitter — built ENTIRELY from
srmech introspection. No hand-authored manifest, no hardcoded version /
tool-list / interpreter path.

Spec: anthropics/mcpb MANIFEST.md (server.type ``uv | python | node |
binary``; a ``.mcpb`` IS a ZIP archive whose ROOT carries
``manifest.json``). The ``uv`` server.type is the spec's own recommended
answer for a package that "cannot portably bundle compiled dependencies":
at install time the host runs ``uv`` against the bundled
``pyproject.toml`` and resolves ``srmech`` from PyPI, pulling the correct
platform wheel (with the compiled ``libsrmech.{so,dll,dylib}`` inside) —
nothing native is bundled in the ``.mcpb`` itself. A ``python`` fallback
(``user_config``-gated interpreter path) is kept for hosts without uv.

Framework reading: Class F (render srmech's own shape to the Claude
Desktop substrate-class) ∘ Class E (catalog enumeration of the advertised
tool surface) ∘ Class A (content-addressing the tool_schema via
``sha256_bytes`` for the MPR attestation block) ∘ Class H
(self-introspection — the package describing its own callable shape).
"""

from __future__ import annotations

import datetime
import json
import zipfile
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional


# ──────────────────────────────────────────────────────────────────────
# Module constants
# ──────────────────────────────────────────────────────────────────────

_MANIFEST_VERSION = "0.4"
"""The ``.mcpb`` manifest SCHEMA revision (the spec example value) — NOT
srmech's own version. Deliberately decoupled: ``manifest_version`` tracks
the anthropics/mcpb format; ``version`` (below) tracks ``srmech.__version__``."""

_DEFAULT_NAME = "srmech"
_SERVER_ENTRY_POINT = "server/main.py"

# The bundled entry-point shim. Defaults to stdio transport (``main([])``
# ignores process argv) — exactly what Claude Desktop spawns.
_SERVER_SHIM = (
    "# Generated by `srmech mcp emit-mcpb`.\n"
    "from srmech.mcp._cli import main\n"
    "raise SystemExit(main([]))\n"
)


# ──────────────────────────────────────────────────────────────────────
# Private helpers
# ──────────────────────────────────────────────────────────────────────


def _utc_now_iso() -> str:
    """MPR ``retrieved_at``-style UTC stamp (``...Z``, second-resolution).

    Uses ``datetime.timezone.utc`` (3.10-safe; ``datetime.UTC`` is 3.11+,
    but ``requires-python`` is ``>=3.10``)."""
    return (
        datetime.datetime.now(datetime.timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def _advertised_tool_defs(
    *, name_filter: Optional[Callable[[str], bool]] = None
) -> List[Dict[str, Any]]:
    """The SSoT ADVERTISED tool surface (honours ``mcp_callable`` +
    ``--filter``) as a concrete list."""
    from ._tools import tool_entries_to_mcp_defs

    return list(tool_entries_to_mcp_defs(name_filter=name_filter))


def _tool_schema_hash() -> str:
    """Content-address the FULL declared tool schema (stable, sorted)
    via :func:`srmech.amsc.format.sha256_bytes` — the AMSC attestation
    hash. Routes native dispatch; no new ``hashlib.sha256`` call."""
    from ..amsc.format import sha256_bytes
    from ..amsc.tool_schema import get_tool_schema

    schema = get_tool_schema()
    payload = json.dumps(
        schema.to_jsonable(), sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return sha256_bytes(payload)  # 64 lowercase hex


def _server_block(server_type: str) -> Dict[str, Any]:
    """The ``server`` object for the chosen ``server_type``.

    ``uv`` — host runs ``uv`` against the bundled ``pyproject.toml``;
    ``mcp_config`` is OPTIONAL for uv, so it is omitted (no baked command,
    no baked interpreter). ``python`` — a ``user_config``-gated interpreter
    invokes ``-m srmech.mcp._cli``."""
    if server_type == "uv":
        return {"type": "uv", "entry_point": _SERVER_ENTRY_POINT}
    if server_type == "python":
        return {
            "type": "python",
            "entry_point": _SERVER_ENTRY_POINT,
            "mcp_config": {
                "command": "${user_config.python_path}",
                "args": ["-m", "srmech.mcp._cli"],
                "env": {},
            },
        }
    raise ValueError(
        f"unsupported server_type {server_type!r}; expected 'uv' or 'python'"
    )


def _user_config_block(server_type: str) -> Optional[Dict[str, Any]]:
    """The ``user_config`` block — only the ``python`` fallback needs one
    (the interpreter path). ``uv`` returns ``None`` (host manages
    Python)."""
    if server_type != "python":
        return None
    return {
        "python_path": {
            "type": "string",
            "title": "Python interpreter",
            "description": (
                "Path to a Python (>=3.10) interpreter with `srmech` "
                "installed (pip install srmech). uv-type bundles avoid "
                "this; use python-type only when uv is unavailable."
            ),
            "required": True,
            "default": "python3",
        }
    }


def _bundle_pyproject_toml() -> str:
    """Minimal ``[project]`` whose only dependency is ``srmech`` pinned to
    the emitting ``__version__`` — so ``uv`` resolves the exact platform
    wheel that carries ``libsrmech`` at install time. Version DERIVED, not
    hardcoded."""
    from ..version import __version__ as srmech_version

    return (
        "[project]\n"
        'name = "srmech-mcpb-runner"\n'
        'version = "0.0.0"\n'
        'requires-python = ">=3.10"\n'
        f'dependencies = ["srmech=={srmech_version}"]\n'
    )


# ──────────────────────────────────────────────────────────────────────
# Public: build_manifest
# ──────────────────────────────────────────────────────────────────────


def build_manifest(
    *,
    name: str = _DEFAULT_NAME,
    server_type: str = "uv",
    name_filter: Optional[Callable[[str], bool]] = None,
) -> Dict[str, Any]:
    """Build the ``.mcpb`` ``manifest.json`` dict ENTIRELY from srmech
    introspection.

    ``version`` is ``srmech.__version__`` (never a literal); ``tools[]``
    is built from the ADVERTISED tool surface (``mcp_callable`` subset,
    honouring ``name_filter``), so a future handle-pending tool cannot
    silently desync the manifest. A srmech-extension ``attestation`` block
    (MPR-style) carries the version + a content hash of the full tool
    schema (the MPM crystallisation per CLAUDE.md §2).

    Parameters
    ----------
    name
        Bundle + server name (default ``srmech``).
    server_type
        ``"uv"`` (default; host fetches the platform wheel via uv) or
        ``"python"`` (``user_config``-gated interpreter fallback).
    name_filter
        Optional ``str -> bool`` predicate; only matching tool names are
        advertised. Wired to the ``--filter`` CLI flag.
    """
    assert server_type in ("uv", "python"), (
        "server_type must be 'uv' or 'python'"
    )
    from ..version import __version__ as srmech_version
    from ..amsc.tool_schema import get_tool_schema

    defs = _advertised_tool_defs(name_filter=name_filter)

    manifest: Dict[str, Any] = {
        "manifest_version": _MANIFEST_VERSION,
        "name": name,
        "version": srmech_version,  # DERIVED — never a literal
        "description": (
            "srmech (Stored-Relationship Mechanism) MCP server — exposes "
            f"{len(defs)} attested AMSC/QM cascade tools (14-class A-N "
            "vocabulary) to Claude Desktop. Each tools/call carries an "
            "MPR attestation block."
        ),
        "author": {
            "name": "Steven Kirkland",
            "url": "https://github.com/lemonforest/mlehaptics",
        },
        "homepage": (
            "https://github.com/lemonforest/mlehaptics/tree/main/docs/"
            "srmech/python"
        ),
        "documentation": (
            "https://github.com/lemonforest/mlehaptics/blob/main/docs/"
            "srmech/srmech_research_notebook.md"
        ),
        "license": "GPL-3.0-or-later",
        "keywords": ["mcp", "srmech", "spectral", "amsc", "cascade"],
        "server": _server_block(server_type),
        # tools[] element = {name (required), description (optional)} per
        # spec; built from the ADVERTISED iterator, not a frozen literal.
        "tools": [
            {"name": d["name"], "description": d["description"]} for d in defs
        ],
        # srmech advertises its FULL set statically -> false.
        "tools_generated": False,
        "compatibility": {
            "claude_desktop": ">=0.10.0",
            "platforms": ["darwin", "win32", "linux"],
            "runtimes": {"python": ">=3.10"},
        },
        # srmech EXTENSION top-level key — the MPM crystallisation. The
        # spec is permissive (all non-required top-level fields optional);
        # Claude Desktop ignores unknown keys.
        "attestation": {
            "mpr_version": "1.0",
            "srmech_version": srmech_version,
            "tool_schema_version": get_tool_schema().tool_schema_version,
            "tool_count": len(defs),
            "tool_schema_sha256": _tool_schema_hash(),  # 64-hex
            "parser_version": f"srmech {srmech_version}",
            "generated_at": _utc_now_iso(),
            "generator": "srmech mcp emit-mcpb",
        },
    }
    uc = _user_config_block(server_type)
    if uc is not None:
        manifest["user_config"] = uc
    return manifest


# ──────────────────────────────────────────────────────────────────────
# Public: pack_mcpb
# ──────────────────────────────────────────────────────────────────────


def pack_mcpb(
    out_dir: str = ".",
    *,
    name: str = _DEFAULT_NAME,
    server_type: str = "uv",
    manifest_only: bool = False,
    name_filter: Optional[Callable[[str], bool]] = None,
) -> Path:
    """Write ``manifest.json`` and (unless ``manifest_only``) pack a
    ``<name>.mcpb`` ZIP into ``out_dir``.

    The ``.mcpb`` is a stdlib-``zipfile`` ZIP whose ROOT carries
    ``manifest.json`` (required), plus ``pyproject.toml`` (uv reads it to
    resolve the platform wheel that carries ``libsrmech``) and
    ``server/main.py`` (the ``entry_point`` shim). No Node / mcpb
    toolchain is required.

    Returns the ABSOLUTE :class:`~pathlib.Path` of the written artifact
    (the ``.mcpb`` normally; ``manifest.json`` when ``manifest_only``)."""
    out = Path(out_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)

    manifest = build_manifest(
        name=name, server_type=server_type, name_filter=name_filter
    )
    manifest_bytes = (
        json.dumps(manifest, indent=2, sort_keys=False) + "\n"
    ).encode("utf-8")
    manifest_path = out / "manifest.json"
    manifest_path.write_bytes(manifest_bytes)
    if manifest_only:
        return manifest_path.resolve()

    pyproject_bytes = _bundle_pyproject_toml().encode("utf-8")
    shim_bytes = _SERVER_SHIM.encode("utf-8")
    mcpb_path = out / f"{name}.mcpb"
    with zipfile.ZipFile(
        mcpb_path, "w", compression=zipfile.ZIP_DEFLATED
    ) as zf:
        zf.writestr("manifest.json", manifest_bytes)  # ROOT — REQUIRED
        zf.writestr("pyproject.toml", pyproject_bytes)
        zf.writestr("server/main.py", shim_bytes)  # entry_point
    return mcpb_path.resolve()


__all__ = ["build_manifest", "pack_mcpb"]
