"""_tool_docs_curated.py — HAND-CURATED introspection docs for the
central ops (rc240 #838). Merged OVER the docstring-seeded floor by
tools/gen_tool_docs.py (curation wins). Every EXAMPLE here is a REAL
executed result (probed by tools/gen_curated_probe.py), never typed.

THIS is the file to hand-edit. ``_tool_docs.py`` is GENERATED —
text written there is destroyed by the next tools/gen_tool_docs.py
run, which is what happened to the genome/plasmid explanations
between rc274 and rc290 (rc291 migrated them here). The generator
now refuses to write when it would clobber prose it cannot
re-derive from a docstring, so that failure mode is loud."""
from __future__ import annotations

from typing import Any, Dict

CURATED: Dict[str, Dict[str, Any]] = {
    "srmech.amsc.cascade.magnitude": {"example": {"input": {"x": "-3.5"}, "output": "3.5"}, "explanation": "The Class-K real pin-slot magnitude |x| — the cascade-honest replacement for Python abs(): a sign-branch phase-boundary op, NOT a complex modulus (it rejects complex input by contract)."},
    "srmech.amsc.cascade.net_chirality": {"example": {"input": {"orientations": "[1, -1, 1, 1]"}, "output": "-1"}, "explanation": "Class-C net chirality: the signed product/sum reduction of a sequence of per-step orientations into the one net which-way handedness."},
    "srmech.amsc.cascade.pin_slot_at_zero": {"example": {"input": {"x": "-3.5"}, "output": "(-1, 3.5)"}, "explanation": "The Class-K pin-slot at zero: splits x into its sign (the pinned phase boundary, −1/0/+1) and its magnitude — the primitive |·| composes from."},
    "srmech.amsc.cascade.the_one": {"example": {"input": {"sigma": "1", "theta_den": "4", "theta_num": "1", "w": "(1, 0, 1)"}, "output": "One(sigma=+1, theta=(1, 4), terms=24, dim=14, partition=(1, 3, 7, 3), winding=(1, 0, 1))"}, "explanation": "The One S(σ,θ,w) = ⨁(ℝ·1 ⊕ σ·e^{Î·θ}·Im 𝔸ₙ) over the 1+3+7 Hurwitz tower (dim 2+4+8=14). σ is chirality, (θ_num/θ_den) the epicycle angle, and the winding triad w = (Saros, Metonic, Callippic) carries the spinor sign (−1)^Σw + the metacycle tower — the object whose two chiralities are one."},
    "srmech.amsc.cyclic.gcd": {"example": {"input": {"a": "12", "b": "18"}, "output": "6"}},
    "srmech.amsc.cyclic.mod_pow": {"example": {"input": {"a": "7", "k": "13", "n": "11"}, "output": "2"}, "explanation": "Modular exponentiation a^k mod n by square-and-multiply (Class-I cyclic group). Exact; the Fermat/RSA-style fast power on ℤ/n."},
    "srmech.amsc.format.sha256_bytes": {"example": {"input": {"data": "b'abc'"}, "output": "'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'"}},
    "srmech.amsc.genome.accessible": {"explanation": "The COMPUTED accessibility level (num, den) of a chromosome under cell_state (§98.1/G1) — the chromatin-scale op⊗operand: the SAME genome under a DIFFERENT cell_state reads a DIFFERENT accessible level (facultative heterochromatin — the Barr body / X-inactivation). A CONSTITUTIVE cap is constant in cell_state; a FACULTATIVE cap (set via condense(state={'activator':..}/{'dnf':..}/{'weights':..})) reads its when-open level iff its gate FIRES, else (0, 1); a chromatin-free strand reads (1, 1). num > 0 is open (Class-K). A READ; never mutates. Native-dispatched (srmech_genome_chromatin_access)."},
    "srmech.amsc.genome.amplify": {"explanation": "Set a gene's COPY NUMBER (multiplicity) to ``n`` — the IS26-amplification analog (§135/rc273 / F1251). Records the count on the named plain gene's 0x47 cap (in what was NUL padding, transparent to every reader); n==1 is byte-identical to a plain gene, n>=2 spends a uint64 field; format 15 stays. C-dispatched since rc281 (srmech_genome_amplify) — a bare-C host can WRITE the axis, not just ignore it. Read back with copy_number_of."},
    "srmech.amsc.genome.chromatin_of": {"explanation": "Recover a chromosome's FIRST chromatin ACCESS state (§98) — {type, state, level (num, den), handle, at, scope} — or ``None`` if it carries no chromatin marker (an all-euchromatin, fully-accessible chromosome; the default). A READ; never mutates."},
    "srmech.amsc.genome.condense": {"explanation": "CONDENSE a region — SET the chromatin ACCESS marker (0x48) on an EXISTING chromosome IN-PLACE (§98 / F1246-F1247); a byte-splice preserving the centromere + body (no re-mint). state True/'condensed' silences, False/'open' opens, a (num, den) is a graded level; region=None is whole-chromosome (head), an int / gene-label is an interior stretch."},
    "srmech.amsc.genome.copy_number_of": {"explanation": "Read a gene's COPY NUMBER (multiplicity) — the reader companion to amplify (§135/rc273 / F1251). Returns the amplified count, or 1 (present-once) for a plain / un-amplified / pre-rc273 gene (back-compat). A READ; never mutates. C-dispatched since rc281 (srmech_genome_copy_number)."},
    "srmech.amsc.genome.cwf_consistency_mod2": {"explanation": "rc313 — the mod-2 Calugareanu-White-Fuller check on a strand: Lk == Tw + Wr (mod 2). Lk = the intrinsic center-parity holonomy (rc309, quaternion_cycle_holonomy over the Q8 gains); Tw = the Q8 negative-coset SIGN-accumulation parity; Wr = the directional writhe from the supplied GEOMETRY (discrete_writhe), NEVER Lk-Tw — so the writhe supplies the non-abelian Q8 cocycle (i.i=-1) the per-turn sign-sum Tw misses. HONEST: a finite group pins Lk only MOD 2, not the integer Gauss Lk; the Tw<->Q8 map is unpinned at integer level (parity only). No embedding -> intrinsic mod-2 Lk only (no fabricated Wr).", "composes": ["srmech.amsc.genome.discrete_writhe", "srmech.qm.quaternion.quaternion_cycle_holonomy"], "preserves": ["Wr is computed from geometry (discrete_writhe), never defined as Lk-Tw — a real independent check", "mod-2 only: Q8 pins Lk to its center-parity, not the unbounded integer linking number", "no-embedding path returns only the intrinsic mod-2 Lk; no Wr is fabricated"]},
    "srmech.amsc.genome.discrete_writhe": {"explanation": "rc313 — the EXACT-rational DIRECTIONAL discrete writhe of a polygonal backbone: the signed CROSSING-number double-sum over non-adjacent segment pairs in the z-drop projection (eps = sign of the scalar triple product (B-A).((D-C)x(C-A)), an exact INTEGER determinant over srmech_bigint; native==pure byte-identical). Each vertex is an exact rational (int / Fraction / (num,den)). NOT the transcendental smooth solid-angle Gauss writhe — that is this integer averaged over the direction sphere; the mod-2 CWF check uses only the PARITY. No float, no libm, no abs() (sign is Class K . Class C)."},
    "srmech.amsc.genome.decondense": {"explanation": "DECONDENSE — CLEAR the chromatin ACCESS marker(s), the inverse of condense (§98); splices out every 0x48 cap, preserving the centromere + body (a condensed-then-decondensed nuclear chromosome is byte-identical to the original mint)."},
    "srmech.amsc.genome.genome_catalog": {"explanation": "Read the catalog of a genome at ``path`` — UPSTREAM §41 / §44 (per-chromosome cap_kind since §96)."},
    "srmech.amsc.genome.genome_census": {"explanation": "Census ONE genome — the §96 per-genome roll-up {path, n_chromosomes, types (plasmid/nuclear/diploid), chromosomes, total_leaves, topology}; a thin roll-up over genome_catalog's §96 cap_kind (rc271 F1251: plasmid was 'stick', nuclear was 'minted')."},
    "srmech.amsc.genome.genome_from_graph": {"explanation": "BUILD a multi-chromosome genome from a directed graph, PARTITIONED BY ITS OWN STRUCTURE (§100 GAP 2 / PR#687 / F1250 / F1251) — 'hand a graph, get nuclear + plasmid from its structure'. Runs :func:`genome_partition`, then MINTS each nuclear community (:func:`mint_strand` -> a 0x58 centromere) and KEEPS each plasmid community as a Tier-1 plasmid chromosome; if ``path`` is given, ``genome_save`` + ``genome_census`` report the measured ``{nuclear, plasmid}``. BYTE-EXACT per community (:func:`kernel_to_graph` recovers each induced sub-graph). numpy-free; no ``abs()``.", "composes": ["srmech.amsc.genome.genome_partition", "srmech.amsc.genome.graph_to_kernel", "srmech.amsc.genome.mint_strand", "srmech.amsc.genome.genome_save", "srmech.amsc.genome.genome_census"], "preserves": ["byte-exact per-community round-trip: kernel_to_graph on any chromosome (with its n_syms) recovers that community's induced sub-graph exactly (§44 interior-centromere skip-on-read)", "measured {nuclear, plasmid} counts equal genome_partition's classification", "numpy-free; no abs() — sign-handling stays Class-K pin-slot + Class-C"]},
    "srmech.amsc.genome.genome_partition": {"explanation": "PARTITION a directed relational GRAPH into nuclear-core vs plasmid-periphery BY ITS OWN STRUCTURE (§100 GAP 2 / PR#687 / F1250 / F1251). An introspectable READ (builds nothing): runs the out-of-core spectral community partition (:func:`~srmech.amsc.laplacian.recursive_cut`), measures each node's degree-normalized PARTICIPATION (fraction of incident edge-mass that crosses a community boundary — HIGH = plasmid/mobile accessory, LOW = nuclear/embedded core), then MEASURES the antimode: BIMODAL -> split nuclear (low) + plasmid (high), asymmetric minority-nuclear (F1251); UNIMODAL -> ACCEPT ONE-DNA-TYPE, no forced split (F1250). Composes the C-dispatched recursive_cut with a pure exact-integer participation + antimode read (native==pure); numpy-free, no ``abs()``."},
    "srmech.amsc.genome.genome_registry": {"explanation": "Census a ROOT of genomes — the §96 cell/melange census {root, n_genomes, genomes:[census, …]}, sorted by name (the nucleus-vs-organelle read over a directory of genomes)."},
    "srmech.amsc.genome.integrate": {"explanation": "Integrate a PROVIRUS (a chromosome strand) INTO a host genome-strand — the viral-integration analog (§95.1d / F1244 / #1407), the coherency-translation-layer capstone. §135/rc273 (F1251): a COMPATIBILITY GATE checks host<->provirus coherence (default: equal coupling width == same the_one) BEFORE splicing and HONEST-DECLINES on incompatibility (returns None, host unchanged — the CG258 segregated-replicon analog); Python callers may also pass a compatible=(host, provirus)->bool hook for a domain lineage barrier (an in-process affordance, not an MCP wire param — a callable can't cross JSON-RPC). A compatible provirus integrates exactly as rc262. rc276 (#891 / G4): the SPLICE has a direct C peer srmech_genome_integrate (the stage-2 primitive) — a bare-C host integrates end-to-end, and when HAS_NATIVE this dispatches the splice to it (byte-identical native or pure); the compatible= hook stays Python-only."},
    "srmech.amsc.genome.mint_strand": {"explanation": "MINT an ALREADY-PACKED strand — splice a §95a interior CENTROMERE (``0x58``) into it at the p:q arm-split, turning a Tier-1 STICK into a Tier-2 MINTED chromosome (§100 GAP 1 / PR#687 F1249)."},
    "srmech.amsc.genome.plasmid": {"explanation": "Pack many kernels into ONE telomere-partitioned strand of pure STICK chromosomes — biology's plasmid (F715; the rc260 rename of the old ``genome``, §95.2 / #1407)."},
    "srmech.amsc.hdc.bind": {"example": {"input": {"a": "b'abc'", "b": "b'abc'"}, "output": "b'\\x00\\x00\\x00'"}, "explanation": "Component-wise XOR of two binary-spatter-code (BSC) hypervectors — the Class-M bind that ties a role to a filler; self-inverse (bind(x,x)=0). F1216: Class-M / HDC = WORKING MEMORY / active context (fuzzy, composable, BOUNDED ~24-bind span, gracefully decays) — a transient read of the Class-L Laplacian long-term store, never the store itself."},
    "srmech.amsc.hdc.bundle": {"example": {"input": {"vectors": "[b'abc', b'abd', b'abe']"}, "output": "b'abe'"}, "explanation": "Majority-rule superposition of several BSC hypervectors into one that is similar to each input — the Class-M bundle (the set/record former)."},
    "srmech.amsc.hdc.similarity": {"example": {"input": {"a": "b'abc'", "b": "b'abd'"}, "output": "Q(3, 4)"}, "explanation": "Normalised agreement (1 − 2·Hamming/D) between two BSC hypervectors, as an exact rational Q. +1 = identical, 0 = orthogonal, −1 = complementary."},
    "srmech.amsc.laplacian.dense_laplacian": {"example": {"input": {"edges": "[(0, 1), (1, 2), (2, 0), (2, 3)]", "n": "4", "weights": "[1.0, 1.0, 1.0, 1.0]"}, "output": "Mat(4x4, real)"}, "explanation": "Combinatorial graph Laplacian L = D − A of a weighted undirected graph (n nodes, edges + per-edge weights) as a dense Mat — the foundation the Class-L spectral readers (fiedler / spine / eigvals) run on. F1216: the Class-L Laplacian IS the LONG-TERM relational STORE (exact, addressed, directional, GROWS with knowledge — the genome / disk); the Class-M Klein-4/HDC bundle is the transient working-memory read, bridged by the reversible spectral basis-change (eigen / Walsh-Hadamard)."},
    "srmech.amsc.laplacian.fiedler_vector": {"example": {"input": {"arg0": "Mat(4x4, real)"}, "output": "Vec(4, real)"}, "explanation": "Eigenvector of the second-smallest Laplacian eigenvalue (λ1). Its sign per node gives the natural 2-way spectral cut of the graph."},
    "srmech.amsc.laplacian.jacobi_eigvals": {"example": {"input": {"arg0": "Mat(4x4, real)"}, "output": "Vec(4, real)"}, "explanation": "Ascending eigenvalues of a symmetric Mat via cyclic Jacobi rotations (no numpy). On a graph Laplacian: λ0 = 0 for a connected graph; λ1 (the Fiedler value) measures algebraic connectivity."},
    "srmech.amsc.laplacian.spectral_spine": {"example": {"input": {"edges": "[(0, 1), (1, 2), (2, 0), (2, 3)]", "k": "3", "weights": "[1.0, 1.0, 1.0, 1.0]"}, "output": "[2, 3, 0]"}, "explanation": "The structurally-central 'spine': top-|component| nodes of the dominant-eigenvalue eigenvector — the centrality axis, complementing the community readers (fiedler 2-way / three_fold 3-way)."},
    "srmech.amsc.laplacian.three_fold_eigvec_groups": {"example": {"input": {"arg0": "Mat(4x4, real)"}, "output": "{'low': Mat(4x1, real), 'mid': Mat(4x1, real), 'high': Mat(4x2, real)}"}, "explanation": "3-way spectral partition from the sign pattern across the low eigenvectors (the k=3 community read; complements fiedler's 2-way and spine's centrality)."},
    "srmech.amsc.plasmid.add_plasmid": {"explanation": "INCREMENTAL STAGE 1 + 2 (F1252 / §102) — add ONE document: stage-1 append + an O(section) count bump + a re-mint of the small conserved core. No global recursive_cut, no re-extraction; untouched sections stay byte-identical. Threads a running organize state. Calling it D times is BYTE-IDENTICAL to one genome_integrate_plasmids over the same D sections (the exactness contract the rc279 test pins)."},
    "srmech.amsc.plasmid.conserved_core": {"explanation": "CONSERVE (F1252 / §102 STAGE 2 step 1) — read the section-count distribution and return the CONSERVED CORE node set + the threshold k DERIVED FROM THE DATA (the ANTIMODE of the count histogram — the rc272 participation-antimode discipline in the count domain, with the metric INVERTED: high section-count = the conserved NUCLEAR core). k='auto' (default) derives OR HONESTLY DECLINES: when no qualifying antimode exists it returns k_source='declined' with k=0 and an empty core rather than inventing a threshold — and the REAL F1253 corpus curve (heavy-tailed / near-power-law: singleton 64.6%, >=5 14.5%, >=100 1.7%, ratios decaying smoothly) takes exactly that path, because a scale-free distribution has no characteristic scale and hence no natural antimode. An explicit int is k_source='policy', a stated choice the CALLER owns — never presented as measured, and never selected to reproduce F1251's ~16% core fraction (that would be post-hoc numerology). Dispatches to the srmech_genome_conserved_core C peer."},
    "srmech.amsc.plasmid.genome_integrate_plasmids": {"explanation": "STAGE 2 ORGANIZE (F1252 / §102) — CONSERVE (derive-or-decline k; the returned k_source records which) -> PROMOTE (mint the core, 0x58 centromere) -> MERGE (fold the retained plasmids), removing the monolithic from-scratch partition from the encode path (recursive_cut is never called). PASS section_count — plasmid_extract returns it FREE as a streamed accumulator; omitting it triggers the deliberate O(P*section) section_counts re-derivation (the slow verification path). Dispatches to the srmech_genome_integrate_plasmids C peer; progress= is a Python-only kwarg ticking between whole chromosomes (MINTING then INTEGRATING)."},
    "srmech.amsc.plasmid.plasmid_extract": {"explanation": "STAGE 1 EXTRACT (F1252 / §102) — stream documents into APPEND-ONLY plasmid sections (each doc -> ONE §89 KERNEL chromosome of its LOCAL co-occurrence graph, GLOBAL node-ids), retiring the loose monolithic co-occurrence JSON at the graph-L layer. Native-dispatches the whole section to the srmech_genome_plasmid_extract C orchestrator (byte-identical to the pure path); progress= is a Python-only kwarg firing between whole SECTIONS (phase EXTRACTING, clean cancel at a chromosome boundary)."},
    "srmech.amsc.plasmid.section_counts": {"explanation": "Derive {global_id: n_sections} — how many distinct PLASMID sections each GLOBAL node appears in — by scanning a plasmid_extract store's sections (their GLOBAL node_ids). The genome-native SSoT read stage-2 (F1252 rc279) promotes on (a node is CONSERVED iff its section-occurrence count >= k). rc280 (F1253): the catalog is derived ONCE for the whole scan (it was re-derived per section, re-reading the entire body each time — O(P^2 x body)) and each section is read TARGETED, paging only the node_ids prefix the §89 payload puts before the edges — O(P x node_ids), byte-identical counts, no format change. Prefer plasmid_extract's free streamed section_count; this is the resume/verify path."},
    "srmech.amsc.primes.is_prime": {"example": {"input": {"n": "97"}, "output": "True"}, "explanation": "Deterministic primality test (Class-J). True iff n is prime."},
    "srmech.amsc.rational.best_rational": {"example": {"input": {"denominator": "100000", "max_denominator": "100", "numerator": "314159"}, "output": "(22, 7)"}, "explanation": "Best rational p/q with q ≤ max_denominator approximating numerator/denominator (Class-N small-denominator anchor via continued fractions). Takes an INTEGER numerator/denominator pair, never a float."},
    "srmech.amsc.text.fold_marks": {"example": {"input": {"text": "'क्षि'"}, "output": "'कष'"}, "explanation": "Drop combining marks by Unicode CATEGORY — Mn/Mc/Me and nothing else (Class B/G text-framing; §106/F1258; rc293). The name is the contract: a VIRAMA is a mark, not an accent, so `fold_accents` would have been wrong in exactly the Indic cases that matter most while quietly re-scoping the op toward Latin. Category only — no case change, no locale tailoring, no NFKD/compatibility folding, no ligature expansion — so 'ø' and the OHM SIGN are unchanged and Hangul is unchanged in either normalization form. Needs NO normalizer: precomposed characters are handled by the vendored table's replacement rows and decomposed sequences by its drop rows, so the same marks fall out whichever form is supplied. Idempotent. A SEPARATE op, not a glyph_stream mode — folding is lossy and glyph_stream is contractually lossless; compose as glyph_stream(fold_marks(s))."},
    "srmech.amsc.text.glyph_stream": {"explanation": "Segment ``text`` into UAX #29 extended grapheme clusters — the language-agnostic glyph stream (§40 / F698; rc287). A cluster is what a reader perceives as ONE character and is the only unit well-defined in every script, so there is no per-language word decision: no length floor, no casefold, no stoplist. Emoji ZWJ sequences (GB11), flag pairs (GB12/13) and Indic conjuncts (GB9c) each come back as ONE cluster. Lossless — ''.join(result) reconstructs the NFC-normalised input exactly."},
}
