"""srmech.amsc.carrier_schema — the CARRIER (operand) introspection surface
(rc205; gh #1293) — the noun-side DUAL of :mod:`srmech.amsc.tool_schema`.

``tool_schema`` exposes the **ops** (the verbs — the A–N operator vocabulary)
richly; this module exposes the **carrier TYPES** (the nouns — the operand
vocabulary) the ops consume and produce. Before rc205 a consumer discovering
the carriers had to scrape :func:`srmech.amsc.carrier_ladder.
carrier_ladder_descriptor` (ladder/rung ints + ``adds_variable``) with no
human-readable description per carrier, so introspection could not say *what a
``TriPoly`` IS* beyond "rung 3" (the Siona / RBS-LM self-hosting finding —
``docs/srmech/rbs_lm_research/R-RBS-LM-FINDING_1110_*``; UPSTREAM_NOTES §91).

:func:`carrier_schema` returns, per carrier::

    {
      "<name>": {
        "name":        "<name>",
        "description": "<one line: what it is / variable semantics / when>",
        "ladder":      "variable" | "variable_q" | "cayley_dickson" | None,
        "rung":        <int> | None,
        "variables":   ["k", ...],        # shift variables (poly ladders)
        "ops": {                          # back-index into tool_schema
          "consumes": ["srmech....", ...],   # full ToolEntry names
          "produces": ["srmech....", ...],
        },
      },
      ...
    }

The ``ops`` back-index is **DERIVED, never hand-maintained**: it unions

* a word-boundary token scan of every registered ToolEntry's declared
  ``parameters[].type`` / ``returns.type`` strings (the tool_schema SSoT), and
* the rc120 per-op CARRIER CONTRACT (:data:`srmech.amsc.carrier_ladder.
  _OP_CONTRACTS`) resolved through the ladder rung → carrier-name map (so the
  Cayley–Dickson ops — whose ToolEntry type strings say ``list[float]`` — still
  index under ``quaternion`` / ``octonion`` / ``sedenion``).

The ``ladder`` / ``rung`` values agree with ``carrier_ladder_descriptor()``
(tested); the Cayley–Dickson rungs surface under their value-carrier names
(``float``/``complex``/``quaternion``/``octonion``/``sedenion`` = the
descriptor's R/C/H/O/S keys at dims 1/2/4/8/16).

Scope: the registry covers the carriers ON the public op surface — every
srmech carrier type a registered ToolEntry consumes or produces, plus the
three promote/project ladders' rungs. Internal exact representations no
public op surfaces (``QMat`` / ``Qalg`` / the genus-``RiemannTheta`` family)
join when an op surfaces them (the drift ratchet in
``tests/test_carrier_schema_rc205.py`` forces the addition).

Native dispatch: when the rc205 C peer is loaded (``srmech_carrier_schema``
over the compiled-in ``srmech_carrier_registry`` const table — GENERATED by
``c/tools/gen_carrier_registry.py``, the rc184/rc202 codegen model) and no
profile tools are registered, :func:`carrier_schema` parses the C canonical
JSON — BYTE-IDENTICAL to ``json.dumps(<pure>, sort_keys=True,
separators=(",", ":"))`` (the sha256 hash-ratchet contract locking the C table
to this Python SSoT). A profile tool, a stale/absent lib, or a non-OK status
falls back to the pure path (never a wrong answer).

Pure data + a derivation over the live registry — no numerical kernel; no
float math, no numpy, no ``abs()``.
"""

from __future__ import annotations

import json
import re
from typing import Any, Dict, List, Optional

from .carrier_ladder import _OP_CONTRACTS

__all__ = ["carrier_schema"]


# ── the authored per-carrier metadata (the human-readable half) ───────────────
#
# name -> {description, ladder, rung, variables}. The ops back-index is DERIVED
# (below), never authored. ladder/rung must agree with
# carrier_ladder_descriptor() — tests/test_carrier_schema_rc205.py pins it.

_CARRIERS: Dict[str, Dict[str, Any]] = {
    # ── the ordinary variable ladder (Poly → BiPoly → TriPoly) ───────────────
    "Poly": {
        "description": (
            "Exact-ℚ univariate polynomial in the summation variable k — a "
            "trimmed tuple of exact Q coefficients in ascending degree, "
            "immutable. Rung 1 of the ordinary variable ladder: the operand "
            "gosper telescopes over; promote (trivial embedding) to BiPoly "
            "to feed zeilberger."),
        "ladder": "variable", "rung": 1, "variables": ["k"],
    },
    "BiPoly": {
        "description": (
            "Exact-ℚ bivariate polynomial in (n, k) — a polynomial in k "
            "whose coefficients are Poly in n. Rung 2 of the ordinary "
            "variable ladder: the substrate the zeilberger / wz_certificate "
            "term-ratios r_n(n,k) / r_k(n,k) ride."),
        "ladder": "variable", "rung": 2, "variables": ["n", "k"],
    },
    "TriPoly": {
        "description": (
            "Exact-ℚ trivariate polynomial in (n, j, k) — a trimmed tuple of "
            "BiPoly in (n,k) indexed by j-degree, immutable. Rung 3 of the "
            "ordinary variable ladder: the operand of apagodu_zeilberger "
            "(multivariate sums-of-sums creative telescoping)."),
        "ladder": "variable", "rung": 3, "variables": ["n", "j", "k"],
    },
    # ── the q variable ladder (QPoly → QBiPoly) ───────────────────────────────
    "QPoly": {
        "description": (
            "Exact q-shift carrier: a Laurent polynomial in x = qⁿ with "
            "exact ℚ[q] (Poly-in-q) coefficients, immutable — the q-analog "
            "of Poly. Rung 1 of the q variable ladder: the operand of "
            "q_gosper; promote to QBiPoly to feed q_zeilberger."),
        "ladder": "variable_q", "rung": 1, "variables": ["x=qⁿ"],
    },
    "QBiPoly": {
        "description": (
            "Exact bivariate-q polynomial in (X, Y) = (qⁿ, qᵏ) — a "
            "polynomial in Y whose coefficients are QPoly in X (Laurent "
            "over ℚ[q]). Rung 2 of the q variable ladder: the substrate of "
            "q_zeilberger / q_wz_certificate."),
        "ladder": "variable_q", "rung": 2, "variables": ["X=qⁿ", "Y=qᵏ"],
    },
    # ── the Cayley–Dickson ladder (ℝ ↪ ℂ ↪ ℍ ↪ 𝕆 ↪ 𝕊, keyed by dim) ──────────
    "float": {
        "description": (
            "The float64 scalar — rung 1 (R) of the Cayley–Dickson ladder "
            "and the FPU last-mile carrier: numeric results collapse to "
            "float only at the observed-frame read-out (exact carriers stay "
            "rational in the fiber; frame rotation is the terminal op)."),
        "ladder": "cayley_dickson", "rung": 1, "variables": [],
    },
    "complex": {
        "description": (
            "The complex scalar — rung 2 (C) of the Cayley–Dickson ladder, "
            "carried as (re, im) float pairs (interleaved on the native "
            "side, C99 double _Complex layout): the spectral / "
            "eigendecomposition read-out scalar."),
        "ladder": "cayley_dickson", "rung": 2, "variables": [],
    },
    "quaternion": {
        "description": (
            "A quaternion as a length-4 float sequence (1, i, j, k basis) — "
            "rung 4 (H) of the Cayley–Dickson ladder: the operand of the "
            "qm.quaternion.* family and the generic cascade cd_* ops."),
        "ladder": "cayley_dickson", "rung": 4, "variables": [],
    },
    "octonion": {
        "description": (
            "An octonion as a length-8 float sequence (e0..e7 basis) — rung "
            "8 (O) of the Cayley–Dickson ladder, the LAST division algebra "
            "(Hurwitz): the operand of the qm.octonion.* family, the "
            "octonion DFT, and the generic cascade cd_* ops."),
        "ladder": "cayley_dickson", "rung": 8, "variables": [],
    },
    "sedenion": {
        "description": (
            "A sedenion as a length-16 float sequence (e0..e15 basis) — "
            "rung 16 (S) of the Cayley–Dickson ladder, PAST Hurwitz (zero "
            "divisors appear — the open-exterior boundary): the "
            "SedenionRegister's address space and the cd_* boundary "
            "demonstrator operand."),
        "ladder": "cayley_dickson", "rung": 16, "variables": [],
    },
    # ── scalar carriers off the ladders ───────────────────────────────────────
    "int": {
        "description": (
            "The bit-exact integer — Python arbitrary-precision int, "
            "mirrored by srmech_bigint in C: the fiber-side carrier every "
            "exact cascade accumulates in (add/sub/shift; no float until "
            "the terminal read-out)."),
        "ladder": None, "rung": None, "variables": [],
    },
    "Fraction": {
        "description": (
            "stdlib exact rational (fractions.Fraction) — accepted/emitted "
            "at the exact-LA boundaries (dense_solve exact=True, "
            "schur_complement, cd_norm_sq): the interchange twin of the "
            "srmech Q scalar."),
        "ladder": None, "rung": None, "variables": [],
    },
    "Q": {
        "description": (
            "srmech's exact rational scalar — a reduced (num, den) integer "
            "pair that compares like a float and collapses to one only via "
            "float(q): the return carrier of the Class-N series-truncate "
            "trig/exp/log surface and the HDC similarity scores."),
        "ladder": None, "rung": None, "variables": [],
    },
    # ── the float-LA carriers (numpy-free array('d') family) ─────────────────
    "Mat": {
        "description": (
            "Numpy-free dense matrix: a flat array('d') + (n_rows, n_cols); "
            "complex entries stored interleaved (re, im). THE float linear-"
            "algebra carrier — fed zero-copy to the native dense kernels "
            "(mat_matmul / mat_solve / mat_eigvals / mat_svd / "
            "hermitian_eigendecompose)."),
        "ladder": None, "rung": None, "variables": [],
    },
    "Vec": {
        "description": (
            "Numpy-free dense vector: a flat array('d') + a length n; "
            "complex interleaved. The 1-D peer of Mat for matvec / dot / "
            "eigenvector read-outs."),
        "ladder": None, "rung": None, "variables": [],
    },
    "HV": {
        "description": (
            "Numpy-free Klein-4 hypervector: an array('B') sector buffer + "
            "a sectors count. The Class-M HDC carrier (bind / bundle / "
            "permute / similarity and the klein4_* sector ops)."),
        "ladder": None, "rung": None, "variables": [],
    },
    # ── the elliptic row carriers ─────────────────────────────────────────────
    "EllMonomial": {
        "description": (
            "Exact signed Laurent monomial coeff·∏symᵉ over the elliptic "
            "argument lattice (symbols q / p / parameters), immutable — the "
            "argument-carrier of the elliptic row: the thing a theta factor "
            "is taken of."),
        "ladder": None, "rung": None, "variables": [],
    },
    "EllRatio": {
        "description": (
            "Exact elliptic-hypergeometric TERM-RATIO: a product "
            "prefactor·∏(num θ)/∏(den θ) of theta factors over an "
            "EllMonomial prefactor, immutable — the multiplicative carrier "
            "the elliptic engine (elliptic_gosper → elliptic_zeilberger → "
            "elliptic_wz_certificate) telescopes over."),
        "ladder": None, "rung": None, "variables": [],
    },
    "ThetaSum": {
        "description": (
            "Exact cleared rational theta-function: a ℚ(q,p)-linear SUM of "
            "theta-products over one theta-product denominator — the "
            "ADDITIVE layer above EllRatio that genuine elliptic creative "
            "telescoping needs (theta-quotients are not additively "
            "closed)."),
        "ladder": None, "rung": None, "variables": [],
    },
    "ThetaBracketSum": {
        "description": (
            "Exact free commutative ℤ-algebra of genus-g odd Riemann-theta "
            "BRACKET products coeff·∏[u_i] ([-u]=-[u], the pure Class-K "
            "antisymmetry) — the GENUS-AXIS additive carrier the higher-genus "
            "(Spiridonov math/0408366) theta-multisum reduction row lives in; "
            "the genus-g peer of ThetaSum."),
        "ladder": None, "rung": None, "variables": [],
    },
    # ── the weight-axis / harmonic-Maass carriers ─────────────────────────────
    "UnaryTheta": {
        "description": (
            "Exact unary theta series as a finite generating rule emitting "
            "integer q-power coefficients to any depth — the weight-axis "
            "theta carrier and the SHADOW slot of a harmonic-Maass pair."),
        "ladder": None, "rung": None, "variables": [],
    },
    "MockQSeries": {
        "description": (
            "Thin exact q-series carrier for the HOLOMORPHIC mock part f⁺ "
            "of a harmonic Maass form: a leading rational q-power + a "
            "finite generating rule emitting exact coefficients to any "
            "depth, immutable."),
        "ladder": None, "rung": None, "variables": [],
    },
    "HarmonicMaass": {
        "description": (
            "A harmonic (weak) Maass form as the FINITE EXACT PAIR "
            "(hol, shadow) that determines it (the Bruinier–Funke shadow "
            "map); the non-holomorphic completion is recoverable, not "
            "stored — the operand-irrepresentable boundary made explicit."),
        "ladder": None, "rung": None, "variables": [],
    },
    # ── the HDC domain-object carriers surfaced by cascade factories ─────────
    "One": {
        "description": (
            "The One S(σ,θ) — the single generator of the 14-D substrate as "
            "an addressable HDC object (σ rotation × θ grading): produced "
            "by cascade.the_one, read by the one_* accessors / to_scalar."),
        "ladder": None, "rung": None, "variables": [],
    },
    "SedenionRegister": {
        "description": (
            "Sedenion (dim-16) addressable RBS-HDC register: 16 named "
            "slots, an octonion reversible working word, a Hamming EC/carry "
            "block, and a CD-respecting navigate — produced by "
            "cascade.sedenion_register, driven via the sed_* class "
            "surface."),
        "ladder": None, "rung": None, "variables": [],
    },
}


# The ladder rung → carrier-name maps (the value-carrier names of the
# carrier_ladder_descriptor rung tables; cayley_dickson keys R/C/H/O/S surface
# under their Python value-carrier names). Tested against the descriptor.
_LADDER_RUNG_CARRIERS: Dict[str, Dict[int, str]] = {
    "variable": {1: "Poly", 2: "BiPoly", 3: "TriPoly"},
    "variable_q": {1: "QPoly", 2: "QBiPoly"},
    "cayley_dickson": {
        1: "float", 2: "complex", 4: "quaternion", 8: "octonion",
        16: "sedenion",
    },
}


def _token_re(name: str) -> "re.Pattern[str]":
    """A word-boundary regex for carrier token ``name`` inside a free-form
    ToolEntry type string ('Poly | BiPoly', 'list[list[Fraction]]', …).
    Identifier-boundary lookarounds so 'Poly' never matches inside 'QPoly'
    and 'int' never matches inside 'uint32'."""
    return re.compile(
        r"(?<![A-Za-z0-9_])" + re.escape(name) + r"(?![A-Za-z0-9_])")


def _ladder_slot_carriers(slot: Dict[str, Any], *, produces: bool) -> List[str]:
    """The carrier names a rc120 contract SLOT touches. A non-ladder slot
    contributes nothing here (the ToolEntry token scan covers it); a ladder
    slot resolves through :data:`_LADDER_RUNG_CARRIERS`:

    * a fixed int rung → that rung's carrier;
    * ``"any"`` (consume) / ``"same"`` / ``"arg:<param>"`` (produce) → every
      rung of the ladder (variadic — e.g. ``poly_promote(p, n_vars=cur)``
      returns the input rung unchanged);
    * ``"step_down"`` (produce) → every rung EXCEPT the highest (project
      always descends)."""
    ladder = slot.get("ladder")
    if ladder is None:
        return []
    rungs = _LADDER_RUNG_CARRIERS[ladder]
    rung = slot.get("rung")
    if isinstance(rung, int) and not isinstance(rung, bool):
        return [rungs[rung]]
    if rung == "step_down":
        top = max(rungs)
        return [name for r, name in rungs.items() if r != top]
    # "any" / "same" / "arg:<param>" — variadic over the whole ladder.
    assert produces or rung == "any", f"unexpected consume rung {rung!r}"
    return list(rungs.values())


def _derive_ops_index() -> Dict[str, Dict[str, List[str]]]:
    """The DERIVED per-carrier ops back-index: carrier name →
    ``{"consumes": [tool names], "produces": [tool names]}`` (each sorted,
    deduped). Union of the ToolEntry type-token scan and the rc120 carrier
    contract (see module docstring). Calls ``warmup_all()`` first so the
    registry is fully populated regardless of entry path (the rc9 orphan
    lesson) — this also makes the pure path deterministic against the
    compiled-in C table."""
    from .tool_schema import get_tool_schema, warmup_all

    warmup_all()
    consumes: Dict[str, set] = {name: set() for name in _CARRIERS}
    produces: Dict[str, set] = {name: set() for name in _CARRIERS}
    patterns = {name: _token_re(name) for name in _CARRIERS}

    for tool in get_tool_schema().tools:
        param_types = " ".join(p.type for p in tool.parameters)
        ret_type = tool.returns.type if tool.returns is not None else ""
        for name, pat in patterns.items():
            if param_types and pat.search(param_types):
                consumes[name].add(tool.name)
            if ret_type and pat.search(ret_type):
                produces[name].add(tool.name)

    for spec in _OP_CONTRACTS.values():
        for name in _ladder_slot_carriers(spec["consumes"], produces=False):
            consumes[name].add(spec["tool"])
        for name in _ladder_slot_carriers(spec["produces"], produces=True):
            produces[name].add(spec["tool"])

    return {
        name: {
            "consumes": sorted(consumes[name]),
            "produces": sorted(produces[name]),
        }
        for name in _CARRIERS
    }


def _pure_carrier_schema() -> Dict[str, Dict[str, Any]]:
    """The pure-Python carrier schema (the SSoT the C const table is
    generated from and hash-ratcheted against). Fresh (mutation-safe)
    structures each call."""
    ops_index = _derive_ops_index()
    out: Dict[str, Dict[str, Any]] = {}
    for name, meta in _CARRIERS.items():
        out[name] = {
            "name": name,
            "description": meta["description"],
            "ladder": meta["ladder"],
            "rung": meta["rung"],
            "variables": list(meta["variables"]),
            "ops": ops_index[name],
        }
    return out


def _native_carrier_schema() -> Optional[Dict[str, Dict[str, Any]]]:
    """The rc205 C ``srmech_carrier_schema`` canonical JSON parsed to a
    dict, or ``None`` when the native peer is unavailable / returns non-OK
    (caller falls back to the pure path)."""
    try:
        from . import _native
    except Exception:  # pragma: no cover — defensive; _native always imports
        return None
    raw = _native.carrier_schema_json_c()
    if raw is None:
        return None
    return json.loads(raw.decode("utf-8"))


def carrier_schema() -> Dict[str, Dict[str, Any]]:
    """The CARRIER introspection registry (rc205; gh #1293) — per carrier
    ``{"name", "description", "ladder", "rung", "variables", "ops"}`` keyed
    by carrier name; the operand-side dual of ``tool_schema`` (see the
    module docstring for the full shape + the derivation of ``ops``).

    Native-dispatched: when the rc205 C peer is loaded AND no profile tools
    are registered (a profile tool could extend the live ops back-index the
    compiled-in table cannot know), the payload comes from the bare-C-host
    ``srmech_carrier_schema`` over the ``srmech_carrier_registry`` const
    table — VALUE-identical to the pure path (byte-identical in canonical
    form; the sha256 hash-ratchet in tests locks the two). Otherwise the
    pure path derives it live."""
    from .tool_schema import _REGISTRY

    if not any(e.owner != "srmech" for e in _REGISTRY.values()):
        native = _native_carrier_schema()
        if native is not None:
            return native
    return _pure_carrier_schema()
