"""srmech.amsc.ellbase — the EXACT theta-factor FOUNDATION (``EllMonomial`` +
``Theta``) of the ELLIPTIC F929 reduction row, the top of the base-axis
degeneration tower ``elliptic → q → ordinary``.

Where :class:`~srmech.amsc.poly.Poly` carries an ordinary polynomial (the
``q → 1`` ground) and :class:`~srmech.amsc.qpoly.QPoly` carries a Laurent
polynomial in ``x = q**n`` (the ``p → 0`` / basic-hypergeometric ground), the
ELLIPTIC level — Frenkel–Turaev's ₁₀E₉, Spiridonov's elliptic hypergeometric
series; Warnaar, *Constr. Approx.* 18 (2002) 479–502 — carries term-ratios built
from the **modified theta function**

    θ(z; p) = ∏_{j≥0} (1 − z·pʲ)·(1 − z⁻¹·p^{j+1})

a DOUBLY-periodic (elliptic) object: the genuine "cycle of cycles" (a torus, two
periods ``q`` and the nome ``p``), the un-collapsed top fiber whose ``p → 0``
degeneration is the q-level and whose further ``q → 1`` degeneration is ordinary.

This module is the FOUNDATION (rc59): the two atoms the elliptic engine
(elliptic-Gosper → elliptic-Zeilberger → elliptic-WZ) manipulates —

- **``EllMonomial``** — a signed Laurent *monomial* ``coeff · ∏ sym**e`` over the
  multiplicative argument-lattice generated by the formal symbols ``q``, the nome
  ``p``, and any parameters (``a``, ``b``, …); ``coeff`` an exact :class:`Q`
  (the sign is the **Class-K** pin-slot, never an ALU ``abs()``), every exponent
  an int. Exact ``*`` / inverse / ``**``; collapses to a single exact ``Q`` only
  under :meth:`EllMonomial.eval`.
- **``Theta``** — the symbol ``θ(z; p)`` for ``z`` an ``EllMonomial`` (the nome
  ``p`` is the global modulus). The load-bearing operation is
  :meth:`Theta.canonicalize`, which uses the theta quasi-periodicity +
  inversion rewrites — **empirically pinned in exact ℚ at build**:

      θ(pᵏ·z₀; p) = (−1)ᵏ · p^{−k(k−1)/2} · z₀⁻ᵏ · θ(z₀; p)     (quasi-periodicity)
      θ(z⁻¹; p)   = −z⁻¹ · θ(z; p)                              (inversion)

  to pull the ``p``-exponent of the argument to 0 AND fix a canonical orientation
  of ``{z₀, z₀⁻¹}``, emitting the exact ``EllMonomial`` prefactor those rewrites
  produce. This is the elliptic analogue of the q-shift's monomial bookkeeping
  (:meth:`QPoly.qshift`), one algebra up — the atoms are theta-factors, not
  monomials.

The elliptic shifted factorial — the **theta-Pochhammer** ``(a; q, p)_n =
∏_{k=0}^{n-1} θ(a·qᵏ; p)`` — is :func:`theta_pochhammer`; the very-well-poised
₁₀E₉ is built entirely of these.

Everything is exact (ℚ coefficients + integer exponents); the ONE place a number
is materialised is the exact-ℚ truncated product :func:`modified_theta_trunc`
(the eval / cross-check oracle — truncating the infinite product at ``N`` terms
stays in exact ℚ, no float, no ``math``, no numpy). The exact-rational truncated
product is also how the quasi-periodicity sign conventions above were verified.

C peer (rc59-prefix, owed by the everything-mirrors discipline): ``srmech_ell*``
mirrors the EllMonomial/Theta exponent-lattice algebra over the integer exponent
vectors; the pure-Python body here is the COMPLETE alternative + the parity
oracle.
"""

from __future__ import annotations

from fractions import Fraction
from typing import Dict, Iterable, List, Mapping, Tuple

from .q import Q

__all__ = ["EllMonomial", "Theta", "EllRatio", "elliptic_lagrange_basis",
           "half_shift_response", "chirality_parity", "beat_relation_residue"]

_Q_ZERO = Q(0, 1)
_Q_ONE = Q(1, 1)
_P = "p"        # the nome symbol (the elliptic modulus; theta's second argument)
_Q_SYM = "q"    # the base symbol (the summation variable enters as q**n)


def _coerce_q(value) -> "Q | None":
    """Coerce an exact scalar (``Q`` / ``int`` / ``(num, den)`` / ``Fraction``)
    to a ``Q``, or ``None``. A ``float`` is REJECTED — exact only."""
    if isinstance(value, Q):
        return value
    if isinstance(value, bool):
        return Q(int(value), 1)
    if isinstance(value, int):
        return Q(value, 1)
    if isinstance(value, Fraction):
        return Q(value.numerator, value.denominator)
    if isinstance(value, float):
        return None
    if (isinstance(value, (tuple, list)) and len(value) == 2
            and isinstance(value[0], int) and isinstance(value[1], int)
            and value[1] != 0):
        return Q(value[0], value[1])
    return None


class EllMonomial:
    """A numpy-free EXACT signed Laurent monomial ``coeff · ∏ sym**e`` over the
    elliptic argument-lattice (symbols ``q`` / ``p`` / parameters), immutable.
    The argument-carrier of the elliptic row — the thing a ``Theta`` is taken of.
    ``coeff`` is an exact :class:`Q` (sign = Class-K); every exponent an int.
    Collapses to a single exact ``Q`` only via :meth:`eval`."""

    __slots__ = ("_coeff", "_exps")

    def __init__(self, coeff=_Q_ONE, exps: "Mapping[str, int] | None" = None) -> None:
        c = _coerce_q(coeff)
        if c is None:
            raise TypeError(
                "EllMonomial coeff must be exact-rational (Q / int / (num, den) / "
                f"Fraction); a float must enter elsewhere — got {coeff!r}")
        self._coeff = c
        if c == _Q_ZERO:
            # The zero monomial absorbs all exponents (degenerate; rarely used).
            self._exps: Tuple[Tuple[str, int], ...] = ()
            return
        items: List[Tuple[str, int]] = []
        for sym, e in (exps or {}).items():
            if not isinstance(sym, str):
                raise TypeError(f"EllMonomial symbol must be a str; got {sym!r}")
            if not isinstance(e, int):
                raise TypeError(f"EllMonomial exponent must be an int; got {e!r}")
            if e != 0:
                items.append((sym, e))
        items.sort()
        self._exps = tuple(items)

    # ── construction ────────────────────────────────────────────────────────
    @classmethod
    def one(cls) -> "EllMonomial":
        """The unit monomial ``1`` (coeff 1, no symbols)."""
        return cls(_Q_ONE, {})

    @classmethod
    def scalar(cls, coeff) -> "EllMonomial":
        """The pure-scalar monomial ``coeff`` (no symbols)."""
        return cls(coeff, {})

    @classmethod
    def symbol(cls, name: str, exp: int = 1, coeff=_Q_ONE) -> "EllMonomial":
        """The single-symbol monomial ``coeff · name**exp`` (the natural
        constructor for a parameter or a ``q``/``p`` power)."""
        return cls(coeff, {name: exp})

    # ── accessors ───────────────────────────────────────────────────────────
    @property
    def coeff(self) -> Q:
        """The exact ``Q`` scalar coefficient (sign included — Class-K)."""
        return self._coeff

    @property
    def exps(self) -> Dict[str, int]:
        """The exponent map ``{symbol: exponent}`` (nonzero exponents only)."""
        return dict(self._exps)

    @property
    def is_zero(self) -> bool:
        """True iff this is the zero monomial (coeff 0)."""
        return self._coeff == _Q_ZERO

    @property
    def is_unit(self) -> bool:
        """True iff this is exactly ``1`` (coeff 1, no symbols)."""
        return self._coeff == _Q_ONE and not self._exps

    def exp_of(self, sym: str) -> int:
        """The exponent of ``sym`` (0 if absent)."""
        for s, e in self._exps:
            if s == sym:
                return e
        return 0

    def symbols(self) -> Tuple[str, ...]:
        """The sorted tuple of symbols carried (nonzero exponents)."""
        return tuple(s for s, _e in self._exps)

    # ── exact multiplicative algebra (Class-K sign via Q) ────────────────────
    def __mul__(self, other) -> "EllMonomial":
        if isinstance(other, EllMonomial):
            if self.is_zero or other.is_zero:
                return EllMonomial(_Q_ZERO)
            merged: Dict[str, int] = dict(self._exps)
            for s, e in other._exps:
                merged[s] = merged.get(s, 0) + e
            return EllMonomial(self._coeff * other._coeff, merged)
        c = _coerce_q(other)
        if c is not None:
            return EllMonomial(self._coeff * c, dict(self._exps))
        return NotImplemented

    __rmul__ = __mul__

    def inv(self) -> "EllMonomial":
        """The multiplicative inverse ``1 / self`` (invert ``coeff``, negate every
        exponent). The zero monomial has no inverse."""
        if self.is_zero:
            raise ZeroDivisionError("EllMonomial: the zero monomial has no inverse")
        return EllMonomial(_Q_ONE / self._coeff, {s: -e for s, e in self._exps})

    def __truediv__(self, other) -> "EllMonomial":
        if isinstance(other, EllMonomial):
            return self * other.inv()
        c = _coerce_q(other)
        if c is not None:
            if c == _Q_ZERO:
                raise ZeroDivisionError("EllMonomial: divide by zero scalar")
            return EllMonomial(self._coeff / c, dict(self._exps))
        return NotImplemented

    def __pow__(self, k: int) -> "EllMonomial":
        if not isinstance(k, int):
            raise TypeError("EllMonomial power must be an int")
        if k == 0:
            return EllMonomial.one()
        if self.is_zero:
            if k < 0:
                raise ZeroDivisionError("EllMonomial: zero monomial to a negative power")
            return EllMonomial(_Q_ZERO)
        return EllMonomial(self._coeff ** k, {s: e * k for s, e in self._exps})

    def __eq__(self, other) -> bool:
        if other is self:
            return True
        if isinstance(other, EllMonomial):
            return self._coeff == other._coeff and self._exps == other._exps
        return NotImplemented

    def __ne__(self, other):
        r = self.__eq__(other)
        return r if r is NotImplemented else (not r)

    def __hash__(self) -> int:
        return hash((self._coeff, self._exps))

    def _sort_key(self) -> "Tuple":
        """A deterministic total order on monomials (exponent tuple, then coeff).
        Used to pick a canonical orientation of ``{z, z⁻¹}`` in
        :meth:`Theta.canonicalize` — satisfies ``key(z) != key(z⁻¹)`` whenever
        ``z != z⁻¹``."""
        return (self._exps, self._coeff.numerator, self._coeff.denominator)

    def __repr__(self) -> str:
        if self.is_zero:
            return "EllMonomial(0)"
        body = "·".join(f"{s}^{e}" for s, e in self._exps)
        return f"EllMonomial({self._coeff}{('·' + body) if body else ''})"

    # ── evaluation (the exact-Q collapse) ────────────────────────────────────
    def eval(self, values: "Mapping[str, object]") -> Q:
        """Substitute an exact ``Q`` for every symbol → a single exact ``Q``.
        ``values`` maps each symbol (``q`` / ``p`` / params) to an exact scalar;
        a missing symbol raises ``KeyError``. A negative exponent needs a nonzero
        value. No float."""
        acc = self._coeff
        if self.is_zero:
            return _Q_ZERO
        for s, e in self._exps:
            if s not in values:
                raise KeyError(f"EllMonomial.eval: no value for symbol {s!r}")
            v = _coerce_q(values[s])
            if v is None:
                raise TypeError(f"EllMonomial.eval: value for {s!r} not exact-rational")
            if e >= 0:
                acc = acc * (v ** e)
            else:
                if v == _Q_ZERO:
                    raise ZeroDivisionError(
                        f"EllMonomial.eval: symbol {s!r} is zero but has exponent {e}")
                acc = acc * (_Q_ONE / (v ** (-e)))
        return acc


class Theta:
    """The exact symbol ``θ(z; p)`` (modified theta) for an ``EllMonomial``
    argument ``z`` — the nome ``p`` is the global modulus. Immutable. The atom the
    elliptic engine telescopes over; :meth:`canonicalize` applies the
    quasi-periodicity + inversion rewrites (build-pinned in exact ℚ) to reduce the
    argument to a canonical ``p``-exponent-0, orientation-fixed representative,
    emitting the exact ``EllMonomial`` prefactor."""

    __slots__ = ("_z",)

    def __init__(self, z: EllMonomial) -> None:
        if not isinstance(z, EllMonomial):
            raise TypeError("Theta argument must be an EllMonomial")
        if z.is_zero:
            raise ValueError("Theta(0) is undefined (the argument cannot be the zero monomial)")
        self._z = z

    @property
    def arg(self) -> EllMonomial:
        """The argument ``z`` of ``θ(z; p)``."""
        return self._z

    def __eq__(self, other) -> bool:
        if other is self:
            return True
        if isinstance(other, Theta):
            return self._z == other._z
        return NotImplemented

    def __ne__(self, other):
        r = self.__eq__(other)
        return r if r is NotImplemented else (not r)

    def __hash__(self) -> int:
        return hash(("Theta", self._z))

    def __repr__(self) -> str:
        return f"Theta({self._z!r}; p)"

    def canonicalize(self) -> "Tuple[EllMonomial, Theta]":
        """Return ``(prefactor, theta0)`` with ``θ(z; p) == prefactor · θ(z0; p)``,
        where ``z0`` has ``p``-exponent 0 and a fixed orientation (the canonical
        rep of ``{z0, z0⁻¹}``). Uses the build-pinned exact identities

            θ(pᵏ·z₀) = (−1)ᵏ · p^{−k(k−1)/2} · z₀⁻ᵏ · θ(z₀)
            θ(w⁻¹)   = −w⁻¹ · θ(w)

        — so ``prefactor`` is an exact ``EllMonomial`` and the canonical form is
        unique. (``θ`` of a self-inverse argument is left as-is.)"""
        k = self._z.exp_of(_P)
        z0 = self._z * EllMonomial.symbol(_P, -k)        # strip p**k → p-exp 0
        # θ(pᵏ z0) = (−1)ᵏ p^{−k(k−1)/2} z0⁻ᵏ θ(z0)
        sign = Q(-1, 1) if (k % 2 != 0) else _Q_ONE   # (−1)^k; k may be negative
        pref = EllMonomial(sign, {_P: -(k * (k - 1)) // 2}) * (z0 ** (-k))
        # Orientation: pick the canonical rep of {z0, z0⁻¹}; θ(w⁻¹) = −w⁻¹ θ(w).
        z0_inv = z0.inv()
        if z0 != z0_inv and z0._sort_key() > z0_inv._sort_key():
            # z0 is the "larger" key → flip to the smaller rep w = z0⁻¹:
            # θ(z0) = θ((z0⁻¹)⁻¹) = −(z0⁻¹)⁻¹ θ(z0⁻¹) = −z0 · θ(z0⁻¹).
            pref = pref * EllMonomial(Q(-1, 1), {}) * z0
            z0 = z0_inv
        return pref, Theta(z0)

    def eval_trunc(self, values: "Mapping[str, object]", n_terms: int) -> Q:
        """The exact-ℚ truncated modified theta ``θ(z; p)`` at ``n_terms`` — the
        eval / cross-check oracle (no float). ``values`` supplies ``p`` and every
        argument symbol."""
        if _P not in values:
            raise KeyError("Theta.eval_trunc: no value for the nome 'p'")
        p_val = _coerce_q(values[_P])
        if p_val is None:
            raise TypeError("Theta.eval_trunc: 'p' must be exact-rational")
        return _modified_theta_trunc(self._z.eval(values), p_val, n_terms)

    @classmethod
    def pochhammer(cls, a: EllMonomial, n: int) -> "Tuple[Theta, ...]":
        """The elliptic shifted factorial (theta-Pochhammer) ``(a; q, p)_n =
        ∏_{k=0}^{n-1} θ(a·qᵏ; p)`` as a tuple of ``Theta`` factors (``n ≥ 0``;
        ``n = 0`` is the empty product). ``a`` is an ``EllMonomial`` (a parameter,
        a ``q``-power, or any argument). The building block of the very-well-poised
        ₁₀E₉ (the elliptic analogue of the q-Pochhammer)."""
        if not isinstance(a, EllMonomial):
            raise TypeError("Theta.pochhammer: a must be an EllMonomial")
        if not isinstance(n, int) or n < 0:
            raise ValueError("Theta.pochhammer: n must be a non-negative int")
        return tuple(cls(a * EllMonomial.symbol(_Q_SYM, k)) for k in range(n))


def _modified_theta_trunc(z_val, p_val, n_terms: int) -> Q:
    """The modified theta ``θ(z; p) = ∏_{j≥0}(1 − z·pʲ)(1 − z⁻¹·p^{j+1})``
    truncated to ``n_terms`` factor-pairs, in EXACT ℚ (the eval oracle; no float,
    no ``math``, no numpy). ``z_val`` / ``p_val`` are exact scalars; ``z ≠ 0`` and
    ``|p| < 1`` for the series to converge (convergence is the caller's concern —
    the truncation is exact whatever the magnitudes)."""
    z = _coerce_q(z_val)
    p = _coerce_q(p_val)
    if z is None or p is None:
        raise TypeError("modified_theta_trunc: z and p must be exact-rational")
    if z == _Q_ZERO:
        raise ZeroDivisionError("modified_theta_trunc: z must be nonzero")
    if not isinstance(n_terms, int) or n_terms < 0:
        raise ValueError("modified_theta_trunc: n_terms must be a non-negative int")
    acc = _Q_ONE
    z_inv = _Q_ONE / z
    pj = _Q_ONE                       # p**j
    for _j in range(n_terms):
        acc = acc * (_Q_ONE - z * pj)            # (1 − z·pʲ)
        acc = acc * (_Q_ONE - z_inv * pj * p)    # (1 − z⁻¹·p^{j+1})
        pj = pj * p
    return acc


_X = "x"        # the summation-variable symbol (x = q**n); the elliptic-shift σ
                # (n ↦ n+1, i.e. x ↦ q·x) and the period-shift (x ↦ p·x) act on x.


def _ratio_cancel(num: "List[Theta]", den: "List[Theta]") -> "Tuple[Tuple[Theta, ...], Tuple[Theta, ...]]":
    """Cancel matching ``Theta`` between two factor multisets (canonical thetas);
    return ``(num', den')`` with common factors removed, each sorted by argument
    key (a canonical form). Plain multiset bookkeeping — not a Counter / spectral
    proxy."""
    dn: "Dict[Theta, int]" = {}
    for t in num:
        dn[t] = dn.get(t, 0) + 1
    dd: "Dict[Theta, int]" = {}
    for t in den:
        dd[t] = dd.get(t, 0) + 1
    for t in list(dn):
        if t in dd:
            c = dn[t] if dn[t] < dd[t] else dd[t]    # multiset min (Class-K-free)
            dn[t] -= c
            dd[t] -= c
    out_n: "List[Theta]" = []
    for t, c in dn.items():
        out_n.extend([t] * c)
    out_d: "List[Theta]" = []
    for t, c in dd.items():
        out_d.extend([t] * c)
    out_n.sort(key=lambda th: th.arg._sort_key())
    out_d.sort(key=lambda th: th.arg._sort_key())
    return tuple(out_n), tuple(out_d)


class EllRatio:
    """A numpy-free EXACT elliptic-hypergeometric TERM-RATIO carrier: an exact
    product ``prefactor · ∏(num θ) / ∏(den θ)`` of :class:`Theta` factors over an
    :class:`EllMonomial` prefactor, immutable. The carrier the elliptic engine
    (elliptic-Gosper → elliptic-Zeilberger → elliptic-WZ) telescopes over — the
    elliptic analogue of the q-term-ratio (a ``QPoly`` quotient), one algebra up.

    On construction every ``Theta`` is canonicalized (:meth:`Theta.canonicalize`)
    and its prefactor folded into the global prefactor; matching ``θ`` cancel
    between numerator and denominator; the surviving multisets are sorted — so the
    representation is canonical and ``==`` is exact.

    The two load-bearing operations:

    - :meth:`qshift` — the **summation shift** ``σ`` (``n ↦ n+1``, i.e. the
      substitution ``x ↦ q·x`` in every theta argument), the elliptic analogue of
      :meth:`QPoly.qshift`. The elliptic engine's telescoping consumes it.
    - :meth:`is_elliptic` — the **balancing / very-well-poised predicate**, defined
      operationally: a theta-hypergeometric term-ratio is *elliptic* (a genuine
      function on the elliptic curve ``ℂ*/⟨p⟩``) **iff it is invariant under the
      period shift** ``x ↦ p·x`` — so ``is_elliptic() ≡ (pshift() == self)``. The
      carrier's exact canonicalization (the theta quasi-periodicity rewrites)
      decides it; no hand-rolled balancing algebra. This is the structural gate
      the elliptic reducers consult before attempting a closed form.
    """

    __slots__ = ("_pref", "_num", "_den")

    def __init__(self, prefactor: "EllMonomial | None" = None,
                 num: "Iterable[Theta]" = (), den: "Iterable[Theta]" = ()) -> None:
        pref = EllMonomial.one() if prefactor is None else prefactor
        if not isinstance(pref, EllMonomial):
            raise TypeError("EllRatio prefactor must be an EllMonomial")
        num_l: "List[Theta]" = []
        for t in num:
            if not isinstance(t, Theta):
                raise TypeError("EllRatio numerator factors must be Theta")
            pr, t0 = t.canonicalize()
            pref = pref * pr
            num_l.append(t0)
        den_l: "List[Theta]" = []
        for t in den:
            if not isinstance(t, Theta):
                raise TypeError("EllRatio denominator factors must be Theta")
            pr, t0 = t.canonicalize()
            pref = pref / pr                      # a den factor contributes 1/pr
            den_l.append(t0)
        if pref.is_zero:
            self._pref, self._num, self._den = EllMonomial(_Q_ZERO), (), ()
            return
        self._num, self._den = _ratio_cancel(num_l, den_l)
        self._pref = pref

    # ── construction ────────────────────────────────────────────────────────
    @classmethod
    def _wrap(cls, pref: EllMonomial, num: "Tuple[Theta, ...]",
              den: "Tuple[Theta, ...]") -> "EllRatio":
        """Internal: wrap ALREADY-canonical (pref, num, den) with no re-canon."""
        r = cls.__new__(cls)
        r._pref, r._num, r._den = pref, num, den
        return r

    @classmethod
    def one(cls) -> "EllRatio":
        """The unit ratio ``1`` (unit prefactor, no theta factors)."""
        return cls._wrap(EllMonomial.one(), (), ())

    @classmethod
    def monomial(cls, m: EllMonomial) -> "EllRatio":
        """The pure-monomial ratio ``m`` (no theta factors)."""
        if not isinstance(m, EllMonomial):
            raise TypeError("EllRatio.monomial: m must be an EllMonomial")
        if m.is_zero:
            return cls._wrap(EllMonomial(_Q_ZERO), (), ())
        return cls._wrap(m, (), ())

    @classmethod
    def theta(cls, t: Theta) -> "EllRatio":
        """The single-factor ratio ``θ(z; p)`` (a numerator theta)."""
        return cls(num=(t,))

    # ── accessors ───────────────────────────────────────────────────────────
    @property
    def prefactor(self) -> EllMonomial:
        """The exact ``EllMonomial`` prefactor (sign = Class-K)."""
        return self._pref

    @property
    def num(self) -> "Tuple[Theta, ...]":
        """The canonical numerator ``Theta`` multiset (sorted)."""
        return self._num

    @property
    def den(self) -> "Tuple[Theta, ...]":
        """The canonical denominator ``Theta`` multiset (sorted)."""
        return self._den

    @property
    def is_zero(self) -> bool:
        """True iff the ratio is identically zero (zero prefactor)."""
        return self._pref.is_zero

    @property
    def is_unit(self) -> bool:
        """True iff the ratio is exactly ``1`` (unit prefactor, no thetas)."""
        return self._pref.is_unit and not self._num and not self._den

    @property
    def weight(self) -> Q:
        """The modular WEIGHT of this term-ratio on the operand ladder. A BALANCED
        theta-quotient (equal numerator/denominator theta count — the
        very-well-poised / elliptic case :meth:`is_elliptic` gates on) is a genuine
        elliptic function on ``ℂ*/⟨p⟩``, hence **weight 0** (the ladder before
        :class:`srmech.amsc.unary_theta.UnaryTheta` is entirely weight-0). The
        weight axis is the new grade the unary-theta carrier introduces: ``θ(z;p)``
        carries weight ``1/2`` per factor, so a ratio with ``#num − #den`` net theta
        factors has weight ``(#num − #den)/2``; a balanced ratio is weight 0.

        Returns the exact :class:`~srmech.amsc.q.Q` net weight ``(len(num) −
        len(den)) / 2`` (``Q(0)`` for the balanced / elliptic case)."""
        return Q(len(self._num) - len(self._den), 2)

    # ── exact multiplicative algebra ─────────────────────────────────────────
    def __mul__(self, other) -> "EllRatio":
        if isinstance(other, EllRatio):
            return EllRatio(self._pref * other._pref,
                            self._num + other._num, self._den + other._den)
        if isinstance(other, EllMonomial):
            return EllRatio._wrap(self._pref * other, self._num, self._den) \
                if not (self._pref * other).is_zero else \
                EllRatio._wrap(EllMonomial(_Q_ZERO), (), ())
        return NotImplemented

    __rmul__ = __mul__

    def inv(self) -> "EllRatio":
        """The reciprocal ``1 / self`` (swap num↔den, invert the prefactor). The
        zero ratio has no inverse."""
        if self.is_zero:
            raise ZeroDivisionError("EllRatio: the zero ratio has no inverse")
        return EllRatio._wrap(self._pref.inv(), self._den, self._num)

    def __truediv__(self, other) -> "EllRatio":
        if isinstance(other, EllRatio):
            return self * other.inv()
        if isinstance(other, EllMonomial):
            return EllRatio._wrap(self._pref / other, self._num, self._den)
        return NotImplemented

    def __eq__(self, other) -> bool:
        if other is self:
            return True
        if isinstance(other, EllRatio):
            return (self._pref == other._pref and self._num == other._num
                    and self._den == other._den)
        return NotImplemented

    def __ne__(self, other):
        r = self.__eq__(other)
        return r if r is NotImplemented else (not r)

    def __hash__(self) -> int:
        return hash((self._pref, self._num, self._den))

    def __repr__(self) -> str:
        if self.is_zero:
            return "EllRatio(0)"
        return (f"EllRatio(pref={self._pref!r}, "
                f"num={len(self._num)}θ, den={len(self._den)}θ)")

    # ── the two shifts (summation σ: x↦qx ; period: x↦px) ───────────────────
    def _shift(self, base: str) -> "EllRatio":
        """Substitute ``x ↦ base·x`` (``base`` = ``'q'`` for the summation shift σ,
        ``'p'`` for the period shift) in the prefactor and every theta argument.
        Under ``x ↦ base·x`` a monomial ``m`` with x-exponent ``e`` becomes
        ``m · base**e`` (the ``x**e`` factor → ``(base·x)**e``); re-canonicalizes
        (a ``base='p'`` shift introduces p-exponents the theta rewrites resolve)."""
        def sm(m: EllMonomial) -> EllMonomial:
            return m * EllMonomial.symbol(base, m.exp_of(_X))
        pref = sm(self._pref)
        num = [Theta(sm(t.arg)) for t in self._num]
        den = [Theta(sm(t.arg)) for t in self._den]
        return EllRatio(pref, num, den)

    def qshift(self) -> "EllRatio":
        """The **summation shift** ``σ`` (``n ↦ n+1`` / ``x ↦ q·x``) — the
        elliptic analogue of :meth:`QPoly.qshift`. What the elliptic-Gosper
        antidifference and elliptic-Zeilberger creative telescoping consume."""
        return self._shift(_Q_SYM)

    def pshift(self) -> "EllRatio":
        """The **period shift** ``x ↦ p·x`` — the elliptic-curve translation by
        the nome. A theta-hypergeometric ratio is elliptic iff it is invariant
        under this shift (:meth:`is_elliptic`)."""
        return self._shift(_P)

    def is_elliptic(self) -> bool:
        """The **balancing / very-well-poised predicate**: True iff the ratio is a
        genuine elliptic function (invariant under the period shift ``x ↦ p·x``).
        Operationally ``pshift() == self`` — the exact theta-canonicalization
        decides it. The elliptic reducers consult this before attempting a closed
        form; a non-elliptic (unbalanced) input is honestly out of the row.

        DISPATCHES to the native ``srmech_ellratio_is_elliptic`` C peer when it is
        loaded (a 1:1 structural mirror of this exact decision — the C verdict EQUALS
        the Python verdict byte-for-byte, so it is trusted unconditionally); otherwise
        the pure-Python :meth:`_is_elliptic_py` body decides (it is the COMPLETE
        alternative + the C peer's parity oracle)."""
        c = self._is_elliptic_c()
        if c is not None:
            return c
        return self._is_elliptic_py()

    def _is_elliptic_py(self) -> bool:
        """The COMPLETE pure-Python ``is_elliptic`` decision (the parity oracle for the
        C peer): the period shift equals self, decided by the exact theta-canon."""
        return self.pshift() == self

    def _is_elliptic_c(self) -> "bool | None":
        """Dispatch the ``is_elliptic`` decision to the native
        ``srmech_ellratio_is_elliptic`` C peer → the bool verdict, or ``None`` when the
        native symbols are absent (the caller falls to :meth:`_is_elliptic_py`). The
        CANONICAL ratio (prefactor + num/den canonical theta arguments) is marshalled
        over an interned symbol table (the distinct symbols across the prefactor + every
        theta argument, sorted by NAME so the C dense exponent vector reproduces the
        :meth:`EllMonomial._sort_key` tuple order)."""
        from . import _native as _nat
        if not _nat.has_native_ellratio():
            return None
        if self.is_zero:
            # the zero ratio: pshift(0) == 0, trivially elliptic (no theta marshalling).
            return self.pshift() == self
        # The interned symbol universe MUST include p AND x even when the canonical form
        # carries neither: the period shift x ↦ p·x INTRODUCES a p-power (keyed off the
        # x-exponent), so the C needs a p slot to write it into AND an x slot to read it
        # from — without them the C period shift would be a silent no-op (always
        # reporting elliptic). Mirrors EllMonomial.symbol('p', …) materialising p.
        syms: "set" = {_X, _P}
        syms.update(self._pref.exps.keys())
        for t in self._num:
            syms.update(t.arg.exps.keys())
        for t in self._den:
            syms.update(t.arg.exps.keys())
        sym_list = sorted(syms)
        idx = {s: i for i, s in enumerate(sym_list)}
        n_syms = len(sym_list)

        def row(m: EllMonomial) -> "List[int]":
            r = [0] * n_syms
            for s, e in m.exps.items():
                r[idx[s]] = e
            return r

        monomials: "List[Tuple[int, int, List[int]]]" = []
        monomials.append((self._pref.coeff.numerator,
                          self._pref.coeff.denominator, row(self._pref)))
        for t in self._num:
            a = t.arg
            monomials.append((a.coeff.numerator, a.coeff.denominator, row(a)))
        for t in self._den:
            a = t.arg
            monomials.append((a.coeff.numerator, a.coeff.denominator, row(a)))
        return _nat.ellratio_is_elliptic_c(
            n_syms, idx.get(_X, -1), idx.get(_P, -1),
            len(self._num), len(self._den), monomials)

    # ── the #712 half-period edge readers (Dzhanibekov harmonic⊗subharmonic) ──
    def _negate_var(self, var: str) -> "EllRatio":
        """The double-cover deck transformation ``var ↦ −var`` on the prefactor +
        every theta argument: each monomial's Class-K coeff picks up
        ``(−1)^{var-exponent}`` (a theta arg EVEN in ``var`` is invariant; an ODD-in-
        ``var`` arg flips to ``θ(−z)``, a DIFFERENT canonical theta). Re-canonicalizes."""
        def sm(m: EllMonomial) -> EllMonomial:
            e = m.exp_of(var)
            return EllMonomial(m.coeff * (Q(-1, 1) if (e % 2 != 0) else _Q_ONE), m.exps)
        return EllRatio(sm(self._pref),
                        [Theta(sm(t.arg)) for t in self._num],
                        [Theta(sm(t.arg)) for t in self._den])

    def _shift_var(self, base: str, var: str) -> "EllRatio":
        """Substitute ``var ↦ base·var`` (``base`` = ``'p'`` for the period shift)
        in the prefactor + every theta argument — the ``var``-generalized
        :meth:`_shift` (``_shift(base)`` is ``_shift_var(base, _X)``); re-canonicalizes."""
        def sm(m: EllMonomial) -> EllMonomial:
            return m * EllMonomial.symbol(base, m.exp_of(var))
        return EllRatio(sm(self._pref),
                        [Theta(sm(t.arg)) for t in self._num],
                        [Theta(sm(t.arg)) for t in self._den])

    def half_shift_response(self, axis: str, var: "str | None" = None) -> EllMonomial:
        """The exact monomial MULTIPLIER this carrier acquires under a HALF-period
        translation along ``axis`` — see the module-level :func:`half_shift_response`."""
        return half_shift_response(self, axis, var)

    def chirality_parity(self, var: str = "w") -> str:
        """``"even"`` (harmonic) / ``"odd"`` (subharmonic) — see the module-level
        :func:`chirality_parity`."""
        return chirality_parity(self, var)

    def beat_relation_residue(self, var: str = _X) -> EllMonomial:
        """The exact ``q²·p⁻¹`` beat-relation residue — see the module-level
        :func:`beat_relation_residue`."""
        return beat_relation_residue(self, var)

    # ── evaluation (the exact-ℚ cross-check oracle) ──────────────────────────
    def eval_trunc(self, values: "Mapping[str, object]", n_terms: int) -> Q:
        """Evaluate to a single exact ``Q``: ``prefactor(values)`` times the
        truncated modified-theta product of every numerator factor over that of
        every denominator factor (``n_terms`` truncation; no float). ``values``
        supplies ``p`` and every argument symbol. The zero ratio → ``Q(0)``; a
        denominator theta evaluating to 0 raises ``ZeroDivisionError``."""
        if self.is_zero:
            return _Q_ZERO
        acc = self._pref.eval(values)
        for t in self._num:
            acc = acc * t.eval_trunc(values, n_terms)
        for t in self._den:
            d = t.eval_trunc(values, n_terms)
            if d == _Q_ZERO:
                raise ZeroDivisionError("EllRatio.eval_trunc: denominator theta is zero")
            acc = acc / d
        return acc


# ── the degree-d elliptic Lagrange interpolation basis ──────────────────────────


def elliptic_lagrange_basis(points: "List[EllMonomial]",
                            multiplier: EllMonomial,
                            var: str = _X) -> "List[EllRatio]":
    """The elliptic Lagrange interpolation basis of degree ``k = len(points)`` over the
    space ``V_t = {f analytic on ℂ* : f(p·z) = t·z^{-k}·f(z)}`` of higher-order theta
    functions in the variable ``z = var``.

    ``var`` selects the interpolation variable (default ``_X``, the summation axis). It is
    fully variable-agnostic: pass ``var=_Y`` to build the DUAL basis on the recurrence axis
    ``y = qⁿ``. The elliptic Zeilberger certificate factors as ``R(x,y) = R_x(x)·R_y(y)``
    (the order-0 keystone certificate's x-dependent thetas carry only ``{b,q}`` while its
    x-free thetas carry only ``{a,y}`` — clean decoupling), with BOTH factors balanced
    (elliptic in their own variable). So the y-side recurrence coefficients ``aⱼ(y)`` live
    in a ``V_{t_y}`` spanned by ``elliptic_lagrange_basis(…, var=_Y)`` exactly as ``R_x``'s
    numerator lives in ``V_{t_x}`` on x — the x/y operand DUALITY made constructive.

    Source (MPM-verified at build against the actual PDF): Hjalmar Rosengren, *Elliptic
    Hypergeometric Functions* (Lectures at OPSF-S6, arXiv:1608.06161v3 [math.CA]), §1.3
    **Corollary 1.3.5**: any analytic ``f`` on ``ℂ*`` with ``f(p·x) = t·x^{-k}·f(x)``
    (``k ∈ ℤ``, ``t ∈ ℂ*``, ``0 < |p| < 1``) satisfies ``k ≥ 0`` and factors as
    ``f(x) = C·θ(x/a₁, …, x/a_k; p)`` with ``(−1)^k·a₁···a_k = t``. The space ``V_t`` is
    ``k``-dimensional; this returns the Lagrange basis at the ``k`` interpolation points
    ``u₁, …, u_k`` (each an :class:`EllMonomial`), where the ``i``-th element places its
    ``k`` zeros at ``{u_j : j ≠ i}`` plus the BALANCING point
    ``v_i = (−1)^k·t / ∏_{j≠i} u_j`` (so the product of all ``k`` zeros equals
    ``(−1)^k·t``, satisfying Cor. 1.3.5):

        ``L_i(x) = θ(x/u₁, …, x̂/u_i, …, x/u_k, x/v_i; p)``     (omitting the ``i``-th).

    By construction:

      * **Lagrange interpolation** — ``L_i`` VANISHES at ``u_j`` for ``j ≠ i`` (it carries
        the factor ``θ(x/u_j)``, zero at ``x = u_j`` since ``θ(1; p) = 0``) and is non-zero
        at ``u_i`` (no ``θ(x/u_i)`` factor).
      * **Multiplier EXACTLY ``t·x^{-k}``** — under ``x ↦ p·x`` each ``θ(x/c)`` picks up the
        Class-K pin-slot prefactor ``θ(p·x/c) = −(c/x)·θ(x/c)`` (Eq. 1.5), so the product is
        ``(−1)^k·(∏ of the k zeros)·x^{-k} = (−1)^k·(−1)^k·t·x^{-k} = t·x^{-k}`` — the SAME
        multiplier for every ``i``.

    The ``k`` elements are linearly independent and SPAN ``V_t``, so any ``f ∈ V_t`` is
    ``Σ_i c_i·L_i`` with exact-``ℚ`` (or parameter-polynomial) coefficients ``c_i`` — the
    linear ansatz that closes the degree-``d`` elliptic Gosper–Petkovšek certificate solve
    (the unknown elliptic certificate's numerator lives in such a ``V_t``). Returns the
    ``k`` basis :class:`EllRatio` theta-products (un-normalized; the ``c_i`` absorb the
    scale). Exact over the modified-theta algebra — no float, no ``abs()`` (sign is the
    Class-K pin-slot), no ``math`` / numpy.

    DISPATCHES to the native ``srmech_elliptic_lagrange_basis`` C peer when it is
    loaded (a 1:1 structural mirror of this exact construction — the C basis EQUALS
    the Python basis byte-for-byte, so it is trusted unconditionally); otherwise the
    pure-Python :func:`_elliptic_lagrange_basis_py` body builds it (it is the COMPLETE
    alternative + the C peer's parity oracle)."""
    c = _elliptic_lagrange_basis_c(points, multiplier, var)
    if c is not None:
        return c
    return _elliptic_lagrange_basis_py(points, multiplier, var)


def _elliptic_lagrange_basis_py(points: "List[EllMonomial]",
                                multiplier: EllMonomial,
                                var: str = _X) -> "List[EllRatio]":
    """The COMPLETE pure-Python ``elliptic_lagrange_basis`` construction (the parity
    oracle for the C peer): the ``k`` basis :class:`EllRatio` theta-products."""
    pts = list(points)
    k = len(pts)
    if k == 0:
        raise ValueError("elliptic_lagrange_basis: need at least one interpolation point")
    x = EllMonomial.symbol(var)                            # the interpolation axis (x or the y-dual)
    sign_k = EllMonomial.scalar(Q((-1) ** k, 1))           # (−1)^k as an exact Q monomial
    basis: "List[EllRatio]" = []
    for i in range(k):
        others = [pts[j] for j in range(k) if j != i]
        prod_others = EllMonomial.one()
        for u in others:
            prod_others = prod_others * u
        v_i = (sign_k * multiplier) * prod_others.inv()    # the balancing point
        thetas = [Theta(x * u.inv()) for u in others] + [Theta(x * v_i.inv())]
        basis.append(EllRatio(num=thetas))
    return basis


def _mono_to_form(m: EllMonomial, idx: "Mapping[str, int]", n_syms: int) -> "Tuple":
    """Marshal an :class:`EllMonomial` to the C wire triple ``(coeff_num, coeff_den,
    dense_exps_row)`` over the interned symbol table ``idx`` (a length-``n_syms`` int
    row, the Python sorted-symbol-NAME order so the C dense vector reproduces
    :meth:`EllMonomial._sort_key`)."""
    row = [0] * n_syms
    for s, e in m.exps.items():
        row[idx[s]] = e
    return (m.coeff.numerator, m.coeff.denominator, row)


def _ellratio_from_form(form, sym_list: "List[str]") -> "EllRatio":
    """Rebuild a canonical :class:`EllRatio` from the C bridge form (a dict with a
    ``prefactor`` ``(coeff_num, coeff_den, exps_row)`` triple + ``num`` / ``den`` lists
    of the SAME ``(coeff_num, coeff_den, exps_row)`` triples — the theta ARGUMENT
    coefficient travels with each row, since the balancing arg ``z·v_i^{-1}`` carries a
    non-unit Class-K sign). The C rows are ALREADY canonical (p-exponent 0, oriented,
    cancelled, sorted), so :meth:`EllRatio._wrap` wraps them with NO re-canonicalization
    — byte-exact to the Python carrier."""
    n_syms = len(sym_list)

    def _mono(triple) -> EllMonomial:
        coeff_num, coeff_den, row = triple
        exps = {sym_list[j]: int(row[j]) for j in range(n_syms) if row[j] != 0}
        return EllMonomial(Q(int(coeff_num), int(coeff_den)), exps)

    pref = _mono(form["prefactor"])
    num = tuple(Theta(_mono(t)) for t in form["num"])
    den = tuple(Theta(_mono(t)) for t in form["den"])
    return EllRatio._wrap(pref, num, den)


def _elliptic_lagrange_basis_c(points: "List[EllMonomial]",
                               multiplier: EllMonomial,
                               var: str = _X) -> "List[EllRatio] | None":
    """Dispatch the basis construction to the native ``srmech_elliptic_lagrange_basis``
    C peer → the ``k`` basis :class:`EllRatio`, or ``None`` when the native symbols are
    absent (the caller falls to :func:`_elliptic_lagrange_basis_py`). The interned
    symbol universe MUST include ``var`` AND ``p``: the C sets ``z = symbol(var)`` off
    ``varsym`` and the :meth:`Theta.canonicalize` quasi-periodicity rewrite reads/writes
    ``p`` off ``psym`` — without those slots the C would silently mis-build (mirrors the
    same forcing in :meth:`EllRatio._is_elliptic_c`)."""
    from . import _native as _nat
    if not _nat.has_native_elliptic_lagrange_basis():
        return None
    pts = list(points)
    k = len(pts)
    if k == 0:
        raise ValueError("elliptic_lagrange_basis: need at least one interpolation point")
    syms: "set" = {var, _P}
    for u in pts:
        syms.update(u.exps.keys())
    syms.update(multiplier.exps.keys())
    sym_list = sorted(syms)
    idx = {s: i for i, s in enumerate(sym_list)}
    n_syms = len(sym_list)
    point_monos = [_mono_to_form(u, idx, n_syms) for u in pts]
    mult_mono = _mono_to_form(multiplier, idx, n_syms)
    forms = _nat.elliptic_lagrange_basis_c(
        n_syms, idx.get(var, -1), idx.get(_P, -1), k, point_monos, mult_mono)
    if forms is None:
        return None
    return [_ellratio_from_form(f, sym_list) for f in forms]


# ── the #712 Dzhanibekov half-period readers (harmonic⊗subharmonic cascade) ──────
#
# The torque-free (Dzhanibekov / tennis-racket) rotation's Jacobi sn/cn/dn map to
# EllRatio theta quotients under the #712 bridge (w = e^{iζ}, x = w², carrier-p =
# q_c²; DLMF 22.2/20.5). Its two-torus has TWO independent half-beats — the REAL 2K
# axis and the NOME 2iK′ axis (DLMF 22.4). These three ops read the EXACT carrier
# structure the #712 probes established:
#   • ``half_shift_response`` — the exact edge MULTIPLIER under a half-period shift
#     (real axis → the Class-K (−1)^{w-parity} sign; nome axis → the −x⁻¹-type
#     Theta.canonicalize pshift prefactor). The EDGE-relationship read: exact even
#     where the theta value is transcendental.
#   • ``chirality_parity`` — ``"even"`` (harmonic; closes under one 2K half-beat, like
#     dn) vs ``"odd"`` (subharmonic; needs 4K / the pair, like sn/cn).
#   • ``beat_relation_residue`` — the ``q²·p⁻¹`` residue that recovers the beat
#     relation ``p = q_c²`` (the harmonic torus is the SQUARE of the subharmonic one).
# In-repo SSoT: the committed #712 probes (dzhan_q1…q5) — the exact-Q oracle these
# ops reproduce. Carrier lineage: Gasper–Schlosser arXiv:math/0505215 / Rosengren
# arXiv:1608.06161 (already pinned by the rc59–rc67 elliptic carrier build).

_HALF_SHIFT_REAL_ALIASES = ("real", "2k")
_HALF_SHIFT_NOME_ALIASES = ("nome", "2ik", "2ikprime", "2ikp", "2ikprim")


def _normalize_half_axis(axis: str) -> str:
    """Normalize a half-period axis label to ``"real"`` / ``"nome"``. Accepts the
    #712-probe aliases (case-, whitespace-, and apostrophe-insensitive): the real 2K
    axis → ``{"real", "2K"}``; the nome 2iK′ axis → ``{"nome", "2iK'", "2iKprime"}``."""
    a = "".join(ch for ch in str(axis).strip().lower() if ch not in " _-'")
    if a in _HALF_SHIFT_REAL_ALIASES:
        return "real"
    if a in _HALF_SHIFT_NOME_ALIASES:
        return "nome"
    raise ValueError(
        f"half-shift axis {axis!r} not recognised; use 'real'/'2K' (the real 2K "
        f"half-beat) or 'nome'/\"2iK'\" (the nome 2iK′ half-beat)")


def _half_shift_response_py(ratio: EllRatio, a: str, var: str) -> EllMonomial:
    """The COMPLETE pure-Python half_shift_response body (the parity oracle for the C
    peer). ``a`` is the NORMALIZED axis (``"real"`` / ``"nome"``)."""
    shifted = ratio._negate_var(var) if a == "real" else ratio._shift_var(_P, var)
    d = shifted * ratio.inv()
    if d.num or d.den:
        raise ValueError(
            f"half_shift_response: the ratio is not half-shift-covariant along the "
            f"{a!r} axis in var {var!r} — {len(d.num)}+{len(d.den)} theta factor(s) "
            f"remain, so the edge multiplier is not a bare monomial (a chirality-ODD "
            f"theta under the real double-cover, or an unbalanced ratio)")
    return d.prefactor


def _half_shift_response_c(ratio: EllRatio, a: str, var: str) -> "EllMonomial | None":
    """Dispatch half_shift_response to the native ``srmech_ellratio_half_shift_response``
    C peer → the exact multiplier :class:`EllMonomial`, or ``None`` when the native
    symbols are absent (the caller falls to :func:`_half_shift_response_py`). The
    interned symbol universe MUST include ``var`` AND ``p`` (the shift + the theta-canon
    read/write those slots — mirrors :meth:`EllRatio._is_elliptic_c`)."""
    from . import _native as _nat
    if not _nat.has_native_ellratio_half_shift():
        return None
    syms = {var, _P}
    syms.update(ratio.prefactor.exps.keys())
    for t in ratio.num:
        syms.update(t.arg.exps.keys())
    for t in ratio.den:
        syms.update(t.arg.exps.keys())
    sym_list = sorted(syms)
    idx = {s: i for i, s in enumerate(sym_list)}
    n_syms = len(sym_list)

    def row(m: EllMonomial):
        r = [0] * n_syms
        for s, e in m.exps.items():
            r[idx[s]] = e
        return r

    monomials = [(ratio.prefactor.coeff.numerator,
                  ratio.prefactor.coeff.denominator, row(ratio.prefactor))]
    for t in ratio.num:
        monomials.append((t.arg.coeff.numerator, t.arg.coeff.denominator, row(t.arg)))
    for t in ratio.den:
        monomials.append((t.arg.coeff.numerator, t.arg.coeff.denominator, row(t.arg)))
    axis_int = 0 if a == "real" else 1
    got = _nat.ellratio_half_shift_response_c(
        n_syms, idx[var], idx.get(_P, -1), axis_int,
        len(ratio.num), len(ratio.den), monomials)
    if got is None:
        return None
    is_bare, cnum, cden, exps = got
    if not is_bare:
        # The pure-Python body raises the SAME contract error (a non-bare response).
        return _half_shift_response_py(ratio, a, var)
    return EllMonomial(Q(cnum, cden),
                       {sym_list[i]: exps[i] for i in range(n_syms) if exps[i] != 0})


def half_shift_response(ratio: EllRatio, axis: str,
                        var: "str | None" = None) -> EllMonomial:
    """The exact monomial MULTIPLIER an :class:`EllRatio` carrier acquires under a
    HALF-period translation along ``axis`` — the #712 Dzhanibekov half-beat edge read
    (exact even where the theta value is transcendental; the full :meth:`EllRatio.pshift`
    already exists, this is the HALF + reads ONLY the multiplier).

    ``axis`` ∈ the real 2K axis (``"real"`` / ``"2K"``) or the nome 2iK′ axis
    (``"nome"`` / ``"2iK'"``; case-/apostrophe-insensitive aliases, see
    :func:`_normalize_half_axis`):

    - **real 2K** — the double-cover deck transformation ``var ↦ −var`` (the physical
      ``z ↦ z + 2K`` ⇔ ``w ↦ −w``); the multiplier is the pure **Class-K** sign
      ``(−1)^{var-parity of the prefactor}`` (default ``var = "w"``, the subharmonic
      half-variable). Bare (a pure sign) iff every theta argument is EVEN in ``var``.
    - **nome 2iK′** — the carrier PERIOD shift ``var ↦ p·var`` (the physical
      ``z ↦ z + 2iK'`` ⇔ ``x ↦ p·x``); the multiplier is the ``−x⁻¹``-type
      :meth:`Theta.canonicalize` quasi-periodicity prefactor (default ``var = _X``,
      the summation variable ``x``). Always bare (pshift maps each canonical theta to a
      scalar multiple of itself).

    Returns the exact multiplier as an :class:`EllMonomial` (the coefficient is a
    Class-K ``±1``; the exponents are the ``p`` / ``x`` / ``q`` powers). Raises
    ``ValueError`` when the ratio is not half-shift-covariant along ``axis``/``var``
    (the multiplier is not a bare monomial — e.g. a chirality-ODD theta under the real
    double-cover). Oracle: the #712 probe ``dzhan_q2`` (sn/cn/dn → real 2K: −1/−1/+1;
    nome pshift theta-parts q/−q/−1). DISPATCHES to the native
    ``srmech_ellratio_half_shift_response`` C peer when loaded (the C multiplier EQUALS
    the pure-Python one byte-for-byte); else the complete pure-Python body decides.
    Exact-ℚ theta algebra — no float, no ``abs()`` (sign is Class-K), no numpy / math."""
    if not isinstance(ratio, EllRatio):
        raise TypeError("half_shift_response: ratio must be an EllRatio")
    a = _normalize_half_axis(axis)
    if var is None:
        var = "w" if a == "real" else _X
    c = _half_shift_response_c(ratio, a, var)
    if c is not None:
        return c
    return _half_shift_response_py(ratio, a, var)


def chirality_parity(ratio: EllRatio, var: str = "w") -> str:
    """The CHIRALITY parity of an :class:`EllRatio` theta-quotient carrier under the
    #712 harmonic⊗subharmonic reading: ``"even"`` (a HARMONIC reader — it closes under
    a SINGLE 2K half-beat, like ``dn``: real period 2K, chirality-even) vs ``"odd"``
    (a SUBHARMONIC reader — it needs 4K / the PAIR, like ``sn`` / ``cn``: real period
    4K, chirality-odd, half the harmonic frequency).

    Read as the parity of the ``var``-exponent of the prefactor (default ``var = "w"``,
    the subharmonic half-variable): EVEN ⇔ the real-2K :func:`half_shift_response` is
    ``+1`` (boundary-blind — cannot see the Dzhanibekov flip); ODD ⇔ it is ``−1``
    (holds the flip's ``−1``). A pure structural read (Class-K parity, no compute).
    Oracle: the #712 probes ``dzhan_q3`` / ``dzhan_q4`` (sn/cn → odd, dn → even;
    every quadratic/intensity observable sn²/cn²/sn·cn/… → even, boundary-blind)."""
    if not isinstance(ratio, EllRatio):
        raise TypeError("chirality_parity: ratio must be an EllRatio")
    return "odd" if (ratio.prefactor.exp_of(var) % 2 != 0) else "even"


def beat_relation_residue(ratio: EllRatio, var: str = _X) -> EllMonomial:
    """The exact BEAT-RELATION residue of an :class:`EllRatio` written on the HARMONIC
    (``x``) frame: the nome-axis (period-shift ``var ↦ p·var``) mismatch monomial that
    RECOVERS the #712 beat relation ``p = q_c²`` (the harmonic torus nome is the SQUARE
    of the subharmonic half-step). For the harmonic ``sn²`` object
    ``x⁻¹·θ(x)²/θ(q·x)²`` the residue is exactly ``q²·p⁻¹`` — the coherence residue the
    carrier surfaces unprompted (:meth:`EllRatio.is_elliptic` honestly declines it, and
    the residue is unity ⇔ ``p = q²``).

    Equivalent to :func:`half_shift_response`\\ ``(ratio, "nome", var)`` read as the
    beat-relation constraint. Returns the residue as an exact :class:`EllMonomial`; it
    evaluates to ``1`` exactly at the bridge point ``p = q_c²``. A pure structural read
    (composes the carrier period-shift; no new compute). Oracle: the #712 probe
    ``dzhan_q4`` (residue ``q²·p⁻¹``; closes at ``q=3/7, p=9/49``) + the ``dzhan_q1``
    bridge (``p = q_c²``)."""
    if not isinstance(ratio, EllRatio):
        raise TypeError("beat_relation_residue: ratio must be an EllRatio")
    return half_shift_response(ratio, "nome", var)
