"""JPL Power-of-Ten ratchet for srmech's C library.

Task #201 Phase B6 — mechanically detectable rule violations are
pinned at the counts documented in
``docs/srmech/c/JPL_AUDIT.md``. The pins can only go DOWN
(violations removed), never UP (violations added).

A PR that pushes a new function over 60 lines, removes an assertion
from a function below the 2-assert floor, introduces a goto /
malloc / multi-line macro, etc. will fail this test.

Mirrors the discipline of ephemerides-spectral's
``tests/test_jpl_audit.py``.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest


# The C source tree lives at docs/srmech/c/, three levels up from
# this test file (tests/ -> python/ -> srmech/ -> c/ sibling of python/).
_HERE = Path(__file__).resolve().parent
_C_SRC_DIR = _HERE.parent.parent / "c" / "src"
_C_INCLUDE_DIR = _HERE.parent.parent / "c" / "include"


def _c_files() -> list[Path]:
    """All srmech C source files we audit."""
    files = sorted(_C_SRC_DIR.glob("*.c"))
    files += sorted(_C_INCLUDE_DIR.glob("*.h"))
    return files


pytestmark = pytest.mark.skipif(
    not _C_SRC_DIR.exists(),
    reason=(
        "C source tree not present "
        f"({_C_SRC_DIR} does not exist); "
        "this test pins the JPL audit of the C library and is "
        "only meaningful when the C sources are checked out"
    ),
)


# ──────────────────────────────────────────────────────────────────────
# Rule-by-rule mechanical pins
# ──────────────────────────────────────────────────────────────────────


# Generated pure-DATA translation units — const tables ONLY, zero
# executable code. Their string-literal VALUES (e.g. ToolEntry summaries)
# are arbitrary English prose that can contain tokens like "free(" or
# "goto" which the mechanical string-content regex scans (Rule 1 goto /
# Rule 3 malloc) would mis-flag INSIDE a data string. These files are
# excluded from those two regex rules. The function-scan rules (Rule 4
# length / Rule 5 asserts) already find ZERO functions in them (const
# array declarations are not functions), so they stay in-scope there as a
# guard that the file remains data-only. See c/JPL_AUDIT.md.
GENERATED_DATA_FILES: set[str] = {
    # rc184 — the C MCP-server tool registry, generated by
    # c/tools/gen_tool_registry.py. A const srmech_tool_entry_t[] table
    # whose summary strings are the (English) ToolEntry summaries.
    "srmech_tool_registry.c",
}


def _mask_c_literals(text: str) -> str:
    """Blank the CONTENT of comments, string literals and CHAR literals,
    preserving every newline so line numbers and line counts are unchanged.

    rc441 (``#T1148``) — this is the fix for the scanner's brace-literal
    blindness. :func:`_scan_functions` finds a function's end by counting
    ``{`` and ``}`` per line, and it counted them in ``'{'`` / ``'}'`` CHAR
    LITERALS too. A JSON scanner written in C is full of those, so its brace
    depth never returned to zero, the scan ran off the end of the file, and
    the function was reported as ``lines=1`` — under Rule 4's 60-line limit by
    an accident of arithmetic rather than by being short.

    The second consequence was worse and is why this is not cosmetic: the
    same runaway scan kept counting ``assert(`` all the way to EOF, so those
    functions reported HUNDREDS of assertions. Rule 5 (>= 2 asserts) was
    therefore vacuous exactly where the scanner had lost its place. Measured
    on rc440: ``genome_json_object_span`` reported ``lines=1 asserts=458`` and
    ``genome_find_attest_span`` reported ``lines=1 asserts=456``; the census
    that produced this fix found a THIRD, ``toml_parse_value``
    (``lines=1 asserts=35``), which no prior report had named.

    Post-fix measurement, whole tree (138 files, 3092 functions): the detected
    function SET is unchanged (0 added, 0 removed) and exactly FIVE functions
    change their numbers -- the three above become
    ``(24, 2)`` / ``(20, 2)`` / ``(35, 2)``, ``toml_parse_inline_table`` grows
    ``54 -> 58`` lines (a real length the old counter under-reported), and
    ``srmech_bigint_pow_bound`` drops ``3 -> 2`` asserts (one ``assert(`` was
    inside a comment). NO new Rule 4 or Rule 5 violation appears, which is why
    the strict-zero ratchets on both rules stay strict-zero.
    """
    out: list[str] = []
    i, n = 0, len(text)
    state = "code"                     # code | line_comment | block | str | chr
    while i < n:
        c = text[i]
        nxt = text[i + 1] if i + 1 < n else ""
        if state == "code":
            if c == "/" and nxt == "/":
                state, i = "line_comment", i + 2
                out.append("  ")
                continue
            if c == "/" and nxt == "*":
                state, i = "block", i + 2
                out.append("  ")
                continue
            if c == '"':
                state, i = "str", i + 1
                out.append(" ")
                continue
            if c == "'":
                state, i = "chr", i + 1
                out.append(" ")
                continue
            out.append(c)
            i += 1
            continue
        if state == "line_comment":
            out.append("\n" if c == "\n" else " ")
            if c == "\n":
                state = "code"
            i += 1
            continue
        if state == "block":
            if c == "*" and nxt == "/":
                state, i = "code", i + 2
                out.append("  ")
                continue
            out.append("\n" if c == "\n" else " ")
            i += 1
            continue
        # inside a string or char literal
        if c == "\\":                  # an escape consumes its successor
            out.append("  ")
            i += 2
            continue
        if (state == "str" and c == '"') or (state == "chr" and c == "'"):
            state, i = "code", i + 1
            out.append(" ")
            continue
        out.append("\n" if c == "\n" else " ")
        i += 1
    return "".join(out)


def test_rule_1_no_goto() -> None:
    """JPL Rule 1: no goto, no setjmp / longjmp."""
    pattern = re.compile(r"\b(goto|setjmp|longjmp)\b")
    for f in _c_files():
        if f.name in GENERATED_DATA_FILES:
            continue
        text = f.read_text(encoding="utf-8")
        # Strip /* ... */ and // comments so doc mentions don't count
        text_no_block = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
        text_no_line = re.sub(r"//.*$", "", text_no_block, flags=re.MULTILINE)
        matches = pattern.findall(text_no_line)
        assert not matches, (
            f"{f.relative_to(_HERE.parent.parent)}: Rule 1 violation "
            f"— goto/setjmp/longjmp found: {matches}"
        )


# ──────────────────────────────────────────────────────────────────────
# Rule 1, second half: RECURSION (rc441, `#T1148`)
# ──────────────────────────────────────────────────────────────────────
#
# JPL Rule 1 bans "direct or indirect recursion". Through rc440 the Rule 1
# test above grepped for `goto|setjmp|longjmp` and NOTHING ELSE — it did not
# look for recursion at all, while `docs/srmech/c/JPL_AUDIT.md` stated that
# all ten rules pass. The rule's own subject was unmeasured, so the surface
# was BELIEVED ABSENT rather than known-clean.
#
# The census that closed it (whole tree: 138 files, 3092 functions) found
# NINE recursion cycles — one direct, eight mutual. A prior report had named
# two of the eight; the tree carries 4.5x that. So this ships as a SEEDED
# DOWN-ONLY ratchet, not as strict zero: the population is real, it is
# depth-bounded by construction in every case, and unwinding it is a
# different piece of work from being able to SEE it.
#
# The gate is strict on the decidable class — a NEW cycle, or a cycle whose
# membership changed, fails immediately — and down-only on the count.

# The recursion population as measured at rc441. Each entry is a cycle: a
# 1-tuple is direct self-recursion, an n-tuple is a mutual cycle (sorted).
# Every one of these is depth-bounded in the source (an explicit depth
# parameter checked against a compiled-in cap, or a bounded nesting level),
# which is why they were tolerable while invisible — but Rule 1's objection
# is to the CONSTRUCT, because a bound that is not enforced by the call
# structure is a bound that a later edit can move.
RULE_1_RECURSION_SEEDED: set = {
    # srmech_invoke.c — the mval -> JSON emitter. Self-recurses on nested
    # list/tuple items (`iv_emit_node(e, v->items[k], depth + 1u)`), bounded
    # by an explicit `depth` argument.
    ("iv_emit_node",),
    # srmech_dsl_chain_run.c — the ADR-0008 chain engine's three arms
    # (a stage array may hold a loop, which runs a combinator, which runs a
    # stage array); bounded by the chain nesting the descriptor declares.
    ("dsl_run_combinator", "dsl_run_loop", "dsl_run_stage_array"),
    # srmech_dsl_chain_run.c — the F1 descriptor PARSE pair. Bounded by
    # DV_MAX_DEPTH, checked in dv_from_desc before it descends.
    ("dv_from_desc", "dv_from_list"),
    # srmech_dsl_chain_run.c — the F1 descriptor EMIT pair, the mirror of the
    # parse pair above. Same DV_MAX_DEPTH bound, checked in dv_to_desc.
    ("dv_list_to_desc", "dv_to_desc"),
    # srmech_mcp_marshal.c — JSON -> mval, over nested arrays and objects.
    ("mm_from_json", "mm_from_json_array", "mm_from_json_object"),
    # srmech_mcp_marshal.c — mval -> JSON, the mirror of the pair above.
    ("mm_serialise", "mm_serialise_dict", "mm_serialise_list"),
    # srmech_dsl_chain_run.c — the TOML -> JSON value bridge, over nested
    # tables and arrays.
    ("toml_arr_to_json", "toml_tbl_to_json", "toml_to_json"),
    # srmech_toml.c — the deferred-table finalisers.
    ("toml_finalize_atable", "toml_finalize_btable", "toml_finalize_bvalue"),
    # srmech_toml.c — the inline-value parser: an array may hold an inline
    # table, which holds a value, which may be an array.
    ("toml_parse_array", "toml_parse_inline_table", "toml_parse_value"),
}

# Down-only. Unwinding any cycle above (to an explicit stack, the usual JPL
# remedy) lowers this. It must NEVER go up: a new recursive construct is a
# Rule 1 violation, and the strict half of the gate below rejects it outright.
CEIL_RULE_1_RECURSION: int = 9

_C_KEYWORDS_CALLLIKE = frozenset({
    "if", "for", "while", "switch", "return", "sizeof", "do", "else",
})
_CALL_RE = re.compile(r"\b([a-zA-Z_][a-zA-Z_0-9]*)\s*\(")


def _function_bodies(path: Path) -> "dict[str, str]":
    """``{name: body-text}`` for every function defined in `path`.

    The body starts AFTER the opening brace on purpose: including the
    definition line would make every function appear to call itself through
    its own signature, which is a self-loop in every node and not recursion.
    """
    text = _mask_c_literals(path.read_text(encoding="utf-8"))
    lines = text.split("\n")
    def_pat = re.compile(
        r"^[a-zA-Z_][a-zA-Z_0-9 \t\*]+[ \t\*]([a-zA-Z_][a-zA-Z_0-9]+)\s*\("
    )
    starts: "list[tuple[str, int]]" = []
    for i, line in enumerate(lines):
        if line.rstrip().endswith(";"):
            continue
        m = def_pat.match(line)
        if m is None:
            continue
        if line.lstrip().startswith(("typedef", "static const", "extern", "#")):
            continue
        for look in range(i, min(i + 10, len(lines))):
            if "{" in lines[look]:
                starts.append((m.group(1), i))
                break
    out: "dict[str, str]" = {}
    for name, start_idx in starts:
        body_start = start_idx
        while body_start < len(lines) and "{" not in lines[body_start]:
            body_start += 1
        if body_start >= len(lines):
            continue
        depth = lines[body_start].count("{") - lines[body_start].count("}")
        end = len(lines) - 1
        for j in range(body_start + 1, len(lines)):
            depth += lines[j].count("{") - lines[j].count("}")
            if depth == 0:
                end = j
                break
        chunk = "\n".join(lines[body_start:end + 1])
        brace = chunk.find("{")
        out[name] = chunk[brace + 1:] if brace >= 0 else chunk
    return out


def _recursion_cycles() -> "set[tuple[str, ...]]":
    """Every direct + indirect recursion cycle in the C tree.

    Builds the whole-tree call graph (a static helper is unit-local but a
    public symbol is not, and a cycle can in principle cross files), then
    reports self-loops and every strongly-connected component of size > 1.
    """
    bodies: "dict[str, str]" = {}
    for f in sorted(_C_SRC_DIR.glob("*.c")):
        bodies.update(_function_bodies(f))
    graph = {
        name: {c for c in (m.group(1) for m in _CALL_RE.finditer(body))
               if c in bodies and c not in _C_KEYWORDS_CALLLIKE}
        for name, body in bodies.items()
    }
    cycles = {(n,) for n in graph if n in graph[n]}     # direct self-calls

    # Iterative Tarjan — the C tree has ~3k nodes, and a recursive SCC walk
    # inside the test that bans recursion would be a poor joke.
    index: "dict[str, int]" = {}
    low: "dict[str, int]" = {}
    on: "dict[str, bool]" = {}
    stack: "list[str]" = []
    counter = 0
    for root in list(graph):
        if root in index:
            continue
        work = [(root, iter(graph[root]))]
        index[root] = low[root] = counter
        counter += 1
        stack.append(root)
        on[root] = True
        while work:
            node, it = work[-1]
            descended = False
            for w in it:
                if w not in index:
                    index[w] = low[w] = counter
                    counter += 1
                    stack.append(w)
                    on[w] = True
                    work.append((w, iter(graph[w])))
                    descended = True
                    break
                if on.get(w):
                    low[node] = min(low[node], index[w])
            if descended:
                continue
            work.pop()
            if work:
                low[work[-1][0]] = min(low[work[-1][0]], low[node])
            if low[node] == index[node]:
                comp = []
                while True:
                    w = stack.pop()
                    on[w] = False
                    comp.append(w)
                    if w == node:
                        break
                if len(comp) > 1:
                    cycles.add(tuple(sorted(comp)))
    return cycles


def test_rule_1_recursion_detector_is_not_vacuous() -> None:
    """The detector must FIND the seeded population.

    Without this, a detector that silently returned nothing — a bad regex, a
    changed layout, a mask that ate every body — would make the ratchet below
    pass while measuring zero, which is precisely the "believed absent" state
    rc441 closed. An instrument that cannot return a nonzero reading is not
    an instrument.
    """
    found = _recursion_cycles()
    assert found, "the recursion detector found NOTHING — it is not looking"
    known_direct = {c for c in found if len(c) == 1}
    known_mutual = {c for c in found if len(c) > 1}
    assert known_direct, "no direct recursion found; iv_emit_node self-calls"
    assert len(known_mutual) >= 8, (
        f"only {len(known_mutual)} mutual cycles found; rc441 measured 8"
    )
    assert ("dv_from_desc", "dv_from_list") in found
    assert ("dv_list_to_desc", "dv_to_desc") in found


def test_rule_1_no_new_recursion() -> None:
    """JPL Rule 1, recursion half: strict on NEW cycles, down-only on count.

    A cycle that is not in the seeded population — including an existing
    cycle that GREW a member — fails outright. Recursion is banned; the
    seeded set is a debt record, not a licence to add more.
    """
    found = _recursion_cycles()
    novel = found - RULE_1_RECURSION_SEEDED
    assert not novel, (
        "Rule 1 violation — NEW direct/indirect recursion introduced: "
        + "; ".join(" <-> ".join(c) for c in sorted(novel))
        + ". JPL Rule 1 bans direct and indirect recursion; unwind it to an "
          "explicit bounded stack, or justify it and extend "
          "RULE_1_RECURSION_SEEDED with the depth bound that makes it safe."
    )
    assert len(found) <= CEIL_RULE_1_RECURSION, (
        f"Rule 1 recursion population {len(found)} exceeds the down-only "
        f"ceiling {CEIL_RULE_1_RECURSION}"
    )


def test_rule_1_recursion_ceiling_is_not_slack() -> None:
    """The ceiling tracks the measurement — it may not drift above it.

    A ceiling left higher than the live count is invisible slack that a
    future cycle could be added into without any gate firing.
    """
    found = _recursion_cycles()
    assert len(found) == CEIL_RULE_1_RECURSION, (
        f"live recursion population is {len(found)} but "
        f"CEIL_RULE_1_RECURSION is {CEIL_RULE_1_RECURSION} — if a cycle was "
        f"unwound, LOWER the ceiling (it is down-only) and drop its entry "
        f"from RULE_1_RECURSION_SEEDED"
    )


# Source files for which JPL Rule 3 (no malloc/free) is RELAXED at
# the cold-path setup boundary. Each entry must document the rationale
# in the JPL_AUDIT.md scope note. The relaxation does NOT extend to
# hot-path code — entries here just opt the FILE out of the regex
# scan; the spirit of Rule 3 (no allocation per-request inside the
# accept loop) still applies.
RULE_3_COLD_PATH_FILES: set[str] = {
    # v0.5.0rc2: bus C peer. calloc + malloc in srmech_bus_serve
    # (once per server start); free in srmech_bus_server_stop /
    # srmech_bus_client_close (once per teardown). No allocation in
    # srmech_bus_server_accept_one / srmech_bus_send_recv / the
    # per-request worker (those reuse the workspace allocated at
    # serve-time).
    "srmech_bus.c",
    # v0.9.0rc194: MCP HTTP+SSE C server. calloc + malloc in the cold-path
    # sse_alloc_server (once per srmech_mcp_sse_serve — the accept-thread
    # scratch buffers: reqbuf / ws / respbuf / framebuf); free in the cold-path
    # sse_free_server (once per srmech_mcp_sse_stop / serve-forever teardown).
    # NO allocation in the accept loop / per-connection handlers / SSE framing /
    # the bounded session registry (those reuse the buffers allocated at serve).
    "srmech_mcp_sse.c",
}


def test_rule_3_no_dynamic_allocation() -> None:
    """JPL Rule 3: no malloc / calloc / realloc / free / alloca.

    The ``RULE_3_COLD_PATH_FILES`` allowlist relaxes the regex scan
    for files whose only allocations are once-per-server-setup /
    once-per-server-teardown (no per-request allocation in the hot
    path). See entries above for per-file rationale.
    """
    pattern = re.compile(r"\b(malloc|calloc|realloc|free|alloca)\s*\(")
    for f in _c_files():
        if f.name in RULE_3_COLD_PATH_FILES:
            continue
        if f.name in GENERATED_DATA_FILES:
            continue
        text = f.read_text(encoding="utf-8")
        text_no_block = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
        text_no_line = re.sub(r"//.*$", "", text_no_block, flags=re.MULTILINE)
        matches = pattern.findall(text_no_line)
        assert not matches, (
            f"{f.relative_to(_HERE.parent.parent)}: Rule 3 violation "
            f"— dynamic allocation found: {matches}"
        )


# ──────────────────────────────────────────────────────────────────────
# Rule 4 (functions ≤ 60 lines) + Rule 5 (≥ 2 asserts) ratchet
# ──────────────────────────────────────────────────────────────────────


# Functions exempted from Rule 5's ≥2-assert floor. See
# JPL_AUDIT.md for rationale per entry.
RULE_5_EXEMPT_FUNCTIONS: set[str] = {
    "srmech_version",       # trivial accessor returning a constant
    "srmech_abi_version",   # trivial accessor returning a constant
    "srmech_plat_has_threads",  # PAL trivial accessor: returns a compile-time
                                # 1/0 (is a threading backend present?). No
                                # state to assert; see c/JPL_AUDIT.md.
    "srmech_plat_has_streams",  # PAL trivial accessor: returns a compile-time
                                # 1/0 (is a stream-IPC backend present?). No
                                # state to assert; see c/JPL_AUDIT.md.
    "srmech_plat_has_filesystem",  # PAL trivial accessor: returns a compile-
                                # time 1/0 (is a filesystem backend present?).
                                # No state to assert; see c/JPL_AUDIT.md.
    "srmech_plat_has_dirlist",  # PAL trivial accessor: returns a compile-time
                                # 1/0 (is a directory-iteration backend
                                # present?). No state to assert; see
                                # c/JPL_AUDIT.md.
    "srmech_plat_has_stdio",    # PAL trivial accessor (rc186): returns a
                                # compile-time 1/0 (is a stdin/stdout backend
                                # present?). No state to assert; the stdin_read
                                # / stdout_write fns carry >=2 asserts. See
                                # c/JPL_AUDIT.md.
    "srmech_plat_has_tcp",      # PAL trivial accessor (rc194): returns a
                                # compile-time 1/0 (is a TCP backend present?).
                                # No state to assert; the tcp_listen / accept /
                                # read_some / write_all fns carry >=2 asserts.
                                # See c/JPL_AUDIT.md.
    "srmech_plat_sleep_ms",     # PAL trivial OS-timer wrapper (rc194): the
                                # POSIX (nanosleep) / Windows (Sleep) bodies
                                # carry >=2 asserts; the bare-metal stub is a
                                # 1-assert no-op (no pointer/bounds invariant, a
                                # second would be a tautology). See c/JPL_AUDIT.md.
    "srmech_mcp_sse_port",      # rc194: trivial const accessor returning the
                                # handle's bound TCP port (NULL-graceful → 0);
                                # no state to assert beyond the guard, like the
                                # exempt srmech_version. See c/JPL_AUDIT.md.
    # sha256 inline helpers — 4-7 lines each, no anomalous conditions
    "srmech_ror32",
    "srmech_ch",
    "srmech_maj",
    "srmech_bigsig0",
    "srmech_bigsig1",
    "srmech_smallsig0",
    "srmech_smallsig1",
    # v0.5.0rc2: srmech_bus.c framing helpers — each is a 1-assert
    # big-endian u32 (de)serialiser on its sole pointer arg; a second
    # assert would re-assert the same pointer. Static-internal-only;
    # the public API entry points have ≥2 asserts. (v0.7.5rc5: the
    # platform read/write/ensure-dir wrappers moved to the PAL —
    # srmech_platform.c — where each gained a 2nd assert and left the
    # exempt list; the ratchet went DOWN by five entries.)
    "srmech_bus__write_u32_be",
    "srmech_bus__read_u32_be",
    # v0.7.0rc10 (F292 graft #1): srmech_sha256_batch.c `__ror` is a 1-line
    # rotate (like the exempt scalar srmech_ror32), no pointer/bounds invariant.
    "srmech_sha256b__ror",
    # v0.7.0rc11 (SIMD optimize-path HAL): srmech_simd.c CPU-feature detectors
    # are pure cpuid/xgetbv probes returning 0/1 with no pointer/bounds
    # invariant to assert (they replaced per-file copies in sha256_batch.c /
    # loopbind_hd.c — net FEWER exempt functions). srmech_simd_tier is NOT
    # exempt (it asserts env_var != NULL + max_tier >= 0). See c/JPL_AUDIT.md.
    "srmech_simd_has_avx2",
    "srmech_simd_has_avx",
    "srmech_simd_has_sse2",
    # v0.7.0rc18 (F292 graft #3): srmech_simd_has_shani is the same kind of
    # pure cpuid feature detector (leaf7 EBX bit29). srmech_sha256_shani.c
    # `__ror` is the 1-line rotate (like srmech_ror32 / srmech_sha256b__ror).
    "srmech_simd_has_shani",
    "srmech_sha256ni__ror",
    # srmech_toml.c char classifiers — pure `char -> bool` predicates over a
    # single value argument (is-whitespace / is-bare-key-char). No pointer,
    # no bounds, no state: the only "input" is a char, which has no anomalous
    # value to assert (every char is a valid input). Asserting a tautology
    # would be cargo-cult per the Rule 5 exemption policy in c/JPL_AUDIT.md;
    # same shape as the exempt sha256 ch/maj inline primitives.
    "toml_is_ws",
    "toml_is_bare_key_char",
    # srmech_json.c (§41 genome-persistence C mirror): trivial char
    # classifiers — 4-line predicates returning 0/1 over a single char,
    # no pointer/bounds invariant to assert (same kind as the TOML
    # parser's toml_is_ws). See c/JPL_AUDIT.md.
    "json_is_ws",
    "json_is_digit",
    # rc81 srmech_riemann_theta.c (the Schottky-form counter): pure value
    # ops over a single scalar argument, no pointer/bounds invariant to
    # assert (same kind as the exempt sha256 ror / toml char classifiers).
    # rtsch_class_of maps a doubled inner product -> its class index 0..4
    # (or -1); it already asserts RTSCH_NCLASS == 5. rtsch_ctz counts the
    # trailing zeros of a nonzero uint64 (the lowest set-bit index); it
    # already asserts x != 0u. See c/JPL_AUDIT.md.
    "rtsch_class_of",
    "rtsch_ctz",
    # rc165 srmech_factor_poly.c: fac_is_prime is a pure value predicate over a
    # single scalar (trial-division primality of n < 2^32) — it already asserts
    # its domain bound n < 2^32 (the loop-safety invariant, so d*d cannot
    # overflow); there is no pointer/bounds invariant for a second assert, and a
    # tautology would be cargo-cult (same kind as the exempt sha256 ror / toml
    # char classifiers). See c/JPL_AUDIT.md.
    "fac_is_prime",
    # rc242 srmech_progress.c: srmech_set_progress_cb is a trivial process-global
    # setter (stash user_data, publish the callback pointer, return the previous)
    # — both cb and user_data are NULLABLE BY DESIGN (cb == NULL clears the hook),
    # so there is no pointer/bounds invariant to assert; a tautology would be
    # cargo-cult (same kind as the exempt srmech_version / PAL accessors). The
    # non-trivial srmech_progress_emit_dispatch carries its >= 2 asserts. See
    # c/JPL_AUDIT.md.
    "srmech_set_progress_cb",
    # rc249 srmech_genome.c (#1390 item 2): gk_zig / gk_unzig are the Class-K
    # zig-zag sign transform — single-expression pure integer functions (signed
    # <-> non-negative), no pointer/bounds invariant to assert; a tautology would
    # be cargo-cult (same kind as the exempt sha256 ror). Their callers gk_emit /
    # gk_read / the encode/decode carry the >= 2 asserts. See c/JPL_AUDIT.md.
    "gk_zig",
    "gk_unzig",
}

# Maximum allowed function length (JPL Rule 4).
RULE_4_MAX_LINES: int = 60

# Minimum allowed asserts per non-exempt function (JPL Rule 5).
RULE_5_MIN_ASSERTS: int = 2


def _scan_functions(path: Path) -> list[tuple[str, int, int]]:
    """``(name, lines, asserts)`` per function — the long-standing contract.

    Derived from :func:`_scan_function_records` so that there is exactly ONE
    brace-walk in this file. rc475 (``#T1188``) needed the same walk to report
    SPANS, for Rule 2's attribution of a ``while (1)`` to its enclosing
    function; a second scanner would have been a second set of blind spots to
    keep in step, and this scanner has already had three
    (``static const``-returning definitions, the 10-line brace look-ahead, and
    braces inside char literals).
    """
    return [(name, end - start + 1, asserts)
            for name, start, end, asserts in _scan_function_records(path)]


def _scan_function_records(path: Path) -> "list[tuple[str, int, int, int]]":
    """Crude C function scanner — returns ``(name, start_line, end_line,
    asserts)`` per function defined in `path`, with the line numbers 1-BASED
    and INCLUSIVE. Same algorithm the
    JPL_AUDIT.md audit script uses; pure regex + brace counting.

    Limitations: this isn't a real C parser. It assumes srmech's
    formatting conventions: function definitions are at column 0,
    parameter list opens on the definition line, body brace opens
    on the next line OR same line.

    rc441 (``#T1148``): the scan now runs over :func:`_mask_c_literals` output
    rather than the raw text, so a ``'{'`` / ``'}'`` CHAR LITERAL — or a brace
    inside a string or a comment — can no longer run the brace counter off the
    end of the file. See that function for the measured before/after.
    """
    text = _mask_c_literals(path.read_text(encoding="utf-8"))
    lines = text.split("\n")
    # Track {definition_line_idx: (name, fn_body_open_idx)}
    fn_starts: list[tuple[str, int]] = []

    def_pat = re.compile(
        r"^[a-zA-Z_][a-zA-Z_0-9 \t\*]+[ \t\*]([a-zA-Z_][a-zA-Z_0-9]+)\s*\("
    )
    for i, line in enumerate(lines):
        # Skip declarations (semicolon-terminated)
        if line.rstrip().endswith(";"):
            continue
        m = def_pat.match(line)
        if m is None:
            continue
        # ⚠️ `static const` USED TO BE SKIPPED UNCONDITIONALLY HERE, and that
        # hid every function returning a CONST POINTER from Rules 4 and 5.
        # Measured at rc447: 24 functions across 9 files — cr_walk_json,
        # cr_find_named_chain, genome_find_chrom, json_emit_step, mc_method_spec
        # and 19 more — were scanned by nothing. The skip is meant for const
        # DATA (`static const char *const map_k[4] = {...}`), and an initializer
        # is what distinguishes the two: a definition has a parameter list and
        # no `=` ahead of it.
        #
        # All 24 measured CLEAN on both rules when first revealed, so closing
        # the hole cost zero violations — but it had to close BEFORE the map
        # arm lands, which adds ~45 functions to srmech_compose_run.c. A blind
        # spot is cheapest to fix while it is still empty.
        _is_const_data = (line.lstrip().startswith("static const")
                          and "=" in line.split("(")[0])
        if _is_const_data or line.lstrip().startswith(("typedef", "extern", "#")):
            continue
        # ⚠️ THIS LOOK-AHEAD WAS 10 LINES, AND THAT WAS THE THIRD BLIND SPOT IN
        # THIS SCANNER. A function whose PARAMETER LIST is long pushes its
        # opening brace past the window, and the scanner then never sees the
        # function at all. Measured at rc447: 42 functions across the tree,
        # with braces up to +27 lines past the definition —
        # `srmech_q_zeilberger` at +22, and it is 141 LINES against a 60 cap.
        # 12 Rule-4 and 2 Rule-5 violations had never been audited by anything.
        #
        # 40 covers the measured worst case (+27) with headroom. It is a window,
        # not a parser: the scanner still documents itself as crude, and a
        # fourth shape may exist.
        for look in range(i, min(i + 40, len(lines))):
            if "{" in lines[look] and not lines[look].lstrip().startswith("/*"):
                fn_starts.append((m.group(1), i))
                break

    # For each detected function start, count brace depth to find
    # the closing brace + count asserts in between.
    out: "list[tuple[str, int, int, int]]" = []
    for name, start_idx in fn_starts:
        depth = 0
        asserts = 0
        end_idx = start_idx
        # Find first '{'
        body_start = start_idx
        while body_start < len(lines) and "{" not in lines[body_start]:
            body_start += 1
        if body_start >= len(lines):
            continue
        depth = lines[body_start].count("{") - lines[body_start].count("}")
        for j in range(body_start + 1, len(lines)):
            depth += lines[j].count("{") - lines[j].count("}")
            if "assert(" in lines[j]:
                asserts += 1
            if depth == 0:
                end_idx = j
                break
        out.append((name, start_idx + 1, end_idx + 1, asserts))
    return out



#: ⚠️ THE SEEDED RULE-4 POPULATION (rc447). Revealed when the brace look-ahead
#: went 10 -> 40 lines; every one of these had been invisible to this audit for
#: its whole life, so none is a regression and none was introduced by the rc
#: that surfaced them.
#:
#: DOWN-ONLY, and STRICT ON NOVEL — exactly the shape `#T1148` used for the
#: Rule-1 recursion census it seeded at 9. A function not in this dict that
#: exceeds the cap FAILS; a function in it may only shrink. Removing an entry
#: (by splitting the function) is the drain, and the entry must go with it.
#:
#: They are NOT fixed here on purpose. Splitting `srmech_q_zeilberger` (141
#: lines), `srmech_q_gosper` (123) and ten more numerics kernels is a large,
#: risky change in code this rc does not otherwise touch, and doing it under
#: the pressure of a newly-red gate is how a scanner fix turns into a
#: correctness incident. Made VISIBLE and DRAINABLE now; drained deliberately.
RULE_4_SEEDED_OVER_CAP: dict[str, int] = {
    "srmech_q_zeilberger": 141,
    "srmech_q_gosper": 123,
    "srmech_graph_cycle_holonomy": 103,
    "srmech_apagodu_zeilberger": 102,
    "srmech_q_wz_verify": 93,
    "srmech_wz_verify": 84,
    "srmech_template_render": 75,
    "srmech_multivariate_elliptic_jackson": 73,
    "srmech_cn_vwp_multisum_lhs": 72,
    "srmech_zeilberger": 63,
    "srmech_ellbase_theta_canon_full": 62,
    "srmech_genome_graph_partition": 62,
}

#: The Rule-5 half of the same reveal. Same discipline: down-only, strict on
#: novel. These carry ONE assert where two are required, so the fix is additive
#: and small — but it is still a change to numerics this rc does not touch.
RULE_5_SEEDED_UNDER_MIN: dict[str, int] = {
    "srmech_graph_cycle_holonomy": 1,
    "srmech_quaternion_cycle_holonomy": 1,
}

def test_rule_4_function_length_under_60() -> None:
    """JPL Rule 4: every function ≤ 60 lines."""
    violations: list[str] = []
    for f in sorted(_C_SRC_DIR.glob("*.c")):
        for name, lines, _ in _scan_functions(f):
            if lines <= RULE_4_MAX_LINES:
                continue
            seeded = RULE_4_SEEDED_OVER_CAP.get(name)
            if seeded is None:
                violations.append(
                    f"{f.name}::{name} = {lines} lines (> {RULE_4_MAX_LINES}) "
                    f"— NOT in the seeded population, so this is NEW"
                )
            elif lines > seeded:
                violations.append(
                    f"{f.name}::{name} GREW to {lines} lines (seeded at "
                    f"{seeded}) — the seed is down-only"
                )
    assert not violations, "Rule 4 violations: " + "; ".join(violations)


def test_rule_4_seed_is_tight_and_drains():
    """The seed must describe reality EXACTLY — no stale rows, no slack.

    A seeded ceiling that is merely an upper bound stops measuring: a function
    could shrink 141 -> 70 and the row would still 'pass' while claiming 141.
    So each entry must match the CURRENT length, and an entry whose function is
    now under the cap (or gone) must be deleted.
    """
    live = {}
    for f in sorted(_C_SRC_DIR.glob("*.c")):
        for name, lines, _ in _scan_functions(f):
            if lines > RULE_4_MAX_LINES:
                live[name] = lines
    stale = sorted(n for n in RULE_4_SEEDED_OVER_CAP if n not in live)
    assert not stale, (
        "these seeded Rule-4 rows no longer exceed the cap (or no longer "
        "exist) — delete them, that is the drain: %s" % stale)
    drifted = sorted((n, RULE_4_SEEDED_OVER_CAP[n], live[n])
                     for n in RULE_4_SEEDED_OVER_CAP if live[n] != RULE_4_SEEDED_OVER_CAP[n])
    assert not drifted, (
        "seeded length does not match measured length %s — a seed that is only "
        "an upper bound has stopped measuring" % drifted)


def test_rule_5_minimum_two_asserts_per_function() -> None:
    """JPL Rule 5: every non-exempt function has ≥ 2 assertions."""
    violations: list[str] = []
    for f in sorted(_C_SRC_DIR.glob("*.c")):
        for name, _, asserts in _scan_functions(f):
            if name in RULE_5_EXEMPT_FUNCTIONS:
                continue
            if name in RULE_5_SEEDED_UNDER_MIN and \
                    asserts >= RULE_5_SEEDED_UNDER_MIN[name]:
                continue          # seeded, down-only: may only gain asserts
            if asserts < RULE_5_MIN_ASSERTS:
                violations.append(
                    f"{f.name}::{name} has {asserts} asserts "
                    f"(< {RULE_5_MIN_ASSERTS}); add asserts or document "
                    f"in RULE_5_EXEMPT_FUNCTIONS with rationale"
                )
    assert not violations, "Rule 5 violations: " + "; ".join(violations)


# ──────────────────────────────────────────────────────────────────────
# Rule 7: RETURN VALUES CHECKED (rc473 pre-publish pass, `#T1188`)
# ──────────────────────────────────────────────────────────────────────
#
# JPL Rule 7: "The return value of non-void functions must be checked by each
# calling function, and the validity of parameters must be checked inside each
# function."
#
# Through v0.9.0rc472 `c/JPL_AUDIT.md` recorded Rule 7 as "Violations: 0" and
# "✅ Pass" on a four-function evidence table, and THIS FILE contained the
# string `RULE_7` zero times — so nothing was positioned to contradict that
# sentence while `c/src` carried 24 discarded `srmech_status_t` returns across
# seven translation units. rc473 repaired the 24, and its own CHANGELOG entry
# named this ratchet as owed TWICE without shipping it. This is it.
#
# ── THE PREDICATE, STATED ─────────────────────────────────────────────
#
# An unstated predicate is why this population could not be reproduced: during
# rc473 several different cardinals were in circulation for "the Rule 7
# count" — the Class-N float family alone (24 on `b398b8c46`), every
# `(void)srmech_*(` regardless of return type (51 on this tree, 44 of them
# `srmech_plat_*` and one of them a `const char *` function), and the totals
# below. Every one was honestly measured; none of them was the same question.
#
# Rule 7 is about a returned STATUS, so the population gated here is:
#
#   CALLEE   a function whose return type is `srmech_status_t` — either an
#            export declared `[SRMECH_NODISCARD] srmech_status_t srmech_NAME(`
#            at line start in the literal-masked `c/include/srmech.h` (512 of
#            them on this tree), or a `static srmech_status_t NAME(` defined
#            in the translation unit being scanned.
#
#   DISCARD  one of TWO forms, over literal-masked text:
#            (a) `(void)NAME(` ANYWHERE on a line — the cast idiom, which is
#                the form all 24 sites rc473 repaired took (24 cast / 0 bare,
#                measured on `b398b8c46`). "Anywhere" rather than at line
#                start is load-bearing: two of the 24 sat mid-line inside
#                `if (re_arg > 0.0) { (void)srmech_rational_sqrt(...); }`, and
#                a line-start anchor finds 22 of 24.
#            (b) `NAME(` as the FIRST token on a line, where the previous
#                non-blank masked line does not end in a continuation
#                character (`= ( , + - * / ? : & | ! < > ^ %`) or in the word
#                `return`.
#
# Which clauses are load-bearing was MEASURED rather than argued, on this tree
# and on `b398b8c46`, one clause at a time:
#
#   * the continuation clause IS load-bearing — removing it takes `c/src`
#     18 -> 24 here and 42 -> 47 on main, and EVERY added row is a CHECKED
#     call, which is the property the clause exists to preserve. (That line
#     read "the added rows being `st =` followed by a wrapped `jade_pair(`
#     continuation line" until the A6 repair pass, which enumerated them with
#     this same predicate: 6 added rows here, exactly ONE of them `jade_pair`,
#     and 5 added rows on main with NONE — `jade_pair` is `static void` on
#     `b398b8c46` and so is not a status callee there at all. Four of the six
#     follow `!= SRMECH_OK ||` inside a multi-line condition rather than an
#     `st =`. The cardinals reproduced; the description of the rows did not,
#     and `notes/_rc473_a4_rule7_ratchet.py` recorded no callee breakdown to
#     check it against.);
#   * `return` in that set moves NO row on either tree. It is kept because
#     `return\n    foo(x);` is a propagation and not a discard, and it is
#     named here as a correctness clause rather than a measured one;
#   * treating a trailing `else` as a continuation moves NO row on either
#     tree, so it is NOT shipped — it would be a judgement wearing a
#     measurement's clothes, and `else\n    foo(x);` IS a discard;
#   * a "skip definition heads" clause moves NO row on either tree, because
#     form (b) cannot match a one-line definition head anyway. Not shipped:
#     a clause that cannot fire is a dead instrumentation seam.
#
# KNOWN BLIND SPOT, named here rather than discovered later: a call that is the
# SECOND statement on one line (`if (x > 0.0) { } srmech_cos(1.0, &o);`) is not
# found. That form is a BARE discard, which gcc AND clang both refuse outright
# for a `SRMECH_NODISCARD`-tagged callee — while the compiler guard's own blind
# spot is the `(void)` cast, refused on gcc alone and on nothing at all under
# `_MSC_VER` (the matrix is in `c/JPL_AUDIT.md`'s Rule 7 section). The two
# detectors' blind spots are COMPLEMENTARY, which is why this one is the
# primary detector for the form the defect actually had and not a backstop.
#
# SCOPE OF THE CALLEE POPULATION, and what it leaves out. "Header export or
# file-local static" does NOT reach a status-returning helper declared in a
# PRIVATE `c/src/*.h` and called from another TU. Measured: `srmech_platform.h`
# carries 38 such declarations, `c/include/srmech.h` mentions `srmech_plat_`
# exactly once, and 44 of the 51 residual `(void)srmech_*(` discards
# `c/JPL_AUDIT.md` enumerates are `srmech_plat_*` — so they sit outside the
# ceilings below. They are not lost: that enumeration is in the audit document,
# by symbol and by count, and most are teardown paths. Widening the population
# to `c/src/*.h` is the next drain of this ratchet and is deliberately not
# folded into the change that first ships it. The ONE `srmech_plat_*` row the
# ceilings DO hold is `srmech_plat__ensure_dir`, because it is a file-local
# `static srmech_status_t` (srmech_platform.c) rather than a cross-TU
# declaration.
#
# NOT COVERED, named: Rule 7's PARAMETER-VALIDATION half. It remains
# unmeasured — `c/JPL_AUDIT.md` says so, and its evidence table is four
# functions, two of which take no parameters.

# The C test harness. Separate from _C_SRC_DIR because it is NOT shipped:
# python/pyproject.toml's sdist.include carries `tests/**`, `../c/src/**` and
# `../c/include/**` and NOT `../c/test/**`, so in an sdist-installed cell this
# directory does not exist while c/src does. The module-level `pytestmark`
# above guards only _C_SRC_DIR, which is why the test-side ceiling below
# carries its own skip — without it the shipped sdist's own suite goes red on
# a `==` assertion against an empty scan.
_C_TEST_DIR = _HERE.parent.parent / "c" / "test"

#: The `SRMECH_NODISCARD`-tagged export roster as of the rc473 pre-publish
#: pass — 29 of the 512 status-returning declarations. Pinned LITERALLY and
#: checked TWO-WAY against a live scan of the header, because the failure this
#: catches is the attribute being silently LOST: rc473 has one recorded
#: instance already, where a line-anchored regex stopped matching the moment
#: `SRMECH_NODISCARD` landed in front of `srmech_status_t` and "the scan fell
#: from eight symbols to one".
RULE_7_NODISCARD_ROSTER: "frozenset[str]" = frozenset({
    "srmech_atan",
    "srmech_atan2",
    "srmech_atan_q61",
    "srmech_atan_series_truncate_big",
    "srmech_bigint_isqrt",
    "srmech_cos",
    "srmech_cos_q61",
    "srmech_cos_series_truncate_big",
    "srmech_exp",
    "srmech_exp_q61",
    "srmech_exp_series_truncate",
    "srmech_exp_series_truncate_big",
    "srmech_hypercomplex_couple_q61",
    "srmech_hypercomplex_couple_turn_q61",
    "srmech_hypercomplex_exp_q61",
    "srmech_isqrt",
    "srmech_log",
    "srmech_log1p_series_truncate_big",
    "srmech_log_q61",
    "srmech_octonion_exp",
    "srmech_quaternion_exp",
    "srmech_quaternion_log",
    "srmech_rational_sqrt",
    "srmech_sin",
    "srmech_sin_q61",
    "srmech_sin_series_truncate_big",
    "srmech_sqrt_q61",
    "srmech_winding_fold",
    "srmech_winding_tower",
})

#: Down-only. The residual status discards in the shipped library. Repairing
#: one (propagate it, consume it with a documented assert, or tag its callee
#: and let `-Werror` refuse it) lowers this; it must NEVER go up.
#: Seeded at the rc473 pre-publish pass: 16 `(void)` casts + 2 bare.
CEIL_RULE_7_SRC: int = 18

#: Down-only, same discipline, over the C test harness. 6 casts + 112 bare.
#: The drain path is the one rc473 walked for `c/test/test_srmech_trans_q61.c`
#: and `c/test/test_srmech_bigint.c`: a `check_*(...)` row per call site.
CEIL_RULE_7_TEST: int = 118

#: What the detector MUST see, or it is not looking. Both entries are residual
#: discards that no `(void)srmech_*(` grep can find on its own: `genome_hex` is
#: a file-local `static srmech_status_t` whose return is dropped BARE on the
#: line after a CHECKED `srmech_sha256_hex` — invisible to every cast-form
#: scan and to the attribute alike, since the attribute is plantable only on
#: declarations in the public header.
RULE_7_VACUITY_SEEDS: "set[tuple[str, str, str]]" = {
    ("srmech_genome.c", "genome_hex", "bare"),
    ("srmech_bus.c", "srmech_bus_client_close", "void"),
}

_RULE_7_HDR_DECL = re.compile(
    r"^(?P<tag>SRMECH_NODISCARD\s+)?srmech_status_t\s+(?P<name>srmech_\w+)\s*\(",
    re.MULTILINE,
)
_RULE_7_STATIC_DEF = re.compile(
    r"^static\s+srmech_status_t\s+(\w+)\s*\(", re.MULTILINE
)
_RULE_7_VOID_CAST = re.compile(r"\(\s*void\s*\)\s*([A-Za-z_]\w*)\s*\(")
_RULE_7_STMT_HEAD = re.compile(r"^\s*([A-Za-z_]\w*)\s*\(")
_RULE_7_CONTINUATION_TAIL = tuple("=(,+-*/?:&|!<>^%")
_RULE_7_RETURN_TAIL = re.compile(r"\breturn$")


def _rule7_header_population() -> "tuple[set[str], set[str]]":
    """``(every status-returning export, the SRMECH_NODISCARD-tagged subset)``.

    Read from the MASKED header so a declaration quoted inside a comment
    cannot enter the population — the same discipline the Rule 7 census had to
    adopt after an unmasked scan reported a site that was a bad spelling inside
    a block comment.
    """
    text = _mask_c_literals(
        (_C_INCLUDE_DIR / "srmech.h").read_text(encoding="utf-8")
    )
    decls: "set[str]" = set()
    tagged: "set[str]" = set()
    for m in _RULE_7_HDR_DECL.finditer(text):
        decls.add(m.group("name"))
        if m.group("tag"):
            tagged.add(m.group("name"))
    return decls, tagged


def _rule7_discards(directory: Path) -> "list[tuple[str, int, str, str]]":
    """Every status discard in ``directory``'s ``*.c``, per the predicate above.

    Returns ``(file name, 1-based line, form, callee)`` rows, where form is
    ``"void"`` (the cast idiom) or ``"bare"`` (a statement-start call).
    """
    exports, _tagged = _rule7_header_population()
    rows: "list[tuple[str, int, str, str]]" = []
    for path in sorted(directory.glob("*.c")):
        text = _mask_c_literals(path.read_text(encoding="utf-8"))
        population = exports | set(_RULE_7_STATIC_DEF.findall(text))
        previous_nonblank = ""
        for lineno, line in enumerate(text.split("\n"), 1):
            for m in _RULE_7_VOID_CAST.finditer(line):
                if m.group(1) in population:
                    rows.append((path.name, lineno, "void", m.group(1)))
            m = _RULE_7_STMT_HEAD.match(line)
            if (
                m is not None
                and m.group(1) in population
                and m.group(1) not in _C_KEYWORDS_CALLLIKE
            ):
                previous = previous_nonblank.rstrip()
                continued = previous.endswith(_RULE_7_CONTINUATION_TAIL) or bool(
                    _RULE_7_RETURN_TAIL.search(previous)
                )
                if not continued:
                    rows.append((path.name, lineno, "bare", m.group(1)))
            if line.strip():
                previous_nonblank = line
    return rows


def test_rule_7_detector_is_not_vacuous() -> None:
    """The detector must FIND the seeded residual, in BOTH forms.

    Same discipline as the Rule 1 and Rule 9 vacuity checks. A scan that
    silently returned nothing — a changed layout, a mask that ate every body,
    a regex that stopped matching when a macro moved in front of the return
    type (which has already happened once in this rc) — would make every
    ratchet below pass while measuring zero, which is the "believed absent"
    state this rule spent its whole life in.
    """
    exports, tagged = _rule7_header_population()
    assert len(exports) > 400, (
        f"the header scan found only {len(exports)} status-returning "
        "declarations; it is not parsing srmech.h"
    )
    assert tagged, "the header scan found NO SRMECH_NODISCARD-tagged export"

    found = _rule7_discards(_C_SRC_DIR)
    assert found, "the Rule 7 detector found NOTHING in c/src — it is not looking"
    seen = {(f, callee, form) for f, _line, form, callee in found}
    missing = sorted(RULE_7_VACUITY_SEEDS - seen)
    assert not missing, (
        f"the Rule 7 scan cannot see {missing} — residual discards measured at "
        "the rc473 pre-publish pass. The detector is broken, not the tree "
        "clean. Note genome_hex is a BARE discard of a file-local static: no "
        "`(void)srmech_*(` grep and no compiler attribute can reach it, which "
        "is the whole reason this form is in the predicate."
    )


def test_rule_7_no_discarded_status_from_a_tagged_callee() -> None:
    """Strict ZERO, and a two-way pin of the roster against the live header.

    The roster pin comes first because the strict-zero clause is meaningless
    without it: if the attribute were silently lost from a declaration, the
    live tagged set would shrink, and a discard of that callee would stop
    being counted at the same instant it stopped being a build error.

    Non-vacuity of the strict-zero half is measured rather than asserted:
    applying THIS roster to `b398b8c46` — the tree rc473 branched from — finds
    32 rows (24 in c/src, 8 in c/test), so the clause reads 32 -> 0 across the
    repair and can plainly return otherwise.
    """
    _exports, tagged = _rule7_header_population()
    assert tagged == set(RULE_7_NODISCARD_ROSTER), (
        "RULE_7_NODISCARD_ROSTER and the live SRMECH_NODISCARD scan of "
        "srmech.h disagree.\n"
        f"  tagged in the header but not in the roster: "
        f"{sorted(tagged - set(RULE_7_NODISCARD_ROSTER))}\n"
        f"  in the roster but no longer tagged: "
        f"{sorted(set(RULE_7_NODISCARD_ROSTER) - tagged)}\n"
        "If the attribute was added, add the name here and update the count in "
        "c/JPL_AUDIT.md's Rule 7 section in the same commit. If it was "
        "REMOVED, say why in that section — an untagged callee is one the "
        "compiler stops refusing."
    )

    directories = [_C_SRC_DIR] + ([_C_TEST_DIR] if _C_TEST_DIR.exists() else [])
    offenders = [
        (f, line, form, callee)
        for d in directories
        for (f, line, form, callee) in _rule7_discards(d)
        if callee in tagged
    ]
    assert not offenders, (
        "Rule 7 violation — the status of a SRMECH_NODISCARD-tagged callee is "
        "discarded at: "
        + "; ".join(f"{f}:{line} ({form}) {callee}" for f, line, form, callee
                    in sorted(offenders))
        + ". Propagate it, or consume it with an assert and a comment that "
          "states what makes the refusal unreachable and on which build. Note "
          "that under `_MSC_VER` the attribute expands EMPTY, so the Windows "
          "leg compiles this silently and only this gate sees it."
    )


def test_rule_7_src_ceiling_is_not_slack() -> None:
    """Down-only, and the ceiling tracks the measurement rather than leading it.

    A ceiling left above the live count is invisible slack a new discard could
    be added into with nothing firing — the same reason Rules 1 and 9 assert
    equality rather than `<=`.
    """
    found = _rule7_discards(_C_SRC_DIR)
    assert len(found) <= CEIL_RULE_7_SRC, (
        f"Rule 7 population in c/src is {len(found)}, over the down-only "
        f"ceiling {CEIL_RULE_7_SRC}. New rows: "
        + "; ".join(f"{f}:{line} ({form}) {callee}"
                    for f, line, form, callee in sorted(found))
    )
    assert len(found) == CEIL_RULE_7_SRC, (
        f"live Rule 7 population in c/src is {len(found)} but CEIL_RULE_7_SRC "
        f"is {CEIL_RULE_7_SRC} — if a discard was repaired, LOWER the ceiling "
        f"(it is down-only) and move c/JPL_AUDIT.md's Rule 7 count with it"
    )


@pytest.mark.skipif(
    not _C_TEST_DIR.exists(),
    reason=(
        "the C test harness is not present. python/pyproject.toml's "
        "sdist.include ships tests/**, ../c/src/** and ../c/include/** and "
        "NOT ../c/test/**, so an sdist-installed cell has c/src and no c/test. "
        "Without this skip the `==` assertion below would go red in the "
        "shipped artifact while every CI job — none of which installs from "
        "sdist — stayed green."
    ),
)
def test_rule_7_test_ceiling_is_not_slack() -> None:
    """The harness-side residual. Same ratchet, its own ceiling.

    Pooling this with c/src would let a c/test drain hide a c/src regression
    behind one cardinal, so the two are counted separately and neither can
    borrow the other's headroom.
    """
    found = _rule7_discards(_C_TEST_DIR)
    assert len(found) <= CEIL_RULE_7_TEST, (
        f"Rule 7 population in c/test is {len(found)}, over the down-only "
        f"ceiling {CEIL_RULE_7_TEST}"
    )
    assert len(found) == CEIL_RULE_7_TEST, (
        f"live Rule 7 population in c/test is {len(found)} but "
        f"CEIL_RULE_7_TEST is {CEIL_RULE_7_TEST} — if a discard was repaired "
        f"(the `check_*(...)` row rc473 used in test_srmech_trans_q61.c and "
        f"test_srmech_bigint.c), LOWER the ceiling; it is down-only"
    )


# ──────────────────────────────────────────────────────────────────────
# Rule 2: BOUNDED LOOPS (rc475, `#T1188` — the first detector of any kind)
# ──────────────────────────────────────────────────────────────────────
#
# JPL Rule 2: "All loops must have a fixed upper bound." `JPL_AUDIT.md` recorded
# "Violations: 0" and "We never use `while(1)` or `for(;;)`" from its first
# commit, on an eight-row illustrative table. Both sentences were FALSE, and
# they survived because this file had no Rule-2 detector at all — the same shape
# as the Rule 7 correction at rc473, where the audit read "0 violations / Pass"
# while 24 discarded statuses sat in the tree. Measured at rc475 on
# `46eeea6c9`: 17 `while (1)` / `for (;;)` sites across 10 units in `c/src`,
# identical raw and literal-masked, with ZERO in `c/include`.
#
# WHAT THE REPAIR IN THIS RC DID TO THAT NUMBER, stated rather than glossed.
# Two of the 17 were `ti_lift_mono`'s bignum-factoring loops, and they were the
# only GENUINE violations in the population: they assumed a nonzero coefficient
# with no in-loop cap, and `srmech_bigint_divmod_small(quo, &rem, 0, p)` returns
# SRMECH_OK with `quo = 0` and `rem = 0`, so on a zero they were a FIXED POINT —
# the next iteration byte-identical to the last, forever, with `e++` / `e--`
# running away on a signed int32_t. Measured by EXECUTION in both projections
# (the pure twin in `apokatastasis/thetasum.py` did not return inside 12 s on
# `Q(0, 1)`), and the sibling `ti_collect_mono_primes` 50 lines earlier guards
# exactly that state, so the tree already treated it as reachable. rc475 repairs
# both by making the zero test the loop CONDITION, which also removes both from
# this detector's view: the census is now 15, and the detector verified nothing
# about the two that left. What bounds them is arithmetic — each pass divides a
# strictly positive magnitude by p >= 2 — not the spelling.
#
# ⚠️ SEEDED BY (file, ENCLOSING FUNCTION), NOT BY (file, line). This file
# already states the reason at `RULE_9_FN_PTR_SEEDED`: "line numbers
# deliberately NOT pinned (they drift; the identifier is the site)". rc475
# proves it on itself — its own splitting change moves
# `srmech_factor_poly.c`'s `while (1)` by +92 lines, so a line-keyed table
# written against the pre-change tree would have been wrong before the rc even
# landed. The `(file, function)` table below was MEASURED byte-identical on the
# pre-change and post-change trees.
#
# ⚠️ THE SCAN IS LITERAL-MASKED, and that is measured load-bearing rather than
# insurance. A `for (;;)` QUOTED INSIDE A COMMENT is matched by a raw scan and
# correctly rejected by the masked one, and the splitting lane hit exactly that
# — its first draft's docstring quoted the retry loop it was removing, and the
# raw census counted it as an ADDED loop form. Same discipline CLAUDE.md records
# for the bare-`#NNN` ref guard.
#
# WHAT THIS CANNOT PROVE. Source SHAPE only. It cannot verify that a stated
# bound is CORRECT, that a `do { } while` or a plain `while` with a
# data-dependent condition terminates, or that a classified "invariant" holds —
# the `ti_lift_mono` rows are the standing proof that the reader can get that
# wrong, since a previous pass classified them as benign
# "invariant-terminating" and they were infinite loops. The classification in
# the seed comments is a READER's claim, recorded so it can be challenged.

_RULE2_RE = re.compile(r"while\s*\(\s*1\s*\)|for\s*\(\s*;\s*;\s*\)")

#: (file, enclosing function) -> hit count. Line numbers deliberately NOT
#: pinned (they drift — rc475 itself moved srmech_factor_poly.c's site by
#: +92 lines); the enclosing function is the site. Same discipline as
#: RULE_9_FN_PTR_SEEDED. DOWN-ONLY, and STRICT ON NOVEL.
#:
#: The class letter in each comment is the rc475 classification:
#:   (a)  PROVEN BOUND      — a stated numeric or caller-supplied limit,
#:                            checked every pass.
#:   (b1) DESIGNED-BLOCKING — a server dispatch loop, unbounded ON PURPOSE,
#:                            exiting on transport EOF / a callback stop.
#:   (b2) OS-IDIOM          — the POSIX EINTR retry; advances only on a signal.
#:   (c)  LATENT-UNBOUNDED  — the class that matters. EMPTY at rc475, because
#:                            its two members were repaired rather than seeded.
#: The (b) split is not cosmetic: lumping "blocks forever by design" together
#: with "spins forever if an upstream invariant breaks" under one letter is what
#: let two genuine infinite loops sit beside two intentional server loops.
RULE_2_SEEDED: "dict[tuple[str, str], int]" = {
    # (a) <= 2*n_syms; both indices non-decreasing, every branch returns or advances
    ("srmech_ellbase.c",         "srmech_ellbase_exps_cmp"):   1,
    # (a) C(rem_n, size); next_combo is a strictly increasing combinadic that returns 0 once exhausted
    ("srmech_factor_poly.c",     "fac_walk"):                  1,
    # (a) SRMECH_GK_MAX_DIGITS = 15, checked before every increment
    ("srmech_genome.c",          "gk_emit"):                   1,
    # (a) heap height, ceil(log2 n)
    ("srmech_genome.c",          "sc_sift"):                   1,
    # (a) heap height, ceil(log2 n)
    ("srmech_genome.c",          "gap_u64_sift"):              1,
    # (a) heap height, ceil(log2 n)
    ("srmech_genome.c",          "gap_edge_sift"):             1,
    # (a) line_cap + 1; `if (n >= cap) return OVERFLOW` precedes the increment
    ("srmech_mcp.c",             "mcp_read_line"):             1,
    # (a) SSE_REQ_CAP + 1, same shape
    ("srmech_mcp_sse.c",         "sse_read_head"):             1,
    # (a) n + 1, explicit `idx > n` exit
    ("srmech_qalg.c",            "qalg_jordan_powers"):        1,
    # (a) 27, documented inline AND asserted
    ("srmech_ryu.c",             "ryu_pow5_factor"):           1,
    # (a) TI_Z6_MAX_ATTEMPTS, the first statement in the body, commented "JPL cap"
    ("srmech_thetasum_interp.c", "ti_z6_leaf"):                1,
    # (b1) designed-blocking: a subscribe API; exits on transport EOF/error or a callback stop
    ("srmech_bus.c",             "srmech_bus_subscribe"):      1,
    # (b1) designed-blocking: JSON-RPC stdio dispatch; exits on EOF
    ("srmech_mcp.c",             "srmech_mcp_serve_stdio"):    1,
    # (b2) EINTR idiom: continues ONLY on errno == EINTR
    ("srmech_platform.c",        "srmech_plat_stdin_read"):    1,
    # (b2) EINTR idiom, identical shape
    ("srmech_platform.c",        "srmech_plat_tcp_read_some"): 1,
}

#: Total hits the masked scan must find. DOWN-ONLY, and asserted in BOTH
#: directions, so draining a site forces the table and the ceiling down
#: together. 17 before the rc475 ti_lift_mono repair; 15 after it.
CEIL_RULE_2: int = 15

#: Class-(c) rows — a loop this audit calls a GENUINE latent-infinite loop and
#: ships anyway. DOWN-ONLY, and it is 0 because rc475 REPAIRED its two members
#: rather than seeding them. A nonzero value here is the audit admitting it
#: knows about an unterminating loop, which is shipping known-broken.
CEIL_RULE_2_VIOLATION: int = 0

#: What the detector MUST see, or it is not looking: an always-present class-(a)
#: site, documented and asserted in the C itself. Mirrors Rule 9's vacuity check
#: on `srmech_ndjson_line_cb`.
RULE_2_VACUITY_SEED: "tuple[str, str]" = ("srmech_ryu.c", "ryu_pow5_factor")


def _rule2_hits() -> "tuple[dict[tuple[str, str], int], int]":
    """``({(file, enclosing function): count}, unattributed)`` over the same
    file set Rule 9 scans, on literal-MASKED text.

    ``unattributed`` counts hits that fall outside every span
    :func:`_scan_function_records` reports. It is a DETECTOR-GAP counter, not a
    finding: a hit the walker cannot place would otherwise vanish from the
    census and take the gate green with it.
    """
    found: "dict[tuple[str, str], int]" = {}
    unattributed = 0
    for path in _c_files():
        masked = _mask_c_literals(path.read_text(encoding="utf-8"))
        spans = _scan_function_records(path)
        for lineno, line in enumerate(masked.split("\n"), start=1):
            n_hits = len(_RULE2_RE.findall(line))
            if not n_hits:
                continue
            owner = None
            for name, start, end, _asserts in spans:
                if start <= lineno <= end:
                    owner = name
                    break
            if owner is None:
                unattributed += n_hits
                continue
            key = (path.name, owner)
            found[key] = found.get(key, 0) + n_hits
    return found, unattributed


def test_rule_2_detector_is_not_vacuous() -> None:
    """The scan must find a site known to be there, attributed to its owner.

    Without this, a regex that stopped matching — or a span walk that placed
    nothing — would report an empty census, and every assertion below would
    pass on it.
    """
    found, _unattributed = _rule2_hits()
    assert RULE_2_VACUITY_SEED in found, (
        f"Rule 2 detector found no `for (;;)` in {RULE_2_VACUITY_SEED[1]} "
        f"({RULE_2_VACUITY_SEED[0]}) — a documented, asserted, always-present "
        f"class-(a) site. The scan is broken, not the tree. Census was: "
        f"{sorted(found)}"
    )
    assert found, "Rule 2 census is empty; 15 sites were measured at rc475"


def test_rule_2_no_new_unbounded_loops() -> None:
    """STRICT on novelty: a NEW `while (1)` / `for (;;)` fails outright.

    A seeded site may only shrink. Both halves matter — a new loop form in a
    function that already has one would otherwise hide inside its count.
    """
    found, _unattributed = _rule2_hits()
    novel = sorted(set(found) - set(RULE_2_SEEDED))
    assert not novel, (
        "NEW unbounded loop form(s) — JPL Rule 2 requires a fixed upper bound "
        "on every loop:\n  "
        + "\n  ".join(f"{f}: {fn} ({found[(f, fn)]} hit(s))" for f, fn in novel)
        + "\nIf the loop genuinely has a bound, express it in the loop HEADER "
          "(a counted `for`, or a `while` whose condition is the bound) rather "
          "than seeding it here. If it cannot be, it is class (c) and the "
          "answer is to fix it: rc475 measured two such loops and both were "
          "infinite on a reachable input."
    )
    grown = sorted(
        (k, RULE_2_SEEDED[k], found[k]) for k in found
        if k in RULE_2_SEEDED and found[k] > RULE_2_SEEDED[k]
    )
    assert not grown, (
        "seeded Rule 2 site(s) GREW — down-only:\n  "
        + "\n  ".join(f"{f}: {fn} {was} -> {now}" for (f, fn), was, now in grown)
    )


def test_rule_2_ceiling_is_not_slack() -> None:
    """``sum(found) == CEIL_RULE_2``, in BOTH directions.

    An inequality would let the census drift downward silently and leave a seed
    table describing loops that no longer exist. Equality forces a drain to move
    the table and the ceiling in the same commit — the discipline the Rule 4 and
    Rule 7 seeds already use.
    """
    found, _unattributed = _rule2_hits()
    total = sum(found.values())
    assert total == CEIL_RULE_2, (
        f"Rule 2 census is {total}, CEIL_RULE_2 is {CEIL_RULE_2}. "
        + ("A site was DRAINED — lower the ceiling and remove its row from "
           "RULE_2_SEEDED in the same commit." if total < CEIL_RULE_2 else
           "A site was ADDED — see test_rule_2_no_new_unbounded_loops.")
        + f" Census: {sorted(found.items())}"
    )
    seeded_total = sum(RULE_2_SEEDED.values())
    assert seeded_total == CEIL_RULE_2, (
        f"RULE_2_SEEDED sums to {seeded_total} but CEIL_RULE_2 is "
        f"{CEIL_RULE_2}; the table and the ceiling must agree by construction"
    )
    assert CEIL_RULE_2_VIOLATION == 0, (
        f"CEIL_RULE_2_VIOLATION is {CEIL_RULE_2_VIOLATION}, not 0 — the audit "
        "is recording a loop it calls genuinely unterminating and shipping it. "
        "Repair it instead; rc475's two class-(c) rows cost ~6 lines of C and "
        "~4 of Python, mirroring a guard the same file already had."
    )


def test_rule_2_every_hit_is_attributed() -> None:
    """``unattributed == 0`` — the detector's own blind-spot guard.

    A `while (1)` the function walker cannot place is invisible to the seed
    table, to the novelty check and to the ceiling at once, so the gate would go
    green on a gap rather than on a clean tree. This scanner has had three
    measured blind spots already (see :func:`_scan_function_records`), which is
    the argument for counting rather than assuming.
    """
    found, unattributed = _rule2_hits()
    assert unattributed == 0, (
        f"{unattributed} Rule 2 hit(s) fall outside every function span the "
        f"scanner reports, so they are in the tree and NOT in the census "
        f"({sum(found.values())} attributed). Fix the span walk — do not widen "
        f"the ceiling."
    )


def test_rule_2_planted_loop_is_detected() -> None:
    """Prove the predicate can FAIL, on both spellings and through the mask.

    Replays what a future author would actually write, through the same regex
    and the same masking helper the gate uses. Without this, "no novel sites"
    and "the regex no longer matches anything" read identically green.
    """
    src = (
        "static int planted(void)\n"
        "{\n"
        "    for (;;) { break; }\n"
        "    while (1) { break; }\n"
        "    return 0;\n"
        "}\n"
    )
    assert len(_RULE2_RE.findall(src)) == 2, "both spellings must match"
    assert _RULE2_RE.search("while(1)") is not None, "no-space spelling"
    assert _RULE2_RE.search("for(;;)") is not None, "no-space spelling"

    # ...and the mask must SUPPRESS a quoted one. This is the control that
    # caught a real false positive: a draft docstring quoting the loop it
    # removed, counted by the raw census as an ADDED loop form.
    quoted = "/* the old retry was `for (;;) { ... }` here */\nint x;\n"
    assert _RULE2_RE.search(quoted) is not None, "raw scan sees the comment"
    assert _RULE2_RE.search(_mask_c_literals(quoted)) is None, (
        "the literal mask must reject a `for (;;)` quoted inside a comment"
    )
    in_string = 'const char *s = "for (;;)";\n'
    assert _RULE2_RE.search(_mask_c_literals(in_string)) is None, (
        "the literal mask must reject a `for (;;)` inside a string literal"
    )


def test_rule_8_no_multiline_macros() -> None:
    """JPL Rule 8: no multi-line macros, no token-paste, no varargs."""
    forbidden = re.compile(r"##|__VA_ARGS__|\\\s*$")
    for f in _c_files():
        text = f.read_text(encoding="utf-8")
        for i, line in enumerate(text.split("\n"), 1):
            # Only check inside #define lines
            stripped = line.lstrip()
            if not stripped.startswith("#define"):
                continue
            if forbidden.search(line):
                pytest.fail(
                    f"{f.name}:{i}: Rule 8 violation — "
                    f"multi-line macro / token-paste / VA_ARGS in "
                    f"#define: {line.rstrip()!r}"
                )


# ──────────────────────────────────────────────────────────────────────
# Rule 9: FUNCTION POINTERS (rc452, the A1-dispatch census)
# ──────────────────────────────────────────────────────────────────────
#
# JPL Rule 9: "Function pointers are not permitted." Through the whole life of
# this file, NOTHING measured that — the module docstring says Rules 1/3/4/5/8
# are the mechanically detectable set, and JPL_AUDIT.md documented exactly ONE
# deliberate deviation (the `srmech_ndjson_line_cb` callback). The census that
# closed the gap (masked scan over src/*.c + src/*.h + include/*.h, 150 files)
# measured **14 function-pointer declarator sites across 5 files**, of which
# 12 PREDATED rc452 — including `IV_VTABLE` in src/srmech_invoke.c, a 38-row
# name-to-function-pointer dispatch table shipped since ~rc189. So "passes all
# ten rules" was ALREADY FALSE before rc452, and rc452's first cut grew the
# undocumented population from 12 to 14 without tripping anything.
#
# rc452's A1 dispatch drained srmech_compose_run.c 4 -> 0 (two rc452-new table
# typedefs, plus the two PRE-rc452 sites: the `cr_series_fn_t` typedef and
# `cr_op_dseq`'s inline fn param — all replaced by small-int enums + no-default
# switches). The remaining population is seeded below, down-only. The next
# drain, by the identical recipe (enum + bounded switch, no `default:` arm), is
# **IV_VTABLE / `iv_thunk_t` in srmech_invoke.c** — deliberately NOT done in
# the same change as the census, so the drain lands reviewed on its own.
#
# The seven `include/srmech.h` sites are the PUBLIC CALLBACK TYPEDEFS
# (progress / ndjson / cascade-op / bus). They are wire contract: each is bound
# as a ctypes CFUNCTYPE and several drove ABI bumps (v2-v6). Draining those is
# an API redesign, not a refactor, which is exactly why the record must be a
# SEEDED population rather than a silent pass.

#: The Rule-9 population as measured after the rc452 A1 dispatch landed.
#: (file name, declarator identifier) pairs — line numbers deliberately NOT
#: pinned (they drift; the identifier is the site).
RULE_9_FN_PTR_SEEDED: "set[tuple[str, str]]" = {
    # src — the two remaining in-library sites, both named next-drain material
    ("srmech_invoke.c", "iv_thunk_t"),          # IV_VTABLE, 38 rows — NEXT DRAIN
    ("srmech_laplacian.c", "fiedler_rec_cb"),
    # src/srmech_platform.h — the thread-start shape the platform shim needs
    ("srmech_platform.h", "srmech_plat_thread_fn"),
    # include/srmech.h — public callback typedefs, CFUNCTYPE wire contract
    ("srmech.h", "srmech_progress_tick_cb_t"),
    ("srmech.h", "srmech_ndjson_line_cb"),      # the ONE documented deviation
    ("srmech.h", "srmech_cascade_op_callback_f64_t"),
    ("srmech.h", "srmech_cascade_body_f64"),
    ("srmech.h", "srmech_bus_handler_callback_t"),
    ("srmech.h", "srmech_bus_subscriber_callback_t"),
    ("srmech.h", "srmech_progress_cb_t"),
}

#: Down-only. Draining a site above (enum + bounded switch, the A1 recipe)
#: lowers this; it must NEVER go up.
CEIL_RULE_9_FN_PTR: int = 10

#: A function-pointer DECLARATOR: `(*name)(`, run over literal-masked text so
#: a mention inside a comment or string cannot count. This catches typedefs,
#: struct columns and inline function-pointer PARAMETERS alike — all three
#: shapes existed in the measured population.
_FN_PTR_RE = re.compile(r"\(\s*\*\s*(\w+)\s*\)\s*\(")


def _rule9_files() -> "list[Path]":
    """src/*.c + src/*.h + include/*.h — the census scope, stated.

    Wider than :func:`_c_files` on purpose: that helper misses ``src/*.h``,
    and ``src/srmech_platform.h`` carries a seeded site. ``c/test/`` stays
    out of scope — harness code is not the shipped library.
    """
    return (sorted(_C_SRC_DIR.glob("*.c")) + sorted(_C_SRC_DIR.glob("*.h"))
            + sorted(_C_INCLUDE_DIR.glob("*.h")))


def _fn_ptr_sites() -> "set[tuple[str, str]]":
    """Every (file, declarator-name) function-pointer site in scope."""
    sites: "set[tuple[str, str]]" = set()
    for f in _rule9_files():
        text = _mask_c_literals(f.read_text(encoding="utf-8"))
        for m in _FN_PTR_RE.finditer(text):
            sites.add((f.name, m.group(1)))
    return sites


def test_rule_9_detector_is_not_vacuous() -> None:
    """The detector must FIND the one deviation JPL_AUDIT.md always documented.

    A scanner that cannot find `srmech_ndjson_line_cb` — the callback the
    audit has named since Phase B6 — is not a scanner, and the ratchet below
    would then pass while measuring zero. Same discipline as the Rule 1
    recursion detector's vacuity check.
    """
    found = _fn_ptr_sites()
    assert found, "the Rule 9 detector found NOTHING — it is not looking"
    assert ("srmech.h", "srmech_ndjson_line_cb") in found, (
        "the Rule 9 scan cannot see srmech_ndjson_line_cb, the ONE deviation "
        "JPL_AUDIT.md has documented since Phase B6 — the detector is broken, "
        "not the tree clean"
    )


def test_rule_9_no_new_function_pointers() -> None:
    """JPL Rule 9: strict on NOVEL sites, down-only on the seeded population.

    A function-pointer declarator not in the seeded set fails outright — the
    A1 dispatch (enum columns + per-domain no-default switches, see
    srmech_compose_run.c) is the shipped replacement shape, and it is SMALLER
    than the wrappers a function-pointer column needs. The seeded set is a
    debt record, not a licence: JPL_AUDIT.md Rule 9 carries the same census
    and the two must move together.
    """
    found = _fn_ptr_sites()
    novel = found - RULE_9_FN_PTR_SEEDED
    assert not novel, (
        "Rule 9 violation — NEW function-pointer declarator site(s): "
        + "; ".join(f"{f}:{n}" for f, n in sorted(novel))
        + ". Function pointers are not permitted; use the A1 dispatch shape "
          "(small-int enum column + bounded switch with NO default arm, so "
          "-Wswitch/-Werror and /w44062//WX make drift a compile error), or "
          "justify a wire-contract callback in JPL_AUDIT.md AND extend "
          "RULE_9_FN_PTR_SEEDED in the same commit."
    )
    assert len(found) <= CEIL_RULE_9_FN_PTR, (
        f"Rule 9 population {len(found)} exceeds the down-only ceiling "
        f"{CEIL_RULE_9_FN_PTR}"
    )


def test_rule_9_ceiling_is_not_slack() -> None:
    """The ceiling tracks the measurement — it may not drift above it."""
    found = _fn_ptr_sites()
    assert len(found) == CEIL_RULE_9_FN_PTR, (
        f"live Rule 9 population is {len(found)} but CEIL_RULE_9_FN_PTR is "
        f"{CEIL_RULE_9_FN_PTR} — if a site was drained, LOWER the ceiling "
        f"(it is down-only), drop its entry from RULE_9_FN_PTR_SEEDED, and "
        f"update JPL_AUDIT.md's Rule 9 census in the same commit"
    )


def test_audit_doc_present_and_mentions_all_rules() -> None:
    """Sanity check: JPL_AUDIT.md exists and references every rule
    by number, so an auditor can find the rationale per rule."""
    audit = _C_SRC_DIR.parent / "JPL_AUDIT.md"
    assert audit.exists(), f"missing {audit}"
    text = audit.read_text(encoding="utf-8")
    for n in range(1, 11):
        marker = f"Rule {n}"
        assert marker in text, (
            f"JPL_AUDIT.md does not mention {marker!r}"
        )
