"""JPL Power-of-Ten ratchet for srmech's C library.

Task #201 Phase B6 — mechanically detectable rule violations are
pinned at the counts documented in
``docs/srmech/c/JPL_AUDIT.md``. The pins can only go DOWN
(violations removed), never UP (violations added).

A PR that pushes a new function over 60 lines, removes an assertion
from a function below the 2-assert floor, introduces a goto /
malloc / multi-line macro, etc. will fail this test.

Mirrors the discipline of ephemerides-spectral's
``tests/test_jpl_audit.py``.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest


# The C source tree lives at docs/srmech/c/, three levels up from
# this test file (tests/ -> python/ -> srmech/ -> c/ sibling of python/).
_HERE = Path(__file__).resolve().parent
_C_SRC_DIR = _HERE.parent.parent / "c" / "src"
_C_INCLUDE_DIR = _HERE.parent.parent / "c" / "include"


def _c_files() -> list[Path]:
    """All srmech C source files we audit."""
    files = sorted(_C_SRC_DIR.glob("*.c"))
    files += sorted(_C_INCLUDE_DIR.glob("*.h"))
    return files


pytestmark = pytest.mark.skipif(
    not _C_SRC_DIR.exists(),
    reason=(
        "C source tree not present "
        f"({_C_SRC_DIR} does not exist); "
        "this test pins the JPL audit of the C library and is "
        "only meaningful when the C sources are checked out"
    ),
)


# ──────────────────────────────────────────────────────────────────────
# Rule-by-rule mechanical pins
# ──────────────────────────────────────────────────────────────────────


# Generated pure-DATA translation units — const tables ONLY, zero
# executable code. Their string-literal VALUES (e.g. ToolEntry summaries)
# are arbitrary English prose that can contain tokens like "free(" or
# "goto" which the mechanical string-content regex scans (Rule 1 goto /
# Rule 3 malloc) would mis-flag INSIDE a data string. These files are
# excluded from those two regex rules. The function-scan rules (Rule 4
# length / Rule 5 asserts) already find ZERO functions in them (const
# array declarations are not functions), so they stay in-scope there as a
# guard that the file remains data-only. See c/JPL_AUDIT.md.
GENERATED_DATA_FILES: set[str] = {
    # rc184 — the C MCP-server tool registry, generated by
    # c/tools/gen_tool_registry.py. A const srmech_tool_entry_t[] table
    # whose summary strings are the (English) ToolEntry summaries.
    "srmech_tool_registry.c",
}


def _mask_c_literals(text: str) -> str:
    """Blank the CONTENT of comments, string literals and CHAR literals,
    preserving every newline so line numbers and line counts are unchanged.

    rc441 (``#T1148``) — this is the fix for the scanner's brace-literal
    blindness. :func:`_scan_functions` finds a function's end by counting
    ``{`` and ``}`` per line, and it counted them in ``'{'`` / ``'}'`` CHAR
    LITERALS too. A JSON scanner written in C is full of those, so its brace
    depth never returned to zero, the scan ran off the end of the file, and
    the function was reported as ``lines=1`` — under Rule 4's 60-line limit by
    an accident of arithmetic rather than by being short.

    The second consequence was worse and is why this is not cosmetic: the
    same runaway scan kept counting ``assert(`` all the way to EOF, so those
    functions reported HUNDREDS of assertions. Rule 5 (>= 2 asserts) was
    therefore vacuous exactly where the scanner had lost its place. Measured
    on rc440: ``genome_json_object_span`` reported ``lines=1 asserts=458`` and
    ``genome_find_attest_span`` reported ``lines=1 asserts=456``; the census
    that produced this fix found a THIRD, ``toml_parse_value``
    (``lines=1 asserts=35``), which no prior report had named.

    Post-fix measurement, whole tree (138 files, 3092 functions): the detected
    function SET is unchanged (0 added, 0 removed) and exactly FIVE functions
    change their numbers -- the three above become
    ``(24, 2)`` / ``(20, 2)`` / ``(35, 2)``, ``toml_parse_inline_table`` grows
    ``54 -> 58`` lines (a real length the old counter under-reported), and
    ``srmech_bigint_pow_bound`` drops ``3 -> 2`` asserts (one ``assert(`` was
    inside a comment). NO new Rule 4 or Rule 5 violation appears, which is why
    the strict-zero ratchets on both rules stay strict-zero.
    """
    out: list[str] = []
    i, n = 0, len(text)
    state = "code"                     # code | line_comment | block | str | chr
    while i < n:
        c = text[i]
        nxt = text[i + 1] if i + 1 < n else ""
        if state == "code":
            if c == "/" and nxt == "/":
                state, i = "line_comment", i + 2
                out.append("  ")
                continue
            if c == "/" and nxt == "*":
                state, i = "block", i + 2
                out.append("  ")
                continue
            if c == '"':
                state, i = "str", i + 1
                out.append(" ")
                continue
            if c == "'":
                state, i = "chr", i + 1
                out.append(" ")
                continue
            out.append(c)
            i += 1
            continue
        if state == "line_comment":
            out.append("\n" if c == "\n" else " ")
            if c == "\n":
                state = "code"
            i += 1
            continue
        if state == "block":
            if c == "*" and nxt == "/":
                state, i = "code", i + 2
                out.append("  ")
                continue
            out.append("\n" if c == "\n" else " ")
            i += 1
            continue
        # inside a string or char literal
        if c == "\\":                  # an escape consumes its successor
            out.append("  ")
            i += 2
            continue
        if (state == "str" and c == '"') or (state == "chr" and c == "'"):
            state, i = "code", i + 1
            out.append(" ")
            continue
        out.append("\n" if c == "\n" else " ")
        i += 1
    return "".join(out)


def test_rule_1_no_goto() -> None:
    """JPL Rule 1: no goto, no setjmp / longjmp."""
    pattern = re.compile(r"\b(goto|setjmp|longjmp)\b")
    for f in _c_files():
        if f.name in GENERATED_DATA_FILES:
            continue
        text = f.read_text(encoding="utf-8")
        # Strip /* ... */ and // comments so doc mentions don't count
        text_no_block = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
        text_no_line = re.sub(r"//.*$", "", text_no_block, flags=re.MULTILINE)
        matches = pattern.findall(text_no_line)
        assert not matches, (
            f"{f.relative_to(_HERE.parent.parent)}: Rule 1 violation "
            f"— goto/setjmp/longjmp found: {matches}"
        )


# ──────────────────────────────────────────────────────────────────────
# Rule 1, second half: RECURSION (rc441, `#T1148`)
# ──────────────────────────────────────────────────────────────────────
#
# JPL Rule 1 bans "direct or indirect recursion". Through rc440 the Rule 1
# test above grepped for `goto|setjmp|longjmp` and NOTHING ELSE — it did not
# look for recursion at all, while `docs/srmech/c/JPL_AUDIT.md` stated that
# all ten rules pass. The rule's own subject was unmeasured, so the surface
# was BELIEVED ABSENT rather than known-clean.
#
# The census that closed it (whole tree: 138 files, 3092 functions) found
# NINE recursion cycles — one direct, eight mutual. A prior report had named
# two of the eight; the tree carries 4.5x that. So this ships as a SEEDED
# DOWN-ONLY ratchet, not as strict zero: the population is real, it is
# depth-bounded by construction in every case, and unwinding it is a
# different piece of work from being able to SEE it.
#
# The gate is strict on the decidable class — a NEW cycle, or a cycle whose
# membership changed, fails immediately — and down-only on the count.

# The recursion population as measured at rc441. Each entry is a cycle: a
# 1-tuple is direct self-recursion, an n-tuple is a mutual cycle (sorted).
# Every one of these is depth-bounded in the source (an explicit depth
# parameter checked against a compiled-in cap, or a bounded nesting level),
# which is why they were tolerable while invisible — but Rule 1's objection
# is to the CONSTRUCT, because a bound that is not enforced by the call
# structure is a bound that a later edit can move.
RULE_1_RECURSION_SEEDED: set = {
    # srmech_invoke.c — the mval -> JSON emitter. Self-recurses on nested
    # list/tuple items (`iv_emit_node(e, v->items[k], depth + 1u)`), bounded
    # by an explicit `depth` argument.
    ("iv_emit_node",),
    # srmech_dsl_chain_run.c — the ADR-0008 chain engine's three arms
    # (a stage array may hold a loop, which runs a combinator, which runs a
    # stage array); bounded by the chain nesting the descriptor declares.
    ("dsl_run_combinator", "dsl_run_loop", "dsl_run_stage_array"),
    # srmech_dsl_chain_run.c — the F1 descriptor PARSE pair. Bounded by
    # DV_MAX_DEPTH, checked in dv_from_desc before it descends.
    ("dv_from_desc", "dv_from_list"),
    # srmech_dsl_chain_run.c — the F1 descriptor EMIT pair, the mirror of the
    # parse pair above. Same DV_MAX_DEPTH bound, checked in dv_to_desc.
    ("dv_list_to_desc", "dv_to_desc"),
    # srmech_mcp_marshal.c — JSON -> mval, over nested arrays and objects.
    ("mm_from_json", "mm_from_json_array", "mm_from_json_object"),
    # srmech_mcp_marshal.c — mval -> JSON, the mirror of the pair above.
    ("mm_serialise", "mm_serialise_dict", "mm_serialise_list"),
    # srmech_dsl_chain_run.c — the TOML -> JSON value bridge, over nested
    # tables and arrays.
    ("toml_arr_to_json", "toml_tbl_to_json", "toml_to_json"),
    # srmech_toml.c — the deferred-table finalisers.
    ("toml_finalize_atable", "toml_finalize_btable", "toml_finalize_bvalue"),
    # srmech_toml.c — the inline-value parser: an array may hold an inline
    # table, which holds a value, which may be an array.
    ("toml_parse_array", "toml_parse_inline_table", "toml_parse_value"),
}

# Down-only. Unwinding any cycle above (to an explicit stack, the usual JPL
# remedy) lowers this. It must NEVER go up: a new recursive construct is a
# Rule 1 violation, and the strict half of the gate below rejects it outright.
CEIL_RULE_1_RECURSION: int = 9

_C_KEYWORDS_CALLLIKE = frozenset({
    "if", "for", "while", "switch", "return", "sizeof", "do", "else",
})
_CALL_RE = re.compile(r"\b([a-zA-Z_][a-zA-Z_0-9]*)\s*\(")


def _function_bodies(path: Path) -> "dict[str, str]":
    """``{name: body-text}`` for every function defined in `path`.

    The body starts AFTER the opening brace on purpose: including the
    definition line would make every function appear to call itself through
    its own signature, which is a self-loop in every node and not recursion.
    """
    text = _mask_c_literals(path.read_text(encoding="utf-8"))
    lines = text.split("\n")
    def_pat = re.compile(
        r"^[a-zA-Z_][a-zA-Z_0-9 \t\*]+[ \t\*]([a-zA-Z_][a-zA-Z_0-9]+)\s*\("
    )
    starts: "list[tuple[str, int]]" = []
    for i, line in enumerate(lines):
        if line.rstrip().endswith(";"):
            continue
        m = def_pat.match(line)
        if m is None:
            continue
        if line.lstrip().startswith(("typedef", "static const", "extern", "#")):
            continue
        for look in range(i, min(i + 10, len(lines))):
            if "{" in lines[look]:
                starts.append((m.group(1), i))
                break
    out: "dict[str, str]" = {}
    for name, start_idx in starts:
        body_start = start_idx
        while body_start < len(lines) and "{" not in lines[body_start]:
            body_start += 1
        if body_start >= len(lines):
            continue
        depth = lines[body_start].count("{") - lines[body_start].count("}")
        end = len(lines) - 1
        for j in range(body_start + 1, len(lines)):
            depth += lines[j].count("{") - lines[j].count("}")
            if depth == 0:
                end = j
                break
        chunk = "\n".join(lines[body_start:end + 1])
        brace = chunk.find("{")
        out[name] = chunk[brace + 1:] if brace >= 0 else chunk
    return out


def _recursion_cycles() -> "set[tuple[str, ...]]":
    """Every direct + indirect recursion cycle in the C tree.

    Builds the whole-tree call graph (a static helper is unit-local but a
    public symbol is not, and a cycle can in principle cross files), then
    reports self-loops and every strongly-connected component of size > 1.
    """
    bodies: "dict[str, str]" = {}
    for f in sorted(_C_SRC_DIR.glob("*.c")):
        bodies.update(_function_bodies(f))
    graph = {
        name: {c for c in (m.group(1) for m in _CALL_RE.finditer(body))
               if c in bodies and c not in _C_KEYWORDS_CALLLIKE}
        for name, body in bodies.items()
    }
    cycles = {(n,) for n in graph if n in graph[n]}     # direct self-calls

    # Iterative Tarjan — the C tree has ~3k nodes, and a recursive SCC walk
    # inside the test that bans recursion would be a poor joke.
    index: "dict[str, int]" = {}
    low: "dict[str, int]" = {}
    on: "dict[str, bool]" = {}
    stack: "list[str]" = []
    counter = 0
    for root in list(graph):
        if root in index:
            continue
        work = [(root, iter(graph[root]))]
        index[root] = low[root] = counter
        counter += 1
        stack.append(root)
        on[root] = True
        while work:
            node, it = work[-1]
            descended = False
            for w in it:
                if w not in index:
                    index[w] = low[w] = counter
                    counter += 1
                    stack.append(w)
                    on[w] = True
                    work.append((w, iter(graph[w])))
                    descended = True
                    break
                if on.get(w):
                    low[node] = min(low[node], index[w])
            if descended:
                continue
            work.pop()
            if work:
                low[work[-1][0]] = min(low[work[-1][0]], low[node])
            if low[node] == index[node]:
                comp = []
                while True:
                    w = stack.pop()
                    on[w] = False
                    comp.append(w)
                    if w == node:
                        break
                if len(comp) > 1:
                    cycles.add(tuple(sorted(comp)))
    return cycles


def test_rule_1_recursion_detector_is_not_vacuous() -> None:
    """The detector must FIND the seeded population.

    Without this, a detector that silently returned nothing — a bad regex, a
    changed layout, a mask that ate every body — would make the ratchet below
    pass while measuring zero, which is precisely the "believed absent" state
    rc441 closed. An instrument that cannot return a nonzero reading is not
    an instrument.
    """
    found = _recursion_cycles()
    assert found, "the recursion detector found NOTHING — it is not looking"
    known_direct = {c for c in found if len(c) == 1}
    known_mutual = {c for c in found if len(c) > 1}
    assert known_direct, "no direct recursion found; iv_emit_node self-calls"
    assert len(known_mutual) >= 8, (
        f"only {len(known_mutual)} mutual cycles found; rc441 measured 8"
    )
    assert ("dv_from_desc", "dv_from_list") in found
    assert ("dv_list_to_desc", "dv_to_desc") in found


def test_rule_1_no_new_recursion() -> None:
    """JPL Rule 1, recursion half: strict on NEW cycles, down-only on count.

    A cycle that is not in the seeded population — including an existing
    cycle that GREW a member — fails outright. Recursion is banned; the
    seeded set is a debt record, not a licence to add more.
    """
    found = _recursion_cycles()
    novel = found - RULE_1_RECURSION_SEEDED
    assert not novel, (
        "Rule 1 violation — NEW direct/indirect recursion introduced: "
        + "; ".join(" <-> ".join(c) for c in sorted(novel))
        + ". JPL Rule 1 bans direct and indirect recursion; unwind it to an "
          "explicit bounded stack, or justify it and extend "
          "RULE_1_RECURSION_SEEDED with the depth bound that makes it safe."
    )
    assert len(found) <= CEIL_RULE_1_RECURSION, (
        f"Rule 1 recursion population {len(found)} exceeds the down-only "
        f"ceiling {CEIL_RULE_1_RECURSION}"
    )


def test_rule_1_recursion_ceiling_is_not_slack() -> None:
    """The ceiling tracks the measurement — it may not drift above it.

    A ceiling left higher than the live count is invisible slack that a
    future cycle could be added into without any gate firing.
    """
    found = _recursion_cycles()
    assert len(found) == CEIL_RULE_1_RECURSION, (
        f"live recursion population is {len(found)} but "
        f"CEIL_RULE_1_RECURSION is {CEIL_RULE_1_RECURSION} — if a cycle was "
        f"unwound, LOWER the ceiling (it is down-only) and drop its entry "
        f"from RULE_1_RECURSION_SEEDED"
    )


# Source files for which JPL Rule 3 (no malloc/free) is RELAXED at
# the cold-path setup boundary. Each entry must document the rationale
# in the JPL_AUDIT.md scope note. The relaxation does NOT extend to
# hot-path code — entries here just opt the FILE out of the regex
# scan; the spirit of Rule 3 (no allocation per-request inside the
# accept loop) still applies.
RULE_3_COLD_PATH_FILES: set[str] = {
    # v0.5.0rc2: bus C peer. calloc + malloc in srmech_bus_serve
    # (once per server start); free in srmech_bus_server_stop /
    # srmech_bus_client_close (once per teardown). No allocation in
    # srmech_bus_server_accept_one / srmech_bus_send_recv / the
    # per-request worker (those reuse the workspace allocated at
    # serve-time).
    "srmech_bus.c",
    # v0.9.0rc194: MCP HTTP+SSE C server. calloc + malloc in the cold-path
    # sse_alloc_server (once per srmech_mcp_sse_serve — the accept-thread
    # scratch buffers: reqbuf / ws / respbuf / framebuf); free in the cold-path
    # sse_free_server (once per srmech_mcp_sse_stop / serve-forever teardown).
    # NO allocation in the accept loop / per-connection handlers / SSE framing /
    # the bounded session registry (those reuse the buffers allocated at serve).
    "srmech_mcp_sse.c",
}


def test_rule_3_no_dynamic_allocation() -> None:
    """JPL Rule 3: no malloc / calloc / realloc / free / alloca.

    The ``RULE_3_COLD_PATH_FILES`` allowlist relaxes the regex scan
    for files whose only allocations are once-per-server-setup /
    once-per-server-teardown (no per-request allocation in the hot
    path). See entries above for per-file rationale.
    """
    pattern = re.compile(r"\b(malloc|calloc|realloc|free|alloca)\s*\(")
    for f in _c_files():
        if f.name in RULE_3_COLD_PATH_FILES:
            continue
        if f.name in GENERATED_DATA_FILES:
            continue
        text = f.read_text(encoding="utf-8")
        text_no_block = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
        text_no_line = re.sub(r"//.*$", "", text_no_block, flags=re.MULTILINE)
        matches = pattern.findall(text_no_line)
        assert not matches, (
            f"{f.relative_to(_HERE.parent.parent)}: Rule 3 violation "
            f"— dynamic allocation found: {matches}"
        )


# ──────────────────────────────────────────────────────────────────────
# Rule 4 (functions ≤ 60 lines) + Rule 5 (≥ 2 asserts) ratchet
# ──────────────────────────────────────────────────────────────────────


# Functions exempted from Rule 5's ≥2-assert floor. See
# JPL_AUDIT.md for rationale per entry.
RULE_5_EXEMPT_FUNCTIONS: set[str] = {
    "srmech_version",       # trivial accessor returning a constant
    "srmech_abi_version",   # trivial accessor returning a constant
    "srmech_plat_has_threads",  # PAL trivial accessor: returns a compile-time
                                # 1/0 (is a threading backend present?). No
                                # state to assert; see c/JPL_AUDIT.md.
    "srmech_plat_has_streams",  # PAL trivial accessor: returns a compile-time
                                # 1/0 (is a stream-IPC backend present?). No
                                # state to assert; see c/JPL_AUDIT.md.
    "srmech_plat_has_filesystem",  # PAL trivial accessor: returns a compile-
                                # time 1/0 (is a filesystem backend present?).
                                # No state to assert; see c/JPL_AUDIT.md.
    "srmech_plat_has_dirlist",  # PAL trivial accessor: returns a compile-time
                                # 1/0 (is a directory-iteration backend
                                # present?). No state to assert; see
                                # c/JPL_AUDIT.md.
    "srmech_plat_has_stdio",    # PAL trivial accessor (rc186): returns a
                                # compile-time 1/0 (is a stdin/stdout backend
                                # present?). No state to assert; the stdin_read
                                # / stdout_write fns carry >=2 asserts. See
                                # c/JPL_AUDIT.md.
    "srmech_plat_has_tcp",      # PAL trivial accessor (rc194): returns a
                                # compile-time 1/0 (is a TCP backend present?).
                                # No state to assert; the tcp_listen / accept /
                                # read_some / write_all fns carry >=2 asserts.
                                # See c/JPL_AUDIT.md.
    "srmech_plat_sleep_ms",     # PAL trivial OS-timer wrapper (rc194): the
                                # POSIX (nanosleep) / Windows (Sleep) bodies
                                # carry >=2 asserts; the bare-metal stub is a
                                # 1-assert no-op (no pointer/bounds invariant, a
                                # second would be a tautology). See c/JPL_AUDIT.md.
    "srmech_mcp_sse_port",      # rc194: trivial const accessor returning the
                                # handle's bound TCP port (NULL-graceful → 0);
                                # no state to assert beyond the guard, like the
                                # exempt srmech_version. See c/JPL_AUDIT.md.
    # sha256 inline helpers — 4-7 lines each, no anomalous conditions
    "srmech_ror32",
    "srmech_ch",
    "srmech_maj",
    "srmech_bigsig0",
    "srmech_bigsig1",
    "srmech_smallsig0",
    "srmech_smallsig1",
    # v0.5.0rc2: srmech_bus.c framing helpers — each is a 1-assert
    # big-endian u32 (de)serialiser on its sole pointer arg; a second
    # assert would re-assert the same pointer. Static-internal-only;
    # the public API entry points have ≥2 asserts. (v0.7.5rc5: the
    # platform read/write/ensure-dir wrappers moved to the PAL —
    # srmech_platform.c — where each gained a 2nd assert and left the
    # exempt list; the ratchet went DOWN by five entries.)
    "srmech_bus__write_u32_be",
    "srmech_bus__read_u32_be",
    # v0.7.0rc10 (F292 graft #1): srmech_sha256_batch.c `__ror` is a 1-line
    # rotate (like the exempt scalar srmech_ror32), no pointer/bounds invariant.
    "srmech_sha256b__ror",
    # v0.7.0rc11 (SIMD optimize-path HAL): srmech_simd.c CPU-feature detectors
    # are pure cpuid/xgetbv probes returning 0/1 with no pointer/bounds
    # invariant to assert (they replaced per-file copies in sha256_batch.c /
    # loopbind_hd.c — net FEWER exempt functions). srmech_simd_tier is NOT
    # exempt (it asserts env_var != NULL + max_tier >= 0). See c/JPL_AUDIT.md.
    "srmech_simd_has_avx2",
    "srmech_simd_has_avx",
    "srmech_simd_has_sse2",
    # v0.7.0rc18 (F292 graft #3): srmech_simd_has_shani is the same kind of
    # pure cpuid feature detector (leaf7 EBX bit29). srmech_sha256_shani.c
    # `__ror` is the 1-line rotate (like srmech_ror32 / srmech_sha256b__ror).
    "srmech_simd_has_shani",
    "srmech_sha256ni__ror",
    # srmech_toml.c char classifiers — pure `char -> bool` predicates over a
    # single value argument (is-whitespace / is-bare-key-char). No pointer,
    # no bounds, no state: the only "input" is a char, which has no anomalous
    # value to assert (every char is a valid input). Asserting a tautology
    # would be cargo-cult per the Rule 5 exemption policy in c/JPL_AUDIT.md;
    # same shape as the exempt sha256 ch/maj inline primitives.
    "toml_is_ws",
    "toml_is_bare_key_char",
    # srmech_json.c (§41 genome-persistence C mirror): trivial char
    # classifiers — 4-line predicates returning 0/1 over a single char,
    # no pointer/bounds invariant to assert (same kind as the TOML
    # parser's toml_is_ws). See c/JPL_AUDIT.md.
    "json_is_ws",
    "json_is_digit",
    # rc81 srmech_riemann_theta.c (the Schottky-form counter): pure value
    # ops over a single scalar argument, no pointer/bounds invariant to
    # assert (same kind as the exempt sha256 ror / toml char classifiers).
    # rtsch_class_of maps a doubled inner product -> its class index 0..4
    # (or -1); it already asserts RTSCH_NCLASS == 5. rtsch_ctz counts the
    # trailing zeros of a nonzero uint64 (the lowest set-bit index); it
    # already asserts x != 0u. See c/JPL_AUDIT.md.
    "rtsch_class_of",
    "rtsch_ctz",
    # rc165 srmech_factor_poly.c: fac_is_prime is a pure value predicate over a
    # single scalar (trial-division primality of n < 2^32) — it already asserts
    # its domain bound n < 2^32 (the loop-safety invariant, so d*d cannot
    # overflow); there is no pointer/bounds invariant for a second assert, and a
    # tautology would be cargo-cult (same kind as the exempt sha256 ror / toml
    # char classifiers). See c/JPL_AUDIT.md.
    "fac_is_prime",
    # rc242 srmech_progress.c: srmech_set_progress_cb is a trivial process-global
    # setter (stash user_data, publish the callback pointer, return the previous)
    # — both cb and user_data are NULLABLE BY DESIGN (cb == NULL clears the hook),
    # so there is no pointer/bounds invariant to assert; a tautology would be
    # cargo-cult (same kind as the exempt srmech_version / PAL accessors). The
    # non-trivial srmech_progress_emit_dispatch carries its >= 2 asserts. See
    # c/JPL_AUDIT.md.
    "srmech_set_progress_cb",
    # rc249 srmech_genome.c (#1390 item 2): gk_zig / gk_unzig are the Class-K
    # zig-zag sign transform — single-expression pure integer functions (signed
    # <-> non-negative), no pointer/bounds invariant to assert; a tautology would
    # be cargo-cult (same kind as the exempt sha256 ror). Their callers gk_emit /
    # gk_read / the encode/decode carry the >= 2 asserts. See c/JPL_AUDIT.md.
    "gk_zig",
    "gk_unzig",
}

# Maximum allowed function length (JPL Rule 4).
RULE_4_MAX_LINES: int = 60

# Minimum allowed asserts per non-exempt function (JPL Rule 5).
RULE_5_MIN_ASSERTS: int = 2


def _scan_functions(path: Path) -> list[tuple[str, int, int]]:
    """Crude C function scanner — returns ``(name, lines, asserts)``
    per function defined in `path`. Same algorithm the
    JPL_AUDIT.md audit script uses; pure regex + brace counting.

    Limitations: this isn't a real C parser. It assumes srmech's
    formatting conventions: function definitions are at column 0,
    parameter list opens on the definition line, body brace opens
    on the next line OR same line.

    rc441 (``#T1148``): the scan now runs over :func:`_mask_c_literals` output
    rather than the raw text, so a ``'{'`` / ``'}'`` CHAR LITERAL — or a brace
    inside a string or a comment — can no longer run the brace counter off the
    end of the file. See that function for the measured before/after.
    """
    text = _mask_c_literals(path.read_text(encoding="utf-8"))
    lines = text.split("\n")
    # Track {definition_line_idx: (name, fn_body_open_idx)}
    fn_starts: list[tuple[str, int]] = []

    def_pat = re.compile(
        r"^[a-zA-Z_][a-zA-Z_0-9 \t\*]+[ \t\*]([a-zA-Z_][a-zA-Z_0-9]+)\s*\("
    )
    for i, line in enumerate(lines):
        # Skip declarations (semicolon-terminated)
        if line.rstrip().endswith(";"):
            continue
        m = def_pat.match(line)
        if m is None:
            continue
        # ⚠️ `static const` USED TO BE SKIPPED UNCONDITIONALLY HERE, and that
        # hid every function returning a CONST POINTER from Rules 4 and 5.
        # Measured at rc447: 24 functions across 9 files — cr_walk_json,
        # cr_find_named_chain, genome_find_chrom, json_emit_step, mc_method_spec
        # and 19 more — were scanned by nothing. The skip is meant for const
        # DATA (`static const char *const map_k[4] = {...}`), and an initializer
        # is what distinguishes the two: a definition has a parameter list and
        # no `=` ahead of it.
        #
        # All 24 measured CLEAN on both rules when first revealed, so closing
        # the hole cost zero violations — but it had to close BEFORE the map
        # arm lands, which adds ~45 functions to srmech_compose_run.c. A blind
        # spot is cheapest to fix while it is still empty.
        _is_const_data = (line.lstrip().startswith("static const")
                          and "=" in line.split("(")[0])
        if _is_const_data or line.lstrip().startswith(("typedef", "extern", "#")):
            continue
        # Confirm an open brace appears within the next ~5 lines
        for look in range(i, min(i + 10, len(lines))):
            if "{" in lines[look] and not lines[look].lstrip().startswith("/*"):
                fn_starts.append((m.group(1), i))
                break

    # For each detected function start, count brace depth to find
    # the closing brace + count asserts in between.
    out: list[tuple[str, int, int]] = []
    for name, start_idx in fn_starts:
        depth = 0
        asserts = 0
        end_idx = start_idx
        # Find first '{'
        body_start = start_idx
        while body_start < len(lines) and "{" not in lines[body_start]:
            body_start += 1
        if body_start >= len(lines):
            continue
        depth = lines[body_start].count("{") - lines[body_start].count("}")
        for j in range(body_start + 1, len(lines)):
            depth += lines[j].count("{") - lines[j].count("}")
            if "assert(" in lines[j]:
                asserts += 1
            if depth == 0:
                end_idx = j
                break
        out.append((name, end_idx - start_idx + 1, asserts))
    return out


def test_rule_4_function_length_under_60() -> None:
    """JPL Rule 4: every function ≤ 60 lines."""
    violations: list[str] = []
    for f in sorted(_C_SRC_DIR.glob("*.c")):
        for name, lines, _ in _scan_functions(f):
            if lines > RULE_4_MAX_LINES:
                violations.append(
                    f"{f.name}::{name} = {lines} lines (> {RULE_4_MAX_LINES})"
                )
    assert not violations, "Rule 4 violations: " + "; ".join(violations)


def test_rule_5_minimum_two_asserts_per_function() -> None:
    """JPL Rule 5: every non-exempt function has ≥ 2 assertions."""
    violations: list[str] = []
    for f in sorted(_C_SRC_DIR.glob("*.c")):
        for name, _, asserts in _scan_functions(f):
            if name in RULE_5_EXEMPT_FUNCTIONS:
                continue
            if asserts < RULE_5_MIN_ASSERTS:
                violations.append(
                    f"{f.name}::{name} has {asserts} asserts "
                    f"(< {RULE_5_MIN_ASSERTS}); add asserts or document "
                    f"in RULE_5_EXEMPT_FUNCTIONS with rationale"
                )
    assert not violations, "Rule 5 violations: " + "; ".join(violations)


def test_rule_8_no_multiline_macros() -> None:
    """JPL Rule 8: no multi-line macros, no token-paste, no varargs."""
    forbidden = re.compile(r"##|__VA_ARGS__|\\\s*$")
    for f in _c_files():
        text = f.read_text(encoding="utf-8")
        for i, line in enumerate(text.split("\n"), 1):
            # Only check inside #define lines
            stripped = line.lstrip()
            if not stripped.startswith("#define"):
                continue
            if forbidden.search(line):
                pytest.fail(
                    f"{f.name}:{i}: Rule 8 violation — "
                    f"multi-line macro / token-paste / VA_ARGS in "
                    f"#define: {line.rstrip()!r}"
                )


def test_audit_doc_present_and_mentions_all_rules() -> None:
    """Sanity check: JPL_AUDIT.md exists and references every rule
    by number, so an auditor can find the rationale per rule."""
    audit = _C_SRC_DIR.parent / "JPL_AUDIT.md"
    assert audit.exists(), f"missing {audit}"
    text = audit.read_text(encoding="utf-8")
    for n in range(1, 11):
        marker = f"Rule {n}"
        assert marker in text, (
            f"JPL_AUDIT.md does not mention {marker!r}"
        )
