"""rc234 (#832) — the ``ThetaSum.is_zero`` SOUNDNESS-HARDENING adversarial battery.

The rc210 rebuild made ``is_zero`` a SOUND-TRUE-ONLY certificate architecture: ``True``
⟺ Z1/Z2/Z3s/Z4/Z5 PROVES the cleared numerator identically zero; ``False`` = "not
proven" (a proven-nonzero object OR an honest decline). The soundness-critical direction
is the ONE this battery attacks: ``is_zero`` must NEVER return ``True`` for a genuinely
NONZERO ThetaSum (a false ZERO is a soundness BUG; a DECLINE on a genuine zero is mere
incompleteness, which is allowed).

This file ENLARGES the adversarial coverage of that direction into the hardest regimes —
the corners the shipped battery (``test_thetasum_is_zero_sound_rc210`` /
``_degree_bound_soundness_693`` / ``_iszero_corpus_parity_rc210`` / ``_z5_theta_constant_rc228``)
does NOT already stress:

  * RANK-≥2 exponent kernels — deep low-``p`` cancellations across MANY theta-product
    families (2-/3-/4-theta, single- and two-variable), where an under-counted degree
    bound or a merged character could yield a false ZERO. The committed rank-2 generator
    searched ONE family (θ(a·x)θ(b·x)θ(c·x⁻²), a·b const) and found no kernel; here the
    search is widened to a systematic multi-family sweep.
  * CROSS-CHARACTER sign cancellations — sums whose terms carry PAIRWISE-DISTINCT
    quasi-periodicity characters (μ_v), so the character split must separate them; a
    character-merge bug would falsely reduce a nonzero sum.
  * the INTERPOLATION-CAP boundary — genuine identities whose Z4 needs exactly ``D+1``
    pairwise-distinct nodes at raised degree ``D`` (θ-multiplied three-term cores) stay
    PROVEN, while a degree-matched perturbed sibling stays FALSE.
  * MIXED p-power / q-power characters (#694 key-hygiene) — shifted (``σ_x`` / ``σ_y``)
    identities where ``q`` / ``p`` powers ride the arguments; a false-merge on the unit
    coordinates could break either direction.
  * a large RANDOMISED FUZZ over all of the above shapes.

THE INDEPENDENT ORACLE (never routes through the machinery under test). A finite sum of
modified-theta products ``N = Σ c·∏ θ(z;p)`` is a genuine Laurent series in ``p`` (and the
kept variables ``x``, ``y``): ``N ≡ 0`` as an elliptic function ⟺ EVERY series coefficient
vanishes. So the EXACT ``p``-expansion (stdlib ``Fraction`` — deliberately NOT srmech's
``Q``) to order ``K``, with the parameter symbols specialised to distinct rationals
(specialisation is a homomorphism: a nonzero coefficient after specialisation proves the
UN-specialised function nonzero), is a DEFINITIVE nonzero-detector: it can only ever
witness NONZERO exactly, never falsely claim zero. The soundness assertion is therefore
one-sided and exact::

    oracle sees a nonzero p-coefficient  ⇒  is_zero MUST be False.

For the deep-cancellation KERNEL objects (whose first nonzero coefficient may sit far
above a modest ``K``) the exact-``Fraction`` kernel GENERATOR itself is the oracle: it
constructs the combination and PROVES its surviving ``p``-valuation, so no truncation is
involved. Every numeric result is generated by committed code (computational-provenance
discipline); no result routes through ``is_zero``.
"""
import random

from fractions import Fraction

import pytest

from srmech.amsc import ThetaSum, _native
from srmech.apokatastasis.ellbase import EllMonomial as M, Theta
from srmech.amsc.q import Q
from srmech.apokatastasis.thetasum import (
    _NONZERO, _UNKNOWN, _ZERO, _decide_thetasum, _joint_char, _term_char_v,
)


# ─────────────────────────  exact-Fraction (p, x, y) series oracle  ─────────────────
# Independent of srmech's Q / is_zero. A theta-product's exact p-expansion, tracking the
# kept-variable (x, y) exponents; parameters are specialised to Fraction constants first.


def _fmul(a, b, K):
    """Multiply two exact (p_pow, x_exp, y_exp) → Fraction series, truncating p-order > K."""
    out = {}
    for (p1, x1, y1), v1 in a.items():
        for (p2, x2, y2), v2 in b.items():
            pk = p1 + p2
            if pk > K:
                continue
            key = (pk, x1 + x2, y1 + y2)
            out[key] = out.get(key, Fraction(0)) + v1 * v2
    return {k: v for k, v in out.items() if v != 0}


def _factor(key, coeff):
    """A single degree-1 factor ``(1 + coeff·monomial)`` as a series, ADDING at ``key`` so
    a CONSTANT-theta collision ``key == (0,0,0)`` folds to ``1 + coeff`` (never overwrites
    the unit term — the flat-key dict-literal collision that would corrupt ``θ(const;p)``)."""
    f = {(0, 0, 0): Fraction(1)}
    f[key] = f.get(key, Fraction(0)) + coeff
    return {k: v for k, v in f.items() if v != 0}


def _theta_f(c, ex, ey, K):
    """The exact p-expansion of ``θ(c·x^ex·y^ey; p) = ∏_{k≥0}(1−z pᵏ)(1−z⁻¹ p^{k+1})`` to
    p-order K, ``z = c·x^ex·y^ey``. Fraction coefficients — the independent oracle. Keys
    are ADDED (see :func:`_factor`) so a constant theta ``ex=ey=0`` has the correct p⁰ term
    ``1−c`` (not ``−c``)."""
    acc = {(0, 0, 0): Fraction(1)}
    ci = Fraction(1) / c
    for k in range(K + 1):
        acc = _fmul(acc, _factor((k, ex, ey), -c), K)
        if k + 1 <= K:
            acc = _fmul(acc, _factor((k + 1, -ex, -ey), -ci), K)
    return acc


def _spec_mono(m, spec):
    """Split an ``EllMonomial`` under a parameter specialisation ``spec`` (name→Fraction)
    into ``(p_shift, x_exp, y_exp, scalar Fraction)`` — every symbol except ``x``/``y``/``p``
    is specialised into the scalar."""
    scal = Fraction(m.coeff.numerator, m.coeff.denominator)
    ps = xe = ye = 0
    for s, e in m.exps.items():
        if s == "p":
            ps += e
        elif s == "x":
            xe += e
        elif s == "y":
            ye += e
        else:
            scal *= spec[s] ** e
    return ps, xe, ye, scal


def _numerator_pexp(ts, spec, K):
    """The exact ``p``-expansion (Fraction; (p,x,y)-keyed) of ``ts``'s cleared numerator to
    order K, parameters specialised by ``spec``."""
    total = {}
    for pref, thetas in ts.terms:
        ps, xe, ye, scal = _spec_mono(pref, spec)
        term = {(ps, xe, ye): scal}
        for t in thetas:
            zps, zxe, zye, zscal = _spec_mono(t.arg, spec)
            assert zps == 0, "a canonical theta argument must be p-exponent 0"
            term = _fmul(term, _theta_f(zscal, zxe, zye, K), K)
        for key, v in term.items():
            total[key] = total.get(key, Fraction(0)) + v
    return {k: v for k, v in total.items() if v != 0}


_ORACLE_PRIMES = (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67,
                  71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113)


def _oracle_nonzero(ts, K, n_spec=4, seed=90210):
    """``True`` iff the exact ``p``-expansion (to order K) is nonzero under SOME parameter
    specialisation — a DEFINITIVE proof the numerator is genuinely NONZERO (never a false
    nonzero: specialisation is a homomorphism, ``x``/``y`` are kept formal). ``False`` is
    inconclusive (a genuine zero, or a nonzero whose first coefficient is above K)."""
    syms = set()
    for pref, thetas in ts.terms:
        for s in pref.exps:
            if s not in ("x", "y", "p"):
                syms.add(s)
        for t in thetas:
            for s in t.arg.exps:
                if s not in ("x", "y", "p"):
                    syms.add(s)
    syms = sorted(syms)
    if not syms:
        return bool(_numerator_pexp(ts, {}, K))
    rng = random.Random(seed)
    need = 2 * len(syms)
    for _ in range(n_spec):
        pool = rng.sample(_ORACLE_PRIMES, need)
        spec = {s: Fraction(pool[2 * i], pool[2 * i + 1]) for i, s in enumerate(syms)}
        if _numerator_pexp(ts, spec, K):
            return True
    return False


# ─────────────────────────  ThetaSum builders  ─────────────────────────


_X = M.symbol("x")


def _pow(name, e):
    """``sym^e`` as an EllMonomial (safe for e<0)."""
    if e == 0:
        return M.one()
    base = M.symbol(name) if e > 0 else M.symbol(name).inv()
    m = M.one()
    for _ in range(e if e > 0 else -e):
        m = m * base
    return m


def _theta(ac, ex, ey=0):
    """``θ(ac·x^ex·y^ey)`` from a Fraction/int/Q arg coefficient."""
    q = ac if isinstance(ac, Q) else (Q(ac.numerator, ac.denominator) if isinstance(ac, Fraction)
                                      else Q(int(ac), 1))
    m = M.scalar(q) * _pow("x", ex) * _pow("y", ey)
    return Theta(m)


def _sum_of_thetas(coeff_and_factors):
    """Build ``Σ c·∏ θ`` from ``[(Q coeff, [(argcoeff, ex, ey), ...]), ...]``."""
    terms = [(c, M.one(), tuple(_theta(ac, ex, ey) for (ac, ex, ey) in facs))
             for c, facs in coeff_and_factors]
    return ThetaSum(terms=terms)


# ─────────────────────────  exact-Fraction kernel generator (deep cancellation)  ────
# The independent nonzero PROOF for a deep-cancellation family: a nullspace over the
# low-p lattice whose surviving combination is proven nonzero above the killed band.


def _theta_series_single(ac, factors, K):
    """A term's exact (p,x,y)-series ``ac·∏ θ(argc·x^ex·y^ey)`` (Fraction)."""
    term = {(0, 0, 0): Fraction(ac)}
    for (argc, ex, ey) in factors:
        term = _fmul(term, _theta_f(Fraction(argc), ex, ey, K), K)
    return term


def _nullspace(rows, ncols):
    """Exact-Fraction RREF nullspace basis."""
    m = [list(r) for r in rows]
    piv = {}
    r = 0
    for c in range(ncols):
        pr = next((i for i in range(r, len(m)) if m[i][c] != 0), None)
        if pr is None:
            continue
        m[r], m[pr] = m[pr], m[r]
        pv = m[r][c]
        m[r] = [x / pv for x in m[r]]
        for i in range(len(m)):
            if i != r and m[i][c] != 0:
                f = m[i][c]
                m[i] = [a - f * b for a, b in zip(m[i], m[r])]
        piv[c] = r
        r += 1
        if r == len(m):
            break
    basis = []
    for fc in [c for c in range(ncols) if c not in piv]:
        v = [Fraction(0)] * ncols
        v[fc] = Fraction(1)
        for c, pr in piv.items():
            v[c] = -m[pr][fc]
        basis.append(v)
    return basis


def _gap_kernel(series_list, B):
    """A kernel vector over ``series_list`` that KILLS every lattice coefficient of
    p-order ≤ B while leaving a PROVEN-nonzero combination above B (valuation > B), or
    ``None``. This is the independent nonzero oracle for a deep-cancellation family."""
    keys = sorted({k for t in series_list for k in t if k[0] <= B})
    rows = [[t.get(k, Fraction(0)) for t in series_list] for k in keys]
    basis = _nullspace(rows, len(series_list))
    for cvec in basis:
        comb = {}
        for ci, t in zip(cvec, series_list):
            if ci == 0:
                continue
            for k, v in t.items():
                comb[k] = comb.get(k, Fraction(0)) + ci * v
        comb = {k: v for k, v in comb.items() if v != 0}
        if not comb:
            continue                       # an accidental TRUE identity — skip
        val = min(k[0] for k in comb)
        if val > B:
            return cvec, val
    return None


# The systematic multi-family sweep. Each entry: (name, factor-builder(param) -> factors,
# param grid). "factors" is a list of (argcoeff-expr, ex, ey); argcoeff-expr is a callable
# of the param giving a Fraction so families like a·b=const are expressible.
def _families():
    grid = [Fraction(t) for t in (2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)]
    fam = []
    # F1: single θ(t·x²) — e=2 divided-difference regime (Σe²=4), NOT in the shipped e=3 test
    fam.append(("single-x2", [(lambda t: [(t, 2, 0)], grid)]))
    # F2: witness-A ±-pair family θ(t·x^±) (rank-1) — the search must reproduce a kernel
    fam.append(("pm-pair-x", [(lambda t: [(t, 1, 0), (t, -1, 0)], grid)]))
    # F3: 2-theta θ(t·x)θ(t·x⁻¹) with independent arg — exps (1,-1)
    fam.append(("two-theta-1m1", [(lambda t: [(t, 1, 0), (t + 1, -1, 0)], grid)]))
    # F4: 3-theta θ(a·x)θ(b·x)θ(c·x⁻²) with a·b const (the committed rank-2 shape, widened)
    fam.append(("rank2-abx-cx2",
                [(lambda t: [(t, 1, 0), (Fraction(30) / t, 1, 0), (Fraction(5), -2, 0)], grid)]))
    # F5: 4-theta θ(a·x)θ(b·x)θ(c·x)θ(d·x⁻³), a·b·c const (deeper rank-2/3 shape)
    fam.append(("rank-abcx-dx3",
                [(lambda t: [(t, 1, 0), (t + 2, 1, 0), (Fraction(60) / (t * (t + 2)), 1, 0),
                             (Fraction(7), -3, 0)], grid)]))
    # F6: single θ(t·x³) — the #693 e=3 regime, distinct grid (fresh nonzero witness)
    fam.append(("single-x3", [(lambda t: [(t, 3, 0)], grid)]))
    # F7: two-variable θ(t·x)θ(t·y) — cross-variable rank family
    fam.append(("xy-pair", [(lambda t: [(t, 1, 0), (t, 0, 1)], grid)]))
    return fam


# ─────────────────────────  (0) oracle self-tests  ──────────────────────────────────


def test_oracle_flags_known_nonzeros():
    """The oracle DEFINITIVELY flags the shipped #771 false-zero witnesses A and B as
    nonzero (they are deep-cancellation objects) — so a soundness assertion built on it
    is not vacuous."""
    # witness A (rank-1 ±-pair; first nonzero coeff at p⁶) — needs K ≥ 6
    a_us = (2, 3, 4, 5, 6, 7)
    a_cs = (Q(-133824, 26411), Q(388557, 26411), Q(-231961600, 11541607),
            Q(19987500, 1322951), Q(-15163200, 2516591), Q(1, 1))
    wa = _sum_of_thetas([(c, [(u, 1, 0), (u, -1, 0)]) for c, u in zip(a_cs, a_us)])
    assert _oracle_nonzero(wa, K=8) is True
    # witness B (11 pairwise-distinct chars; first nonzero coeff at p¹⁵) — needs K ≥ 15
    b_ts = tuple(range(2, 13))

    def _bc(t):
        v = Q(t, 1) ** 4
        for s in b_ts:
            if s != t:
                v = v / Q(t - s, 1)
        return v
    wb = _sum_of_thetas([(_bc(t), [(t, 3, 0)]) for t in b_ts])
    assert _oracle_nonzero(wb, K=16) is True


def test_oracle_sees_zero_on_genuine_identities():
    """The oracle finds NO nonzero coefficient on genuine identities (three-term, its
    shifts, and constant-x leaves) — it never false-alarms on a true zero."""
    a, b, c = M.symbol("a"), M.symbol("b"), M.symbol("c")
    assert _oracle_nonzero(ThetaSum.three_term(a, b, c), K=20) is False
    assert _oracle_nonzero(ThetaSum.three_term(a, b, c).shift_x(), K=20) is False
    assert _oracle_nonzero(
        ThetaSum.three_term(M.scalar(Q(2, 1)), M.scalar(Q(3, 1)), M.scalar(Q(5, 1)),
                            x=M.scalar(Q(7, 1))), K=24) is False


# ─────────────────────────  (1) rank-2 kernel sweep — no false zero  ─────────────────


def test_rank2_kernel_sweep_never_yields_a_false_zero():
    """The ENLARGED rank-2 sweep: for every family, at every band B, any exact kernel
    (a genuinely-NONZERO deep-cancellation object, proven by its surviving p-valuation
    > B) must NEVER be certified zero by ``is_zero`` — dispatched AND pure. The number of
    kernels FOUND is reported; the safety property is what is asserted for each."""
    found = 0
    for _name, specs in _families():
        for builder, grid in specs:
            for B in (2, 3, 4):
                J = B + 5
                series = [_theta_series_single(1, builder(t), J) for t in grid]
                g = _gap_kernel(series, B)
                if g is None:
                    continue
                cvec, val = g
                found += 1
                # `val > B` is the INDEPENDENT nonzero PROOF: the exact-Fraction
                # combination cancels the lattice through p≤B but has a nonzero
                # coefficient at p-order val (the generator IS the oracle here — no
                # truncated re-check needed).
                assert val > B
                cf = [(Q(c.numerator, c.denominator), builder(t))
                      for c, t in zip(cvec, grid) if c != 0]
                obj = _sum_of_thetas([(c, [(Q(a.numerator, a.denominator), ex, ey)
                                           for (a, ex, ey) in facs]) for c, facs in cf])
                assert obj.is_zero is False           # NEVER a false zero (dispatched)
                assert obj._is_zero_py() is False     # NEVER a false zero (pure oracle)
                assert _decide_thetasum(obj, use_fastpath=False) in (_NONZERO, _UNKNOWN)
    assert found >= 1, "the enlarged sweep must exercise at least one real kernel object"


# ─────────────────────────  (2) two-variable rank-2 ±-pair objects  ──────────────────


def test_two_variable_pm_pair_objects_no_false_zero():
    """Genuinely-nonzero two-variable ±-pair sums ``Σ c·θ(u·x^±)·θ(v·y^±)`` (a rank-2
    product structure) are never falsely certified zero, while the corresponding genuine
    ``σ_x``/``σ_y`` three-term identities stay proven zero."""
    # nonzero: an asymmetric two-variable ±-pair sum (no cancellation)
    obj = _sum_of_thetas([
        (Q(3, 1), [(2, 1, 0), (2, -1, 0), (3, 0, 1), (3, 0, -1)]),
        (Q(-2, 1), [(5, 1, 0), (5, -1, 0), (7, 0, 1), (7, 0, -1)]),
        (Q(1, 1), [(2, 1, 0), (2, -1, 0), (7, 0, 1), (7, 0, -1)]),
    ])
    if _oracle_nonzero(obj, K=10):
        assert obj.is_zero is False
        assert obj._is_zero_py() is False
    # the genuine y-shifted three-term identity stays proven zero (mixed-variable Z2/Z4)
    a, b, c = M.symbol("a"), M.symbol("b"), M.symbol("c")
    wy = ThetaSum.three_term(a, b, c, x=M.symbol("y"))
    assert wy.is_zero is True
    assert _decide_thetasum(wy, use_fastpath=False) == _ZERO


# ─────────────────────────  (3) cross-character sign cancellations  ──────────────────


def test_cross_character_sums_no_false_zero():
    """Sums whose terms carry PAIRWISE-DISTINCT x-characters (the μ_x multiplier differs)
    lie in no single theta-section space — the character split must separate them, and no
    such genuinely-nonzero sum may be certified zero. Two constructions: (a) single-theta
    θ(t·x) over distinct t (distinct μ_x), (b) mixed-degree θ(t·x)+θ(s·x²) (distinct D_x)."""
    # (a) distinct-scale single-theta sum — each term a distinct character, sum is nonzero
    obj_a = _sum_of_thetas([(Q(k, 1), [(k + 1, 1, 0)]) for k in range(2, 9)])
    chars_a = {_term_char_v(pref, [t.arg for t in th], "x") for pref, th in obj_a.terms}
    assert len(chars_a) == len(obj_a.terms)          # genuinely cross-character
    if _oracle_nonzero(obj_a, K=12):
        assert obj_a.is_zero is False
        assert obj_a._is_zero_py() is False
    # (b) mixed-DEGREE characters (D_x = 1 vs 4) — a joint-character split by degree
    obj_b = _sum_of_thetas([
        (Q(1, 1), [(2, 1, 0)]), (Q(-1, 1), [(3, 1, 0)]),
        (Q(1, 1), [(2, 2, 0)]), (Q(-1, 1), [(5, 2, 0)]),
    ])
    jchars = {_joint_char(pref, [t.arg for t in th], ["x"]) for pref, th in obj_b.terms}
    assert len(jchars) >= 2                          # spans ≥2 joint characters
    if _oracle_nonzero(obj_b, K=12):
        assert obj_b.is_zero is False
        assert obj_b._is_zero_py() is False


def test_single_var_divided_difference_e2_stays_nonzero():
    """The e=2 analogue of the shipped e=3 witness B: ``Σ (aₜ³/∏_{s≠t}(aₜ−a_s))·θ(aₜ·x²)``
    over t = 2..9 — pairwise-distinct x-characters (μ_x carries aₜ⁻²), a deep cross-character
    cancellation. Independent oracle → nonzero; ``is_zero`` must stay False."""
    av = list(range(2, 10))

    def _c(t):
        v = Q(t, 1) ** 3
        for s in av:
            if s != t:
                v = v / Q(t - s, 1)
        return v
    obj = _sum_of_thetas([(_c(t), [(t, 2, 0)]) for t in av])
    chars = {_term_char_v(pref, [th.arg for th in ths], "x") for pref, ths in obj.terms}
    assert len(chars) == len(obj.terms)              # genuinely cross-character
    assert _oracle_nonzero(obj, K=20) is True        # definitively nonzero
    assert obj.is_zero is False
    assert obj._is_zero_py() is False
    assert _decide_thetasum(obj, use_fastpath=False) in (_NONZERO, _UNKNOWN)


# ─────────────────────────  (4) interpolation-cap boundary  ──────────────────────────


def test_interpolation_cap_boundary_soundness():
    """Genuine three-term identities multiplied by a HIGHER-degree common theta raise the
    Z4 interpolation degree ``D`` (odd theta count breaks the ±-pair fast path → the
    per-character interpolation at ``D+1`` nodes must carry the proof). Each stays proven
    zero; a degree-matched PERTURBED sibling stays False + oracle-nonzero."""
    a, b, c = M.symbol("a"), M.symbol("b"), M.symbol("c")
    g = M.symbol("g")
    for e in (1, 2, 3):                              # common factor θ(g·xᵉ): D grows with e²
        core = ThetaSum.three_term(a, b, c)
        w = core * ThetaSum(terms=((Q(1, 1), M.one(), (Theta(g * _pow("x", e)),)),))
        assert w.is_zero is True
        assert _decide_thetasum(w, use_fastpath=False) == _ZERO
    # a perturbed (broken) identity of the SAME shape is genuinely nonzero
    core = ThetaSum.three_term(a, b, c)
    good = core * ThetaSum(terms=((Q(1, 1), M.one(), (Theta(g * _pow("x", 2)),)),))
    bad = good + ThetaSum(terms=((Q(1, 3), M.one(),
                                  (Theta(a * _X), Theta(a / _X), Theta(b * c), Theta(b / c),
                                   Theta(g * _pow("x", 2)))),))
    assert _oracle_nonzero(bad, K=16) is True
    assert bad.is_zero is False
    assert bad._is_zero_py() is False


# ─────────────────────────  (5) mixed p-power / q-power characters (#694)  ───────────


def test_mixed_p_power_characters_soundness():
    """#694 key-hygiene regime: ``σ_x``/``σ_y`` shifts push ``q`` (and ``p`` powers) onto
    the arguments and prefactors, so terms of the same genuine x-character differ on the
    UNIT coordinates. Shifted identities stay proven zero (both directions of shift, and a
    disjoint sum), while a perturbed sibling stays False."""
    a, b, c = M.symbol("a"), M.symbol("b"), M.symbol("c")
    d, e, f = M.symbol("d"), M.symbol("e"), M.symbol("f")
    for w in (
        ThetaSum.three_term(a, b, c).shift_x(),
        ThetaSum.three_term(a, b, c).shift_y(),
        ThetaSum.three_term(a, b, c).shift_x().shift_x(),
        ThetaSum.three_term(a, b, c).shift_x() + ThetaSum.three_term(d, e, f).shift_y(),
        ThetaSum.three_term(a, b, c, x=M.symbol("x", 2)).shift_x(),
    ):
        assert w.is_zero is True
        assert _decide_thetasum(w, use_fastpath=False) == _ZERO
    # a perturbed shifted identity is genuinely nonzero
    bad = ThetaSum.three_term(a, b, c).shift_x() + ThetaSum(
        terms=((Q(1, 5), M.symbol("q"), (Theta(a * _X),)),))
    assert _oracle_nonzero(bad, K=16) is True
    assert bad.is_zero is False
    assert bad._is_zero_py() is False


# ─────────────────────────  (6) the big randomised fuzz (the hunt)  ──────────────────


def _random_object(rng):
    """A small random ThetaSum drawn from the adversarial shapes: random ±-pair products,
    random single-theta cross-character sums, and random small mixed sums (1–2 variables,
    small exponents) — biased toward the certificate-stressing corners."""
    shape = rng.choice(("pm-pair", "single", "mixed", "two-var"))
    nterms = rng.randint(2, 5)
    coeffs = [Q(rng.randint(-6, 6) or 1, rng.randint(1, 4)) for _ in range(nterms)]
    cf = []
    if shape == "pm-pair":
        for i in range(nterms):
            u = rng.randint(2, 13)
            cf.append((coeffs[i], [(u, 1, 0), (u, -1, 0)]))
    elif shape == "single":
        e = rng.choice((1, 2, 3))
        for i in range(nterms):
            t = rng.randint(2, 13)
            cf.append((coeffs[i], [(t, e, 0)]))
    elif shape == "two-var":
        for i in range(nterms):
            u, v = rng.randint(2, 11), rng.randint(2, 11)
            cf.append((coeffs[i], [(u, 1, 0), (v, 0, 1)]))
    else:                                            # mixed degrees / signs
        for i in range(nterms):
            fac = []
            for _ in range(rng.randint(1, 2)):
                ex = rng.choice((-2, -1, 1, 2))
                fac.append((rng.randint(2, 11), ex, 0))
            cf.append((coeffs[i], fac))
    return _sum_of_thetas(cf)


def test_random_fuzz_soundness_direction():
    """THE HUNT. Many random adversarial objects; the EXACT independent oracle decides
    genuine nonzero-ness, and every oracle-nonzero object MUST have ``is_zero`` False
    (dispatched AND pure) — a false ZERO here is the soundness bug the task targets.
    Objects the oracle cannot resolve within K are simply skipped (no assertion), so the
    test never false-alarms; it only ever FIRES on a definitive nonzero certified zero."""
    rng = random.Random(4242)
    N = 200
    checked = 0
    for _ in range(N):
        obj = _random_object(rng)
        if not obj.terms:                            # cancelled to empty on construction
            continue
        if _oracle_nonzero(obj, K=12, n_spec=2):
            checked += 1
            # the SHIPPING verdict (native-dispatched) on EVERY oracle-nonzero object —
            # a False ZERO here is the soundness bug the task targets.
            assert obj.is_zero is False, f"FALSE ZERO (dispatched): {obj!r} terms={obj.terms}"
            # the pure certificate recursion on a bounded subset (its parity with the
            # native path is the corpus-parity contract; run every 3rd to cap the O(nodes)
            # multivariate recursion cost while keeping deep pure coverage).
            if checked % 3 == 0:
                assert obj._is_zero_py() is False, f"FALSE ZERO (pure): {obj!r}"
                assert _decide_thetasum(obj, use_fastpath=False) in (_NONZERO, _UNKNOWN)
    assert checked >= 80, f"the fuzz must resolve many genuine nonzeros (got {checked})"


# ─────────────────────────  (7) zero-side regression (True stays True)  ──────────────


def test_zero_side_identities_stay_proven():
    """The True side must not regress: a spread of genuine identities (bare three-term,
    θ-multiplied, monomial-prefactored, disjoint sums, and the all-constant Z5 leaf) stay
    ``is_zero`` True AND certificate-proven ZERO by the pure recursion alone."""
    a, b, c = M.symbol("a"), M.symbol("b"), M.symbol("c")
    d, e, f = M.symbol("d"), M.symbol("e"), M.symbol("f")
    g = M.symbol("g")
    objs = [
        ThetaSum.three_term(a, b, c),
        ThetaSum.three_term(a, b, c) * ThetaSum(terms=((Q(1, 1), M.one(), (Theta(g * _X),)),)),
        ThetaSum.three_term(a, b, c) * (a * a / b * _X * _X * _X),
        ThetaSum.three_term(a, b, c) + ThetaSum.three_term(d, e, f),
        ThetaSum.three_term(M.scalar(Q(2, 1)), M.scalar(Q(3, 1)), M.scalar(Q(5, 1)),
                            x=M.scalar(Q(7, 1))),        # Z5 constant leaf
    ]
    for w in objs:
        assert w.is_zero is True
        assert _decide_thetasum(w, use_fastpath=False) == _ZERO
        assert _oracle_nonzero(w, K=18) is False         # oracle agrees it is zero


# ─────────────────────────  (8) native == pure on the adversarial corpus  ────────────


@pytest.mark.skipif(not _native.has_native_thetasum_interpolation(),
                    reason="native structural-certificate peer not loaded")
def test_battery_native_equals_pure():
    """Extend the rc210 corpus-parity contract to this adversarial corpus: for every
    battery object the native certificate verdict EQUALS the pure certificate bool (a
    None decline falls to pure). A native≠pure on any object would be a NEW false-zero
    surface from the C mirror — a blocker."""
    rng = random.Random(1337)
    corpus = [_random_object(rng) for _ in range(45)]
    a, b, c = M.symbol("a"), M.symbol("b"), M.symbol("c")
    g = M.symbol("g")
    corpus += [
        ThetaSum.three_term(a, b, c),
        ThetaSum.three_term(a, b, c) * ThetaSum(terms=((Q(1, 1), M.one(), (Theta(g * _X),)),)),
        ThetaSum.three_term(a, b, c).shift_x(),
    ]
    mismatches = []
    for ts in corpus:
        if not ts.terms:
            continue
        cv = ts._is_zero_interpolation_c()
        pv = ts._is_zero_interpolation()
        if cv is not None and cv != pv:
            mismatches.append({"c": cv, "py": pv, "terms": len(ts.terms)})
        assert ts.is_zero == ts._is_zero_py()
    assert not mismatches, f"NATIVE≠PURE (BLOCKER): {mismatches[:10]}"
