"""PreToolUse(Edit|Write|NotebookEdit) — refuse a hand-edit to a generated file.
(rc452, `#T1166`)

WHAT IT CATCHES
===============
A surgical fix typed straight into one of the six ``tools/regen_all.py``
outputs. The temptation is live every time a count-pin reddens, and the damage
is delayed rather than loud: a hand-edited ``_tool_docs.py`` SHIPS IN THE WHEEL
and reaches users through ``describe()``, the MCP tool list and the compiled-in
C registry — then silently reverts on the next regen, taking the fix with it.

The propagation is measured, not assumed: rc346 injected 14 bytes into
``_tool_docs.py`` and watched ``srmech_tool_registry.c`` move 827380 -> 827394.
The generated ``.c`` embeds the docs prose, so a hand-edit to one output puts
TWO artifacts out of sync with their generator.

TWO INDEPENDENT PREDICATES, EITHER SUFFICIENT
=============================================
1. **The manifest.** ``tools/codegen_manifest.py`` is the SSoT for what is
   generated; its ``GENERATORS`` table carries an ``output`` per row. It is
   loaded here by file path, WITHOUT importing the ``srmech`` package, so this
   hook stays fast and cannot be broken by a half-written module. If the six
   outputs change, this hook follows automatically — there is no second list to
   keep in step.
2. **The banner.** Any file whose first three lines say ``DO NOT EDIT``.
   Verified present: ``_tool_docs.py`` line 1 reads
   ``"_tool_docs.py — GENERATED by tools/gen_tool_docs.py. DO NOT EDIT."``
   This catches generated files the manifest does not list — the
   ``EXCLUDED`` generators, for instance.

Predicate 1 needs no file read at all. Predicate 2 reads three lines.

WHY REGENERATION IS NEVER BLOCKED
=================================
``regen_all.py`` writes through Python file I/O in a Bash invocation, not
through the Edit tool, so it never reaches a PreToolUse(Edit) matcher. The
allowed path stays open by construction rather than by an exemption.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _hooklib as H  # noqa: E402

BANNER = "DO NOT EDIT"
BANNER_LINES = 3


def _manifest_outputs(root: Path) -> List[Path]:
    """Absolute output paths from ``GENERATORS``, or ``[]`` if unavailable.

    Loaded by file path so no package import happens. A failure here is not
    fatal: the banner predicate still applies.
    """
    mf = H.py_root(root) / "tools" / "codegen_manifest.py"
    if not mf.is_file():
        return []
    try:
        spec = importlib.util.spec_from_file_location("_srmech_codegen_manifest", mf)
        if spec is None or spec.loader is None:
            return []
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        gens = getattr(mod, "GENERATORS", ())
        out = []
        srmech_root = root / "docs" / "srmech"
        for g in gens:
            rel = getattr(g, "output", None)
            if isinstance(rel, str) and rel:
                out.append((srmech_root / rel).resolve())
        return out
    except Exception:
        return []


def _has_banner(path: Path) -> bool:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            for _ in range(BANNER_LINES):
                line = fh.readline()
                if not line:
                    break
                if BANNER in line:
                    return True
    except OSError:
        pass
    return False


def _generator_for(root: Path, target: Path) -> Optional[str]:
    mf = H.py_root(root) / "tools" / "codegen_manifest.py"
    if not mf.is_file():
        return None
    try:
        spec = importlib.util.spec_from_file_location("_srmech_codegen_manifest2", mf)
        if spec is None or spec.loader is None:
            return None
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        srmech_root = root / "docs" / "srmech"
        for g in getattr(mod, "GENERATORS", ()):
            rel = getattr(g, "output", None)
            if isinstance(rel, str) and (srmech_root / rel).resolve() == target:
                return getattr(g, "script", None)
    except Exception:
        return None
    return None


def body(payload: Dict[str, Any]) -> int:
    raw = H.target_file(payload)
    if not raw:
        return H.allow()
    root = H.repo_root()
    try:
        target = Path(raw).resolve()
    except Exception:
        return H.allow()

    reason = None
    if target in _manifest_outputs(root):
        reason = "it is a tools/regen_all.py OUTPUT (listed in codegen_manifest.GENERATORS)"
    elif target.is_file() and _has_banner(target):
        reason = f'its first {BANNER_LINES} lines carry a "{BANNER}" banner'

    if reason is None:
        return H.allow()

    try:
        shown = target.relative_to(root)
    except ValueError:
        shown = target

    lines = [
        f"BLOCKED (generated-file-edit-blocker): {shown} must not be hand-edited "
        f"— {reason}.",
        "",
        "A hand-edit here ships in the wheel and then silently reverts on the "
        "next regen. rc346 measured the coupling: 14 bytes injected into "
        "_tool_docs.py moved srmech_tool_registry.c by exactly 14 bytes.",
        "",
        "Edit the GENERATOR INPUT instead, then regenerate:",
    ]
    gen = _generator_for(root, target)
    if gen:
        lines.append(f"    input feeds: {gen}")
    lines += [
        "    (for tool prose: tools/_tool_docs_curated.py or the ToolEntry itself)",
        "    python3 tools/regen_all.py            # writes",
        "    python3 tools/regen_all.py --check    # content-equality, writes nothing",
        "",
        "regen_all.py writes via Bash, not the Edit tool, so regeneration is "
        "never blocked by this hook.",
    ]
    return H.block(lines)


if __name__ == "__main__":
    H.run_hook(body)
