"""PreToolUse(Edit|Write|NotebookEdit) — refuse a hand-edit to a generated file.
(rc452, `#T1166`)

WHAT IT CATCHES
===============
A surgical fix typed straight into one of the six ``tools/regen_all.py``
outputs. The temptation is live every time a count-pin reddens, and the damage
is delayed rather than loud: a hand-edited ``_tool_docs.py`` SHIPS IN THE WHEEL
and reaches users through ``describe()``, the MCP tool list and the compiled-in
C registry — then silently reverts on the next regen, taking the fix with it.

The propagation is measured, not assumed: rc346 injected 14 bytes into
``_tool_docs.py`` and watched ``srmech_tool_registry.c`` move 827380 -> 827394.
The generated ``.c`` embeds the docs prose, so a hand-edit to one output puts
TWO artifacts out of sync with their generator.

⚠️ THE DEAD-PREDICATE REPAIR — READ THIS BEFORE CHANGING THE LOADER
==================================================================
As first shipped this hook ran on its banner predicate ALONE. The manifest
predicate returned ``[]`` on EVERY invocation and the bare ``except Exception:
return []`` swallowed the reason. Measured cause, reproduced deterministically:

    File ".../dataclasses.py", line 711, in _is_type
        ns = sys.modules.get(cls.__module__).__dict__
    AttributeError: 'NoneType' object has no attribute '__dict__'

``codegen_manifest.py`` opens with ``from __future__ import annotations``, so
every field annotation on its ``@dataclass(frozen=True) class Generator`` is a
STRING. ``dataclasses`` must then resolve those strings textually to spot
``ClassVar`` / ``InitVar`` / ``KW_ONLY``, and it does that by looking the
defining module up in ``sys.modules``. Loading by ``spec_from_file_location`` +
``module_from_spec`` + ``exec_module`` never PUTS the module there, so the
lookup returned ``None`` and the class body raised — before ``GENERATORS`` was
ever bound.

**The fix is the one line ``sys.modules[spec.name] = mod`` before
``exec_module``** — the documented importlib recipe, and the reason it is
documented. Any future rewrite of :func:`_load_manifest` must keep it.

The failure was invisible because a dead predicate and a satisfied predicate
are the same shape from outside: both make the hook exit 0 on a hand-written
file. :func:`selftest` exists so the difference is observable — it prints the
POPULATION of each predicate, and ``check_hooks.py`` asserts those populations
are non-empty. A predicate that cannot return otherwise is not a measurement.

TWO INDEPENDENT PREDICATES, EITHER SUFFICIENT
=============================================
1. **The manifest.** ``tools/codegen_manifest.py`` is the SSoT for what is
   generated; its ``GENERATORS`` table carries an ``output`` per row. It is
   loaded here by file path, WITHOUT importing the ``srmech`` package, so this
   hook stays fast and cannot be broken by a half-written module. If the six
   outputs change, this hook follows automatically — there is no second list to
   keep in step. Measured population at rc452: **6**.

2. **The banner**, and it is CONJUNCTIVE — a do-not-edit phrase AND the word
   "generated", case-insensitively, in the first :data:`BANNER_LINES` lines.
   Both halves earn their place, measured over the 3331 tracked files under
   ``docs/srmech/``, ``tests/`` and ``src/``:

   * The shipped predicate was the bare case-SENSITIVE string ``DO NOT EDIT``.
     It matched **6** files and MISSED **7** genuinely generated ones, because
     they spell it in lower case — including ``_c_claims.py`` ("GENERATED by
     ``tools/gen_c_claims.py`` — do not edit by hand"), which is a real
     ``regen_all`` output, and all three ``_unicode_*_tables`` pairs, which are
     the EXCLUDED-generator outputs this predicate was written to cover.
   * Case-insensitive ALONE over 3 lines matches **11** files, and one is a
     false positive: ``rbs_nn_research/UPSTREAM_NOTES.md`` opens with the prose
     "Do not edit srmech package files in this session." — a sentence about
     OTHER files, not a banner.
   * Requiring "generated" as well removes exactly that one and keeps every
     true positive: **13 hits, 13 generated, 0 false positives** at
     ``BANNER_LINES = 5``. Widening from 3 to 5 lines is what admits the three
     ``c/src/srmech_unicode_*_tables.h`` headers, whose banner sits below a
     copyright block.

   Do not "simplify" this back to a single substring. The conjunction IS the
   measurement that separates a banner from a sentence.

Predicate 1 needs no file read at all. Predicate 2 reads five lines.

WHY REGENERATION IS NEVER BLOCKED
=================================
``regen_all.py`` writes through Python file I/O in a Bash invocation, not
through the Edit tool, so it never reaches a PreToolUse(Edit) matcher. The
allowed path stays open by construction rather than by an exemption.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _hooklib as H  # noqa: E402

#: Both halves must appear, case-insensitively, within the first
#: :data:`BANNER_LINES` lines. See the module docstring for the census that
#: fixed each of these three constants.
BANNER_EDIT = "do not edit"
BANNER_GEN = "generated"
BANNER_LINES = 5

#: Files that carry a generated-file banner but whose OWN banner licenses
#: hand-editing. Blocking these is a false positive, and a hook that blocks
#: legitimate work gets switched off within a day.
#:
#: ``_carrier_examples.py`` line 1-2 reads, verbatim:
#:     "DO NOT EDIT auto rows by hand (regenerate); hand-curated construction
#:      examples may be added here and are preserved."
#: Its generator (``gen_carrier_examples_probe.py``) is in the manifest's
#: EXCLUDED table as HUMAN-IN-THE-LOOP for the same reason. The shipped hook
#: blocked it outright; that was a measured false block, so it is allowed here
#: WITH a warning rather than silently.
EXEMPT_WITH_WARNING = {
    "python/srmech/introspect/_carrier_examples.py": (
        "its own banner says hand-curated rows 'may be added here and are "
        "preserved', and its generator is EXCLUDED as human-in-the-loop"),
}

_MANIFEST_CACHE: Dict[str, Any] = {}


def _load_manifest(root: Path):
    """The ``codegen_manifest`` module object, or ``None``.

    Loaded by file path so no ``srmech`` package import happens and a
    half-written module cannot break this hook.

    ⚠️ ``sys.modules[spec.name] = mod`` BEFORE ``exec_module`` is load-bearing,
    not tidiness — see the module docstring. Removing it silently returns this
    hook to running on one predicate.
    """
    key = str(root)
    if key in _MANIFEST_CACHE:
        return _MANIFEST_CACHE[key]
    mod = None
    mf = H.py_root(root) / "tools" / "codegen_manifest.py"
    if mf.is_file():
        try:
            spec = importlib.util.spec_from_file_location(
                "_srmech_codegen_manifest", mf)
            if spec is not None and spec.loader is not None:
                mod = importlib.util.module_from_spec(spec)
                sys.modules[spec.name] = mod   # ← THE FIX. Keep it.
                try:
                    spec.loader.exec_module(mod)
                except Exception:
                    sys.modules.pop(spec.name, None)
                    raise
        except Exception as exc:
            # Announce rather than swallow: a silently dead predicate is the
            # exact defect this hook shipped with.
            print(f"[generated-file-edit-blocker] manifest predicate "
                  f"UNAVAILABLE ({type(exc).__name__}: {exc}) — running on the "
                  f"banner predicate alone.", file=sys.stderr)
            mod = None
    _MANIFEST_CACHE[key] = mod
    return mod


def _manifest_rows(root: Path) -> List[Tuple[Path, Optional[str]]]:
    """``(absolute output path, generator script)`` for every declared row."""
    mod = _load_manifest(root)
    if mod is None:
        return []
    srmech_root = root / "docs" / "srmech"
    rows: List[Tuple[Path, Optional[str]]] = []
    for g in getattr(mod, "GENERATORS", ()):
        rel = getattr(g, "output", None)
        if isinstance(rel, str) and rel:
            rows.append(((srmech_root / rel).resolve(), getattr(g, "script", None)))
    return rows


def _has_banner(path: Path) -> bool:
    """True when the head of ``path`` carries BOTH banner halves."""
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            head = "".join(fh.readline() for _ in range(BANNER_LINES)).lower()
    except OSError:
        return False
    return BANNER_EDIT in head and BANNER_GEN in head


def body(payload: Dict[str, Any]) -> int:
    raw = H.target_file(payload)
    if not raw:
        return H.allow()
    root = H.repo_root()
    try:
        target = Path(raw).resolve()
    except Exception:
        return H.allow()

    for rel, why in EXEMPT_WITH_WARNING.items():
        if target == (root / "docs" / "srmech" / rel).resolve():
            return H.allow([
                f"[generated-file-edit-blocker] {rel} is GENERATED but exempt: "
                f"{why}. Edit curated rows only — an auto row typed here "
                f"reverts on the next regen."])

    reason = None
    gen = None
    for out, script in _manifest_rows(root):
        if out == target:
            reason = ("it is a tools/regen_all.py OUTPUT "
                      "(listed in codegen_manifest.GENERATORS)")
            gen = script
            break
    if reason is None and target.is_file() and _has_banner(target):
        reason = (f'its first {BANNER_LINES} lines carry a generated-file '
                  f'banner ("{BANNER_GEN}" + "{BANNER_EDIT}")')

    if reason is None:
        return H.allow()

    try:
        shown = target.relative_to(root)
    except ValueError:
        shown = target

    lines = [
        f"BLOCKED (generated-file-edit-blocker): {shown} must not be hand-edited "
        f"— {reason}.",
        "",
        "A hand-edit here ships in the wheel and then silently reverts on the "
        "next regen. rc346 measured the coupling: 14 bytes injected into "
        "_tool_docs.py moved srmech_tool_registry.c by exactly 14 bytes.",
        "",
        "Edit the GENERATOR INPUT instead, then regenerate:",
    ]
    if gen:
        lines.append(f"    input feeds: {gen}")
    lines += [
        "    (for tool prose: tools/_tool_docs_curated.py or the ToolEntry itself)",
        "    python3 tools/regen_all.py            # writes",
        "    python3 tools/regen_all.py --check    # content-equality, writes nothing",
        "",
        "regen_all.py writes via Bash, not the Edit tool, so regeneration is "
        "never blocked by this hook.",
    ]
    return H.block(lines)


def selftest() -> int:
    """Print each predicate's POPULATION so a dead one is visible.

    ``check_hooks.py`` asserts both are non-empty. This exists because the
    shipped hook ran for its whole life with the manifest predicate returning
    ``[]``, and from outside that is indistinguishable from a satisfied
    predicate: both exit 0 on a hand-written file.
    """
    root = H.repo_root()
    rows = _manifest_rows(root)
    print(f"manifest predicate population: {len(rows)}")
    for out, script in rows:
        mark = "ok " if out.is_file() else "MISSING"
        try:
            shown = out.relative_to(root)
        except ValueError:
            shown = out
        print(f"  [{mark}] {shown}   <- {script}")
    banner = [out for out, _ in rows if out.is_file() and _has_banner(out)]
    print(f"banner predicate covers {len(banner)} of those {len(rows)} outputs")
    print(f"exempt-with-warning: {len(EXEMPT_WITH_WARNING)}")
    return 0 if rows else 1


if __name__ == "__main__":
    if "--selftest" in sys.argv[1:]:
        sys.exit(selftest())
    H.run_hook(body)
