"""Declarative, one-shot DSL surface for user-declared classes (rc40).

The DSL companion to :mod:`srmech.dsl._class_catalog` — the LLM-/CLI-ergonomic
entry points that introspect and *run* a user-declared ``[class]`` (the rc39
``CatalogClass``) in ONE call. The fluent surface holds a live instance and
chains method calls; that shape isn't tool-ergonomic, so this module exposes the
**stateless** surface instead: pass the instance state in as ``fields``, get the
result + the post-call state back (the name+UUID handle dual-grammar at the
functional level — the caller threads the state, no live handle required).

* :func:`describe_class` / :func:`list_class_surface` — JSON-able introspection
  (fields + methods + binds + provenance) so an LLM / CLI knows what a class
  offers before calling.
* :func:`run_class_method` — construct from ``fields``, invoke ``method`` with
  ``args``, return ``{"result", "fields", ...}``. The one-shot run entry point
  CLI (rc41) + the tool_schema/MCP surface (rc41) compose on.

Framework reading: Class E (catalog enumeration) ∘ Class F (descriptor render)
for the introspection; Class M (the CatalogClass bind-dispatch) for the run. No
new primitive — thin one-shot façades over the rc39 loader.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from ._class_catalog import get_class_descriptor, list_classes, make_class

# Characters allowed unquoted in a TOML bare key (A-Z a-z 0-9 _ -).
_BARE_KEY_OK = set(
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-"
)


def _toml_basic_str(s: str) -> str:
    """Quote ``s`` as a single-line TOML basic string (round-trip-exact).

    Always single-line with ``\\n`` / ``\\t`` etc. escaped, so an introspected
    multi-line ``doc`` re-emits to a value that ``tomllib`` decodes back to the
    identical string (round-trippable through make_class — the §39 contract).
    """
    out: List[str] = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\b":
            out.append("\\b")
        elif ch == "\f":
            out.append("\\f")
        elif ord(ch) < 0x20:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _toml_key(k: str) -> str:
    """Render ``k`` as a TOML key — bare if it's bare-key-safe, else quoted."""
    if not isinstance(k, str) or not k:
        raise ValueError(
            f"generate_class_descriptor: key must be a non-empty str; got {k!r}"
        )
    if all(c in _BARE_KEY_OK for c in k):
        return k
    return _toml_basic_str(k)


def _render_class_toml(
    name: str,
    kind: str,
    doc: str,
    fields: Dict[str, str],
    methods: Dict[str, Dict[str, Any]],
) -> str:
    """Render a ``[class]`` TOML descriptor from its components (the §39 emitter)."""
    lines: List[str] = [
        "# Generated by srmech.dsl.generate_class_descriptor (§39 — the make_class",
        "# inverse). A [class] descriptor: drop it in a register_class_dir /",
        "# SRMECH_CLASS_PATH dir and srmech.dsl.make_class constructs the identical",
        "# class — fields + methods-as-cascade-op-refs, 100% declarative, zero Python.",
        "",
        "[class]",
        "name = " + _toml_basic_str(name),
    ]
    if kind:
        lines.append("kind = " + _toml_basic_str(kind))
    if doc:
        lines.append("doc = " + _toml_basic_str(doc))

    if fields:
        lines.append("")
        lines.append("[class.field]")
        for fname, ftype in fields.items():
            lines.append(_toml_key(fname) + " = " + _toml_basic_str(str(ftype)))

    for mname, mspec in methods.items():
        if not isinstance(mspec, dict):
            raise ValueError(
                f"generate_class_descriptor: method {mname!r} spec must be a "
                f"dict; got {type(mspec).__name__}"
            )
        op = mspec.get("op")
        if not isinstance(op, str) or not op:
            raise ValueError(
                f"generate_class_descriptor: method {mname!r} needs a non-empty "
                f"'op' dotted-path; got {op!r}"
            )
        appends = mspec.get("appends")
        sets = mspec.get("sets")
        if appends is not None and sets is not None:
            raise ValueError(
                f"generate_class_descriptor: method {mname!r} may route its "
                f"result to at most one of 'appends'/'sets', not both"
            )
        binds = mspec.get("binds", []) or []
        lines.append("")
        lines.append("[class.method." + _toml_key(mname) + "]")
        lines.append("op = " + _toml_basic_str(op))
        lines.append(
            "binds = [" + ", ".join(_toml_basic_str(str(b)) for b in binds) + "]"
        )
        if appends is not None:
            lines.append("appends = " + _toml_basic_str(str(appends)))
        if sets is not None:
            lines.append("sets = " + _toml_basic_str(str(sets)))
        mdoc = mspec.get("doc", "")
        if mdoc:
            lines.append("doc = " + _toml_basic_str(str(mdoc)))

    return "\n".join(lines) + "\n"


def describe_class(name: str) -> Dict[str, Any]:
    """Return a JSON-able description of the user-declared class ``name``.

    ``{"name", "kind", "doc", "fields": {field: type}, "methods": {method:
    {"op", "binds", "doc", ["appends"|"sets"]}}, "provenance"}``. Sourced from
    the on-disk ``[class]`` descriptor (the SSoT), so it's always in lockstep
    with what :func:`run_class_method` can actually construct + invoke.
    """
    desc = get_class_descriptor(name)
    cls = desc.get("class", {})
    methods: Dict[str, Any] = {}
    for mname, mspec in cls.get("method", {}).items():
        entry: Dict[str, Any] = {
            "op": str(mspec.get("op", "")),
            "binds": [str(b) for b in mspec.get("binds", [])],
            "doc": str(mspec.get("doc", "")),
        }
        if "appends" in mspec:
            entry["appends"] = str(mspec["appends"])
        if "sets" in mspec:
            entry["sets"] = str(mspec["sets"])
        methods[mname] = entry
    prov = str(desc.get("_provenance", "srmech"))
    return {
        "name": str(cls.get("name", name)),
        "kind": str(cls.get("kind", "")),
        "doc": str(cls.get("doc", "")),
        "fields": {str(k): str(v) for k, v in cls.get("field", {}).items()},
        "methods": methods,
        # MPM provenance tier: "srmech" (A-tier shipped seed) or "user"
        # (a bring-your-own register_class_dir class, attested to its hash).
        "provenance": "srmech" if prov == "srmech" else "user",
    }


def list_class_surface() -> List[Dict[str, Any]]:
    """Enumerate every user-declared class (the discovery companion).

    Returns ``[describe_class(name) for name in list_classes()]`` — the shipped
    seed (genome) PLUS any bring-your-own classes from a ``register_class_dir``
    dir. The introspection view CLI ``srmech class list`` + the LLM tool surface
    consume so a caller can pick a class + method before running.
    """
    return [describe_class(name) for name in list_classes()]


def run_class_method(
    class_name: str,
    method: str,
    *,
    fields: Optional[Dict[str, Any]] = None,
    args: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Construct ``class_name`` from ``fields``, invoke ``method`` with ``args``.

    The stateless one-shot run: a fresh instance is built from the ``fields``
    dict, ``method`` is called with the ``args`` dict, and the result is returned
    alongside the instance's post-call field state — so a caller (CLI / LLM /
    bus) threads the state across calls without holding a live object.

    Returns ``{"class", "method", "result", "fields"}`` where ``fields`` is the
    instance's state AFTER the call (so an ``appends``/``sets`` method's mutation
    is visible). ``fields`` and ``args`` are plain dicts (MCP-grammar friendly:
    no ``**kwargs`` on the public signature).
    """
    factory = make_class(class_name)
    instance = factory(**(fields or {}))
    bound = getattr(instance, method)
    result = bound(**(args or {}))
    return {
        "class": class_name,
        "method": method,
        "result": result,
        "fields": instance.fields,
    }


def generate_class_descriptor(
    name: str,
    *,
    fields: Optional[Dict[str, str]] = None,
    methods: Optional[Dict[str, Dict[str, Any]]] = None,
    doc: Optional[str] = None,
    kind: Optional[str] = None,
) -> str:
    """Render a ``[class]`` TOML descriptor string — the inverse of make_class (§39).

    The make_class loop closed the other direction: given a class ``name`` +
    field declarations + methods-as-dotted-cascade-op-refs, emit a ``[class]``
    TOML descriptor that drops into a :func:`register_class_dir` dir and
    constructs the *identical* class via :func:`make_class`. Two modes:

    * **explicit** — pass ``fields`` (``{field: type}``) and/or ``methods``
      (``{method: {"op": dotted, "binds": [...], "doc": ...,
      ["appends"|"sets"]: field}}`` — the :func:`describe_class` method shape).
      Renders directly from the components. ``kind`` / ``doc`` default to empty.
    * **introspection** — pass ONLY ``name`` (a registered class, e.g.
      ``"Genome"``); the descriptor is recovered via :func:`describe_class` and
      re-emitted. The Class-H self-introspection path: a constructed class
      renders its own ``[class]`` TOML back out. (``fields``/``methods`` left
      ``None`` selects this mode; ``kind``/``doc`` still override if supplied.)

    The emitted string is round-trippable: ``tomllib.loads`` it (or register +
    :func:`make_class`) and you get the same fields + methods + binds back. Docs
    re-emit as single-line basic strings with escaped newlines, so a multi-line
    seed ``doc`` decodes back bit-identically.

    Framework reading: Class E (catalog enumeration) ∘ Class F (descriptor
    render) ∘ Class H (self-introspection) — **no new primitive class.** The
    genome seed proves the target shape; this closes the loop the other way.
    """
    if not isinstance(name, str) or not name:
        raise ValueError(
            "generate_class_descriptor: name must be a non-empty str"
        )

    if fields is None and methods is None:
        # Introspection mode: recover a registered class's descriptor + re-emit.
        described = describe_class(name)
        eff_kind = described["kind"] if kind is None else kind
        eff_doc = described["doc"] if doc is None else doc
        eff_fields = described["fields"]
        eff_methods = described["methods"]
    else:
        # Explicit mode: render straight from the passed components.
        eff_kind = "" if kind is None else kind
        eff_doc = "" if doc is None else doc
        eff_fields = dict(fields or {})
        eff_methods = dict(methods or {})

    return _render_class_toml(name, eff_kind, eff_doc, eff_fields, eff_methods)


__all__ = [
    "describe_class",
    "list_class_surface",
    "run_class_method",
    "generate_class_descriptor",
]
