"""S1 rc429 (`#T1132`) — SIZING the unsourced-claim class: ATTRIBUTION vs MENTION.

WHAT THIS MEASURES
==================
rc428 shipped a gate that verifies *a cited source actually contains the cited
claim*. A claim with **no source** has nothing to check, so that gate cannot
see it by construction. This instrument sizes the blind class and asks the only
question that decides whether it can be gated at all:

    Of the shipped string constants that name a literature concept and carry no
    identifier, how many ATTRIBUTE (credit a result to a named source as its
    warrant) and how many merely MENTION (use a standard name for a standard
    object, the way "Fourier transform" is used)?

A gate that cannot tell those apart would demand citations on ~1.5k sites, and
the predictable response is to bolt a plausible reference onto each —
manufacturing exactly the hallucinated-citation defect the arc exists to kill.

THE UNIT IS AN AST STRING CONSTANT (rc428's finding, re-used not re-litigated)
=============================================================================
``citation_corpus.string_constants`` resolves implicit concatenation. A line
scanner invents phantom truncated identifiers in one direction and cannot see a
claim whose term and locator sit on different source lines in the other.
Falsifier F4 below MEASURES that difference in this tree rather than citing it.

TWO VOCABULARIES, AND WHY THE COUNT DEPENDS ON WHICH
=====================================================
``V_manifest`` — the 32 attested claim terms in
``amsc/attested/literature_claims/row.ndjson``. This is rc428's vocabulary and
the one the 536 figure refers to.

``V_eponym`` — a personal-eponym vocabulary, generated by a proper-noun +
mathematical-object-noun bigram pass and then HAND-VETTED. It exists because
``V_manifest`` is *source-derived*: it holds only terms belonging to the two
attested papers, so it **cannot contain "Calugareanu-White-Fuller"** — one of
the two known defects is invisible to it. That is a structural blind spot in
the population definition, not a tuning parameter, and F1b measures it.

Auto-extraction WITHOUT vetting was refuted at rc428 (top candidates were
``Crossref``, ``Iterable``, ``Optional``, ``Jun``, ``Der``), so the bigram pass
GENERATES candidates and a human decides; the vetted list is data in the
NDJSON, not a hidden constant.

DISCIPLINE
==========
* No stdlib ``math`` / ``fractions`` / ``decimal``; no numpy; no ``abs()``.
* Every falsifier is PRE-REGISTERED in :data:`PREREG` with its prediction
  before it runs, and every null is classified REFUTED / BOUNDED / EMPTY /
  UNSUPPORTED.
* Controls are ASSERTED, not merely computed — :func:`_controls` raises. rc428
  D1 shipped an instrument that computed four controls and read one, and
  ``main()`` returned 0 while printing DEAD SEAM.
* Hand labels are written FIRST (``STAGE=sample``) and scored SECOND
  (``STAGE=score``), so no discriminator can be tuned against a label it has
  already seen.

USAGE
=====
    PYTHONPATH=docs/srmech/python SRMECH_EXPECT_PURE=1 \\
        python3 docs/srmech/notes/_s1_attribution_population_rc429.py sample
    ... hand-label into _s1_attribution_labels_rc429.json ...
    PYTHONPATH=docs/srmech/python SRMECH_EXPECT_PURE=1 \\
        python3 docs/srmech/notes/_s1_attribution_population_rc429.py score
"""

from __future__ import annotations

import ast
import json
import re
import sys
from collections import Counter
from functools import lru_cache
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_PY = _HERE.parent / "python"
sys.path.insert(0, str(_PY / "tests"))
sys.path.insert(0, str(_PY))

import srmech                                                  # noqa: E402
from srmech.amsc.format import sha256_bytes                    # noqa: E402
import citation_corpus as CC                                   # noqa: E402

OUT = _HERE / "_s1_attribution_population_rc429.ndjson"
LABELS = _HERE / "_s1_attribution_labels_rc429.json"
SAMPLE_DUMP = _HERE / "_s1_attribution_sample_rc429.txt"

#: Sample size. 60 is the floor the brief sets; 72 is what a 6-way stratum
#: split over the population's file-concentration divides evenly.
SAMPLE_N = 72


# ── PRE-REGISTRATION ──────────────────────────────────────────────────
# Written before any of it ran. Each entry: what is predicted, and what a null
# would MEAN. "An instrument that cannot return otherwise is not a measurement."

PREREG = {
    "F1a_positive_control_defect_sites_present": {
        "predicts": "Both known defect sites — cascade/cayley_dickson.py "
                    "malcev_defect and biology/genome.py cwf_consistency_mod2 "
                    "— appear in the scanned constant population.",
        "null_means": "UNSUPPORTED: if the instrument cannot see the two "
                      "sites the whole rc is about, every count it emits is "
                      "about a different corpus.",
    },
    "F1b_vocabulary_blind_spot": {
        "predicts": "V_manifest does NOT contain any term matching the "
                    "Calugareanu-White-Fuller concept, so defect site 2 is "
                    "invisible to the rc428 vocabulary.",
        "null_means": "REFUTED: if V_manifest does match it, the vocabulary "
                      "is not source-bounded and the blind-spot finding dies.",
    },
    "F2_negative_control": {
        "predicts": "Terms that cannot occur ('qwertzuiop', 'Zzyzxian "
                    "lemma') return ZERO sites.",
        "null_means": "The matcher is always-true; every count is noise.",
    },
    "F3_encoding": {
        "predicts": "An ASCII-hyphen-only matcher for 'Cayley-Dickson' reads "
                    "STRICTLY FEWER sites than the dash-folded matcher; "
                    "rc428 measured 164 ASCII vs 248 en-dash IN THIS TREE, so "
                    "ASCII-only should see well under 100%.",
        "null_means": "BOUNDED: equal counts would mean the tree has stopped "
                      "using the en-dash, which would make the fold "
                      "unnecessary rather than wrong.",
    },
    "F4_ast_vs_line": {
        "predicts": "A line-based scan yields a DIFFERENT population than the "
                    "ast scan, and at least one term instance is visible ONLY "
                    "after implicit-concatenation resolution.",
        "null_means": "BOUNDED: if identical, the ast choice is free here "
                      "even though it is right in principle.",
    },
    "F5_sample_representativeness": {
        "predicts": "The sample's per-file share tracks the population's; the "
                    "largest single file's share differs by <= 10 points.",
        "null_means": "The sample is not representative and no extrapolation "
                      "from it is honest.",
    },
    "F6_discriminator_can_return_otherwise": {
        "predicts": "Every scored discriminator fires on >0 and <100% of the "
                    "sample.",
        "null_means": "UNSUPPORTED for that discriminator: a predicate that "
                      "cannot return otherwise has measured nothing.",
    },
    "F7_labels_precede_scoring": {
        "predicts": "The labels file's sha256 recorded at score time equals "
                    "the one recorded when the sample was cut, so no label "
                    "moved after a discriminator was seen.",
        "null_means": "The precision/recall figures are tuned, not measured.",
    },
    "F9_matcher_artifact_rate": {
        "PRE_REGISTERED": False,
        "note": "POST-HOC. This falsifier did not exist when the sample was "
                "cut; it was DISCOVERED while hand-reading sample site 08, "
                "where 'Fano' turned out to be the letters of 'o[f a no]n-"
                "negative' joined by whitespace deletion. Reported as "
                "post-hoc because calling it pre-registered would be the "
                "same false-provenance defect this rc is about.",
        "predicts": "A non-trivial share of the rc428-rule population is "
                    "MATCHER ARTIFACT: the term is not present as prose, only "
                    "as a whitespace-joined cross-word accident or as part of "
                    "a code identifier.",
        "null_means": "EMPTY: if the corrected census equals the raw census, "
                      "the dense matcher has no artifact rate on this corpus "
                      "and the raw 1181 stands as measured.",
        "independent_check": "The sample's hand-labelled PHANTOM rate and the "
                             "whole-population B1/B2 census are two "
                             "independent estimates of the same quantity; "
                             "their DISAGREEMENT would be the finding.",
    },
    "F8_known_defects_flagged": {
        "predicts": "The best discriminator flags BOTH known defect sites.",
        "null_means": "REFUTED: a discriminator that misses the two sites the "
                      "rc exists for is the wrong discriminator, and this "
                      "instrument must say so rather than re-tune.",
    },
}


# ── vocabularies ──────────────────────────────────────────────────────

def manifest_terms():
    """``V_manifest`` — the 32 attested claim terms, from the shipped row set."""
    p = (Path(srmech.__file__).resolve().parent / "amsc" / "attested"
         / "literature_claims" / "row.ndjson")
    rows = [json.loads(l) for l in p.read_text(encoding="utf-8").splitlines()]
    return tuple(sorted({r["term"] for r in rows
                         if r.get("row_type") == "term"})), p


#: ``V_eponym`` — HAND-VETTED from the bigram candidates this script generates
#: (see :func:`eponym_candidates`). Every entry is a PERSON's name carried into
#: a mathematical object's name. Deliberately excludes the common-noun terms
#: V_manifest also holds ("modular", "determinant", "interpolation"), because
#: those name objects, never authorities.
V_EPONYM = (
    "Albert", "Baez", "Bott", "Brocot", "Calugareanu", "Cartan", "Cayley",
    "Chebyshev", "Clifford", "Dickson", "Dynkin", "Eisenstein", "Euler",
    "Fano", "Fourier", "Freudenthal", "Frenkel", "Frobenius", "Fuller",
    "Gauss", "Hamming", "Hopf", "Hurwitz", "Jacobi", "Jordan", "Kanerva",
    "Kuramoto", "Lagrange", "Laplace", "Legendre", "Lie", "Mal'cev",
    "Moufang", "Newton", "Noether", "Poincare", "Pythagorean", "Ramanujan",
    "Riemann", "Rosengren", "Schafer", "Stern", "Turaev", "Turin", "Viterbi",
    "Watson", "Weierstrass", "White", "Wick", "Wigner", "Zeilberger",
)

#: Mathematical-object nouns. A capitalised token immediately followed by one
#: of these is the classic eponym shape ``<Person> <object>``.
OBJECT_NOUNS = (
    "algebra", "algebras", "bracket", "conjecture", "construction",
    "criterion", "curve", "decomposition", "defect", "diagram", "equation",
    "expansion", "fibration", "form", "formula", "function", "functions",
    "group", "identity", "identities", "integral", "invariant", "lattice",
    "lemma", "loop", "manifold", "map", "matrix", "measure", "number",
    "numbers", "operator", "pair", "plane", "polynomial", "polynomials",
    "principle", "problem", "product", "relation", "residue", "ring",
    "rule", "series", "space", "sphere", "sum", "symbol", "system",
    "theorem", "theory", "transform", "triple", "tuple",
)

#: Capitalised tokens that precede an object noun but are NOT people. Derived
#: by reading the candidate list this script prints, not guessed: every one
#: really occurs in this tree in that position.
_NOT_A_PERSON = frozenset("""
The This That These Those A An And But For Not Now Note Args Returns Raises
Class Python C Each Every One Two Three Four Five Six Seven Eight Nine Ten
It Its If When Where While With Without From Into Over Under Same Only
Both All Any No Some Such Then Than There They We You I II III IV V VI VII
True False None Optional Iterable Sequence Dict List Tuple Mapping Callable
Union Any Type Set FrozenSet Hashable Exact Free Total Left Right Real
Complex Integer Rational Prime Cyclic Signed Native Pure Dense Sparse
Standard Canonical Universal Whole Half Full Empty Open Closed Finite
Infinite Discrete Continuous Abelian Nonabelian Linear Affine Projective
Positive Negative Zero Unit Identity Inverse Forward Backward Upper Lower
Inner Outer First Last Next Previous Current New Old Base Leaf Root Node
Edge Face Cell Slot Rung Block Stage Phase Step Pass Round Level Layer
Bit Byte Word Line Page File Path Name Key Value Index Count Size Shape
Order Rank Degree Dimension Scale Weight Norm Sign Phase Angle Length
Width Height Depth Mass Charge Spin Field Force Energy Action Metric
Gauge Frame Basis Vector Scalar Tensor Spinor Fiber Fibre Bundle Sheaf
NOTE WHAT WHEN WHY HOW SIBLING SIBLINGS SUBJECT
""".split())

_CAP = r"[A-ZÀ-Þ]"
_LOW = r"[a-zß-ÿ'’]"
_EPONYM_BIGRAM = re.compile(
    r"\b(%s%s{2,}(?:[-‐-―−]%s%s+)*)"
    r"(?:'s|’s)?\s+(%s)\b"
    % (_CAP, _LOW, _CAP, _LOW, "|".join(OBJECT_NOUNS)))


def eponym_candidates(paths, limit_files=None):
    """Generate ``<Capitalised> <object-noun>`` candidates for HUMAN vetting.

    This is a CANDIDATE GENERATOR, never a vocabulary. rc428 measured what
    happens when such a pass is trusted: its top hits were ``Crossref``,
    ``Iterable``, ``Optional``, ``Jun`` and ``Der``.
    """
    c = Counter()
    for p in (paths if limit_files is None else paths[:limit_files]):
        for _lineno, val in CC.string_constants(p):
            for m in _EPONYM_BIGRAM.finditer(CC._strip_code_spans(val)):
                head = m.group(1)
                if head in _NOT_A_PERSON:
                    continue
                c[head] += 1
    return c


# ── identifiers ───────────────────────────────────────────────────────

_DOI = re.compile(r"10\.\d{4,9}/[-._;()/:A-Za-z0-9]+")
_URL = re.compile(r"https?://\S+")
_ISBN = re.compile(r"\bISBN[- ]?[-0-9X ]{10,}", re.I)


def identifier_kinds(text):
    """Which identifier families does ``text`` carry? Empty = UNSOURCED."""
    out = []
    if CC._ARXIV.search(text):
        out.append("arxiv")
    if _DOI.search(text):
        out.append("doi")
    if _URL.search(text):
        out.append("url")
    if _ISBN.search(text):
        out.append("isbn")
    return out


# ── the matcher ───────────────────────────────────────────────────────

_WORDCH = re.compile(r"[0-9A-Za-z_]")
#: Suffixes that keep a match a real occurrence of the same word. Plurals and
#: possessives only — ``modular`` + ``ity`` is a DIFFERENT word and must not
#: pass, while ``Theta Function`` + ``s`` is the same term pluralised and must.
_OK_SUFFIX = ("", "s", "es", "'s", "’s")


def prose_occurrences(text, term):
    """Occurrences of ``term`` that are PROSE, not matcher artifacts.

    Two subtractions, each forced by a measured false positive in the rc429
    sample, and each a SYNTACTIC rule that names no file and no line:

    **B1 word boundary.** ``densify`` deletes whitespace so a term can cross a
    line wrap (``Cayley-\\n    Dickson``). The same deletion joins ADJACENT
    WORDS: ``of a non-negative`` densifies to ``ofanon-negative``, which
    contains ``fano``. Measured in the rc429 sample: ``Fano`` inside
    ``o[f a no]n-``, ``Bott`` inside ``Bott[om]-k``, ``F_4`` inside
    ``f_4[58]``. So a match must be bounded in the ORIGINAL text.

    **B2 identifier context.** A term inside a dotted or underscored
    identifier is CODE — ``srmech.physics.qm.triality``, ``triality_swap``,
    ``moufang_residue``, ``srmech_modular_forms_ring_represent``. This is
    rc428's axis A4 arriving from the other side: A4 blanks ``code spans``,
    and worked-example snippets carry bare identifiers with no span markers.

    Returns ``[(start, end, surface)]`` in ORIGINAL offsets.
    """
    stripped = CC._strip_code_spans(text)
    dense, idx = CC.densify_indexed(stripped)
    out = []
    for m in re.finditer(term_pattern_cached(term), dense, re.IGNORECASE):
        a, b = idx[m.start()], idx[m.end() - 1] + 1
        # B1 — the character before must not be a word character.
        if a > 0 and _WORDCH.match(stripped[a - 1]):
            continue
        # B2 left — a dotted-identifier prefix (``qm.triality``).
        if a > 0 and stripped[a - 1] == "." and a > 1 \
                and _WORDCH.match(stripped[a - 2]):
            continue
        # B1/B2 right — the trailing run must be a legal word suffix.
        j = b
        while j < len(stripped) and (_WORDCH.match(stripped[j])
                                     or stripped[j] in ".'’"):
            j += 1
        tail = stripped[b:j]
        if tail.rstrip(".") not in _OK_SUFFIX:
            continue
        out.append((a, b, text[a:b]))
    return out


@lru_cache(maxsize=256)
def term_pattern_cached(term):
    return CC.term_pattern(term)


def build_alt(terms):
    """One alternation over ``terms`` against DENSE text, groups keyed by index.

    Longest-first so ``exceptional Jordan`` wins over ``Jordan algebra``'s
    prefix and a nested term never masks its container.
    """
    ordered = sorted(terms, key=lambda t: (-len(t), t))
    pat = "|".join("(?P<t%d>%s)" % (i, CC.term_pattern(t))
                   for i, t in enumerate(ordered))
    return re.compile(pat, re.IGNORECASE), {"t%d" % i: t
                                            for i, t in enumerate(ordered)}


def terms_in(dense, alt, idx):
    return [idx[m.lastgroup] for m in alt.finditer(dense)]


# ── the population ────────────────────────────────────────────────────

class Site:
    """One string constant that names a claim term and carries no identifier."""

    __slots__ = ("path", "line", "text", "terms", "in_docstring", "sid",
                 "identifiers", "prose_terms")

    def __init__(self, path, line, text, terms, in_docstring, identifiers):
        self.path = path
        self.line = line
        self.text = text
        self.terms = terms
        self.in_docstring = in_docstring
        #: Which identifier families this constant carries. EMPTY = unsourced.
        self.identifiers = identifiers
        #: The subset of :attr:`terms` that survives B1/B2 as PROSE.
        self.prose_terms = []
        # Class A content-addressing: the site's identity IS its content hash.
        self.sid = sha256_bytes(
            ("%s|%d|%s" % (path, line, text)).encode("utf-8"))

    @property
    def unsourced(self):
        return not self.identifiers

    def as_row(self, quote=400):
        return {
            "site_id": self.sid[:16], "path": self.path, "line": self.line,
            "terms": sorted(set(self.terms)),
            "prose_terms": list(self.prose_terms),
            "in_docstring": self.in_docstring,
            "identifiers": self.identifiers,
            "chars": len(self.text),
            "quote": self.text[:quote],
        }


def docstring_lines(path):
    tree = ast.parse(path.read_bytes(), filename=str(path))
    out = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef,
                             ast.AsyncFunctionDef, ast.ClassDef)):
            b = node.body
            if (b and isinstance(b[0], ast.Expr)
                    and isinstance(b[0].value, ast.Constant)
                    and isinstance(b[0].value.value, str)):
                out.add(b[0].value.lineno)
    return out


def population(paths, alt, idx):
    """EVERY claim-term site (sourced or not), plus the totals a count needs.

    Returns the whole term-bearing set rather than only the unsourced subset,
    because the positive control has to be able to find a site that turned out
    to BE sourced — which is exactly what happened to ``malcev_defect`` at
    rc428, and an instrument holding only the unsourced subset reports that as
    "the corpus is wrong" instead of as the finding it is.
    """
    sites, tot = [], Counter()
    for p in paths:
        rel = p.relative_to(CC.PKG_ROOT).as_posix()
        docs = docstring_lines(p)
        for lineno, val in CC.string_constants(p):
            tot["str_constants"] += 1
            hits = terms_in(CC.densify(val), alt, idx)
            if not hits:
                continue
            tot["with_term"] += 1
            ids = identifier_kinds(val)
            if ids:
                tot["with_identifier"] += 1
            else:
                tot["unsourced"] += 1
                tot["unsourced_term_pairs"] += len(set(hits))
                tot["unsourced_term_occurrences"] += len(hits)
            s = Site(rel, lineno, val, hits, lineno in docs, ids)
            # B1/B2-corrected: does any hit survive as PROSE?
            s.prose_terms = sorted({t for t in set(hits)
                                    if prose_occurrences(val, t)})
            if not ids:
                if s.prose_terms:
                    tot["unsourced_prose"] += 1
                else:
                    tot["unsourced_all_artifact"] += 1
            sites.append(s)
    return sites, tot


def unsourced_of(sites):
    return [s for s in sites if s.unsourced]


# ── DISCRIMINATORS — pre-registered, scored, never tuned ───────────────
# Each takes a Site and returns True ("this ATTRIBUTES") or False.

_CREDIT = re.compile(
    r"\b(due to|after|following|per|proved|proves|proven|showed|shows|"
    r"established|introduced|attributed to|according to|cited|citing|"
    r"cites|states|asserts|derives from|goes back to|is named for|"
    r"named after|theorem of|result of|construction of)\b", re.I)
_YEAR = re.compile(r"\((?:1[6-9]\d{2}|20[0-4]\d)\)")
_POSSESSIVE = re.compile(r"\b%s%s{2,}(?:'s|’s)\b" % (_CAP, _LOW))
_REFBLOCK = re.compile(
    r"\b(References?|Citations?|Bibliograph|Provenance|SSoT|SSOT|cite_as|"
    r"Source|Attribution|See also|Further reading)\b\s*[:—-]", re.I)
_BIBSHAPE = re.compile(
    #: ``Baez, J.C. (`` — an author-initials-year byline
    (r"%s%s+,\s*%s\.(?:\s*%s\.)?\s*\(" % (_CAP, _LOW, _CAP, _CAP))
    #: ``*An Introduction to Nonassociative Algebras*`` — an italic title
    + r"|\*[^*]{6,}\*"
    #: ``ch. III`` — a chapter locator
    + r"|\bch\.\s*[IVXLC0-9]"
    #: publisher / journal apparatus
    + r"|\b(?:Press|Univ\.|University|Springer|Wiley|Elsevier"
      r"|Bull\.|Trans\.|Amer\.|Soc\.)\b")


def d1_possessive(site):
    """A capitalised name in POSSESSIVE form — ``CWF's writhe``, ``Baez's``."""
    return _POSSESSIVE.search(CC._strip_code_spans(site.text)) is not None


def d2_year(site):
    """A parenthesised publication year — ``(1966)``, ``(2002)``."""
    return _YEAR.search(site.text) is not None


def d3_credit_verb(site):
    """A credit verb or preposition — ``due to`` / ``proved`` / ``states``."""
    return _CREDIT.search(CC._strip_code_spans(site.text)) is not None


def d4_eponym_vocab(site):
    """A PERSONAL eponym is present, matched the rc428 way (dense).

    Kept in its ORIGINAL dense form even after B1/B2 was discovered, so the
    correction's value is MEASURED against :func:`d4b_eponym_vocab_prose`
    rather than asserted. Silently upgrading it would have deleted the
    evidence that the fix mattered.
    """
    dense = CC.densify(site.text)
    return any(re.search(term_pattern_cached(e), dense, re.IGNORECASE)
               for e in V_EPONYM)


def d4b_eponym_vocab_prose(site):
    """The same vocabulary under B1/B2 — the eponym must occur as PROSE."""
    return any(prose_occurrences(site.text, e) for e in V_EPONYM)


def d8_prose_term_present(site):
    """Any manifest claim term survives B1/B2 — i.e. the site is not artifact."""
    return bool(site.prose_terms)


#: A stated relation: an identity written out, rather than merely named.
_RELATION = re.compile(r"[=≡≅≈]|\\equiv|\bmod\s*2\b")


def d9_bare_eponym_relation(site):
    """POST-HOC. A personal eponym as prose, NO bibliographic apparatus, and a
    RELATION stated in the same string.

    Written after F8 REFUTED the best sample-scored discriminator on both
    known defects, to describe the sub-class those defects actually belong to:
    a theorem NAMED by its eponym, its content ASSERTED, and nothing behind
    it. Reported as post-hoc, and — see the F10 record — it cannot be
    validated on this sample, which drew zero members of the sub-class.
    """
    return (d4b_eponym_vocab_prose(site)
            and not (d2_year(site) or d5_ref_block(site) or d6_bib_shape(site))
            and _RELATION.search(site.text) is not None)


def d5_ref_block(site):
    """The string carries a References / Provenance / SSoT header."""
    return _REFBLOCK.search(site.text) is not None


def d6_bib_shape(site):
    """Bibliographic apparatus — ``Author, I. (``, ``*Title*``, ``ch. III``."""
    return _BIBSHAPE.search(CC._strip_code_spans(site.text)) is not None


def d7_module_has_identifier(site, modules_with_ids):
    """The site's MODULE cites an identifier somewhere — proximity proxy."""
    return site.path in modules_with_ids


#: name -> (fn, needs_context)
DISCRIMINATORS = {
    "D1_possessive_name": (d1_possessive, False),
    "D2_year": (d2_year, False),
    "D3_credit_verb": (d3_credit_verb, False),
    "D4_eponym_vocab": (d4_eponym_vocab, False),
    "D4b_eponym_vocab_prose": (d4b_eponym_vocab_prose, False),
    "D5_ref_block": (d5_ref_block, False),
    "D6_bib_shape": (d6_bib_shape, False),
    "D7_module_has_identifier": (d7_module_has_identifier, True),
    "D8_prose_term_present": (d8_prose_term_present, False),
    "D9_bare_eponym_relation": (d9_bare_eponym_relation, False),
}

#: Composites, evaluated the same way. Named because a single signal was
#: predicted to be too weak, and a conjunction is the obvious next thing to try.
COMPOSITES = {
    "C1_bib_or_refblock": lambda f: f["D5_ref_block"] or f["D6_bib_shape"],
    "C2_eponym_and_credit": lambda f: (f["D4_eponym_vocab"]
                                       and f["D3_credit_verb"]),
    "C3_any_of_D2_D5_D6": lambda f: (f["D2_year"] or f["D5_ref_block"]
                                     or f["D6_bib_shape"]),
    "C4_eponym_and_any_bib": lambda f: (
        f["D4b_eponym_vocab_prose"]
        and (f["D2_year"] or f["D5_ref_block"] or f["D6_bib_shape"]
             or f["D3_credit_verb"])),
    #: The bibliographic-APPARATUS conjunction: a year AND a title/publisher
    #: shape. Named because the sample's four attributions all carry both and
    #: rst emphasis (``*directional*``) carries only the second.
    "C5_year_and_bib": lambda f: f["D2_year"] and f["D6_bib_shape"],
    "C6_year_or_refblock": lambda f: f["D2_year"] or f["D5_ref_block"],
}


# ── controls: these RAISE ──────────────────────────────────────────────

def _controls(sites, tot, alt, idx, v_manifest):
    """Every control is ASSERTED. rc428 D1: computed four, read one."""
    out = {}

    # F2 negative control — the matcher must be able to return nothing.
    for junk in ("qwertzuiop", "Zzyzxian lemma"):
        jalt, jidx = build_alt((junk,))
        n = sum(1 for s in sites if terms_in(CC.densify(s.text), jalt, jidx))
        assert n == 0, "NEGATIVE CONTROL FAILED: %r found %d times" % (junk, n)
    out["F2_negative_control"] = {"verdict": "PASS", "junk_hits": 0}

    # F1a positive control — the known site must be IN the SCANNED population.
    # Scanned, NOT "unsourced": the first cut of this control asserted against
    # the unsourced subset and FIRED, because rc428 had already attached a
    # provenance block carrying arXiv:math/0105155 to malcev_defect. The
    # control was right to bite and the assertion was the wrong assertion —
    # this is the finding, recorded at record "known_defect_status", not a
    # corpus error.
    malcev = [s for s in sites if s.path == "cascade/cayley_dickson.py"
              and "Mal'cev" in s.terms]
    assert malcev, ("POSITIVE CONTROL FAILED: malcev_defect's site is not in "
                    "the scanned population; the instrument is reading a "
                    "different corpus.")
    out["F1a_positive_control"] = {
        "verdict": "PASS", "malcev_sites_scanned": len(malcev),
        "malcev_sites_unsourced": sum(1 for s in malcev if s.unsourced)}

    # Vocabulary sanity: every manifest term must be a legal pattern and the
    # alternation must actually bind each one.
    assert len(idx) == len(v_manifest), (len(idx), len(v_manifest))
    out["vocabulary"] = {"n_terms": len(v_manifest)}

    # B1/B2 controls — BOTH directions. Each string is verbatim from the
    # rc429 sample or from this tree, so none of them can be tuned away.
    for text, term in [
            # must SURVIVE: real prose, including a line-wrapped spelling,
            # a plural, and a term whose own spelling holds punctuation
            ("the fixed\n    Cayley–Dickson convention", "Cayley-Dickson"),
            ("Igusa, *Theta Functions* (1972)", "theta function"),
            ("Spin(8) generators are not block-diagonal", "Spin(8)"),
            ("{a : associator(a,x,y)=0 for all x,y}", "associator"),
            ("turn every Fano plane through", "Fano"),
            ("a normed division algebra (Hurwitz 1898)", "Hurwitz")]:
        assert prose_occurrences(text, term), (
            "B1/B2 POSITIVE CONTROL FAILED: %r lost in %r" % (term, text))
    for text, term in [
            # must be SUBTRACTED: whitespace-joined cross-word accidents…
            ("square root of a non-negative ``int``", "Fano"),
            ("the value oracle). Bottom-k modes of L", "Bott"),
            ("the SU(3) structure constant f_458 = f_678", "F_4"),
            # …and code identifiers, dotted or underscored
            ("from srmech.physics.qm.triality import x", "triality"),
            ("srmech_modular_forms_ring_represent", "modular"),
            ("moufang_residue", "Moufang"),
            ("quasimodular_represent", "modular")]:
        assert not prose_occurrences(text, term), (
            "B1/B2 NEGATIVE CONTROL FAILED: %r survived in %r"
            % (term, text))
    out["B1_B2_controls"] = {"verdict": "PASS", "positive": 6, "negative": 7}
    return out


def _f3_encoding(sites):
    """ASCII-hyphen-only vs dash-folded, MEASURED in this tree."""
    ascii_only = re.compile(r"Cayley-Dickson", re.I)
    folded = re.compile(CC.term_pattern("Cayley-Dickson"), re.I)
    a = sum(1 for s in sites if ascii_only.search(s.text))
    f = sum(1 for s in sites if folded.search(CC.densify(s.text)))
    # count the dash variants actually used
    variants = Counter()
    for s in sites:
        for m in re.finditer(r"Cayley([%s]?)\s*Dickson" % re.escape(CC.DASHES),
                             s.text, re.I):
            variants["U+%04X" % ord(m.group(1)) if m.group(1) else "no-dash"] \
                = variants.get("U+%04X" % ord(m.group(1))
                               if m.group(1) else "no-dash", 0) + 1
    verdict = "REFUTED" if a < f else ("BOUNDED" if a == f else "BROKEN")
    return {"ascii_only_sites": a, "dash_folded_sites": f,
            "ascii_sees_pct": (100 * a // f) if f else None,
            "dash_variants": dict(variants), "verdict": verdict}


def _f4_ast_vs_line(paths, alt, idx):
    """A LINE scan vs the AST scan, on the same tree. Both directions."""
    line_sites = 0
    for p in paths:
        for raw in p.read_text(encoding="utf-8").splitlines():
            if terms_in(CC.densify(raw), alt, idx) and not identifier_kinds(raw):
                line_sites += 1
    # split-claim probe: a term visible ONLY after concatenation
    split_only = []
    for p in paths:
        raw_lines = p.read_text(encoding="utf-8").splitlines()
        joined_hits = set()
        for lineno, val in CC.string_constants(p):
            if "\n" in val:
                continue                       # a triple-quoted body is 1 line
            for t in set(terms_in(CC.densify(val), alt, idx)):
                joined_hits.add((lineno, t))
        for lineno, t in joined_hits:
            src = raw_lines[lineno - 1] if 0 < lineno <= len(raw_lines) else ""
            if not terms_in(CC.densify(src), *build_alt((t,))):
                split_only.append({"path": p.name, "line": lineno, "term": t})
    return {"line_scan_sites": line_sites, "split_only_examples":
            split_only[:8], "n_split_only": len(split_only)}


# ── sampling: content-addressed, reproducible, Class A ─────────────────

def sample(sites, n=SAMPLE_N, salt="rc429/s1"):
    """A deterministic uniform sample: order by ``sha256(salt|site_id)``.

    Not ``random.sample`` — an RNG's stream is an implementation detail across
    interpreter versions, while a content hash is the same everywhere and is
    the project's own Class-A addressing.
    """
    keyed = sorted(sites, key=lambda s: sha256_bytes(
        (salt + "|" + s.sid).encode("utf-8")))
    return keyed[:n]


# ── scoring ───────────────────────────────────────────────────────────

def score(labels, feats):
    """Precision / recall of each predicate against the hand labels.

    ATTRIBUTION is the positive class. AMBIGUOUS rows are EXCLUDED from
    precision/recall and reported separately — folding them either way would
    manufacture a number the labels do not support.
    """
    out = {}
    decided = [k for k, v in labels.items() if v in ("ATTRIBUTION", "MENTION")]
    pos = {k for k in decided if labels[k] == "ATTRIBUTION"}
    for name in list(DISCRIMINATORS) + list(COMPOSITES):
        fired = {k for k in decided if feats[k][name]}
        tp = len(fired & pos)
        fp = len(fired - pos)
        fn = len(pos - fired)
        tn = len(decided) - tp - fp - fn
        fires_all = len([k for k in feats if feats[k][name]])
        out[name] = {
            "tp": tp, "fp": fp, "fn": fn, "tn": tn,
            "precision": _pct(tp, tp + fp),
            "recall": _pct(tp, tp + fn),
            "fires_on_sample": fires_all,
            "sample_n": len(feats),
            # F6: a predicate that cannot return otherwise measured nothing.
            "F6_can_return_otherwise": 0 < fires_all < len(feats),
        }
    return out, len(decided), len(pos)


def _pct(num, den):
    """Integer percent, or ``None`` when undefined. No float, no ``abs()``."""
    return None if den == 0 else (100 * num) // den


# ── main ──────────────────────────────────────────────────────────────

def emit(fh, rec):
    fh.write(json.dumps(rec, ensure_ascii=False, sort_keys=True) + "\n")


def main(stage):
    v_manifest, man_path = manifest_terms()
    alt, idx = build_alt(v_manifest)

    hand = list(CC.shipped_modules())
    gen = list(CC.generated_modules())
    h_all, h_tot = population(hand, alt, idx)
    g_all, g_tot = population(gen, alt, idx)
    h_sites = unsourced_of(h_all)          # THE population of interest
    g_sites = unsourced_of(g_all)

    ctrl = _controls(h_all, h_tot, alt, idx, v_manifest)
    f3 = _f3_encoding(h_sites)
    f4 = _f4_ast_vs_line(hand, alt, idx)

    # F1b — the vocabulary blind spot, measured not asserted.
    cwf_matched = [t for t in v_manifest
                   if CC.contains_term("Calugareanu-White-Fuller consistency "
                                       "check, Lk = Tw + Wr", t)]
    f1b = {"v_manifest_terms_matching_CWF": cwf_matched,
           "verdict": "CONFIRMED" if not cwf_matched else "REFUTED"}

    modules_with_ids = {
        p.relative_to(CC.PKG_ROOT).as_posix() for p in hand
        if any(identifier_kinds(v) for _l, v in CC.string_constants(p))}

    cwf_hand = cwf_census(h_all, hand)
    cwf_gen = cwf_census(g_all, gen)

    #: A Site for an arbitrary (path, line) so the CWF rows — which no
    #: manifest term reaches — can still be run through the predicates.
    _docs_cache = {}

    def mk_site(rel, line):
        p = CC.PKG_ROOT / rel
        if rel not in _docs_cache:
            _docs_cache[rel] = docstring_lines(p)
        for ln, val in CC.string_constants(p):
            if ln == line:
                return Site(rel, ln, val,
                            terms_in(CC.densify(val), alt, idx),
                            ln in _docs_cache[rel], identifier_kinds(val))
        return None

    smp = sample(h_sites)

    with OUT.open("w", encoding="utf-8", newline="\n") as fh:
        emit(fh, {"record": "provenance", "task": "#T1132", "rc": "rc429",
                  "stage": stage,
                  "srmech_file": srmech.__file__,
                  "srmech_version": srmech.__version__,
                  "python": "%d.%d.%d" % sys.version_info[:3],
                  "manifest_path": str(man_path),
                  "manifest_sha256": sha256_bytes(man_path.read_bytes())})
        emit(fh, {"record": "prereg", "falsifiers": PREREG})
        emit(fh, {"record": "population", "stratum": "hand_written",
                  "n_modules": len(hand), **dict(h_tot),
                  "distinct_modules_with_sites":
                      len({s.path for s in h_sites})})
        emit(fh, {"record": "population", "stratum": "generated",
                  "n_modules": len(gen), **dict(g_tot),
                  "distinct_modules_with_sites":
                      len({s.path for s in g_sites})})
        emit(fh, {"record": "population_by_file", "stratum": "hand_written",
                  "top": Counter(s.path for s in h_sites).most_common(20)})
        emit(fh, {"record": "population_by_term", "stratum": "hand_written",
                  "raw_freq": Counter(t for s in h_sites
                                      for t in set(s.terms)).most_common(),
                  "prose_freq": Counter(t for s in h_sites
                                        for t in s.prose_terms).most_common()})
        for label, sites_ in (("hand_written", h_sites),
                              ("generated", g_sites)):
            raw = len(sites_)
            pro = sum(1 for s in sites_ if s.prose_terms)
            emit(fh, {"record": "falsifier_F9_matcher_artifact",
                      "PRE_REGISTERED": False,
                      "stratum": label, "raw_unsourced": raw,
                      "prose_unsourced": pro,
                      "all_artifact": raw - pro,
                      "artifact_pct": (100 * (raw - pro) // raw) if raw else 0,
                      "verdict": "CONFIRMED" if pro < raw else "EMPTY"})
        emit(fh, {"record": "controls", **ctrl})
        emit(fh, {"record": "falsifier_F1b_vocabulary_blind_spot", **f1b})
        emit(fh, {"record": "cwf_census", "stratum": "hand_written",
                  "n": len(cwf_hand),
                  "n_unsourced": sum(1 for r in cwf_hand if r["unsourced"]),
                  "rows": cwf_hand})
        emit(fh, {"record": "cwf_census", "stratum": "generated",
                  "n": len(cwf_gen),
                  "n_unsourced": sum(1 for r in cwf_gen if r["unsourced"]),
                  "rows": cwf_gen})
        emit(fh, {"record": "known_defect_status",
                  **known_defect_sites(h_all, cwf_hand, modules_with_ids,
                                       mk_site)})
        emit(fh, {"record": "falsifier_F3_encoding", **f3})
        emit(fh, {"record": "falsifier_F4_ast_vs_line", **f4})
        emit(fh, {"record": "eponym_candidates",
                  "note": "GENERATED for human vetting; never a vocabulary. "
                          "rc428 refuted trusting such a pass.",
                  "top": eponym_candidates(hand).most_common(60)})

        # sample rows, always emitted so the population and the labels are in
        # ONE artifact and cannot drift apart.
        for s in smp:
            emit(fh, {"record": "sample_site", **s.as_row()})

        # F5 representativeness
        pop_top = Counter(s.path for s in h_sites).most_common(1)[0]
        smp_share = sum(1 for s in smp if s.path == pop_top[0])
        f5 = {"top_file": pop_top[0],
              "population_share_pct": 100 * pop_top[1] // len(h_sites),
              "sample_share_pct": 100 * smp_share // len(smp),
              "sample_n": len(smp)}
        f5["delta_pp"] = f5["sample_share_pct"] - f5["population_share_pct"]
        f5["verdict"] = ("PASS" if -10 <= f5["delta_pp"] <= 10
                         else "NOT REPRESENTATIVE")
        emit(fh, {"record": "falsifier_F5_representativeness", **f5})

        if stage == "sample":
            SAMPLE_DUMP.write_text(
                "\n\n".join(
                    "### %s  %s:%d  terms=%s\n%s"
                    % (s.sid[:16], s.path, s.line, sorted(set(s.terms)),
                       s.text[:1600])
                    for s in smp), encoding="utf-8")
            emit(fh, {"record": "stage", "stage": "sample",
                      "dump": str(SAMPLE_DUMP), "n": len(smp)})
            print("wrote %d sample sites to %s" % (len(smp), SAMPLE_DUMP))
            return 0

        # ── stage: score ──
        labels_raw = json.loads(LABELS.read_text(encoding="utf-8"))
        labels = {k: v["label"] for k, v in labels_raw["labels"].items()}
        by_id = {s.sid[:16]: s for s in smp}
        missing = sorted(set(by_id) - set(labels))
        assert not missing, "UNLABELLED sample sites: %s" % missing[:5]
        extra = sorted(set(labels) - set(by_id))
        assert not extra, ("labels reference sites NOT in the sample — the "
                           "sample moved under the labels: %s" % extra[:5])

        feats = {sid: features_of(s, modules_with_ids)
                 for sid, s in by_id.items()}

        scores, n_decided, n_pos = score(labels, feats)
        dist = Counter(labels.values())
        term_status = {k: v["term_status"] for k, v in
                       labels_raw["labels"].items()}
        cross = Counter((term_status[k], labels[k]) for k in labels)
        n_phantom = sum(1 for v in term_status.values() if v == "PHANTOM")
        emit(fh, {"record": "hand_labels",
                  "labels_sha256":
                      sha256_bytes(LABELS.read_bytes()),
                  "distribution": dict(dist),
                  "n": len(labels),
                  "ambiguous_rate_pct":
                      100 * dist.get("AMBIGUOUS", 0) // len(labels),
                  "attribution_rate_pct_of_decided":
                      _pct(n_pos, n_decided),
                  "term_status": dict(Counter(term_status.values())),
                  "cross_tab": {"%s|%s" % k: v for k, v in cross.items()}})

        # F9 independent check — the sample's PHANTOM rate against the
        # whole-population B1/B2 census. Two estimates of one quantity; the
        # DISAGREEMENT would be the finding.
        pop_art = 100 * (len(h_sites) - sum(1 for s in h_sites
                                            if s.prose_terms)) // len(h_sites)
        smp_art = 100 * n_phantom // len(labels)
        half = 100 // _isqrt(len(labels))
        emit(fh, {"record": "falsifier_F9_independent_check",
                  "population_artifact_pct": pop_art,
                  "sample_artifact_pct": smp_art,
                  "delta_pp": smp_art - pop_art,
                  "sampling_half_width_pp": half,
                  "verdict": ("AGREE" if -half <= smp_art - pop_art <= half
                              else "DISAGREE — one of the two is wrong and "
                                   "that is the finding")})
        emit(fh, {"record": "discriminator_scores",
                  "positive_class": "ATTRIBUTION",
                  "n_decided": n_decided, "n_attribution": n_pos,
                  "scores": scores})
        emit(fh, {"record": "per_site_features",
                  "rows": [{"site_id": k, "label": labels[k], **v}
                           for k, v in sorted(feats.items())]})

        # F6 — assert at least one discriminator is a real measurement.
        alive = [k for k, v in scores.items() if v["F6_can_return_otherwise"]]
        assert alive, ("F6 UNSUPPORTED for every discriminator: none can "
                       "return otherwise on this sample.")
        emit(fh, {"record": "falsifier_F6", "alive": alive,
                  "dead": [k for k in scores if k not in alive]})

        # F8 — does the BEST discriminator flag both known defects?
        best = max(
            (k for k in scores if scores[k]["F6_can_return_otherwise"]),
            key=lambda k: ((scores[k]["precision"] or 0)
                           + (scores[k]["recall"] or 0)))
        known = known_defect_sites(h_all, cwf_hand, modules_with_ids, mk_site)
        by_defect = {}
        for row in known["sites"]:
            f = row.get("features") or {}
            by_defect.setdefault(row["defect"], []).append(
                {"path": row["path"], "line": row["line"],
                 "unsourced": row["unsourced"], "flagged_by_best": f.get(best)})
        f8 = {"best_discriminator": best,
              "best_scores": scores[best],
              "per_defect": by_defect}
        unsourced_rows = [r for rows in by_defect.values() for r in rows
                          if r["unsourced"]]
        f8["unsourced_rows"] = len(unsourced_rows)
        f8["flagged_unsourced_rows"] = sum(1 for r in unsourced_rows
                                           if r["flagged_by_best"])
        f8["verdict"] = (
            "CONFIRMED" if unsourced_rows and f8["flagged_unsourced_rows"]
            == len(unsourced_rows) else "REFUTED — the best discriminator "
            "does not flag every unsourced known-defect site, so it is the "
            "wrong discriminator for this class")
        emit(fh, {"record": "falsifier_F8_known_defects", **f8})
        emit(fh, {"record": "known_defect_detail", **known})

        # The rubric applied to defect site 2, in the open. The brief calls it
        # a defect; the labelling rubric this rc used on 72 other sites, run
        # blind, calls it a MENTION — and the honest thing is to say so and
        # show the peers it is indistinguishable from, not to bend the rubric.
        cwf_site = mk_site("biology/genome.py", 1487)
        peers = [labels_raw["labels"][sid]["note"] for sid in by_id
                 if feats[sid]["D9_bare_eponym_relation"]][:6]
        emit(fh, {
            "record": "cwf_adjudication_under_own_rubric",
            "site": "biology/genome.py:1487 cwf_consistency_mod2",
            "quote": cwf_site.text[:200] if cwf_site else None,
            "rubric_label": "MENTION",
            "reasoning":
                "'The mod-2 Calugareanu-White-Fuller consistency check on a "
                "strand: Lk = Tw + Wr (mod 2)' names a standard theorem by "
                "its standard eponym and then states what THIS op computes. "
                "Under the definition used for all 72 sample sites — an "
                "ATTRIBUTION credits a result to a named source AS ITS "
                "WARRANT — that is the same act as 'the Frenkel-Turaev "
                "summation', 'the Faddeev-Leverrier characteristic "
                "polynomial' and 'Apagodu-Zeilberger creative telescoping', "
                "each of which the sample labelled MENTION.",
            "what_would_make_it_a_defect":
                "Not the missing citation: the missing PROVENANCE VERDICT. "
                "malcev_defect at cayley_dickson.py:2370 is the model — it "
                "carries no live citation either, and is NOT in the unsourced "
                "population, because rc428 attached a DERIVED-AND-MEASURED "
                "block naming what was checked and what was refused. The "
                "difference between the two sites is a verdict, not a DOI.",
            "indistinguishable_peers_in_sample": peers,
        })

        # ── the BARE-EPONYM sub-class, censused DIRECTLY ──
        # Not extrapolated. At ~1% of the population a 72-draw sample expects
        # fewer than one member, so a rate estimated from it would be noise
        # wearing a percentage sign. This counts every site instead.
        bare = [s for s in h_sites
                if d4b_eponym_vocab_prose(s)
                and not (d2_year(s) or d5_ref_block(s) or d6_bib_shape(s))]
        bare_rel = [s for s in bare if d9_bare_eponym_relation(s)]
        in_sample = sum(1 for sid in by_id if feats[sid]["D9_bare_eponym_relation"])
        emit(fh, {"record": "bare_eponym_census",
                  "definition": "a personal eponym present as PROSE, no "
                                "identifier, and no bibliographic apparatus "
                                "(no year, no title, no publisher)",
                  "n_bare_eponym": len(bare),
                  "n_bare_eponym_with_stated_relation": len(bare_rel),
                  "pct_of_prose_population":
                      100 * len(bare) // max(1, n_prose_pop(h_sites)),
                  "by_file": Counter(s.path for s in bare_rel).most_common(12),
                  "sample_members_drawn": in_sample,
                  "sample_members_labelled_attribution":
                      sum(1 for sid in by_id
                          if feats[sid]["D9_bare_eponym_relation"]
                          and labels[sid] == "ATTRIBUTION"),
                  "F10_verdict": _f10_verdict(
                      in_sample,
                      sum(1 for sid in by_id
                          if feats[sid]["D9_bare_eponym_relation"]
                          and labels[sid] == "ATTRIBUTION"),
                      len(bare_rel))})

        # extrapolation, on BOTH population definitions
        n_prose = sum(1 for s in h_sites if s.prose_terms)
        emit(fh, {"record": "estimate", "frame": "rc428_rule_raw",
                  **extrapolate(len(h_sites), dist, len(labels))})
        emit(fh, {"record": "estimate", "frame": "B1_B2_corrected_prose",
                  "note": "The same per-site rate applied to the corrected "
                          "population. Reported because the raw frame counts "
                          "388 sites whose claim term is not present.",
                  **extrapolate(n_prose, dist, len(labels))})
        print(json.dumps({"labels": dict(dist), "n_pop_raw": len(h_sites),
                          "n_pop_prose": n_prose}))
    return 0


#: Any spelling of the Calugareanu-White-Fuller concept this tree writes.
#: Three, and the ASCII one is what the GENERATED copies carry — an
#: accent-sensitive matcher sees the hand-written docstring and misses the
#: ToolEntry that actually ships to users.
_CWF = re.compile(r"C[aă]lug[aă]reanu|White\s*[-–—]?\s*Fuller|\bCWF\b")


def cwf_census(all_sites, extra_paths):
    """Every Calugareanu-White-Fuller site in the tree, with its sourced state.

    Kept separate from the manifest scan on purpose: **no term in V_manifest
    matches CWF**, so the rc428 vocabulary cannot see this defect at all. The
    census runs over raw constants rather than over ``all_sites`` for the same
    reason — a site is only in ``all_sites`` if some MANIFEST term hit it.
    """
    rows = []
    for p in extra_paths:
        rel = p.relative_to(CC.PKG_ROOT).as_posix()
        for lineno, val in CC.string_constants(p):
            if not _CWF.search(val):
                continue
            ids = identifier_kinds(val)
            rows.append({"path": rel, "line": lineno,
                         "identifiers": ids, "unsourced": not ids,
                         "spelling": sorted({m.group(0) for m
                                             in _CWF.finditer(val)}),
                         "chars": len(val), "quote": val[:220]})
    return rows


def known_defect_sites(all_sites, cwf_rows, modules_with_ids, mk_site):
    """The two named defects: sourced state at rc428, and every predicate."""
    out = []

    # ── site 1: malcev_defect. Every constant naming Mal'cev, anywhere.
    for s in [x for x in all_sites if "Mal'cev" in x.terms]:
        out.append({"defect": "malcev_defect", "path": s.path, "line": s.line,
                    "site_id": s.sid[:16], "identifiers": s.identifiers,
                    "unsourced": s.unsourced,
                    "features": features_of(s, modules_with_ids),
                    "quote": s.text[:260]})

    # ── site 2: cwf_consistency_mod2 and its CWF peers.
    for r in cwf_rows:
        s = mk_site(r["path"], r["line"])
        out.append({"defect": "cwf_consistency_mod2", "path": r["path"],
                    "line": r["line"], "identifiers": r["identifiers"],
                    "unsourced": r["unsourced"],
                    "features": features_of(s, modules_with_ids) if s else None,
                    "quote": r["quote"]})
    return {"sites": out}


def features_of(site, modules_with_ids):
    if site is None:
        return None
    f = {}
    for name, (fn, ctx) in DISCRIMINATORS.items():
        f[name] = bool(fn(site, modules_with_ids) if ctx else fn(site))
    for name, fn in COMPOSITES.items():
        f[name] = bool(fn(f))
    return f


def extrapolate(n_pop, dist, n_sample):
    """Point estimate + an honest interval, integer arithmetic only.

    The interval is the exact Clopper-Pearson-free bound this project can state
    without stdlib float machinery: a normal-approximation half-width is
    replaced by the conservative ``+/- 1/sqrt(n)`` rule expressed as integer
    percentage points via a small integer square root. Stated as what it is —
    a crude bound, honest about being crude — rather than a spurious CI.
    """
    a = dist.get("ATTRIBUTION", 0)
    amb = dist.get("AMBIGUOUS", 0)
    rate_pp = 100 * a // n_sample
    hi_pp = 100 * (a + amb) // n_sample          # every AMBIGUOUS resolves bad
    half = 100 // _isqrt(n_sample)               # ~ 1/sqrt(n) in points
    lo = max(0, rate_pp - half)
    hi = min(100, hi_pp + half)
    return {
        "population_hand_written": n_pop,
        "sample_n": n_sample,
        "attribution_rate_pct": rate_pp,
        "ambiguous_rate_pct": 100 * amb // n_sample,
        "point_estimate_sites": n_pop * rate_pp // 100,
        "interval_sites": [n_pop * lo // 100, n_pop * hi // 100],
        "interval_basis": "lower = point - 100/sqrt(n) points; upper = "
                          "(ATTRIBUTION+AMBIGUOUS) + 100/sqrt(n) points, i.e. "
                          "every AMBIGUOUS resolving to ATTRIBUTION",
        "sampling_assumption":
            "Sites are exchangeable within the hand-written stratum. They are "
            "NOT: 30% of the population lives in one file "
            "(introspect/_tool_docs_curated.py), so the estimate is a "
            "population mean, not a per-file rate.",
    }


def n_prose_pop(sites):
    return sum(1 for s in sites if s.prose_terms)


def _f10_verdict(drawn, attributed, census):
    """What the sample says about the sub-class the two known defects live in."""
    if drawn == 0:
        return ("BOUNDED — the sample drew no member of this sub-class, so no "
                "rate is estimable from it; the census of %d is the only "
                "measurement." % census)
    if attributed == 0:
        return ("REFUTED as an attribution predicate — the sample drew %d "
                "members of this sub-class and hand-labelled ALL of them "
                "MENTION (0 ATTRIBUTION). The shape the two known defects "
                "share is the shape %d shipped sites share, and on the "
                "evidence those sites are standard-name uses. A gate on this "
                "predicate would fire on %d sites at a measured precision of "
                "0/%d." % (drawn, census, census, drawn))
    return ("PARTIAL — %d of %d drawn members labelled ATTRIBUTION; the "
            "sub-class is mixed and the census of %d bounds it."
            % (attributed, drawn, census))


def _isqrt(n):
    """Integer square root by Newton descent — no stdlib math, no float."""
    if n < 2:
        return 1
    x, y = n, (n + 1) // 2
    while y < x:
        x, y = y, (y + n // y) // 2
    return x


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else "sample"))
