"""rc430 (`#T1127`) S2 — the ACCEPTANCE TEST for a per-parameter DOMAIN
CONSTRAINT field: would it actually make the semigroup census decidable?

WHY THIS FILE EXISTS
====================
The rc430 brief proposes adding a **domain-constraint** field to
``ToolParameter`` (which today publishes exactly ``name`` / ``type`` /
``required`` / ``summary`` — re-measured here, still four fields at rc429), and
justifies it with a headline: the registry-wide **semigroup census** is
permanently BOUNDED without it.

The census (``_s2_semigroup_census_rc427.py``, run at rc425/649) measured
**15 of 241** Tier-A ops as self-maps at all; pre-registered floor **PF4 fired**
(15 < 20) and was not tuned to pass. 226 Tier-A ops were unreachable: **92
NOT_CLOSED** + **134 NOT_EXECUTABLE**.

This file asks the question the brief demands be asked BEFORE the rc ships:
**is the census bounded by what the REGISTRY fails to publish, or by what the
INSTRUMENT chose to enumerate?** Those two answers imply opposite rcs.

THE THREE INDEPENDENT MEASUREMENTS
==================================
**M1 — REPRODUCTION.** Re-run the rc427 instrument, unmodified, at rc429/655 by
IMPORTING it (never re-typing it) so the partition is the same code, not a
lookalike. Report the current numbers.

**M2 — WHY, per unreachable op.** For each of the 226, capture what actually
happened — the exception type and message for NOT_EXECUTABLE, the OBSERVED
return type vs the OBSERVED input type for NOT_CLOSED — and bucket it. The
bucket that decides the rc:

  * a **VALUE / SHAPE guard** ("must be non-negative", "power of two <= 64",
    "length must be 8") is a domain constraint the registry could publish, and
    publishing it WOULD unblock the op;
  * a **TYPE wall** ("expected Mat", "object of type 'int' has no len()") is
    blocked on the declared type, which the registry ALREADY publishes. What is
    missing there is not a constraint but a **constructor** — how to BUILD an
    inhabitant. A constraint field does not supply one;
  * **NOT_CLOSED with a different observed return type** (``bytes -> str`` for
    ``sha256_bytes``, ``int -> tuple`` for ``pin_slot_at_zero``) is a property
    of the OP. No constraint on its input fixes it. It is not a self-map and
    never will be.

**M3 — THE ORACLE CEILING.** This is the acceptance test proper. A perfect
domain-constraint field has exactly one job: let a consumer produce a **valid
argument**. So the ceiling of what ANY such field can deliver is measured by
handing the census a valid argument obtained some other way — and the tree
already has one.

``ToolEntry.example["worked"]`` is **executable Python** and is present on
**570 of 655** entries; ``tools/run_worked_examples.py`` executes them and
``tests/worked_examples_result.ndjson`` records **467 status="ok"**. So for a
large fraction of the registry a *working call* is already committed in-tree.
This instrument executes the snippet with the op **monkeypatched by a recording
wrapper**, and keeps the arguments of every call that RETURNED. Those arguments
are valid by construction — the op accepted them — and in-contract by
provenance, because they are the op's own published example.

If the census reaches N with oracle arguments, then N is achievable with
information ALREADY in the tree, and the field's marginal contribution is
whatever lies beyond N — not the whole gap from 15.

THE ORBIT-CLOSURE CRITERION — AND WHY IT DEFUSES THE rc427 DEFECT
=================================================================
Instrument v1 was refuted by its own negative control: ``cyclic_mod_add``, a
translation and provably a bijection, classified SEMIGROUP_NOT_GROUP on the
witness ``carrier=Z12, binding (b=12, n=6)``. The sweep had bound a modulus
**smaller than the carrier it enumerated**. The collapse measured the WINDOW.

The window is the defect, so this instrument does not choose one. Given seed
arguments ``X0``, it takes ``S`` = the closure of ``X0`` under ``f``. ``S`` is
**generated by f itself**:

  1. ``f`` is total on ``S`` — every element of ``S`` is an ``f``-image or a
     seed, and every step that raised is recorded as NOT_TOTAL instead;
  2. ``f(S) subset-of S`` by construction;
  3. ``f|_S`` is non-injective iff ``|f(S)| < |S|`` — for a single seed this is
     exactly the rho-shape: an orbit with a **tail** ``t >= 1`` before its cycle
     has ``x_{t-1} != x_{t+c-1}`` both mapping to ``x_t``.

There is no window to get wrong because there is no window. ``cyclic_mod_add``
is therefore a **live negative control** (PC3): seeded from its own published
example, ``a -> (a + b) mod n`` with in-contract ``b, n`` orbits inside ``Z/n``
as a pure cycle, ``t = 0``, GROUP. If it fires SEMIGROUP here, this instrument
has inherited v1's defect and its Tier-B numbers are VOID.

WHAT THIS INSTRUMENT CANNOT DO — STATED BEFORE THE NUMBERS
==========================================================
O1. **Positives are CONFIRMED, negatives are BOUNDED.** A GROUP_ON_ORBIT
    verdict means "injective on the orbit closure of THESE seeds", never "the op
    is a bijection". Same L1 discipline as rc427; the seed set is emitted.
O2. **Identity is by content-address of ``repr``.** Two values are the same
    element iff ``sha256(repr(v))`` agrees (Class A). An object whose ``repr``
    embeds its address never repeats, so its orbit does not close and is
    reported ORBIT_UNCLOSED — BOUNDED, never a verdict.
O3. **The WHY-classifier is a regex over exception messages.** A regex is a
    declaration, so it is CROSS-CHECKED against the oracle (does the recovered
    valid argument have a ladder-representable type or not?) and the agreement
    rate is reported. Disagreements are printed, not smoothed.
O4. **The oracle is a LOWER bound on valid-argument availability**, not an
    upper one: an op with no ``worked`` snippet may still have a trivially
    findable argument. So "the oracle could not rescue it" is BOUNDED.
O5. **Snippet execution has side effects.** Runs in a temp cwd, in a worker
    subprocess the parent can kill; the known-slow allowlist is skipped by name.

PRE-REGISTERED FALSIFIERS — declared here, evaluated below, none tuned
=====================================================================
PC1  SENSITIVITY. ``q8_project_v4`` (the shipped non-injective idempotent with a
     C peer) MUST land SEMIGROUP under orbit closure. Else the orbit instrument
     is blind and every M3 number is VOID.
PC2  SPECIFICITY. ``chiral_flip`` (an involution) MUST land GROUP.
PC3  THE v1 REFUTATION, RE-RUN. ``cyclic_mod_add`` MUST land GROUP under
     oracle-bound orbit closure. It is the control that killed instrument v1;
     if it fires again, M3's Tier-B numbers are VOID.
PC4  NON-VACUITY. Both GROUP and SEMIGROUP buckets must be non-empty, else the
     injectivity test never separates (the "instrument cannot return otherwise"
     defect).
PC5  ORACLE SEPARATION. The oracle must rescue >= 1 op the ladder called
     NOT_EXECUTABLE **and** fail to rescue >= 1 op that genuinely is not a
     self-map (``sha256_bytes``: bytes -> str). Rescuing all, or none, means the
     seam is dead — the rc428 D1 defect — and M3 is VOID.
PC6  REPRODUCTION. The rc427 partition must reproduce at rc429 up to the
     registry delta. Else M1 is broken and M2/M3 have no denominator.
PC7  CLASSIFIER RESIDUAL. UNCLASSIFIED must be < 20% of the unreachable set,
     else M2's bucketing is reported UNSUPPORTED rather than as a measurement.

DISCIPLINE
==========
* No Python ``abs()``: the signed window comes from rc427's named Class-K
  pin-slot + Class-C reorientation composition, imported, not re-typed.
* No stdlib ``math`` / ``fractions`` / ``decimal``; no numpy. Exact rates via
  ``srmech.math.q.Q``; content-addressing via ``srmech.amsc.format.sha256_bytes``.
* Output is NDJSON, one record per line.

Run:  PYTHONPATH=docs/srmech/python python3 docs/srmech/notes/_s2_census_precondition_rc430.py
"""

import importlib
import importlib.util
import inspect
import json
import os
import subprocess
import sys
import threading
import time

import srmech
from srmech.amsc.format import sha256_bytes
from srmech.introspect.tool_schema import ToolParameter, get_tool_schema, warmup_all
from srmech.math.q import Q

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "_s2_census_precondition_rc430.ndjson")
RC427 = os.path.join(HERE, "_s2_semigroup_census_rc427.py")

PREREGISTERED = {
    "PC1_sensitivity": {
        "op": "srmech.biology.q8.q8_project_v4",
        "must_land_in": "SEMIGROUP",
        "void_if_fails": True,
        "why": "shipped non-injective idempotent self-map with a C peer; if the "
               "orbit instrument cannot see it, it is blind",
    },
    "PC2_specificity": {
        "op": "srmech.cascade.chiral_flip",
        "must_land_in": "GROUP",
        "void_if_fails": True,
        "why": "order reversal is an involution, hence a bijection",
    },
    "PC3_v1_refutation_rerun": {
        "op": "srmech.cascade.cyclic_mod_add",
        "must_land_in": "GROUP",
        "void_if_fails": True,
        "why": "this control FIRED against census instrument v1 (SEMIGROUP on "
               "carrier=Z12, binding b=12 n=6 -- a modulus SMALLER than the "
               "enumerated carrier). Orbit closure chooses no window, so it must "
               "now pass. If it fires again, M3's Tier-B numbers are VOID.",
    },
    "PC4_non_vacuity": {
        "rule": "both GROUP and SEMIGROUP buckets non-empty",
        "void_if_either_empty": True,
    },
    "PC5_oracle_separation": {
        "rule": "oracle must rescue >= 1 ladder-NOT_EXECUTABLE op AND must fail "
                "to rescue srmech.amsc.format.sha256_bytes (bytes -> str, "
                "genuinely not a self-map)",
        "void_if_fails": True,
        "why": "an oracle that rescues everything, or nothing, cannot separate. "
               "rc428's D1 shipped controls that were computed and never read.",
    },
    "PC6_reproduction": {
        "rule": "rc427 partition reproduces at rc429 up to the 649 -> 655 delta",
        "rc427_baseline": {"registry": 649, "tier_a": 241, "tier_b": 290,
                           "no_carrier_slot": 69, "excluded_safety": 49,
                           "tier_a_buckets": {"SEMIGROUP_NOT_GROUP": 6,
                                              "SEMIGROUP_BOOL_DOMAIN_ARTIFACT": 1,
                                              "GROUP": 8, "NOT_CLOSED": 92,
                                              "NOT_EXECUTABLE": 134},
                           "measured_self_maps": 15},
    },
    "PC7_classifier_residual": {
        "rule": "UNCLASSIFIED < 20% of the unreachable set, else M2 is UNSUPPORTED",
        "threshold_ratio": "1/5",
    },
    "PC9_harness_integrity": {
        "rule": "WORKER_DIED + WORKER_RESTART + TIMEOUT must be < 1/20 of the "
                "probe set, else M3 is VOID",
        "threshold_ratio": "1/20",
        "void_if_fails": True,
        "why": "MEASURED, not hypothetical. One run of this file recorded "
               "WORKER_DIED on 251 of 533 probes -- the worker script had been "
               "deleted out from under the live job -- and it still exited 0 with "
               "PC1 through PC8 ALL PASSING, because every named control op "
               "happened to be probed before the cascade. A control set that a "
               "half-dead run satisfies is not a control set. The worker now "
               "lives in a private temp dir under a PID-unique name so nothing in "
               "the tree can collide with it, and this falsifier makes the "
               "failure loud instead of arithmetic.",
    },
    "PC8_guard_extractor_recall": {
        "rule": "the THREE ops the rc430 brief names by their raises must each be "
                "found with a DOMAIN guard on the named parameter",
        "targets": {
            "srmech.math.primes.cyclic_period": "DOMAIN_RELATIONAL (gcd(a % n, n) != 1)",
            "srmech.cascade.group_algebra_table": "DOMAIN_* (power of two <= 64)",
            "srmech.cascade.cyclic_mod_add": "DOMAIN_* (non-negative / n > 0)",
        },
        "void_if_fails": False,
        "why": "the first draft found only two of three. cyclic_mod_add is a thin "
               "DELEGATING wrapper whose guard lives in srmech.math.cyclic.mod_add, "
               "one call level down. An extractor that does not follow delegation "
               "reports NO_DOMAIN_GUARD for it -- and for 132 other ops. If this "
               "control fails, M4's NO_DOMAIN_GUARD count is an OVER-count and M4 "
               "is reported BOUNDED rather than as a cardinal.",
    },
}

# ── M2 classifier, PRE-REGISTERED (O3: a regex is a declaration; cross-checked) ──
#
# Precedence is ENV > SHAPE > VALUE > TYPE > UNCLASSIFIED, and the reason is
# directional: if ANY ladder element got PAST the type wall and was rejected on
# its value, then the type IS representable and a value constraint would have
# gotten in. So a value/shape signal dominates a type signal.
SHAPE_MARKERS = (
    "length", "len(", "dim", "shape", "size", "square", "power of two",
    "must have", "expected 8", "expected 4", "even", "odd", "rank",
    "n_rows", "n_cols", "same number", "at least", "elements", "width",
)
VALUE_MARKERS = (
    "must be", "must not", "non-negative", "nonnegative", "positive",
    "negative", "out of range", "range", "invalid", "not in", "gcd",
    "coprime", "modulus", "divis", "zero", "empty", "unknown", "unsupported",
    "requires", "greater", "less than", ">=", "<=",
)
TYPE_EXCS = ("TypeError", "AttributeError", "IndexError", "KeyError",
             "UnicodeDecodeError", "StopIteration")
ENV_EXCS = ("FileNotFoundError", "OSError", "ImportError", "ModuleNotFoundError",
            "PermissionError", "ConnectionError", "SystemExit")
VALUE_EXCS = ("ValueError", "AssertionError", "ArithmeticError",
              "ZeroDivisionError", "OverflowError", "NotImplementedError",
              "RuntimeError", "MemoryError")

WHY_BUCKETS = (
    "X_ENV",
    "X_SHAPE_GUARD",
    "X_VALUE_GUARD",
    "X_TYPE_WALL",
    "X_UNCLASSIFIED",
)


def classify_exceptions(pairs):
    """pairs: list of (exc_type_name, message). Returns a WHY_BUCKETS member."""
    if not pairs:
        return "X_UNCLASSIFIED"
    kinds = {k for k, _ in pairs}
    if kinds & set(ENV_EXCS):
        return "X_ENV"
    for k, m in pairs:
        low = m.lower()
        if k in VALUE_EXCS and any(s in low for s in SHAPE_MARKERS):
            return "X_SHAPE_GUARD"
    for k, m in pairs:
        low = m.lower()
        if k in VALUE_EXCS and any(s in low for s in VALUE_MARKERS):
            return "X_VALUE_GUARD"
    for k, m in pairs:
        low = m.lower()
        if k in TYPE_EXCS and any(s in low for s in SHAPE_MARKERS):
            return "X_SHAPE_GUARD"
    if kinds & set(VALUE_EXCS):
        return "X_VALUE_GUARD"
    if kinds & set(TYPE_EXCS):
        return "X_TYPE_WALL"
    return "X_UNCLASSIFIED"


# ── M4: is the constraint DERIVABLE from the guards already in the code? ──
#
# The rc430 brief's own preference is "PREFER DERIVED OVER DECLARED", on the
# grounds that many constraints ALREADY EXIST IN CODE as guards -- and it names
# three: ``cyclic_period`` raises on ``gcd != 1``, ``group_algebra_table`` on
# ``dim must be a power of two <= 64``, ``cyclic_mod_add`` on a negative ``a``.
# Whether they can be extracted MECHANICALLY is the scope question. This is that
# measurement, and PC8 is its recall control: those three MUST be found, because
# the first draft of this extractor found only two. It missed ``cyclic_mod_add``
# outright -- that op is a thin delegating wrapper whose guard lives one call
# level down, in ``srmech.math.cyclic.mod_add``. Following delegation moved
# NO_DOMAIN_GUARD from 423 to 291, so an extractor that does not follow it
# over-counts "nothing to derive" by a third.
GUARD_CLASSES = ("NO_DOMAIN_GUARD", "TYPE_GUARD_ONLY",
                 "DOMAIN_SINGLE_PARAM", "DOMAIN_RELATIONAL")
GUARD_DEPTH = 3


def _fnode(fn):
    import ast as _ast
    import textwrap as _tw
    try:
        tree = _ast.parse(_tw.dedent(inspect.getsource(fn)))
    except (OSError, TypeError, SyntaxError, IndentationError):
        return None
    for n in tree.body:
        if isinstance(n, (_ast.FunctionDef, _ast.AsyncFunctionDef)):
            return n
    return None


def _atoms(test):
    """Split a boolean guard into ATOMS.

    ``a < 0 or b < 0`` names two parameters but is TWO INDEPENDENT single-param
    constraints, not a relation between a and b. Counting it as relational would
    inflate the one number this rc turns on, so the split is not optional.
    """
    import ast as _ast
    out = []

    def rec(n):
        if isinstance(n, _ast.BoolOp):
            for v in n.values:
                rec(v)
        elif isinstance(n, _ast.UnaryOp) and isinstance(n.op, _ast.Not):
            rec(n.operand)
        else:
            out.append(n)

    rec(test)
    return out


def _is_type_atom(a):
    """``isinstance(x, int)`` re-states the type the registry ALREADY publishes.
    Extracting it adds no information, so it is not a domain constraint."""
    import ast as _ast
    for c in _ast.walk(a):
        if isinstance(c, _ast.Call) and isinstance(c.func, _ast.Name) and \
                c.func.id in ("isinstance", "issubclass", "callable", "type"):
            return True
    return False


def _own_guard_atoms(fn, pset):
    import ast as _ast
    node = _fnode(fn)
    if node is None:
        return []
    rows = []
    for n in _ast.walk(node):
        test = None
        if isinstance(n, _ast.If) and any(isinstance(s, _ast.Raise) for s in n.body):
            test = n.test
        elif isinstance(n, _ast.Assert):
            test = n.test
        if test is None:
            continue
        for at in _atoms(test):
            names = sorted({x.id for x in _ast.walk(at)
                            if isinstance(x, _ast.Name) and x.id in pset})
            if names:
                rows.append({"params": names,
                             "kind": "TYPE" if _is_type_atom(at) else "DOMAIN",
                             "src": _ast.unparse(at)[:130]})
    return rows


def _callees(fn, live):
    """Direct callees this function forwards its LIVE names to, with the
    callee-param -> live-name map. The map is CARRIED down the chain: matching
    by bare name across scopes is unsound and manufactured a false positive
    (``group_algebra_table`` inheriting ``mod_add``'s ``n == 0``)."""
    import ast as _ast
    import types as _types
    node = _fnode(fn)
    if node is None:
        return []
    g = getattr(fn, "__globals__", {})
    out = []
    for n in _ast.walk(node):
        if not isinstance(n, _ast.Call):
            continue
        f = n.func
        if isinstance(f, _ast.Name):
            tgt = g.get(f.id)
        elif isinstance(f, _ast.Attribute) and isinstance(f.value, _ast.Name):
            base = g.get(f.value.id)
            tgt = getattr(base, f.attr, None) if base is not None else None
        else:
            continue
        if not isinstance(tgt, _types.FunctionType):
            continue
        tn = _fnode(tgt)
        if tn is None:
            continue
        ta = tn.args
        tps = [p.arg for p in
               (list(ta.posonlyargs) + list(ta.args) + list(ta.kwonlyargs))]
        m = {}
        for i, arg in enumerate(n.args):
            if isinstance(arg, _ast.Name) and arg.id in live and i < len(tps):
                m[tps[i]] = live[arg.id]
        for kw in n.keywords:
            if kw.arg and isinstance(kw.value, _ast.Name) and kw.value.id in live:
                m[kw.arg] = live[kw.value.id]
        if m:
            out.append((tgt, m))
    return out


def guard_profile(fn):
    """Guard atoms attributable to this op's OWN parameters, following
    delegation up to GUARD_DEPTH with a soundly-carried parameter map."""
    node = _fnode(fn)
    if node is None:
        return None
    a = node.args
    pos = list(a.posonlyargs) + list(a.args)
    ndef = len(a.defaults)
    req = [p.arg for p in (pos[:len(pos) - ndef] if ndef else pos)]
    req += [k.arg for k, d in zip(a.kwonlyargs, a.kw_defaults) if d is None]
    params = [p.arg for p in pos + list(a.kwonlyargs)]
    rows = _own_guard_atoms(fn, set(params))
    own = len(rows)
    seen = {fn}
    frontier = [(fn, {p: p for p in params}, 0)]
    while frontier:
        cur, live, d = frontier.pop()
        if d >= GUARD_DEPTH:
            continue
        for tgt, m in _callees(cur, live):
            if tgt in seen:
                continue
            seen.add(tgt)
            for r in _own_guard_atoms(tgt, set(m)):
                mapped = sorted({m[p] for p in r["params"] if p in m})
                if mapped:
                    rows.append({"params": mapped, "kind": r["kind"],
                                 "src": r["src"], "depth": d + 1,
                                 "via": tgt.__module__ + "." + tgt.__name__})
            frontier.append((tgt, m, d + 1))
    dom = [r for r in rows if r["kind"] == "DOMAIN"]
    if not dom:
        cls = "NO_DOMAIN_GUARD" if not rows else "TYPE_GUARD_ONLY"
    elif any(len(r["params"]) >= 2 for r in dom):
        cls = "DOMAIN_RELATIONAL"
    else:
        cls = "DOMAIN_SINGLE_PARAM"
    return {"params": params, "required": req, "atoms": rows,
            "own_atom_count": own, "class": cls}


def load_rc427():
    """Import the rc427 census MODULE so M1 is the same code, not a lookalike."""
    spec = importlib.util.spec_from_file_location("_s2_rc427", RC427)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# ── the worker: executes one op's published example and orbit-closes ──────
WORKER_SRC = r'''
import importlib, inspect, json, os, sys, tempfile
os.chdir(tempfile.mkdtemp(prefix="s2rc430_"))
sys.stdout.reconfigure(line_buffering=True)
import srmech
from srmech.amsc.format import sha256_bytes
from srmech.introspect.tool_schema import get_tool_schema, warmup_all
warmup_all()
BY_NAME = {e.name: e for e in get_tool_schema().tools}

MAX_SET = 512
MAX_SEEDS = 8
MAX_REPR = 400000


def ident(v):
    try:
        r = repr(v)
    except BaseException:
        return None
    if len(r) > MAX_REPR:
        return None
    return sha256_bytes((type(v).__name__ + "\x00" + r).encode("utf-8", "replace"))


def record_calls(entry, fn_mod, fname):
    """Exec the published example with the op wrapped; keep args of calls that RETURNED."""
    ex = entry.example if isinstance(entry.example, dict) else {}
    worked = ex.get("worked")
    if not worked:
        return [], "no_worked_snippet"
    src = ((ex.get("setup") or "") + "\n" + worked) if ex.get("setup") else worked
    real = getattr(fn_mod, fname)
    seen = []

    def wrapper(*a, **kw):
        r = real(*a, **kw)
        if len(seen) < MAX_SEEDS:
            seen.append((a, dict(kw)))
        return r

    try:
        wrapper.__name__ = getattr(real, "__name__", fname)
        wrapper.__doc__ = getattr(real, "__doc__", None)
    except Exception:
        pass
    setattr(fn_mod, fname, wrapper)
    err = None
    try:
        g = {"__name__": "__worked__"}
        exec(compile(src, "<worked>", "exec"), g)
    except BaseException as exc:
        err = type(exc).__name__ + ": " + str(exc)[:200]
    finally:
        setattr(fn_mod, fname, real)
    return seen, err


def bind_positional(real, a, kw):
    sig = inspect.signature(real)
    b = sig.bind(*a, **kw)
    b.apply_defaults()
    names = [n for n in sig.parameters
             if sig.parameters[n].kind not in
             (sig.parameters[n].VAR_POSITIONAL, sig.parameters[n].VAR_KEYWORD)]
    return names, [b.arguments[n] for n in names]


def orbit(real, seeds, base, slot):
    """S = the closure of the recorded SEEDS under f, varying ONE slot.

    This is rc427's stated criterion with the WINDOW removed: S is generated by
    f itself, so there is no modulus-smaller-than-the-carrier to get wrong.

      * f total on S      -- an IMAGE that raises collapses the closure to
                             NOT_TOTAL; a SEED that raises is simply dropped
                             (it was valid in another binding, not this one);
      * f(S) subset-of S  -- by construction;
      * non-injective     -- |f(S)| < |S|.

    |S| < 2 is VACUOUS, never GROUP: a lone fixed point makes every op with any
    fixed point a "bijection" and the test would stop separating.
    """
    x0 = base[slot]
    if ident(x0) is None:
        return {"verdict": "UNKEYABLE_SEED"}
    keys, img, dropped_seeds = set(), {}, 0
    pend = [(s, True) for s in seeds] or [(x0, True)]
    while pend:
        x, is_seed = pend.pop()
        kx = ident(x)
        if kx is None:
            return {"verdict": "UNKEYABLE_IMAGE", "set_size": len(keys)}
        if kx in keys:
            continue
        if type(x) is not type(x0):
            if is_seed:
                dropped_seeds += 1
                continue
            return {"verdict": "NOT_ENDO", "in_type": type(x0).__name__,
                    "out_type": type(x).__name__}
        args = list(base)
        args[slot] = x
        try:
            y = real(*args)
        except BaseException as exc:
            if is_seed:
                dropped_seeds += 1
                continue
            return {"verdict": "NOT_TOTAL", "exc": type(exc).__name__,
                    "msg": str(exc)[:180], "set_size": len(keys)}
        if type(y) is not type(x0):
            return {"verdict": "NOT_ENDO", "in_type": type(x0).__name__,
                    "out_type": type(y).__name__}
        ky = ident(y)
        if ky is None:
            return {"verdict": "UNKEYABLE_IMAGE", "set_size": len(keys)}
        keys.add(kx)
        img[kx] = ky
        pend.append((y, False))
        if len(keys) > MAX_SET:
            return {"verdict": "ORBIT_UNCLOSED", "set_size": len(keys),
                    "max_set": MAX_SET}
    n, m = len(keys), len(set(img.values()))
    if n < 2:
        return {"verdict": "VACUOUS", "set_size": n, "image_size": m,
                "why": "|S| < 2 -- a lone fixed point is not a measurement"}
    return {"verdict": "SEMIGROUP" if m < n else "GROUP",
            "set_size": n, "image_size": m, "dropped_seeds": dropped_seeds,
            "surviving": str(m) + "/" + str(n)}


def run_one(name):
    entry = BY_NAME.get(name)
    out = {"op": name}
    if entry is None:
        out["oracle"] = "ABSENT_FROM_REGISTRY"
        return out
    mod_name, _, fname = name.rpartition(".")
    fn_mod = importlib.import_module(mod_name)
    real = getattr(fn_mod, fname)
    calls, err = record_calls(entry, fn_mod, fname)
    out["snippet_error"] = err
    if not calls:
        out["oracle"] = "NO_VALID_ARG_RECOVERED"
        return out
    try:
        names, base = bind_positional(real, *calls[0])
    except BaseException as exc:
        out["oracle"] = "BIND_FAILED"
        out["bind_exc"] = type(exc).__name__ + ": " + str(exc)[:160]
        return out
    sig = inspect.signature(real)
    req = [n for n in names if sig.parameters[n].default is sig.parameters[n].empty]
    out["oracle"] = "ARG_RECOVERED"
    out["n_recorded_calls"] = len(calls)
    out["param_names"] = names
    out["required"] = req
    out["arg_types"] = [type(v).__name__ for v in base]
    out["arg_reprs"] = [repr(v)[:90] for v in base]
    # Every recorded call is a VALID call, so every value it put in this slot is
    # a valid value for it, and a collision between two distinct seeds is an
    # information-destruction witness a single orbit cannot see.
    #
    # BUT seeds are admitted ONLY from calls whose OTHER slots match `base`
    # exactly. Pooling across bindings re-imports the precise defect that
    # refuted instrument v1: the first draft of this instrument scored
    # ``mod_mul`` SEMIGROUP 222/223 on binding (b=96, n=223) because a seed
    # ``a=235`` harvested from a DIFFERENT published call collided with
    # ``235 mod 223 = 12``. That collapse is real for the map ``a -> 96a mod
    # 223`` on all of Z-nonneg, but it is once again the CROSS-BINDING window
    # talking, not the op on the binding under test. Same-binding only, and
    # ``mod_mul`` returns GROUP -- which is correct, gcd(96, 223) = 1.
    # For Tier A (one required param) there are no other slots, so this
    # restriction costs the headline class nothing.
    bound = []
    for a, kw in calls:
        try:
            bound.append(bind_positional(real, a, kw)[1])
        except BaseException:
            continue
    base_keys = [ident(v) for v in base]
    results = []
    for rn in req:
        slot = names.index(rn)
        seeds, seen_k, cross = [], set(), 0
        for b in bound:
            if slot >= len(b):
                continue
            same = all(ident(b[j]) == base_keys[j]
                       for j in range(min(len(b), len(base))) if j != slot)
            if not same:
                cross += 1
                continue
            k = ident(b[slot])
            if k is not None and k not in seen_k:
                seen_k.add(k)
                seeds.append(b[slot])
        r = orbit(real, seeds, base, slot)
        r["slot"] = rn
        r["n_seeds"] = len(seeds)
        r["cross_binding_seeds_rejected"] = cross
        results.append(r)
    out["slots"] = results
    order = ("SEMIGROUP", "GROUP", "NOT_ENDO", "ORBIT_UNCLOSED", "VACUOUS",
             "NOT_TOTAL", "UNKEYABLE_SEED", "UNKEYABLE_IMAGE")
    verds = [r["verdict"] for r in results]
    for v in order:
        if v in verds:
            out["verdict"] = v
            break
    else:
        out["verdict"] = "NONE"
    return out


for line in sys.stdin:
    nm = line.strip()
    if not nm:
        continue
    try:
        rec = run_one(nm)
    except BaseException as exc:
        rec = {"op": nm, "oracle": "WORKER_ERROR",
               "exc": type(exc).__name__ + ": " + str(exc)[:200]}
    print("\x01" + json.dumps(rec, sort_keys=True), flush=True)
'''

#: measured-slow ops, skipped by NAME with the reason recorded (O5). Sourced
#: from tools/run_worked_examples.py's own SLOW_ALLOWLIST -- these are minutes
#: apiece and would dominate the run without changing any bucket.
SLOW_SKIP = {
    "srmech.physics.qm.so8.an_embedding",
    "srmech.physics.qm.so8.so7_subalgebra",
    "srmech.math.laplacian.recover_check",
    "srmech.math.laplacian.recover_check_spectral",
    "srmech.math.laplacian.recover_check_structural",
    "srmech.math.primes.is_prime",
}

PER_OP_ORACLE_BUDGET_S = 20.0


class Worker:
    """A long-lived child the parent can kill. Nothing in-process can interrupt
    arbitrary Python reliably; a process kill cannot be defeated by a C loop."""

    def __init__(self, src_path, env):
        self.src_path = src_path
        self.env = env
        self.proc = None
        self.q = None
        self._start()

    def _start(self):
        self.proc = subprocess.Popen(
            [sys.executable, "-u", self.src_path],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL, text=True, env=self.env,
        )
        self.q = []
        self.lock = threading.Lock()
        self.reader = threading.Thread(target=self._read, daemon=True)
        self.reader.start()

    def _read(self):
        proc = self.proc
        for line in proc.stdout:
            if line.startswith("\x01"):
                with self.lock:
                    self.q.append(line[1:])

    def kill(self):
        try:
            self.proc.kill()
        except Exception:
            pass

    def ask(self, name, budget):
        try:
            self.proc.stdin.write(name + "\n")
            self.proc.stdin.flush()
        except Exception:
            self.kill()
            self._start()
            return {"op": name, "oracle": "WORKER_RESTART"}
        t0 = time.monotonic()
        while time.monotonic() - t0 < budget:
            with self.lock:
                if self.q:
                    return json.loads(self.q.pop(0))
            if self.proc.poll() is not None:
                self.kill()
                self._start()
                return {"op": name, "oracle": "WORKER_DIED"}
            time.sleep(0.01)
        self.kill()
        self._start()
        return {"op": name, "oracle": "TIMEOUT", "budget_s": budget}


def main():
    print(f"srmech.__file__    = {srmech.__file__}")
    print(f"srmech.__version__ = {srmech.__version__}")
    numpy_present = importlib.util.find_spec("numpy") is not None
    print(f"numpy present      = {numpy_present}")
    warmup_all()
    tools = get_tool_schema().tools
    param_fields = list(ToolParameter.__dataclass_fields__)
    print(f"registry           = {len(tools)}")
    print(f"ToolParameter      = {param_fields}   <- still no domain constraint")
    print()

    rc427 = load_rc427()
    by_name = {e.name: e for e in tools}

    # ══ M1 — REPRODUCTION, using the rc427 module's own code ══════════════
    print("M1 — REPRODUCING THE rc427 PARTITION AT rc429 (imported, not re-typed)")
    carriers = rc427._build_carriers()
    t1 = rc427.tier1_shape_screen(tools)
    tierA = {k: [] for k in rc427.BUCKETS}
    tierB = {k: [] for k in rc427.BUCKETS}
    detail = {}
    fns = {}
    t0 = time.monotonic()
    for i, e in enumerate(tools):
        mod, _, fname = e.name.rpartition(".")
        fn = getattr(importlib.import_module(mod), fname)
        fns[e.name] = fn
        req, opt = rc427._required_params(fn)
        io_params = [] if req is None else [
            n for n in (req + opt) if n.lower() in rc427.DENY_PARAM_NAMES
        ]
        if e.name.startswith(rc427.DENY_PREFIXES) or io_params:
            tierA["EXCLUDED_SAFETY"].append(e.name)
            detail[e.name] = {"bucket": "EXCLUDED_SAFETY", "tier": "-",
                              "witnesses": [], "diag": {}, "req": req or []}
            continue
        if req is None:
            tier, bucket, wits, diag = "-", "NOT_EXECUTABLE", [], {"reason": "no signature"}
        elif len(req) == 0:
            tier, bucket, wits, diag = "-", "NO_CARRIER_SLOT", [], {"reason": "zero required"}
        else:
            tier = "A" if len(req) == 1 else "B"
            bucket, wits, diag = rc427.probe_op(fn, carriers, req, opt)
        (tierA if tier in ("A", "-") else tierB)[bucket].append(e.name)
        detail[e.name] = {"bucket": bucket, "tier": tier, "witnesses": wits,
                          "diag": diag, "req": req or []}
        if (i + 1) % 200 == 0:
            print(f"  ... {i + 1}/{len(tools)} ({time.monotonic() - t0:.0f}s)")
    print(f"  reproduction complete in {time.monotonic() - t0:.0f}s")

    A = {k: [n for n in v if detail[n]["tier"] == "A"] for k, v in tierA.items()}
    adjud = {}
    kept, bool_art = [], []
    for op in A["SEMIGROUP_NOT_GROUP"]:
        clean, art = rc427.adjudicate(by_name[op], detail[op]["witnesses"])
        adjud[op] = {"clean": clean, "artifact": art}
        (kept if clean else bool_art).append(op)
    A["SEMIGROUP_BOOL_DOMAIN_ARTIFACT"] = bool_art
    A["SEMIGROUP_NOT_GROUP"] = kept
    a_self_maps = sum(len(A[k]) for k in ("SEMIGROUP_NOT_GROUP",
                                          "SEMIGROUP_CONSTANT_ONLY",
                                          "SEMIGROUP_BOOL_DOMAIN_ARTIFACT", "GROUP"))
    a_total = sum(len(v) for v in A.values())
    b_total = sum(len(v) for v in tierB.values())
    no_slot = [n for n in tierA["NO_CARRIER_SLOT"] if detail[n]["tier"] == "-"]
    excl = [n for n in tierA["EXCLUDED_SAFETY"] if detail[n]["tier"] == "-"]

    print(f"\n  TIER A total {a_total} | TIER B total {b_total} | "
          f"no-carrier-slot {len(no_slot)} | excluded-safety {len(excl)} "
          f"| sum {a_total + b_total + len(no_slot) + len(excl)} vs {len(tools)}")
    print("  Tier-A buckets:")
    for k in rc427.BUCKETS:
        if A[k]:
            print(f"    {k:<32} {len(A[k]):>4}")
    print(f"    {'-> measured self-maps':<32} {a_self_maps:>4}")
    print("  Tier-B buckets:")
    for k in rc427.BUCKETS:
        if tierB[k]:
            print(f"    {k:<32} {len(tierB[k]):>4}")
    print()

    unreachable = sorted(A["NOT_CLOSED"] + A["NOT_EXECUTABLE"])
    print(f"UNREACHABLE TIER-A SET = {len(unreachable)} "
          f"({len(A['NOT_CLOSED'])} NOT_CLOSED + {len(A['NOT_EXECUTABLE'])} NOT_EXECUTABLE)")
    print()

    # ══ M2 — WHY, per unreachable op ══════════════════════════════════════
    print("M2 — DIAGNOSING WHY EACH UNREACHABLE TIER-A OP IS UNREACHABLE")
    why = {}
    for op in unreachable:
        fn = fns[op]
        req = detail[op]["req"]
        pairs, returns = [], []
        for c in carriers:
            for x in c["elements"][:3]:
                try:
                    r = fn(x)
                except BaseException as exc:
                    pairs.append((type(exc).__name__, str(exc)[:220]))
                    continue
                returns.append((type(x).__name__, type(r).__name__))
        if detail[op]["bucket"] == "NOT_EXECUTABLE":
            b = classify_exceptions(pairs)
            why[op] = {"bucket": "NOT_EXECUTABLE", "why": b,
                       "exc_kinds": sorted({k for k, _ in pairs}),
                       "sample_msgs": [f"{k}: {m}" for k, m in pairs[:3]],
                       "slot": req[0] if req else None}
        else:
            same = [(i, o) for i, o in returns if i == o]
            diff = [(i, o) for i, o in returns if i != o]
            if not returns:
                cls = "C0_UNOBSERVED"
            elif not same:
                cls = "C1_RETURN_TYPE_DIFFERS"
            else:
                cls = "C2_SAME_TYPE_VALUE_ESCAPES"
            why[op] = {"bucket": "NOT_CLOSED", "why": cls,
                       "observed_pairs": sorted({f"{i}->{o}" for i, o in returns})[:6],
                       "n_same_type": len(same), "n_diff_type": len(diff),
                       "slot": req[0] if req else None}
    ne_counts, nc_counts = {}, {}
    for op, d in why.items():
        tgt = ne_counts if d["bucket"] == "NOT_EXECUTABLE" else nc_counts
        tgt[d["why"]] = tgt.get(d["why"], 0) + 1
    print("  NOT_EXECUTABLE — why the op refused every ladder element:")
    for k, v in sorted(ne_counts.items(), key=lambda kv: -kv[1]):
        print(f"    {k:<26} {v:>4}")
    print("  NOT_CLOSED — OBSERVED input type vs OBSERVED return type:")
    for k, v in sorted(nc_counts.items(), key=lambda kv: -kv[1]):
        print(f"    {k:<26} {v:>4}")
    n_unclass = ne_counts.get("X_UNCLASSIFIED", 0) + nc_counts.get("C0_UNOBSERVED", 0)
    print(f"  residual UNCLASSIFIED = {n_unclass} of {len(unreachable)} "
          f"({Q(n_unclass, len(unreachable)) if unreachable else 'n/a'})")
    print()

    # ══ M3 — THE ORACLE CEILING ═══════════════════════════════════════════
    print("M3 — ORACLE CEILING: run each op's OWN published worked example, keep "
          "the args of\n     every call that RETURNED, then orbit-close on them. "
          "No window is chosen.")
    # The worker lives in a PRIVATE temp dir under a PID-unique name. It used to
    # be written beside this file in notes/, and a housekeeping `rm` of that
    # scratch file during a live run killed the child 251 times (see PC9).
    # Nothing in the repo tree can collide with it now.
    import tempfile as _tf
    worker_dir = _tf.mkdtemp(prefix="s2rc430_worker_")
    worker_path = os.path.join(worker_dir, f"_s2_rc430_worker_{os.getpid()}.py")
    with open(worker_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(WORKER_SRC)
    env = dict(os.environ)
    env.setdefault("SRMECH_EXPECT_PURE", "1")

    probe_set = sorted(set(
        [n for n in A["NOT_CLOSED"] + A["NOT_EXECUTABLE"]]
        + [n for n in A["SEMIGROUP_NOT_GROUP"] + A["GROUP"]
           + A["SEMIGROUP_CONSTANT_ONLY"] + A["SEMIGROUP_BOOL_DOMAIN_ARTIFACT"]]
        + [n for k, v in tierB.items() for n in v]
        + ["srmech.cascade.cyclic_mod_add", "srmech.amsc.format.sha256_bytes",
           "srmech.biology.q8.q8_project_v4", "srmech.cascade.chiral_flip"]
    ) & set(by_name))
    probe_set = [n for n in probe_set if n not in SLOW_SKIP]
    print(f"  probing {len(probe_set)} ops "
          f"({len(SLOW_SKIP & set(by_name))} skipped as measured-slow)")

    w = Worker(worker_path, env)
    oracle = {}
    t0 = time.monotonic()
    for i, name in enumerate(probe_set):
        oracle[name] = w.ask(name, PER_OP_ORACLE_BUDGET_S)
        if (i + 1) % 100 == 0:
            print(f"  ... {i + 1}/{len(probe_set)} ({time.monotonic() - t0:.0f}s)")
    w.kill()
    try:
        os.remove(worker_path)
        os.rmdir(worker_dir)
    except OSError:
        pass
    print(f"  oracle pass complete in {time.monotonic() - t0:.0f}s")

    def ov(name):
        r = oracle.get(name, {})
        return r.get("verdict") or r.get("oracle") or "ABSENT"

    orc_counts = {}
    for n in probe_set:
        v = ov(n)
        orc_counts[v] = orc_counts.get(v, 0) + 1
    print("  ORACLE VERDICTS over the whole probe set:")
    for k, v in sorted(orc_counts.items(), key=lambda kv: -kv[1]):
        print(f"    {k:<26} {v:>4}")
    print()

    # decidable = the orbit closed and returned a group/semigroup verdict
    DECIDED = ("SEMIGROUP", "GROUP")
    a_probe = [n for n in probe_set if detail[n]["tier"] == "A"]
    b_probe = [n for n in probe_set if detail[n]["tier"] == "B"]
    a_decided = [n for n in a_probe if ov(n) in DECIDED]
    b_decided = [n for n in b_probe if ov(n) in DECIDED]
    a_semi = [n for n in a_decided if ov(n) == "SEMIGROUP"]
    b_semi = [n for n in b_decided if ov(n) == "SEMIGROUP"]
    rescued = [n for n in unreachable if ov(n) in DECIDED]
    resc_from_ne = [n for n in rescued if detail[n]["bucket"] == "NOT_EXECUTABLE"]
    resc_from_nc = [n for n in rescued if detail[n]["bucket"] == "NOT_CLOSED"]

    ladder_measured_A = [n for n in A["SEMIGROUP_NOT_GROUP"] + A["GROUP"]
                         + A["SEMIGROUP_CONSTANT_ONLY"]
                         + A["SEMIGROUP_BOOL_DOMAIN_ARTIFACT"]]
    union_A = sorted(set(ladder_measured_A) | set(a_decided))
    lost_by_oracle = sorted(set(ladder_measured_A) - set(a_decided))
    a_not_endo = [n for n in a_probe if ov(n) == "NOT_ENDO"]
    a_vacuous = [n for n in a_probe if ov(n) == "VACUOUS"]
    a_noarg = [n for n in a_probe if ov(n) == "NO_VALID_ARG_RECOVERED"]
    vac_one_seed = 0
    for n in probe_set:
        if ov(n) != "VACUOUS":
            continue
        sl = [s for s in (oracle.get(n, {}).get("slots") or [])
              if s.get("verdict") == "VACUOUS"]
        if sl and sl[0].get("n_seeds") == 1:
            vac_one_seed += 1

    print("=" * 78)
    print(f"TIER A decidable — ladder: {a_self_maps}  ->  oracle+orbit: {len(a_decided)}")
    print(f"  rescued from the {len(unreachable)} unreachable: {len(rescued)} "
          f"({len(resc_from_ne)} were NOT_EXECUTABLE, {len(resc_from_nc)} were NOT_CLOSED)")
    print(f"  the two instruments are NOT nested: the oracle LOSES "
          f"{len(lost_by_oracle)} the ladder measured -> UNION = {len(union_A)}")
    for n in lost_by_oracle:
        print(f"      lost: {n}  ({ov(n)})")
    print(f"TIER B decidable — ladder: UNSUPPORTED (window artifact)  ->  "
          f"oracle+orbit: {len(b_decided)} of {len(b_probe)} probed")
    print(f"  Tier-A SEMIGROUP {len(a_semi)} | Tier-B SEMIGROUP {len(b_semi)}")
    print("=" * 78)
    print()
    print("WHAT BLOCKS THE REST — Tier A, under a PERFECT valid-argument supply:")
    print(f"  NOT_ENDO                {len(a_not_endo):>4}   f returns a DIFFERENT type than it "
          f"takes.\n{'':26}No constraint on an INPUT parameter can ever make this a "
          f"self-map.")
    print(f"  VACUOUS                 {len(a_vacuous):>4}   |S| < 2 — one seed, and f fixes it. "
          f"Seed POVERTY,\n{'':26}not a property of the op: a constraint that lets a "
          f"consumer\n{'':26}ENUMERATE the domain would supply more.")
    print(f"  NO_VALID_ARG_RECOVERED  {len(a_noarg):>4}   no published snippet reached the op.")
    print(f"  (whole probe set: {vac_one_seed} of the VACUOUS verdicts rest on exactly ONE seed)")
    print()

    # ── M2 x M3 cross-check (O3): does the classifier agree with the oracle? ──
    agree = disagree = ungraded = 0
    LADDER_TYPES = {"int", "float", "bytes", "tuple", "list", "HV", "bool"}
    xchecks = []
    for op in unreachable:
        d = why[op]
        r = oracle.get(op, {})
        if r.get("oracle") != "ARG_RECOVERED":
            ungraded += 1
            continue
        slot = d.get("slot")
        pn = r.get("param_names") or []
        if slot not in pn:
            ungraded += 1
            continue
        t = r["arg_types"][pn.index(slot)]
        in_ladder = t in LADDER_TYPES
        # prediction: TYPE_WALL <=> the true argument's type is NOT ladder-representable
        pred_type_wall = (d["why"] == "X_TYPE_WALL")
        ok = (pred_type_wall != in_ladder)
        (agree, disagree) = (agree + 1, disagree) if ok else (agree, disagree + 1)
        if not ok:
            xchecks.append({"op": op, "classified": d["why"],
                            "true_arg_type": t, "in_ladder": in_ladder})
    tot_graded = agree + disagree
    print(f"M2 x M3 CROSS-CHECK (O3): classifier vs recovered true argument — "
          f"agree {agree}/{tot_graded}"
          f"{' (' + str(Q(agree, tot_graded)) + ')' if tot_graded else ''}, "
          f"ungraded {ungraded}")
    for x in xchecks[:8]:
        print(f"    DISAGREE {x['op']}: said {x['classified']}, true arg is "
              f"{x['true_arg_type']} (ladder-representable={x['in_ladder']})")
    print()

    # ══ M4 — IS THE CONSTRAINT DERIVABLE FROM THE GUARDS ALREADY IN CODE? ══
    print("M4 — DERIVABILITY: guard atoms already in the code, per op "
          f"(delegation followed to depth {GUARD_DEPTH})")
    gp = {}
    for e in tools:
        p = guard_profile(fns.get(e.name))
        if p is not None:
            gp[e.name] = p
    tierof = {n: detail[n]["tier"] for n in detail}

    def gcount(names):
        c = {k: 0 for k in GUARD_CLASSES}
        for n in names:
            if n in gp:
                c[gp[n]["class"]] += 1
        return c

    all_g = gcount(gp)
    A_names = [n for n in gp if tierof.get(n) == "A"]
    B_names = [n for n in gp if tierof.get(n) == "B"]
    print(f"  {'':<22}" + "".join(f"{k:<22}" for k in GUARD_CLASSES))
    for lbl, names in (("ALL 655", list(gp)), ("TIER A", A_names), ("TIER B", B_names)):
        c = gcount(names)
        print(f"  {lbl + ' (n=' + str(len(names)) + ')':<22}"
              + "".join(f"{c[k]:<22}" for k in GUARD_CLASSES))
    only_via = [n for n in gp
                if gp[n]["own_atom_count"] == 0 and any("via" in a for a in gp[n]["atoms"])]
    print(f"  ops whose ONLY guards are inherited through DELEGATION: {len(only_via)}")
    rel_ops = sorted(n for n in gp if gp[n]["class"] == "DOMAIN_RELATIONAL")
    print(f"  ops with a TRUE inter-parameter relation (>=2 params in ONE atom): "
          f"{len(rel_ops)}")
    for n in rel_ops[:12]:
        at = [a for a in gp[n]["atoms"] if a["kind"] == "DOMAIN" and len(a["params"]) >= 2][0]
        print(f"      {n:<52} {at['params']}  {at['src'][:60]}")
    print()

    # ══ CONTROLS ══════════════════════════════════════════════════════════
    ctl = {}
    ctl["PC1"] = {"op": "srmech.biology.q8.q8_project_v4", "expected": "SEMIGROUP",
                  "measured": ov("srmech.biology.q8.q8_project_v4")}
    ctl["PC2"] = {"op": "srmech.cascade.chiral_flip", "expected": "GROUP",
                  "measured": ov("srmech.cascade.chiral_flip")}
    ctl["PC3"] = {"op": "srmech.cascade.cyclic_mod_add", "expected": "GROUP",
                  "measured": ov("srmech.cascade.cyclic_mod_add"),
                  "v1_verdict": "SEMIGROUP_NOT_GROUP (carrier=Z12, binding b=12 n=6)"}
    for k in ("PC1", "PC2", "PC3"):
        ctl[k]["pass"] = ctl[k]["measured"] == ctl[k]["expected"]
    ctl["PC4"] = {"rule": "both buckets non-empty",
                  "n_group": orc_counts.get("GROUP", 0),
                  "n_semigroup": orc_counts.get("SEMIGROUP", 0)}
    ctl["PC4"]["pass"] = ctl["PC4"]["n_group"] > 0 and ctl["PC4"]["n_semigroup"] > 0
    sha_v = ov("srmech.amsc.format.sha256_bytes")
    ctl["PC5"] = {"rule": "rescues >=1 ladder-NOT_EXECUTABLE AND fails on sha256_bytes",
                  "n_rescued_from_not_executable": len(resc_from_ne),
                  "sha256_bytes_verdict": sha_v,
                  "pass": len(resc_from_ne) > 0 and sha_v not in DECIDED}
    delta = len(tools) - 649
    base = PREREGISTERED["PC6_reproduction"]["rc427_baseline"]
    drift = {"tier_a": a_total - base["tier_a"], "tier_b": b_total - base["tier_b"],
             "no_carrier_slot": len(no_slot) - base["no_carrier_slot"],
             "excluded_safety": len(excl) - base["excluded_safety"]}
    ctl["PC6"] = {"registry_delta": delta, "partition_drift": drift,
                  "sum_ok": a_total + b_total + len(no_slot) + len(excl) == len(tools),
                  "pass": (a_total + b_total + len(no_slot) + len(excl) == len(tools)
                           and sum(drift.values()) == delta)}
    ctl["PC7"] = {"rule": "UNCLASSIFIED < 1/5 of unreachable", "n": n_unclass,
                  "of": len(unreachable),
                  "pass": bool(unreachable) and Q(n_unclass, len(unreachable)) < Q(1, 5)}
    recall = {}
    for t in PREREGISTERED["PC8_guard_extractor_recall"]["targets"]:
        recall[t] = gp.get(t, {}).get("class", "ABSENT")
    ctl["PC8"] = {"rule": "the three brief-named ops each yield a DOMAIN guard",
                  "measured": recall,
                  "pass": all(v.startswith("DOMAIN_") for v in recall.values())}
    n_broken = sum(orc_counts.get(k, 0)
                   for k in ("WORKER_DIED", "WORKER_RESTART", "TIMEOUT"))
    ctl["PC9"] = {"rule": "harness breakage < 1/20 of the probe set",
                  "broken": n_broken, "probed": len(probe_set),
                  "ratio": str(Q(n_broken, len(probe_set))) if probe_set else None,
                  "pass": bool(probe_set) and Q(n_broken, len(probe_set)) < Q(1, 20)}
    void = ("PC1", "PC2", "PC3", "PC4", "PC5", "PC6", "PC9")
    m3_valid = all(ctl[k]["pass"] for k in void)
    print("PRE-REGISTERED FALSIFIERS")
    for k, v in ctl.items():
        print(f"  {k:<5} {'PASS' if v.get('pass') else 'FAIL'}   {v}")
    print(f"\n  M3 VALID: {m3_valid}   (void-if-fail set = {void})")
    print(f"  M2 classification is "
          f"{'a MEASUREMENT' if ctl['PC7']['pass'] else 'UNSUPPORTED (residual too high)'}")
    print()

    # ══ M5 — IS THE BIGGEST BUCKET ALREADY ANSWERABLE FROM SHIPPED FIELDS? ══
    #
    # NOT_ENDO is the largest bucket and the only one no input constraint can
    # ever move. But deciding it needs the RETURN type, and the registry already
    # publishes one. So: score a predictor built ONLY from fields that ship
    # today -- ``returns.type`` against the required parameter's ``type``,
    # widened by rc427's own family map -- against the oracle's executed verdict.
    print("M5 — CAN THE ALREADY-SHIPPED FIELDS PREDICT 'NOT A SELF-MAP'?")
    tp = fp = tn = fn_ = 0
    m5_mismatch = []
    for n in a_probe:
        v = ov(n)
        if v not in ("NOT_ENDO", "SEMIGROUP", "GROUP", "VACUOUS"):
            continue
        e = by_name[n]
        if not e.returns or not e.parameters:
            continue
        req_p = [p for p in e.parameters if p.required]
        if len(req_p) != 1:
            continue
        shaped = bool(rc427._family(req_p[0].type) & rc427._family(e.returns.type))
        truth_not_endo = (v == "NOT_ENDO")
        pred_not_endo = not shaped
        if pred_not_endo and truth_not_endo:
            tp += 1
        elif pred_not_endo and not truth_not_endo:
            fp += 1
            m5_mismatch.append((n, "predicted NOT_ENDO, measured " + v,
                                req_p[0].type, e.returns.type))
        elif not pred_not_endo and truth_not_endo:
            fn_ += 1
            m5_mismatch.append((n, "predicted self-map-shaped, measured NOT_ENDO",
                                req_p[0].type, e.returns.type))
        else:
            tn += 1
    m5_n = tp + fp + tn + fn_
    print(f"  scored {m5_n} Tier-A ops with an executed verdict, using ONLY "
          f"returns.type x parameters[].type")
    print(f"    correctly predicted NOT a self-map .. {tp:>4}")
    print(f"    correctly predicted self-map-shaped . {tn:>4}")
    print(f"    predicted NOT_ENDO, measured otherwise {fp:>3}")
    print(f"    predicted shaped, measured NOT_ENDO .. {fn_:>3}")
    if m5_n:
        print(f"    agreement = {Q(tp + tn, m5_n)}")
    for x in m5_mismatch[:6]:
        print(f"      {x[0]:<50} {x[1]}  (param {x[2]} -> returns {x[3]})")
    print("  NOTE: rc427's L3 stands — `returns=` CAN lie (the immolation gate "
          "exists\n        for that). A disagreement here is NOT by itself a "
          "declared-type defect;\n        a dtype-polymorphic return or a widened "
          "`object` reads the same way.")
    print()

    # ══ THE PROJECTION — with its assumptions stated, not buried ══════════
    a_timeout = [n for n in a_probe if ov(n) in ("TIMEOUT", "WORKER_DIED",
                                                 "WORKER_RESTART")]
    with_arg = [n for n in a_probe if n not in a_noarg and n not in a_timeout]
    n_wa = len(with_arg)
    n_dec = len([n for n in with_arg if ov(n) in DECIDED])
    n_ne = len([n for n in with_arg if ov(n) == "NOT_ENDO"])
    n_vac = len([n for n in with_arg if ov(n) == "VACUOUS"])
    rate_dec = Q(n_dec, n_wa) if n_wa else None
    rate_ne = Q(n_ne, n_wa) if n_wa else None
    # A1: the field supplies an argument wherever one exists, so the NO_ARG
    #     bucket resolves in the SAME proportions as the population that had one.
    p_a1 = len(union_A) + (n_dec * len(a_noarg)) // n_wa if n_wa else len(union_A)
    # A2: the field additionally lets a consumer ENUMERATE the domain, so every
    #     VACUOUS verdict (|S| < 2 on a single seed) gains a second element.
    p_a2 = p_a1 + n_vac + ((n_vac * len(a_noarg)) // n_wa if n_wa else 0)
    # A3: NOT_ENDO converts at ZERO, at every assumption level.
    ne_est = n_ne + ((n_ne * len(a_noarg)) // n_wa if n_wa else 0)
    hard_cap = a_total - ne_est

    print("=" * 78)
    print("THE PROJECTION — Tier A, with every assumption named")
    print("=" * 78)
    print(f"  measured now, ladder only .................... {a_self_maps:>4} of {a_total}")
    print(f"  measured with a PERFECT argument (union) ..... {len(union_A):>4}   "
          f"[no new field: example['worked'] already ships]")
    print(f"  A1  + field supplies an arg where one exists . {p_a1:>4}   "
          f"[assumes the {len(a_noarg)} NO_ARG ops resolve at the")
    print(f"{'':50}observed rate {rate_dec} = {n_dec}/{n_wa}]")
    print(f"  A2  + field lets the domain be ENUMERATED .... {p_a2:>4}   "
          f"[assumes every VACUOUS |S|<2 gains a 2nd element]")
    print(f"  A3  HARD CAP — NOT_ENDO converts at ZERO ..... {hard_cap:>4}   "
          f"[{ne_est} ops return a different type than they take;")
    print(f"{'':50}an INPUT constraint cannot change a RETURN type]")
    print(f"  Tier B, ladder UNSUPPORTED -> oracle-decided .. {len(b_decided):>4} of "
          f"{len(b_probe)}   [in-contract bindings, no window]")
    print("=" * 78)
    print()

    # ══ NDJSON ════════════════════════════════════════════════════════════
    recs = [
        {"record": "environment", "task": "#T1127", "rc": "rc430",
         "srmech_file": srmech.__file__, "srmech_version": srmech.__version__,
         "numpy_present": numpy_present, "registry_total": len(tools),
         "tool_parameter_fields": param_fields,
         "tool_parameter_publishes_domain_constraint": False,
         "tool_entry_fields": list(by_name[tools[0].name].__dataclass_fields__)},
        {"record": "preregistered_falsifiers", "falsifiers": PREREGISTERED},
        {"record": "m1_reproduction", "registry_total": len(tools),
         "tier_a": a_total, "tier_b": b_total, "no_carrier_slot": len(no_slot),
         "excluded_safety": len(excl),
         "sum": a_total + b_total + len(no_slot) + len(excl),
         "tier_a_buckets": {k: len(A[k]) for k in rc427.BUCKETS},
         "tier_b_buckets": {k: len(tierB[k]) for k in rc427.BUCKETS},
         "tier_a_measured_self_maps": a_self_maps,
         "rc427_baseline": base, "drift": drift},
        {"record": "m2_why_buckets", "unreachable_total": len(unreachable),
         "not_executable": ne_counts, "not_closed": nc_counts,
         "unclassified_residual": n_unclass,
         "classifier": {"shape_markers": list(SHAPE_MARKERS),
                        "value_markers": list(VALUE_MARKERS),
                        "type_excs": list(TYPE_EXCS), "env_excs": list(ENV_EXCS),
                        "value_excs": list(VALUE_EXCS),
                        "precedence": "ENV > SHAPE > VALUE > TYPE > UNCLASSIFIED"}},
        {"record": "m3_oracle_ceiling",
         "probed": len(probe_set), "verdicts": orc_counts,
         "tier_a_decidable_ladder": a_self_maps,
         "tier_a_decidable_oracle": len(a_decided),
         "tier_a_semigroup_oracle": len(a_semi),
         "tier_b_probed": len(b_probe),
         "tier_b_decidable_oracle": len(b_decided),
         "tier_b_semigroup_oracle": len(b_semi),
         "rescued_from_unreachable": len(rescued),
         "rescued_from_not_executable": len(resc_from_ne),
         "rescued_from_not_closed": len(resc_from_nc),
         "slow_skipped": sorted(SLOW_SKIP & set(by_name))},
        {"record": "m2_x_m3_cross_check", "agree": agree, "disagree": disagree,
         "ungraded": ungraded, "ladder_types": sorted(LADDER_TYPES),
         "disagreements": xchecks},
        {"record": "m3_tier_a_union",
         "note": "the ladder and the oracle are NOT nested instruments",
         "ladder_measured": sorted(ladder_measured_A),
         "oracle_decided": sorted(a_decided),
         "union": union_A, "union_n": len(union_A),
         "lost_by_oracle": lost_by_oracle,
         "tier_a_not_endo": len(a_not_endo),
         "tier_a_vacuous": len(a_vacuous),
         "tier_a_no_valid_arg": len(a_noarg),
         "vacuous_resting_on_one_seed_whole_probe_set": vac_one_seed},
        {"record": "m4_derivability",
         "question": "is the constraint DERIVABLE from guards already in the code?",
         "delegation_depth": GUARD_DEPTH,
         "all": all_g,
         "tier_a": gcount(A_names), "tier_a_n": len(A_names),
         "tier_b": gcount(B_names), "tier_b_n": len(B_names),
         "guards_only_via_delegation": len(only_via),
         "true_inter_parameter_relation_ops": rel_ops,
         "n_true_inter_parameter_relation": len(rel_ops),
         "atom_rule": "a boolean guard is split into ATOMS; 'a < 0 or b < 0' is "
                      "TWO independent single-param constraints, not a relation. "
                      "An isinstance/type atom re-states the ALREADY-published "
                      "type and is not counted as a domain constraint."},
        {"record": "m5_shipped_fields_predictor",
         "question": "can returns.type x parameters[].type, both shipped TODAY, "
                     "predict the NOT_ENDO class the census can never reach?",
         "scored": m5_n, "true_positive_not_endo": tp, "true_negative": tn,
         "false_positive": fp, "false_negative": fn_,
         "agreement": str(Q(tp + tn, m5_n)) if m5_n else None,
         "mismatches": [{"op": a, "note": b, "param_type": c, "returns_type": d}
                        for a, b, c, d in m5_mismatch],
         "caveat": "rc427 L3 stands: returns= can lie. A disagreement is not by "
                   "itself a declared-type defect -- a dtype-polymorphic return or "
                   "a widened `object` reads the same way."},
        {"record": "projection", "tier_a_total": a_total,
         "now_ladder_only": a_self_maps,
         "with_perfect_argument_union": len(union_A),
         "A1_field_supplies_missing_arg": p_a1,
         "A2_plus_domain_enumeration": p_a2,
         "A3_hard_cap_not_endo_converts_at_zero": hard_cap,
         "estimated_tier_a_not_endo": ne_est,
         "observed_decide_rate": str(rate_dec) if rate_dec is not None else None,
         "observed_not_endo_rate": str(rate_ne) if rate_ne is not None else None,
         "tier_b_ladder": "UNSUPPORTED (window artifact)",
         "tier_b_oracle_decided": len(b_decided), "tier_b_probed": len(b_probe),
         "assumptions": {
             "A1": "the field supplies a valid argument wherever one exists, so the "
                   "NO_VALID_ARG_RECOVERED ops resolve at the rate observed on the "
                   "ops that had one",
             "A2": "the field additionally lets a consumer ENUMERATE the domain, so "
                   "every VACUOUS (|S| < 2, single seed) verdict gains a 2nd element",
             "A3": "NOT_ENDO converts at ZERO under every assumption -- a constraint "
                   "on an INPUT parameter cannot change what type an op RETURNS"}},
        {"record": "controls", "controls": ctl, "m3_valid": m3_valid,
         "void_if_fail_set": list(void)},
        {"record": "limits", "limits": {
            "O1": "positives CONFIRMED, negatives BOUNDED (orbit of THESE seeds)",
            "O2": "identity is sha256(type+repr); address-bearing reprs -> ORBIT_UNCLOSED",
            "O3": "the WHY-classifier is a regex, cross-checked against the oracle",
            "O4": "the oracle is a LOWER bound on valid-argument availability",
            "O5": "snippet execution has side effects; temp cwd + killable worker"}},
    ]
    for op in sorted(why):
        r = oracle.get(op, {})
        recs.append({"record": "unreachable_op", "op": op, **why[op],
                     "oracle_status": r.get("oracle"),
                     "oracle_verdict": r.get("verdict"),
                     "oracle_arg_types": r.get("arg_types"),
                     "oracle_arg_reprs": r.get("arg_reprs"),
                     "oracle_param_names": r.get("param_names"),
                     "oracle_slots": r.get("slots"),
                     "snippet_error": r.get("snippet_error")})
    for op in sorted(probe_set):
        if op in why:
            continue
        r = oracle.get(op, {})
        recs.append({"record": "oracle_only", "op": op,
                     "ladder_bucket": detail[op]["bucket"],
                     "tier": detail[op]["tier"],
                     "oracle_status": r.get("oracle"),
                     "oracle_verdict": r.get("verdict"),
                     "oracle_slots": r.get("slots"),
                     "snippet_error": r.get("snippet_error")})
    recs.append({"record": "oracle_rescued_ops", "n": len(rescued),
                 "from_not_executable": sorted(resc_from_ne),
                 "from_not_closed": sorted(resc_from_nc)})
    for op in sorted(gp):
        if gp[op]["class"] == "NO_DOMAIN_GUARD":
            continue
        recs.append({"record": "guard_profile", "op": op,
                     "tier": tierof.get(op), "class": gp[op]["class"],
                     "required": gp[op]["required"],
                     "own_atom_count": gp[op]["own_atom_count"],
                     "atoms": gp[op]["atoms"][:12]})

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        for r in recs:
            fh.write(json.dumps(r, sort_keys=True) + "\n")
    print(f"wrote {len(recs)} NDJSON records -> {OUT}")
    return 0 if m3_valid else 1


if __name__ == "__main__":
    sys.exit(main())
