#!/usr/bin/env python3
"""music_optheory_costing_rc424 — design + cost measurements for the proposed
srmech music-RELATIONS op family, and the ``music_doa`` homograph evidence.

READ-ONLY RESEARCH. Builds no op, registers nothing, bumps no version. Every
candidate op in the rc424 spec is PROTOTYPED here as a plain function over
shipped srmech primitives, so that:

  1. its A-N class composition is a measured fact, not an assertion;
  2. its exactness is demonstrated rather than claimed;
  3. its worked example is captured from a real run (the strict-zero gate
     re-executes every shipped example, so an example authored from memory is
     a defect waiting to fire);
  4. a candidate that turns out NOT to earn its place can be REJECTED on
     evidence.

Sections
--------
§1  p-limit / just intonation           — Class J ∘ Class N
§2  commas as exact non-vanishing ℚ     — Class N ∘ Class J
§3  the AUDIBLE #T1014 corruption       — just vs 12-EDO, a wrong answer you hear
§4  pitch-class set theory on ℤ/12      — Class I ∘ Class E; Forte vs Rahn
§5  interval inversion under writhe     — Class C ∘ Class I
§6  music_doa — the homograph, measured before/after

Run:  PYTHONPATH=docs/srmech/python python3 music_optheory_costing_rc424.py
Emits: music_optheory_costing_rc424.ndjson
"""
from __future__ import annotations

import itertools
import json
import sys

import srmech
from srmech.cascade import cyclic_mod_add
from srmech.introspect.search import search
from srmech.introspect.tool_schema import get_tool_schema
from srmech.math.cyclic import gcd
from srmech.math.primes import factor
from srmech.math.q import Q
from srmech.math.rational import best_rational
from srmech.music import commensurability_verdict, common_period

RECORDS = []


def emit(kind, **fields):
    RECORDS.append(dict(kind=kind, **fields))


# ═════════════════════════════════════════════════════════════════════════════
# §1  p-LIMIT / JUST INTONATION  —  Class J ∘ Class N
#
# CANDIDATE OP:  just_limit(num, den) -> dict
#   p-limit tuning IS exactly the multiplicative subgroup of ℚ⁺ generated by
#   the primes ≤ p (Wright, *Mathematics and Music*, AMS 2009, p.137). So the
#   op is: factor the numerator (Class J), factor the denominator (Class J),
#   union the prime supports, return the max. Exact, closed-form, total.
# ═════════════════════════════════════════════════════════════════════════════
def proto_just_limit(num, den):
    """PROTOTYPE — the p-limit of a ratio, through the shipped Class-J factor."""
    g = gcd(num, den)                       # Class I — reduce first
    num, den = num // g, den // g
    fn, fd = factor(num), factor(den)       # Class J — the prime supports
    primes = sorted({p for (p, _) in fn} | {p for (p, _) in fd})
    monzo = {}                              # the exponent vector (the "monzo")
    for (p, e) in fn:
        monzo[p] = monzo.get(p, 0) + e
    for (p, e) in fd:
        monzo[p] = monzo.get(p, 0) - e
    return {
        "ratio": f"{num}/{den}",
        "primes": primes,
        "limit": (max(primes) if primes else 1),
        "monzo": {str(p): monzo[p] for p in sorted(monzo)},
        "odd_limit": max([p for p in primes if p != 2] or [1]),
    }


JI_CASES = [
    (1, 1, "unison"), (2, 1, "octave"), (3, 2, "just perfect fifth"),
    (4, 3, "just perfect fourth"), (5, 4, "just major third"),
    (6, 5, "just minor third"), (7, 4, "harmonic seventh (septimal)"),
    (9, 8, "major whole tone"), (10, 9, "minor whole tone"),
    (16, 15, "just diatonic semitone"), (45, 32, "just tritone"),
    (11, 8, "undecimal semi-augmented fourth"),
]


def section_just_intonation():
    for (n, d, name) in JI_CASES:
        r = proto_just_limit(n, d)
        emit("ji_limit", interval=name, **r)
    emit(
        "ji_design_verdict",
        candidate="just_limit / ji_monzo",
        classes="J (prime factorisation) ∘ I (gcd reduce) ∘ N (exact ℚ carrier)",
        exact=True,
        closed_form=True,
        total=True,
        rosetta_bucket_forecast="composition_of_c",
        rationale=("factor / gcd are both already c_dispatched, so this op is "
                   "a provable pure composition of C-backed primitives and "
                   "lands in composition_of_c — it does NOT add to "
                   "CEIL_PYTHON_ONLY_DEBT, which is pinned at exactly 0 with "
                   "an exact-equality ratchet"),
        verdict="ACCEPT — the cleanest fit in the family",
    )


# ═════════════════════════════════════════════════════════════════════════════
# §2  COMMAS  —  exact rationals whose whole point is that they do NOT vanish
# ═════════════════════════════════════════════════════════════════════════════
COMMAS = {
    # name: (num, den, derivation)
    "syntonic": (81, 80, "(3/2)^4 / (5/1) — four just fifths vs a just major third two octaves up"),
    "pythagorean": (531441, 524288, "(3/2)^12 / 2^7 — twelve just fifths vs seven octaves"),
    "schisma": (32805, 32768, "pythagorean / syntonic"),
    "diaschisma": (2048, 2025, "2 / ((3/2)^4 * (5/4)^2) reduced"),
    "septimal_archytas": (64, 63, "(8/7) / (9/8) — the septimal comma"),
}


def section_commas():
    # Derive rather than assert: build each comma from its definition in exact ℚ.
    syn = (Q(3, 2) ** 4) / Q(5, 1)
    pyth = (Q(3, 2) ** 12) / (Q(2, 1) ** 7)
    schisma = pyth / syn
    # NOTE (rc424 self-correction): this first read (9/8)/(8/7) = 63/64 — the
    # RECIPROCAL. The `matches` field caught it. The septimal comma is the
    # amount by which 8/7 EXCEEDS 9/8, so the larger interval goes on top. A
    # Class-C read-direction error, and exactly the class of defect the
    # derive-don't-assert check exists to catch.
    arch = Q(8, 7) / Q(9, 8)
    derived = {
        "syntonic": syn, "pythagorean": pyth,
        "schisma": schisma, "septimal_archytas": arch,
    }
    for name, q in derived.items():
        stated = COMMAS[name]
        emit(
            "comma",
            name=name,
            derived=f"{q.numerator}/{q.denominator}",
            stated=f"{stated[0]}/{stated[1]}",
            matches=(q.numerator == stated[0] and q.denominator == stated[1]),
            derivation=stated[2],
            limit=proto_just_limit(q.numerator, q.denominator)["limit"],
            monzo=proto_just_limit(q.numerator, q.denominator)["monzo"],
            vanishes=(q == Q(1, 1)),
        )
    # The point of a comma: it does NOT vanish, and Class N will hide that.
    for name, q in derived.items():
        for max_d in (10, 100, 1000):
            p, r = best_rational(q.numerator, q.denominator, max_d)
            emit(
                "comma_class_n_erasure",
                name=name,
                max_denominator=max_d,
                exact=f"{q.numerator}/{q.denominator}",
                best_rational=f"{p}/{r}",
                ERASED_TO_UNISON=(p == r),
                note=("a comma is a SMALL exact rational; best_rational at a "
                      "low ceiling returns 1/1 and the comma disappears. This "
                      "is the #T1014 conversion in its purest form — the op "
                      "family must carry the exact value, never an anchor."),
            )
    emit(
        "comma_design_verdict",
        candidate="comma_ratio / temperament_tempers_out",
        classes="N (exact ℚ) ∘ J (prime support) ∘ I (gcd)",
        exact=True,
        composes_with="srmech.music.commensurability_verdict",
        verdict=("ACCEPT — but as a DERIVED op, not a lookup table. A table of "
                 "five constants earns nothing; an op that DERIVES a comma "
                 "from a generator chain and reports whether a given "
                 "temperament tempers it out is a real capability."),
    )


# ═════════════════════════════════════════════════════════════════════════════
# §3  THE AUDIBLE #T1014 CORRUPTION — non-degenerate, on a real chord
# ═════════════════════════════════════════════════════════════════════════════
def section_audible_corruption():
    # A just major triad: 4:5:6 — exact, 5-limit, provably harmonic.
    just = [Q(4, 4), Q(5, 4), Q(6, 4)]
    v_just = commensurability_verdict(just)
    emit(
        "audible_just_triad",
        spectrum="just major triad 4:5:6",
        ratios=[f"{q.numerator}/{q.denominator}" for q in just],
        verdict=v_just["verdict"],
        period=str(v_just.get("period_multiplier")),
        limits=[proto_just_limit(q.numerator, q.denominator)["limit"] for q in just],
        note="the honest answer: harmonic, 5-limit, a real common period",
    )
    # The 12-EDO major triad: 2^(4/12) and 2^(7/12) — irrational, inharmonic.
    # Class N is handed the two irrationals as truncated integer pairs.
    THIRD = (12599210498948732, 10000000000000000)   # 2**(4/12)
    FIFTH = (14983070768766815, 10000000000000000)   # 2**(7/12)
    for max_d in (10, 100, 1000, 10000):
        t = best_rational(*THIRD, max_d)
        f = best_rational(*FIFTH, max_d)
        approx = [Q(1, 1), Q(*t), Q(*f)]
        row = dict(max_denominator=max_d,
                   third=f"{t[0]}/{t[1]}", fifth=f"{f[0]}/{f[1]}",
                   third_limit=proto_just_limit(*t)["limit"],
                   fifth_limit=proto_just_limit(*f)["limit"],
                   third_is_just_5_4=(t == (5, 4)),
                   fifth_is_just_3_2=(f == (3, 2)))
        try:
            v = commensurability_verdict(approx)
            row.update(verdict=v["verdict"], period=str(v.get("period_multiplier")),
                       outcome="ANSWERED")
        except Exception as exc:
            row.update(verdict=None, outcome="RAISED", exc=str(exc)[:160])
        emit("audible_edo_triad_via_class_n", **row,
             note=("12-EDO's third and fifth are IRRATIONAL. Class-N hands "
                   "back a rational and the verdict flips to 'harmonic'. The "
                   "returned ratio is audibly a DIFFERENT interval from the "
                   "just one at low ceilings — this is the corruption you can "
                   "hear."))
    emit(
        "t1014_scoping_verdict",
        surfaced_by_the_family=True,
        how=("just_limit / comma_ratio / temperament_error all take the "
             "Class-N path as their INPUT domain, on values where the wrong "
             "answer is an audible interval rather than an abstract period. "
             "The existing acoustic surface already WARNS about this "
             "(commensurability_verdict.class_n_warning); nothing yet "
             "DEMONSTRATES it."),
        deliverable=("an explicit worked example per op showing the exact "
                     "value and the Class-N anchor side by side, plus a test "
                     "that pins the divergence — a wrong answer you can hear "
                     "is a better instrument than one you must reason about"),
    )


# ═════════════════════════════════════════════════════════════════════════════
# §4  PITCH-CLASS SET THEORY on ℤ/12  —  Class I ∘ Class E
#
# Forte (1973) and Rahn (1980) give DIFFERENT prime-form algorithms. The
# verified divergence list is 6 set classes: 5-20, 6-Z29, 6-31, 7-Z18, 7-20,
# 8-26. Reproduce that count HERE — if the implementations disagree on
# exactly 6, the spec can name a convention on evidence; if not, report
# UNVERIFIED rather than pick one.
# ═════════════════════════════════════════════════════════════════════════════
def pcs_transpose(s, n):
    return frozenset(cyclic_mod_add(x, n, 12) for x in s)


def pcs_invert(s):
    # inversion about 0: x -> -x mod 12, via the shipped modular add
    return frozenset(cyclic_mod_add(0, (12 - x) % 12, 12) for x in s)


def interval_vector(s):
    """The interval-class vector: how a set relates to ITSELF at every ic."""
    v = [0] * 6
    for a, b in itertools.combinations(sorted(s), 2):
        d = (b - a) % 12
        ic = d if d <= 6 else 12 - d
        v[ic - 1] += 1
    return tuple(v)


def _rotations(s):
    srt = sorted(s)
    n = len(srt)
    return [tuple(srt[(i + k) % n] for k in range(n)) for i in range(n)]


def _spans(rot):
    a0 = rot[0]
    return [ (x - a0) % 12 for x in rot[1:] ]


def normal_order(s, convention):
    """Rahn: minimise (d_last, d_{last-1}, ..., d_1). Forte: (d_last, d_1, d_2, ...)."""
    best = None
    for rot in _rotations(s):
        d = _spans(rot)
        if not d:
            key = ()
        elif convention == "rahn":
            key = tuple([d[-1]] + list(reversed(d[:-1])))
        else:
            key = tuple([d[-1]] + d[:-1])
        if best is None or key < best[0] or (key == best[0] and rot < best[1]):
            best = (key, rot)
    return best[1]


def prime_form(s, convention):
    cands = []
    for t in (s, pcs_invert(s)):
        no = normal_order(t, convention)
        cands.append(tuple((x - no[0]) % 12 for x in no))
    return min(cands)


def section_pc_set_theory():
    # Enumerate all set classes (Tn/TnI equivalence) of cardinality 2..10.
    classes_rahn, classes_forte = {}, {}
    for card in range(2, 11):
        for s in itertools.combinations(range(12), card):
            fs = frozenset(s)
            pr = prime_form(fs, "rahn")
            pf = prime_form(fs, "forte")
            classes_rahn.setdefault(pr, set()).add(fs)
            classes_forte.setdefault(pf, set()).add(fs)
    # A set class is the orbit under Tn/TnI; count them per cardinality.
    per_card = {}
    for pr in classes_rahn:
        per_card[len(pr)] = per_card.get(len(pr), 0) + 1
    emit(
        "pcs_set_class_census",
        set_classes_by_cardinality=per_card,
        total_2_to_10=len(classes_rahn),
        note=("the standard count of set classes of cardinality 2..10 under "
              "Tn/TnI; cardinalities 0,1,11,12 are trivial and excluded"),
    )

    # Where do the two conventions disagree? Compare, orbit by orbit.
    disagree = []
    seen = set()
    for card in range(2, 11):
        for s in itertools.combinations(range(12), card):
            fs = frozenset(s)
            pr, pf = prime_form(fs, "rahn"), prime_form(fs, "forte")
            if pr != pf and (pr, pf) not in seen:
                seen.add((pr, pf))
                disagree.append({"rahn": list(pr), "forte": list(pf),
                                 "cardinality": card,
                                 "interval_vector": list(interval_vector(fs))})
    emit(
        "pcs_forte_vs_rahn",
        n_disagreeing_set_classes=len(disagree),
        disagreements=disagree,
        expected_from_literature=6,
        expected_names=["5-20", "6-Z29", "6-31", "7-Z18", "7-20", "8-26"],
        reproduces_literature_count=(len(disagree) == 6),
        note=("Forte (1973) packs from the left; Rahn (1980) packs from the "
              "right. The literature count of affected prime forms is 6 of "
              "208. If this run does not reproduce 6, the divergence is "
              "reported UNVERIFIED and the spec must name its convention "
              "explicitly rather than assume one."),
    )

    # Interval vector — the "classification that can say all the notes it is NOT".
    for name, s in [("major triad", {0, 4, 7}), ("minor triad", {0, 3, 7}),
                    ("diminished 7th", {0, 3, 6, 9}),
                    ("whole-tone", {0, 2, 4, 6, 8, 10}),
                    ("diatonic scale", {0, 2, 4, 5, 7, 9, 11}),
                    ("chromatic hexachord", {0, 1, 2, 3, 4, 5})]:
        emit("pcs_interval_vector", name=name, pcs=sorted(s),
             interval_vector=list(interval_vector(frozenset(s))),
             prime_form_rahn=list(prime_form(frozenset(s), "rahn")))

    # The Z-relation: distinct set classes sharing an interval vector — the
    # exact place where "characterise a thing by all it is NOT" is INCOMPLETE.
    by_iv = {}
    for pr, members in classes_rahn.items():
        iv = interval_vector(next(iter(members)))
        by_iv.setdefault(iv, set()).add(pr)
    z_pairs = {iv: sorted(v) for iv, v in by_iv.items() if len(v) > 1}
    emit(
        "pcs_z_relation",
        n_interval_vectors_shared_by_multiple_set_classes=len(z_pairs),
        examples=[{"interval_vector": list(iv),
                   "set_classes": [list(p) for p in ps]}
                  for iv, ps in sorted(z_pairs.items())[:8]],
        note=("THE LOAD-BEARING CAVEAT for the user's (c): the interval "
              "vector does NOT determine the set class. Z-related pairs share "
              "an interval vector and are genuinely different objects. So "
              "'a classification that can say all the other notes it is NOT' "
              "is a real and computable object, but it is NOT a complete "
              "invariant — it is a lossy one, and the loss is exactly the "
              "Z-relation."),
    )
    emit(
        "pcs_design_verdict",
        candidate="pitch_class_transpose / pitch_class_invert / interval_vector / prime_form",
        classes="I (ℤ/12 modular action) ∘ E (catalog / normal-form selection)",
        exact=True,
        closed_form=True,
        rosetta_bucket_forecast="composition_of_c",
        verdict=("ACCEPT interval_vector + transpose + invert. prime_form "
                 "ACCEPT ONLY IF it names its convention in the op name or a "
                 "required argument — shipping an unnamed prime_form would "
                 "silently pick a side in a live 50-year disagreement and "
                 "would be wrong for whichever community it did not pick."),
    )


# ═════════════════════════════════════════════════════════════════════════════
# §5  INTERVAL INVERSION UNDER READ-DIRECTION WRITHE — Class C ∘ Class I
# ═════════════════════════════════════════════════════════════════════════════
def section_inversion():
    rows = []
    for step in range(1, 7):
        inv7 = 7 - step
        rows.append({"z7_step": step, "z7_inversion": inv7,
                     "sums_to_octave": (step + inv7) == 7})
    chrom = []
    for s in range(0, 13):
        chrom.append({"semitones": s, "inversion": (12 - s) % 12 if s else 0,
                      "self_inverse": (s == 6)})
    emit(
        "inversion_z7", rows=rows,
        note="§3.46.3: +4 (fifth) ⟷ +3 (fourth) under read-reversal; 4+3=7",
    )
    emit(
        "inversion_z12", rows=chrom,
        unique_self_inverse=[r["semitones"] for r in chrom if r["self_inverse"]],
        note=("in ℤ/12 the tritone (6) is the UNIQUE self-inverse interval — "
              "12 is even so the octave CAN be bisected. In ℤ/7 no step is "
              "self-inverse because 7 is odd (§3.46.2's 7/2 = 3.5). That is "
              "precisely why the loop-edge defect of (a) is invisible in the "
              "ℤ/7 lane and lands on 6 in the ℤ/12 lane."),
    )
    emit(
        "inversion_design_verdict",
        candidate="interval_invert",
        classes="C (read-direction chirality) ∘ I (modular complement)",
        exact=True,
        verdict=("REJECT AS A STANDALONE OP — `interval_invert(s, n) = (n-s) "
                 "mod n` is one call to the already-shipped cyclic_mod_add "
                 "and carries no decision. It earns its place only as a "
                 "documented MODE of the interval op, not as a registry "
                 "entry of its own. Shipping it alone would add registry "
                 "surface for zero capability."),
    )


# ═════════════════════════════════════════════════════════════════════════════
# §6  music_doa — THE HOMOGRAPH, MEASURED
# ═════════════════════════════════════════════════════════════════════════════
def section_music_doa():
    ts = get_tool_schema()
    registered = [t.name for t in ts.tools if "music" in t.name.lower()]
    # Is the DOA op registered at all?
    doa_entries = [t.name for t in ts.tools
                   if "closed_form_ops" in t.name or "doa" in t.name.lower()]
    from srmech.signal_processing import registered_ops
    disp = sorted(registered_ops())
    from srmech.signal_processing.closed_form_ops import PATH_A_OP_MODULES
    emit(
        "doa_registration_state",
        toolentry_names_containing_music=registered,
        doa_toolentries=doa_entries,
        doa_has_toolentry=bool(doa_entries),
        dispatcher_registered_ops=disp,
        music_in_dispatcher=("music" in disp),
        path_a_declared_modules=len(PATH_A_OP_MODULES),
        path_a_actually_dispatchable=len(disp),
        note=("MEASURED: the DOA op has NO ToolEntry and is NOT in the "
              "signal_processing dispatcher. It is reachable only as "
              "srmech.signal_processing.closed_form_ops.music.op(). So it has "
              "zero presence in search(), in describe(), in MCP and in the "
              "compiled C registry."),
    )

    for q in ["MUSIC algorithm", "MUltiple SIgnal Classification",
              "direction of arrival", "DOA estimation",
              "subspace eigendecomposition source localisation"]:
        r = search(q, k=5)
        hits = [{"rank": i + 1, "kind": h["kind"], "name": h["name"],
                 "score": str(h["score"])}
                for i, h in enumerate(r)]
        emit("doa_search_before", query=q, hits=hits,
             top_hit=hits[0]["name"] if hits else None,
             doa_op_present=any("closed_form_ops" in h["name"] for h in hits))

    emit(
        "doa_rename_analysis",
        proposal="register the DOA op as `music_doa`",
        finding_that_changes_the_cost=(
            "the brief frames this as a RENAME that fixes search ranking. "
            "Measured, it is not a rename — it is a first REGISTRATION. "
            "search() indexes ToolEntry prose; the DOA op has no ToolEntry, "
            "so today it is not out-ranked by the acoustics ops, it is ABSENT. "
            "Renaming the module alone would change nothing search returns."),
        what_actually_fixes_it=(
            "register a ToolEntry named srmech.signal_processing.music_doa "
            "(or .closed_form_ops.music_doa) carrying 'MUSIC (MUltiple SIgnal "
            "Classification)' + Schmidt (1986) in the summary. That is +1 "
            "registry entry, not a zero-delta rename."),
        predicted_after=(
            "with 'MUSIC', 'MUltiple SIgnal Classification', 'direction of "
            "arrival' and 'DOA' all in one ToolEntry's name+summary+"
            "explanation, the name-leaf 4x boost puts music_doa at rank 1 for "
            "the DOA queries while the acoustics ops keep the acoustic ones. "
            "This is a PREDICTION; it is not measurable until the entry "
            "exists, and it is labelled as a prediction rather than a result."),
        collision_check_alias_layer=(
            "the 8 bound alias names in music_domain_aliases.toml are "
            "partials / bell_tuning / overtone_series / drum_modes / "
            "temperament / is_inharmonic / overtone_period / exactness. "
            "`music_doa` collides with none of them."),
        citation_caveat=(
            "Schmidt (1986) IEEE Trans. AP-34(3) 276-280, DOI "
            "10.1109/TAP.1986.1143830, is PAYWALLED-ONLY. Per "
            "[[feedback_paywalled_doi_cannot_be_attested]] the DOI cannot "
            "stand alone as framework attestation. The open chain is the 1979 "
            "RADC Spectrum Estimation Workshop precursor, DTIC accession "
            "ADA081736 (openly downloadable). The shipped SSOT_CITATION in "
            "closed_form_ops/music.py cites only the paywalled DOI."),
    )


def main():
    try:
        import numpy  # noqa: F401
        np = True
    except ImportError:
        np = False
    emit("env", srmech_file=srmech.__file__, srmech_version=srmech.__version__,
         registry_total=len(get_tool_schema().tools), numpy_present=np,
         python=sys.version.split()[0])

    section_just_intonation()
    section_commas()
    section_audible_corruption()
    section_pc_set_theory()
    section_inversion()
    section_music_doa()

    out = "music_optheory_costing_rc424.ndjson"
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        for r in RECORDS:
            fh.write(json.dumps(r, default=str) + "\n")
    print(f"wrote {len(RECORDS)} records -> {out}")
    for r in RECORDS:
        if "verdict" in r:
            print(f"  [{r['kind']}] {str(r['verdict'])[:170]}")


if __name__ == "__main__":
    main()
