"""
Mathematical primitives + cached precomputed tables for the 640-dim
spectral chess encoder.

Owns the full derivation from scratch — does NOT import encoder_512 at
runtime. Numerics are verified bit-identical to the C reference (which
itself is generated by codegen/emit_tables.py from the same math).

Expensive objects (eigendecomposition, 320 local fiber computations,
SVD-derived FIBER_BASIS) are cached to a single .npz on disk. Cache
key is a version string; bump VERSION when math changes.

Cache location (in order of precedence):
    $CHESS_SPECTRAL_CACHE (if set)
    ~/.cache/chess_spectral/tables.npz (Linux/macOS)
    %LOCALAPPDATA%\\chess_spectral\\tables.npz (Windows)
    <package_dir>/_cache/tables.npz (fallback)

On first import (or after version bump) the tables are computed and
saved. Subsequent imports load from disk in ~20 ms.
"""
from __future__ import annotations

import os
import sys
import time
from pathlib import Path

import numpy as np
from scipy.linalg import eigh, svd

# Bump this whenever the math that produces any cached table changes.
# The loader silently recomputes on version mismatch.
VERSION = "1.0.0"

BOARD_DIM = 64

# ─── Board geometry ─────────────────────────────────────────────────────

def sq(r: int, c: int) -> int:     return r * 8 + c
def rc(s: int) -> tuple[int, int]: return s // 8, s % 8


def knight_targets(r, c):
    for dr, dc in [(-2,-1),(-2,1),(-1,-2),(-1,2),(1,-2),(1,2),(2,-1),(2,1)]:
        nr, nc = r + dr, c + dc
        if 0 <= nr < 8 and 0 <= nc < 8: yield nr, nc

def bishop_targets(r, c):
    for dr, dc in [(-1,-1),(-1,1),(1,-1),(1,1)]:
        nr, nc = r + dr, c + dc
        while 0 <= nr < 8 and 0 <= nc < 8:
            yield nr, nc; nr += dr; nc += dc

def rook_targets(r, c):
    for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:
        nr, nc = r + dr, c + dc
        while 0 <= nr < 8 and 0 <= nc < 8:
            yield nr, nc; nr += dr; nc += dc

def queen_targets(r, c):
    yield from bishop_targets(r, c)
    yield from rook_targets(r, c)

def king_targets(r, c):
    for dr in (-1, 0, 1):
        for dc in (-1, 0, 1):
            if dr == 0 and dc == 0: continue
            nr, nc = r + dr, c + dc
            if 0 <= nr < 8 and 0 <= nc < 8: yield nr, nc


PIECE_FNS = {'Knight': knight_targets, 'King': king_targets,
             'Bishop': bishop_targets, 'Rook': rook_targets,
             'Queen': queen_targets}
SHORT_PFNS = {'N': knight_targets, 'B': bishop_targets, 'R': rook_targets,
              'Q': queen_targets, 'K': king_targets}

VALS = {'P': 1, 'N': 3, 'B': 3.5, 'R': 5, 'Q': 9, 'K': 100,
        'p': -1, 'n': -3, 'b': -3.5, 'r': -5, 'q': -9, 'k': -100}


def build_adjacency(fn) -> np.ndarray:
    """Undirected piece-movement adjacency from a target function."""
    A = np.zeros((BOARD_DIM, BOARD_DIM))
    for r in range(8):
        for c in range(8):
            for tr, tc in fn(r, c):
                A[sq(r, c), sq(tr, tc)] = 1
    return A


def graph_laplacian(A: np.ndarray) -> np.ndarray:
    return np.diag(A.sum(axis=1)) - A


def white_pawn_targets(r, c):
    """White-pawn move+capture targets. Matches
    chess_pawn_laplacian.white_pawn_targets."""
    if r <= 0 or r >= 7:
        return
    yield r - 1, c                       # forward single
    if r == 6:
        yield r - 2, c                   # forward double from starting row
    if c > 0:
        yield r - 1, c - 1               # capture left
    if c < 7:
        yield r - 1, c + 1               # capture right


def build_directed_adjacency(fn) -> np.ndarray:
    """Directed (non-symmetrized) adjacency for pawn-like pieces."""
    A = np.zeros((BOARD_DIM, BOARD_DIM))
    for r in range(8):
        for c in range(8):
            for tr, tc in fn(r, c):
                A[sq(r, c), sq(tr, tc)] = 1
    return A


# ─── D4 symmetry (cheap, always computed) ───────────────────────────────

def make_perm(g: int) -> np.ndarray:
    p = np.zeros(BOARD_DIM, dtype=np.int8)
    for r in range(8):
        for c in range(8):
            if   g == 0: nr, nc = r, c
            elif g == 1: nr, nc = c, 7 - r
            elif g == 2: nr, nc = 7 - r, 7 - c
            elif g == 3: nr, nc = 7 - c, r
            elif g == 4: nr, nc = r, 7 - c
            elif g == 5: nr, nc = 7 - r, c
            elif g == 6: nr, nc = c, r
            elif g == 7: nr, nc = 7 - c, 7 - r
            p[sq(r, c)] = sq(nr, nc)
    return p


D4_PERMS = np.stack([make_perm(g) for g in range(8)])  # (8, 64)

CHARS = {
    'A1': [ 1,  1,  1,  1,  1,  1,  1,  1],
    'A2': [ 1,  1,  1,  1, -1, -1, -1, -1],
    'B1': [ 1, -1,  1, -1,  1, -1,  1, -1],
    'B2': [ 1, -1,  1, -1, -1,  1, -1,  1],
    'E':  [ 2,  0, -2,  0,  0,  0,  0,  0],
}

# ─── Spectral piece values (cheap) ──────────────────────────────────────

def _compute_spectral_vals() -> dict[str, float]:
    out = {}
    for pchar, pfn in SHORT_PFNS.items():
        A = build_adjacency(pfn)
        mean_deg = A.sum() / BOARD_DIM
        out[pchar] = round(mean_deg / 2.6, 1)
    out['P'] = 1.0
    return out


_SV = _compute_spectral_vals()
SPECTRAL_VALS = {
    'P': _SV['P'], 'N': _SV['N'], 'B': _SV['B'],
    'R': _SV['R'], 'Q': _SV['Q'], 'K': _SV['K'],
    'p': -_SV['P'], 'n': -_SV['N'], 'b': -_SV['B'],
    'r': -_SV['R'], 'q': -_SV['Q'], 'k': -_SV['K'],
}


# ─── Expensive tables (cached) ──────────────────────────────────────────

def _cache_path() -> Path:
    """Resolve cache location. Creates parent dirs on access, not here."""
    env = os.environ.get("CHESS_SPECTRAL_CACHE")
    if env:
        return Path(env)
    if sys.platform == "win32":
        base = os.environ.get("LOCALAPPDATA", os.path.expanduser("~"))
        return Path(base) / "chess_spectral" / "tables.npz"
    xdg = os.environ.get("XDG_CACHE_HOME", os.path.expanduser("~/.cache"))
    return Path(xdg) / "chess_spectral" / "tables.npz"


def _fallback_cache_path() -> Path:
    """Package-local fallback if the user cache dir isn't writable."""
    return Path(__file__).parent / "_cache" / "tables.npz"


def _compute_tables(verbose: bool = False) -> dict[str, np.ndarray]:
    """Derive the expensive tables from scratch. ~1.5 s on typical
    hardware. Outputs are keyed by name and stored as float64 arrays
    except where noted. All intermediate arrays use the grid eigenbasis
    EVECS_GRID so downstream code never needs its own eigendecomposition.
    """
    t0 = time.perf_counter()

    # Grid eigenbasis
    A_GRID = np.zeros((BOARD_DIM, BOARD_DIM))
    for r in range(8):
        for c in range(8):
            for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                nr, nc = r + dr, c + dc
                if 0 <= nr < 8 and 0 <= nc < 8:
                    A_GRID[sq(r, c), sq(nr, nc)] = 1
    L_GRID = graph_laplacian(A_GRID)
    EVALS_GRID, EVECS_GRID = eigh(L_GRID)

    # Global fibers (full-piece Laplacians). Concatenate off-diagonal
    # upper-triangles, then SVD to get a 3D fiber basis over 2016 dims.
    upper_idx = np.triu_indices(BOARD_DIM, k=1)
    fibers_global = {}
    for name in ['Knight', 'King', 'Bishop', 'Queen']:
        A = build_adjacency(PIECE_FNS[name])
        L = graph_laplacian(A)
        C = EVECS_GRID.T @ L @ EVECS_GRID
        C_off = C.copy(); np.fill_diagonal(C_off, 0)
        fibers_global[name] = C_off[upper_idx]
    _fiber_mat = np.array([
        fibers_global[n] / np.linalg.norm(fibers_global[n])
        for n in fibers_global
    ])
    _, _, Vt_fib = svd(_fiber_mat, full_matrices=False)
    FIBER_BASIS = Vt_fib[:3].T  # (2016, 3)

    # Per-piece, per-square local fibers. Pack as dense arrays keyed by
    # (piece_idx, square) — piece index matches SHORT_PFNS iteration
    # order: N=0, B=1, R=2, Q=3, K=4.
    LOCAL_FIBER_3D  = np.zeros((5, BOARD_DIM, 3))
    LOCAL_ADJ_ROWS  = np.zeros((5, BOARD_DIM, BOARD_DIM))
    for pidx, pchar in enumerate(['N', 'B', 'R', 'Q', 'K']):
        fn = SHORT_PFNS[pchar]
        for s in range(BOARD_DIM):
            r, c = rc(s)
            A_loc = np.zeros((BOARD_DIM, BOARD_DIM))
            for tr, tc in fn(r, c):
                t = sq(tr, tc)
                A_loc[s, t] = 1; A_loc[t, s] = 1
            LOCAL_ADJ_ROWS[pidx, s] = A_loc[s]
            C_loc = EVECS_GRID.T @ A_loc @ EVECS_GRID
            C_off = C_loc.copy(); np.fill_diagonal(C_off, 0)
            LOCAL_FIBER_3D[pidx, s] = C_off[upper_idx] @ FIBER_BASIS

    # Pawn tables (channel 8 = FA, channel 9 row 0 = FD for pawn).
    A_white = build_directed_adjacency(white_pawn_targets)
    A_anti  = 0.5 * (A_white - A_white.T)
    assert np.allclose(A_anti + A_anti.T, 0.0, atol=1e-14), "A_anti antisymmetric"
    PAWN_ANTI_FIBER = EVECS_GRID.T @ A_anti @ EVECS_GRID   # (64, 64) eigenbasis

    # Diagonal deviation per piece type: P (from sym pawn Laplacian),
    # then N, B, R, Q, K.
    DIAG_DEV = np.zeros((6, BOARD_DIM))
    A_sym_pawn = 0.5 * (A_white + A_white.T)
    L_pawn_sym = graph_laplacian(A_sym_pawn)
    C_pawn = EVECS_GRID.T @ L_pawn_sym @ EVECS_GRID
    DIAG_DEV[0] = np.diag(C_pawn) - EVALS_GRID
    for idx, pname in enumerate(['Knight', 'Bishop', 'Rook', 'Queen', 'King']):
        A = build_adjacency(PIECE_FNS[pname])
        L = graph_laplacian(A)
        C = EVECS_GRID.T @ L @ EVECS_GRID
        DIAG_DEV[idx + 1] = np.diag(C) - EVALS_GRID
    # Sanity: rook diagonal deviation magnitude ~88.05 (chess_rook_shadow.py)
    rook_norm = float(np.linalg.norm(DIAG_DEV[3]))
    assert 87.0 < rook_norm < 89.0, f"Rook diag-dev = {rook_norm} (expected ~88.05)"

    elapsed = time.perf_counter() - t0
    if verbose:
        print(f"chess_spectral: computed tables in {elapsed:.2f}s", file=sys.stderr)

    return dict(
        EVALS_GRID=EVALS_GRID, EVECS_GRID=EVECS_GRID,
        FIBER_BASIS=FIBER_BASIS,
        LOCAL_FIBER_3D=LOCAL_FIBER_3D, LOCAL_ADJ_ROWS=LOCAL_ADJ_ROWS,
        PAWN_ANTI_FIBER=PAWN_ANTI_FIBER, DIAG_DEV=DIAG_DEV,
    )


def _load_cached(path: Path) -> dict[str, np.ndarray] | None:
    """Try to load cached tables from `path`. Returns None on any
    mismatch or I/O error — caller falls through to _compute_tables."""
    if not path.exists():
        return None
    try:
        with np.load(path, allow_pickle=False) as data:
            ver = str(data["version"]) if "version" in data else ""
            if ver != VERSION:
                return None
            return {
                "EVALS_GRID":      data["EVALS_GRID"],
                "EVECS_GRID":      data["EVECS_GRID"],
                "FIBER_BASIS":     data["FIBER_BASIS"],
                "LOCAL_FIBER_3D":  data["LOCAL_FIBER_3D"],
                "LOCAL_ADJ_ROWS":  data["LOCAL_ADJ_ROWS"],
                "PAWN_ANTI_FIBER": data["PAWN_ANTI_FIBER"],
                "DIAG_DEV":        data["DIAG_DEV"],
            }
    except (OSError, KeyError, ValueError):
        return None


def _save_cached(path: Path, tables: dict[str, np.ndarray]) -> Path | None:
    """Save tables to `path`. Returns the actual path written (may be
    the fallback if the primary location isn't writable), or None on
    total failure."""
    for candidate in (path, _fallback_cache_path()):
        try:
            candidate.parent.mkdir(parents=True, exist_ok=True)
            np.savez_compressed(candidate, version=np.str_(VERSION), **tables)
            return candidate
        except OSError:
            continue
    return None


def _load_or_compute(verbose: bool = False) -> tuple[dict[str, np.ndarray],
                                                      str, Path]:
    """Return (tables, source_tag, path_touched). source_tag is one of:
        'cache'   — loaded from disk
        'computed'— recomputed (and saved, if cache write succeeded)
        'fresh'   — recomputed and cache write failed (in-memory only)
    """
    primary = _cache_path()
    for path in (primary, _fallback_cache_path()):
        cached = _load_cached(path)
        if cached is not None:
            return cached, "cache", path
    tables = _compute_tables(verbose=verbose)
    saved_path = _save_cached(primary, tables)
    return tables, ("computed" if saved_path else "fresh"), (saved_path or primary)


# Load once at import time. Environment variable CHESS_SPECTRAL_VERBOSE=1
# prints cache-hit / compute timing to stderr.
_VERBOSE = os.environ.get("CHESS_SPECTRAL_VERBOSE", "") not in ("", "0")
_TABLES, _SOURCE, _CACHE_PATH = _load_or_compute(verbose=_VERBOSE)
if _VERBOSE:
    print(f"chess_spectral: tables {_SOURCE} from {_CACHE_PATH}", file=sys.stderr)

EVALS_GRID      = _TABLES["EVALS_GRID"]
EVECS_GRID      = _TABLES["EVECS_GRID"]
FIBER_BASIS     = _TABLES["FIBER_BASIS"]
LOCAL_FIBER_3D  = _TABLES["LOCAL_FIBER_3D"]   # shape (5, 64, 3)
LOCAL_ADJ_ROWS  = _TABLES["LOCAL_ADJ_ROWS"]   # shape (5, 64, 64)
PAWN_ANTI_FIBER = _TABLES["PAWN_ANTI_FIBER"]  # shape (64, 64)
DIAG_DEV        = _TABLES["DIAG_DEV"]         # shape (6, 64)


# Public cache-management helpers

def cache_info() -> dict[str, object]:
    """Introspection: where the cache lives, whether it was used, what
    version is loaded."""
    return {
        "version":     VERSION,
        "source":      _SOURCE,
        "path":        str(_CACHE_PATH),
        "path_exists": _CACHE_PATH.exists(),
        "size_bytes":  _CACHE_PATH.stat().st_size if _CACHE_PATH.exists() else 0,
    }


def cache_rebuild() -> Path:
    """Force-recompute the tables and overwrite the cache. Returns the
    path written. Does NOT reload the module-level arrays — call sites
    that need the rebuilt values should restart the Python process (or
    use importlib.reload on this module)."""
    tables = _compute_tables(verbose=True)
    path = _save_cached(_cache_path(), tables)
    if path is None:
        raise IOError("could not write cache to any candidate location")
    return path


# ─── Signal / irrep primitives (cheap, pure functions) ──────────────────

def board_signal(pos: dict[int, str], vals: dict[str, float] | None = None
                ) -> np.ndarray:
    """64-dim board signal: piece value at each occupied square."""
    if vals is None:
        vals = VALS
    s = np.zeros(BOARD_DIM)
    for si, p in pos.items():
        s[si] = vals[p]
    return s


def project_irrep(sig: np.ndarray, irrep_name: str) -> np.ndarray:
    """Project 64-dim board signal onto a D4 irrep via Serre's character
    formula. `irrep_name` is one of 'A1', 'A2', 'B1', 'B2', 'E'."""
    chars = CHARS[irrep_name]
    dim_mu = 2 if irrep_name == 'E' else 1
    projected = np.zeros(BOARD_DIM)
    for g_idx, perm in enumerate(D4_PERMS):
        projected += chars[g_idx] * sig[perm]
    return (dim_mu / 8) * projected
