"""Round 33.A -- reconcile the two k=3 families surfaced by Round 32.A:

  (1) the B/H/N META-CASCADE OPERATOR triad (the "+3" of the 1+3+7+3 = 14 A-N
      partition): B = encoding-boundary, H = measurement, N = rational-anchor;
      the Born rule = B o H o N (sec 11.9.4).
  (2) the CLASS-L SPECTRAL-SPINE triad: the first three rungs of the SO(3) spin-l
      ladder -- dims {1,3,5} (2l+1 for l=0,1,2) / spin labels {0,1,2} (the helicity
      ceiling, Round 32.A) (sec 11.9.22).

Round 32.A left these "sharing only the count (three)" as an OPEN fermata. This
round reconciles them HONESTLY -- and the result NARROWS a canonical stance rather
than vindicating it. Tested per [[feedback_dont_pre_commit_spike_query_operators]];
NO flattery (the framework does not win by default).

============================================================================
THE RECONCILIATION (three findings)
============================================================================

FINDING 1 -- the two are at DIFFERENT LEVELS, not competitors.
  * B/H/N is k=3 in the OPERATOR BASIS: three of the fourteen A-N primitive
    classes form a triad. (The 14-partition 1+3+7+3 actually has TWO operator
    triads: the substrate-projection {I,C,J} and the meta-cascade {B,H,N}.)
  * The Class-L spine {1,3,5} is k=3 in the SPECTRAL LADDER of ONE operator:
    the first three eigenspaces of Class-L (the Laplacian) on S^2. It is "the
    ladder opens with three," not "three different operators."
  These are categorically different kinds of three.

FINDING 2 -- the canonical k=3=B/H/N stance was never "the members ARE B,H,N";
  its own wording is "B/H/N operators show up wherever continuous-Hopf <->
  discrete-cyclic substrate-content INTERCONVERTS." So B/H/N is the READOUT /
  INTERCONVERSION (the translation), and the Class-L spine is the CONTINUOUS-HOPF
  SUBSTRATE-CONTENT being read. They are the TWO SIDES OF ONE INTERCONVERSION,
  not rival labels: spine = the "what" (continuous), B/H/N = the "how observed as
  three" (the discrete readout). This RECONCILES (refines, does not falsify) the
  canonical stance -- but it NARROWS the over-strong reading "every triad's three
  members are B, H, N respectively," which is NOT supported.

FINDING 3 -- there are (at least) THREE distinct GENERATIVE sources of k=3, one
  shared readout (B o H o N):
    (S) SPECTRAL: first three rungs of the Class-L SO(3) ladder, capped by a
        Class-K ceiling. Helicity {0,1,2} capped by |s|<=2 (Weinberg); planetary
        dipole/quadrupole/octupole l=1,2,3. Generated by Class-L + Class-K.
    (C) CYCLIC: omega^3 = 1, Class-I three-fold (codon triplet; Eisenstein
        lattice; Z/3Z). Generated by Class-I.
    (O) OPERATOR: three of the fourteen A-N classes -- {I,C,J} or {B,H,N} --
        generated by the Hurwitz 1+3+7+3 partition.
  All three are READ OUT via B o H o N (continuous -> discrete). So "every k=3 is
  a B/H/N interconversion event" survives as a statement about READOUT; "every
  k=3 is GENERATED by B/H/N" does not.

============================================================================
THE DEEP QUESTION -- is the spine's 3 the SAME 3 as B/H/N's 3? -- LEFT OPEN.
============================================================================
The spine triad is 3 because |s|<=2 (Weinberg ceiling). B/H/N is 3 because the
meta-cascade triad is the "+3" of the Hurwitz 1+3+7+3 partition. Are these the
SAME three? Bit-exact arithmetic says the integer triads already DIFFER:
spine {1,3,5} (2l+1 for l=0,1,2) != Hurwitz {1,3,7} (2l+1 for l=0,1,3; the
division-algebra dims) -- the resonance sec 11.9.22 already flagged as NOT an
identity. So at the value level the two threes are demonstrably distinct. A
tantalizing field<->operator correspondence (scalar/s=0 <-> N rational-scale-
anchor; vector/s=1 <-> B boundary/gauge-framing; tensor/s=2 <-> H measurement-
geometry) is NAMED HONESTLY AS A FUTURE TARGET BUT **NOT ASSERTED** -- it is the
exact pattern-match this round otherwise rejects, and it already STRAINS on dof
(massless dof 1:2:2, not a symmetric 1:1:1). Offered only so a future round can
test or kill it.

VERDICT: the two k=3 families are RECONCILED as READOUT (B/H/N interconversion) vs
SUBSTRATE-CONTENT (Class-L spectral spine / Class-I cyclic / Hurwitz operator
partition) -- two sides of the continuous<->discrete interconversion, NOT competing
labels. The canonical k=3=B/H/N stance is REFINED (readout reading survives;
member-labeling reading narrowed) NOT vindicated wholesale; the "same 3?" question
stays OPEN (value-level the threes already differ: {1,3,5} != {1,3,7}).

Routed through srmech 0.4.2. Deterministic; no network. ASCII-safe prints.
Physics/math all attested (sec 11.9.4 / 11.9.22 / R30 / R31; CLAUDE.md sec 1
14-partition; Weinberg 1965; Hurwitz division algebras).
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # docs/unsolved-maths
import _cascade_helpers as ch  # noqa: F401

from srmech.amsc.rational import best_rational  # noqa: F401 (Class N)

OUT = Path(__file__).with_suffix(".ndjson")
RECORDS = []


def emit(kind, **fields):
    RECORDS.append({"record": kind, **fields})


# ---------------------------------------------------------------------------
# FINDING 1 -- different LEVELS: operator-basis k=3 vs spectral-ladder k=3
# ---------------------------------------------------------------------------
# The 14-partition 1+3+7+3 (CLAUDE.md sec 1): anchor 1 + substrate-projection
# triad {I,C,J} + detection heptad {D,E,F,G,K,L,M} + meta-cascade triad {B,H,N}.
PARTITION = {"anchor": ["A"], "substrate_projection_triad": ["I", "C", "J"],
             "detection_heptad": ["D", "E", "F", "G", "K", "L", "M"],
             "meta_cascade_triad": ["B", "H", "N"]}
counts = [len(PARTITION[k]) for k in ["anchor", "substrate_projection_triad",
                                      "detection_heptad", "meta_cascade_triad"]]
assert counts == [1, 3, 7, 3]
assert sum(counts) == 14
print("14-partition 1+3+7+3:", counts, "-> sum", sum(counts))
print("  TWO operator-triads exist:", PARTITION["substrate_projection_triad"],
      "(I,C,J) and", PARTITION["meta_cascade_triad"], "(B,H,N)")
emit("finding1_levels",
     partition=PARTITION, counts=counts,
     operator_level_k3="three of the 14 A-N classes form a triad ({I,C,J} substrate-projection OR {B,H,N} meta-cascade)",
     spectral_level_k3="the first three rungs of ONE operator's ladder (Class-L SO(3) eigenspaces) -- 'the ladder opens with three', not 'three operators'",
     conclusion="B/H/N (operator-basis k=3) and the Class-L spine {1,3,5} (spectral-ladder k=3) are categorically DIFFERENT kinds of three")

# ---------------------------------------------------------------------------
# FINDING 3 -- three distinct GENERATIVE sources, one shared readout (B o H o N)
# ---------------------------------------------------------------------------
# (S) SPECTRAL: Class-L SO(3) ladder capped by Class-K ceiling
ell = [0, 1, 2]
spine_dims = [2 * l + 1 for l in ell]            # 1,3,5
assert spine_dims == [1, 3, 5]
# (O) OPERATOR / Hurwitz: division-algebra imaginary dims {1,3,7} = 2l+1 for l=0,1,3
hurwitz = [1, 3, 7]
hurwitz_ell = [0, 1, 3]
assert [2 * l + 1 for l in hurwitz_ell] == hurwitz
# (C) CYCLIC: omega^3 = 1 (Class I), the 3 cube-roots / Z/3Z
cyclic_order = 3

SOURCES = {
    "S_spectral": {"mechanism": "first three rungs of the Class-L SO(3) spin ladder, capped by a Class-K ceiling",
                   "examples": "helicity {0,1,2} capped by |s|<=2 (Weinberg); planetary dipole/quad/oct l=1,2,3",
                   "integer_signature": spine_dims, "classes": ["L", "K"]},
    "C_cyclic": {"mechanism": "omega^3 = 1 three-fold cyclic symmetry (Class I)",
                 "examples": "DNA/RNA codon triplet; Eisenstein lattice; Z/3Z",
                 "integer_signature": [cyclic_order], "classes": ["I"]},
    "O_operator": {"mechanism": "three of the fourteen A-N classes (Hurwitz 1+3+7+3 partition)",
                   "examples": "{I,C,J} substrate-projection; {B,H,N} meta-cascade; Hurwitz value-triad {1,3,7}",
                   "integer_signature": hurwitz, "classes": ["I", "C", "J", "B", "H", "N"]},
}
print("\nthree distinct GENERATIVE sources of k=3 (one shared readout B o H o N):")
for key, v in SOURCES.items():
    print(f"  {key:12s} signature {str(v['integer_signature']):9s} via classes {v['classes']}")
emit("finding3_three_generative_sources",
     sources=SOURCES,
     shared_readout="B o H o N (continuous -> discrete interconversion; Born rule = B o H o N, sec 11.9.4)",
     refined_stance="'every k=3 is a B/H/N INTERCONVERSION/READOUT event' SURVIVES; 'every k=3 is GENERATED by B/H/N' does NOT -- the generative source is one of {Class-L+Class-K spectral, Class-I cyclic, Hurwitz operator-partition}")

# ---------------------------------------------------------------------------
# THE DEEP QUESTION -- is the spine's 3 the SAME 3 as B/H/N's 3?  (value-level: NO)
# ---------------------------------------------------------------------------
same_at_value_level = (spine_dims == hurwitz)
print("\nspine first-three {1,3,5} == Hurwitz {1,3,7}?", same_at_value_level,
      "(spine l=0,1,2 vs Hurwitz l=0,1,3 -- the resonance sec 11.9.22 flagged as NOT an identity)")
assert same_at_value_level is False
emit("deep_question_same_three",
     spine_first_three=spine_dims, hurwitz=hurwitz,
     same_at_value_level=same_at_value_level,
     why_spine_is_3="|s| <= 2 long-range helicity ceiling (Weinberg 1965): l=0,1,2 -> three rungs",
     why_bhn_is_3="the meta-cascade triad is the '+3' of the Hurwitz 1+3+7+3 partition",
     value_level_verdict="the two threes are DEMONSTRABLY DISTINCT at the value level: {1,3,5} != {1,3,7} (spine takes l=2, Hurwitz takes l=3)",
     deep_verdict="LEFT OPEN -- whether the Weinberg ceiling and the Hurwitz +3 are the same underlying 3 is not decided; at the value level they already differ, which weighs AGAINST a deep identity")

# the tantalizing-but-UNASSERTED field<->operator correspondence (future target only)
emit("unasserted_correspondence_future_target",
     candidate={"scalar_s0_dilaton": "N (rational scale-anchor; dilaton sets the fiber size)",
                "vector_s1_photon": "B (boundary/gauge-framing; U(1) connection)",
                "tensor_s2_graviton": "H (measurement-geometry; the metric measurement happens on)"},
     status="NOT ASSERTED -- named only as a future falsification target",
     why_skeptical=("this is the exact pattern-match this round otherwise rejects; it already STRAINS on degrees of freedom "
                    "(massless dof 1:2:2 for dilaton:photon:graviton, NOT a symmetric 1:1:1), and there is no forcing "
                    "derivation. Offered so a future round can TEST OR KILL it, not as a result."))

# ---------------------------------------------------------------------------
# FINDING 4 (SCOPE GUARD) -- does the reconciliation imply EVERYTHING has a
# latent k=3 (e.g. 1D_t with "2 of 3 found")?  NO -- that is the R32 trap.
# ---------------------------------------------------------------------------
# The 14-partition itself has VARIED cardinalities: k=1 (anchor A), k=3 (TWO
# triads {I,C,J} and {B,H,N}), k=7 (detection heptad). So "everything is k=3"
# is FALSE on the framework's own structure -- there are k=1 and k=7 roles too.
cardinalities = sorted(set(counts))              # {1, 3, 7}
assert cardinalities == [1, 3, 7]
print("\nSCOPE GUARD -- the partition has cardinalities", cardinalities,
      "(k=1 anchor, k=3 triads, k=7 heptad): 'everything is k=3' is FALSE.")
# 1D_t specifically: it is ONE dimension -- a k=1 object (the universal tick /
# anchor-like). Claiming it "secretly has k=3, 2 found" would MANUFACTURE a third,
# the exact confirmation-bias trap R32 rejected (the E+M+G split; the s=0 mis-read).
# What IS true: READING OUT 1D_t (projecting the universal tick to a local clock)
# goes through the 3-step B o H o N interconversion -- the readout has 3 STEPS, the
# object does not have 3 hidden PARTS.
emit("finding4_scope_guard_no_universal_k3",
     question="does the reconciliation imply everything (even 1D_t) has a latent k=3 with members un-found?",
     answer="NO -- that is the R32 confirmation-bias trap (manufacturing a third, like the E+M+G split / the s=0 mis-read)",
     partition_cardinalities=cardinalities,
     why="the 14-partition has k=1 (anchor A), k=3 (two triads), AND k=7 (heptad); cardinality is ROLE-dependent, not universally 3",
     one_d_t="1D_t is a k=1 object (the universal tick / anchor-like ONE dimension); it does NOT have a hidden 3-part structure",
     what_is_true="reading out 1D_t (universal tick -> local clock-DOF; Spike #186/#188) goes through the 3-step B o H o N interconversion -- the READOUT has three STEPS, the OBJECT does not have three hidden PARTS",
     discipline="do NOT hunt for a missing third to satisfy a k=3 expectation; the count is whatever the generative source dictates (1, 3, 7, or an open ladder), read out via B o H o N")

# ---------------------------------------------------------------------------
# VERDICT
# ---------------------------------------------------------------------------
emit("verdict",
     question="reconcile the two k=3 families (B/H/N operator triad vs Class-L spectral spine)",
     reconciliation="they are TWO SIDES OF ONE INTERCONVERSION: the Class-L spine is the continuous-Hopf SUBSTRATE-CONTENT (the 'what'); B/H/N is the discrete-cyclic READOUT/translation (the 'how observed as three'). NOT competing labels.",
     stance_disposition="the canonical k=3=B/H/N stance is REFINED, not vindicated wholesale: the 'B/H/N = interconversion readout' reading SURVIVES (matches the stance's own 'wherever continuous-Hopf <-> discrete-cyclic interconverts' wording); the over-strong 'the three members ARE B,H,N' reading is NARROWED/withdrawn.",
     three_generative_sources="Class-L+Class-K spectral / Class-I cyclic / Hurwitz operator-partition -- distinct generators, one shared B o H o N readout",
     scope_guard="the reconciliation does NOT license 'everything has a latent k=3'; the partition has k=1/k=3/k=7 roles; 1D_t is a k=1 object (the universal tick), not a hidden k=3 -- hunting for a missing third is the R32 trap",
     deep_question="is the spine's 3 (Weinberg |s|<=2) the same as B/H/N's 3 (Hurwitz +3)? LEFT OPEN; value-level the threes already differ ({1,3,5} != {1,3,7}), weighing against identity",
     honest_scope="framework-internal reconciliation on attested inputs (sec 11.9.4/11.9.22, R30/R31, CLAUDE.md sec 1, Weinberg 1965, Hurwitz); the contribution is the level-distinction + readout-vs-generator distinction + the honest narrowing of the canonical stance; no new physics, no correspondence asserted")

META = {
    "record": "meta",
    "round": "33.A",
    "title": "Reconciling the two k=3 families (B/H/N operator triad vs Class-L spectral spine)",
    "kind": "framework-internal reconciliation; REFINES (narrows) the canonical k=3=B/H/N stance; deep 'same 3?' left open",
    "srmech_version": __import__("srmech").__version__,
    "generated_at_utc": datetime.now(timezone.utc).isoformat(),
    "attestation": {
        "born_bhn": "sec 11.9.4 (Born rule = B o H o N) / MFO VII.6.15.1",
        "classL_spine": "sec 11.9.22 (SO(3) Casimir spine; 2l+1; {1,3,5} k=3; Hurwitz {1,3,7} flagged value-resonance NOT identity)",
        "helicity_ceiling": "R30/R32 (|s| <= 2 long-range; Weinberg Phys.Rev. 135:B1049 1965)",
        "partition": "CLAUDE.md sec 1 (14 = 1+3+7+3; {I,C,J} + {B,H,N} the two operator-triads)",
        "hurwitz": "division-algebra imaginary dims {1,3,7} (parallelizable spheres S^1,S^3,S^7)",
    },
    "discipline": "honest reconciliation; NARROWS the canonical stance rather than flattering it; the tantalizing field<->operator correspondence explicitly NOT asserted (named as a future target with its dof-strain stated); deep 'same 3?' left open; deterministic; bit-exact integer arithmetic",
}
RECORDS.append(META)

with OUT.open("w", encoding="utf-8") as fh:
    for rec in RECORDS:
        fh.write(json.dumps(rec, ensure_ascii=True) + "\n")

print("\nwrote", len(RECORDS), "records to", OUT.name)
print("VERDICT: the two k=3 families RECONCILE as READOUT (B/H/N interconversion) vs SUBSTRATE-CONTENT "
      "(Class-L spectral spine / Class-I cyclic / Hurwitz operator partition) -- two sides of the "
      "continuous<->discrete interconversion, NOT competing labels. The canonical k=3=B/H/N stance is "
      "REFINED (readout reading survives; member-labeling reading narrowed), not vindicated wholesale. "
      "Deep 'same 3?' LEFT OPEN -- value-level the threes already differ ({1,3,5} != {1,3,7}).")
