/* GENERATED by codegen/emit_tables_4d.py - DO NOT EDIT BY HAND */
#ifndef CS_FIBER_TABLES_4D_H
#define CS_FIBER_TABLES_4D_H

#include "cs_tables_4d.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Pawn antisymmetric fiber, factored form.
 *   A_anti = I (x) I (x) I (x) A_w_anti  (Kronecker identity)
 *   U^T A_anti U = I (x) I (x) I (x) (U_P8^T A_w_anti U_P8)
 * so the 4096x4096 DCT-basis matrix is block-diagonal over (x,y,z)
 * with this single 8x8 block on the w-axis. */
extern const double W_ANTI_DCT[8][8];

/* Per-piece diagonal deviation from grid spectrum, mode space.
 * Indexed [cs_piece_4d_t][k]. */
extern const double DIAG_DEV_4D[6][4096];

/* Per-(piece, square) fiber coordinates in the rank-3 cross-piece
 * SVD basis. Indexed [cs_fiber_piece_4d_t][square][direction].
 * Rook row is identically zero (see CS_FIBER_DROPPED_MASK). */
extern const float FIBER_LOCAL_4D[5][4096][3];

#ifdef __cplusplus
}
#endif

#endif /* CS_FIBER_TABLES_4D_H */
