/* GENERATED by codegen/emit_tables_4d.py - DO NOT EDIT BY HAND */
#ifndef CS_FIBER_TABLES_4D_H
#define CS_FIBER_TABLES_4D_H

#include "cs_tables_4d.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Pawn antisymmetric fibers, factored form (v1.1.1: per axis).
 *   A_w_anti = I (x) I    (x) I (x) A_w_anti_8   (Kronecker identity)
 *   A_y_anti = I (x) A_y_anti_8 (x) I (x) I
 * so each 4096x4096 DCT-basis matrix reduces to an 8x8 factor.
 *
 * The 8x8 blocks are numerically identical (both = U_P8^T @ A_anti @
 * U_P8 for the shared 0.5*(S-S^T) generator); they are emitted as
 * separate symbols so the two axis channels are structurally
 * distinct and readable in the encoder. */
extern const double W_ANTI_DCT[8][8];
extern const double Y_ANTI_DCT[8][8];

/* Per-piece diagonal deviation from grid spectrum, mode space.
 * Indexed [cs_piece_4d_t][k]. */
extern const double DIAG_DEV_4D[6][4096];

/* Per-(piece, square) fiber coordinates in the rank-3 cross-piece
 * SVD basis. Indexed [cs_fiber_piece_4d_t][square][direction].
 * Rook row is identically zero (see CS_FIBER_DROPPED_MASK). */
extern const float FIBER_LOCAL_4D[5][4096][3];

#ifdef __cplusplus
}
#endif

#endif /* CS_FIBER_TABLES_4D_H */
