/* GENERATED by codegen/emit_tables_4d.py - DO NOT EDIT BY HAND */
#ifndef CS_TABLES_4D_H
#define CS_TABLES_4D_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* 4D encoding dimensions (Z_8^4 lattice) */
#define CS_BOARD_SIDE_4D      8
#define CS_N_DIMS             4
#define CS_N_SQUARES_4D       4096
#define CS_N_CHANNELS_4D      10
#define CS_ENCODING_DIM_4D    40960

/* B_4 group order and orbit count on Z_8^4. */
#define CS_B4_ORDER           384
#define CS_N_ORBITS_4D        35

/* Fiber basis rank (cross-piece SVD of off-diag piece Laplacians) */
#define CS_N_SYM_FIBER_4D     3

/* Diag-dev row order: P=0, N=1, B=2, R=3, Q=4, K=5 (6 pieces). */
typedef enum {
    CS_PIECE_4D_P = 0,
    CS_PIECE_4D_N = 1,
    CS_PIECE_4D_B = 2,
    CS_PIECE_4D_R = 3,
    CS_PIECE_4D_Q = 4,
    CS_PIECE_4D_K = 5,
    CS_PIECE_4D_COUNT = 6
} cs_piece_4d_t;

/* Fiber-piece row order: N=0, B=1, R=2, Q=3, K=4 (5 pieces; no pawn). */
typedef enum {
    CS_FIBER_PIECE_4D_N = 0,
    CS_FIBER_PIECE_4D_B = 1,
    CS_FIBER_PIECE_4D_R = 2,
    CS_FIBER_PIECE_4D_Q = 3,
    CS_FIBER_PIECE_4D_K = 4,
    CS_FIBER_PIECE_4D_COUNT = 5
} cs_fiber_piece_4d_t;

/* P_8 eigenbasis (DCT-II factor) and P_8 Laplacian spectrum. */
extern const double P8_EVECS[8][8];
extern const double P8_EVALS[8];

/* std-4D coordinate residual masks: (I_4 - (1/4) J_4) applied
 * to centered coordinates, indexed [axis][square]. */
extern const double COORD_RESID[4][4096];

/* B_4 A_1 orbit partition, stored as CSR.
 *   ORBIT_OF[s]                  orbit index for square s
 *   ORBIT_MEMBERS[ORBIT_OFFSETS[o] .. ORBIT_OFFSETS[o+1])
 *                                squares in orbit o, ascending
 *   ORBIT_INV_SIZE[o]            1/|orbit_o|
 */
extern const uint16_t ORBIT_OF[4096];
extern const uint16_t ORBIT_MEMBERS[4096];
extern const uint16_t ORBIT_OFFSETS[36];
extern const double   ORBIT_INV_SIZE[35];

/* Nominal piece values (signed-magnitude; encoder flips sign for black). */
extern const double PIECE_VALUES_4D[6];

/* Bitmask (over cs_fiber_piece_4d_t) of pieces whose off-diagonal
 * fiber is structurally zero in the DCT basis and was dropped from
 * the rank-3 SVD. In Z_8^4 the rook Laplacian is a Kronecker sum of
 * four K_8's (exactly diagonal in the P_8-tensor basis), so its
 * off-diagonal vanishes and the SVD drops it. Any other value here
 * means the BLAS build flipped the zero-norm boundary; pin numpy /
 * scipy via codegen/requirements.txt and regenerate the tables. */
#define CS_FIBER_DROPPED_MASK 0x04
_Static_assert(CS_FIBER_DROPPED_MASK == 0x04,
               "rook must be the only dropped fiber piece");

/* Sparse binary adjacency nnz per piece (CSR, ascending indices). */
#define CS_FIBER_ADJ_NNZ_N 129024
#define CS_FIBER_ADJ_NNZ_B 215040
#define CS_FIBER_ADJ_NNZ_R 114688
#define CS_FIBER_ADJ_NNZ_Q 329728
#define CS_FIBER_ADJ_NNZ_K 230160

/* Piece-adjacency CSRs for fiber-sym channels 5-7.
 *   PIECE_ADJ_INDPTR_<pc>[s .. s+1]   target-index range for square s
 *   PIECE_ADJ_INDICES_<pc>[...]       target squares, ascending per row
 * Binary adjacency; no data[] array. 32-bit indices mirror scipy defaults. */
extern const int32_t PIECE_ADJ_INDPTR_N[4097];
extern const int32_t PIECE_ADJ_INDICES_N[CS_FIBER_ADJ_NNZ_N];
extern const int32_t PIECE_ADJ_INDPTR_B[4097];
extern const int32_t PIECE_ADJ_INDICES_B[CS_FIBER_ADJ_NNZ_B];
extern const int32_t PIECE_ADJ_INDPTR_R[4097];
extern const int32_t PIECE_ADJ_INDICES_R[CS_FIBER_ADJ_NNZ_R];
extern const int32_t PIECE_ADJ_INDPTR_Q[4097];
extern const int32_t PIECE_ADJ_INDICES_Q[CS_FIBER_ADJ_NNZ_Q];
extern const int32_t PIECE_ADJ_INDPTR_K[4097];
extern const int32_t PIECE_ADJ_INDICES_K[CS_FIBER_ADJ_NNZ_K];

#ifdef __cplusplus
}
#endif

#endif /* CS_TABLES_4D_H */
