/* GENERATED by codegen/emit_tables_4d.py - DO NOT EDIT BY HAND */
#ifndef CS_TABLES_4D_H
#define CS_TABLES_4D_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* 4D encoding dimensions (Z_8^4 lattice) */
#define CS_BOARD_SIDE_4D      8
#define CS_N_DIMS             4
#define CS_N_SQUARES_4D       4096
#define CS_N_CHANNELS_4D      10
#define CS_ENCODING_DIM_4D    40960

/* B_4 group order and orbit count on Z_8^4. */
#define CS_B4_ORDER           384
#define CS_N_ORBITS_4D        35

/* Fiber basis rank (cross-piece SVD of off-diag piece Laplacians) */
#define CS_N_SYM_FIBER_4D     3

/* Diag-dev row order: P=0, N=1, B=2, R=3, Q=4, K=5 (6 pieces). */
typedef enum {
    CS_PIECE_4D_P = 0,
    CS_PIECE_4D_N = 1,
    CS_PIECE_4D_B = 2,
    CS_PIECE_4D_R = 3,
    CS_PIECE_4D_Q = 4,
    CS_PIECE_4D_K = 5,
    CS_PIECE_4D_COUNT = 6
} cs_piece_4d_t;

/* Fiber-piece row order: N=0, B=1, R=2, Q=3, K=4 (5 pieces; no pawn). */
typedef enum {
    CS_FIBER_PIECE_4D_N = 0,
    CS_FIBER_PIECE_4D_B = 1,
    CS_FIBER_PIECE_4D_R = 2,
    CS_FIBER_PIECE_4D_Q = 3,
    CS_FIBER_PIECE_4D_K = 4,
    CS_FIBER_PIECE_4D_COUNT = 5
} cs_fiber_piece_4d_t;

/* P_8 eigenbasis (DCT-II factor) and P_8 Laplacian spectrum. */
extern const double P8_EVECS[8][8];
extern const double P8_EVALS[8];

/* std-4D coordinate residual masks: (I_4 - (1/4) J_4) applied
 * to centered coordinates, indexed [axis][square]. */
extern const double COORD_RESID[4][4096];

/* B_4 A_1 orbit partition, stored as CSR.
 *   ORBIT_OF[s]                  orbit index for square s
 *   ORBIT_MEMBERS[ORBIT_OFFSETS[o] .. ORBIT_OFFSETS[o+1])
 *                                squares in orbit o, ascending
 *   ORBIT_INV_SIZE[o]            1/|orbit_o|
 */
extern const uint16_t ORBIT_OF[4096];
extern const uint16_t ORBIT_MEMBERS[4096];
extern const uint16_t ORBIT_OFFSETS[36];
extern const double   ORBIT_INV_SIZE[35];

/* Nominal piece values (signed-magnitude; encoder flips sign for black). */
extern const double PIECE_VALUES_4D[6];

#ifdef __cplusplus
}
#endif

#endif /* CS_TABLES_4D_H */
