/* GENERATED by codegen/emit_tables.py — DO NOT EDIT BY HAND */
#ifndef CS_TABLES_H
#define CS_TABLES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Encoding dimensions */
#define CS_BOARD_DIM      64
#define CS_NUM_IRREPS     5
#define CS_NUM_SYM_FIBER  3
#define CS_NUM_CHANNELS   10
#define CS_ENCODING_DIM   640

/* Coprime generators for temporal/spatial binding (all coprime to 640) */
#define CS_COPRIME_ROW    67
#define CS_COPRIME_COL    7
#define CS_COPRIME_TIME   131

/* D4 permutations, character table */
extern const uint8_t D4_PERMS[8][64];
extern const int8_t  CHARS[5][8];

/* Piece-value tables (P=0, N=1, B=2, R=3, Q=4, K=5) */
extern const double SPECTRAL_VALS[6];
extern const double TRAD_VALS[6];

#ifdef __cplusplus
}
#endif

#endif /* CS_TABLES_H */
