/*
 * AUTO-GENERATED by emit_c_tables.py from
 * ../../../research/{bodies,laplacian,bip_instrument}.py.
 *
 * DO NOT EDIT. To regenerate:
 *
 *     cd ../codegen && python emit_c_tables.py
 *
 * Schema and rationale: ../include/ephemerides_spectral.h
 */

#include <stdint.h>
#include <stddef.h>

#include "ephemerides_spectral.h"

_Static_assert(ES_N_BODIES == 26, "body count mismatch — re-run emit_c_tables.py and rebuild");

const es_body_t es_bodies[ES_N_BODIES] = {
    { .name = "callisto", .period_days = 16.689, .mass_earth = 0.018, .category = ES_CATEGORY_MOON },
    { .name = "ceres", .period_days = 1681.63, .mass_earth = 0.00015, .category = ES_CATEGORY_ASTEROID },
    { .name = "deimos", .period_days = 1.263, .mass_earth = 2.4e-10, .category = ES_CATEGORY_MOON },
    { .name = "earth", .period_days = 365.256, .mass_earth = 1.0, .category = ES_CATEGORY_PLANET },
    { .name = "enceladus", .period_days = 1.37, .mass_earth = 1.8e-05, .category = ES_CATEGORY_MOON },
    { .name = "europa", .period_days = 3.551, .mass_earth = 0.008, .category = ES_CATEGORY_MOON },
    { .name = "ganymede", .period_days = 7.155, .mass_earth = 0.025, .category = ES_CATEGORY_MOON },
    { .name = "hygiea", .period_days = 2031.0, .mass_earth = 1.4e-05, .category = ES_CATEGORY_ASTEROID },
    { .name = "io", .period_days = 1.769, .mass_earth = 0.015, .category = ES_CATEGORY_MOON },
    { .name = "jupiter", .period_days = 4332.59, .mass_earth = 317.8, .category = ES_CATEGORY_PLANET },
    { .name = "mars", .period_days = 686.98, .mass_earth = 0.107, .category = ES_CATEGORY_PLANET },
    { .name = "mercury", .period_days = 87.969, .mass_earth = 0.0553, .category = ES_CATEGORY_PLANET },
    { .name = "moon", .period_days = 27.321, .mass_earth = 0.0123, .category = ES_CATEGORY_MOON },
    { .name = "neptune", .period_days = 60182.0, .mass_earth = 17.15, .category = ES_CATEGORY_PLANET },
    { .name = "pallas", .period_days = 1686.0, .mass_earth = 3.4e-05, .category = ES_CATEGORY_ASTEROID },
    { .name = "phobos", .period_days = 0.3189, .mass_earth = 1.7e-09, .category = ES_CATEGORY_MOON },
    { .name = "pluto", .period_days = 90560.0, .mass_earth = 0.00218, .category = ES_CATEGORY_PLANET },
    { .name = "rhea", .period_days = 4.518, .mass_earth = 0.00038, .category = ES_CATEGORY_MOON },
    { .name = "saturn", .period_days = 10759.22, .mass_earth = 95.16, .category = ES_CATEGORY_PLANET },
    { .name = "sun", .period_days = 0.0, .mass_earth = 333000.0, .category = ES_CATEGORY_STAR },
    { .name = "titan", .period_days = 15.945, .mass_earth = 0.0225, .category = ES_CATEGORY_MOON },
    { .name = "titania", .period_days = 8.706, .mass_earth = 0.00057, .category = ES_CATEGORY_MOON },
    { .name = "triton", .period_days = 5.877, .mass_earth = 0.00359, .category = ES_CATEGORY_MOON },
    { .name = "uranus", .period_days = 30688.5, .mass_earth = 14.54, .category = ES_CATEGORY_PLANET },
    { .name = "venus", .period_days = 224.701, .mass_earth = 0.815, .category = ES_CATEGORY_PLANET },
    { .name = "vesta", .period_days = 1325.75, .mass_earth = 4.3e-05, .category = ES_CATEGORY_ASTEROID },
};
