/*
 * AUTO-GENERATED by emit_c_tables.py from
 * ../../../research/{bodies,laplacian,bip_instrument}.py.
 *
 * DO NOT EDIT. To regenerate:
 *
 *     cd ../codegen && python emit_c_tables.py
 *
 * Schema and rationale: ../include/ephemerides_spectral.h
 */

#include <stdint.h>
#include <stddef.h>

#include "ephemerides_spectral.h"

/* Diagonal frequencies (residues/day, signed int64). */
const int64_t es_omega_diag[ES_N_BODIES] = {
    14400078106, /* adrastea */
    8621332623, /* amalthea */
    1704095574, /* ariel */
    257352901, /* callisto */
    2275115151, /* calypso */
    2554049, /* ceres */
    672430349, /* charon */
    3402115979, /* deimos */
    1569273177, /* dione */
    3134514191, /* enceladus */
    6186618790, /* epimetheus */
    1209447588, /* europa */
    600312461, /* ganymede */
    1569273177, /* helene */
    17141048, /* himalia */
    2114706, /* hygiea */
    201863335, /* hyperion */
    54146320, /* iapetus */
    2427717700, /* io */
    6183528073, /* janus */
    991317, /* jupiter */
    157200077, /* luna */
    6251957, /* mars */
    48823505, /* mercury */
    14570076993, /* metis */
    4557371834, /* mimas */
    3038578243, /* miranda */
    71366, /* neptune */
    11925953, /* nereid */
    319014412, /* oberon */
    2547430, /* pallas */
    5775678, /* pasiphae */
    13467637260, /* phobos */
    7801023, /* phoebe */
    47427, /* pluto */
    1569273177, /* polydeuces */
    3826882200, /* proteus */
    950590033, /* rhea */
    399189, /* saturn */
    5659464, /* sinope */
    0, /* sun */
    2275115151, /* telesto */
    11758775, /* terra */
    2275115151, /* tethys */
    6367499112, /* thebe */
    269354274, /* titan */
    493341595, /* titania */
    730827633, /* triton */
    1036386566, /* umbriel */
    139954, /* uranus */
    19114161, /* venus */
    3239651, /* vesta */
};

/* Initial phase residues at REFERENCE_JD = J2000.0 (uint32). */
const uint32_t es_initial_phases[ES_N_BODIES] = {
    2537566963u, /* adrastea */
    614115372u, /* amalthea */
    3835590588u, /* ariel */
    954923981u, /* callisto */
    3857626825u, /* calypso */
    3597717137u, /* ceres */
    3206571533u, /* charon */
    474935390u, /* deimos */
    4163626977u, /* dione */
    1725934353u, /* enceladus */
    3594951378u, /* epimetheus */
    2533952976u, /* europa */
    2622888258u, /* ganymede */
    4163626977u, /* helene */
    90833842u, /* himalia */
    270682330u, /* hygiea */
    2327281680u, /* hyperion */
    1880014365u, /* iapetus */
    213641777u, /* io */
    2884306668u, /* janus */
    432980277u, /* jupiter */
    2664333966u, /* luna */
    4288313135u, /* mars */
    3027660005u, /* mercury */
    1959161098u, /* metis */
    625840904u, /* mimas */
    2840715143u, /* miranda */
    3626000180u, /* neptune */
    1168202796u, /* nereid */
    3296855918u, /* oberon */
    257290448u, /* pallas */
    3121869374u, /* pasiphae */
    1374519043u, /* phobos */
    3364117205u, /* phoebe */
    2989119291u, /* pluto */
    4163626977u, /* polydeuces */
    1979799237u, /* proteus */
    3643334025u, /* rhea */
    545464656u, /* saturn */
    1686520298u, /* sinope */
    0u, /* sun */
    3857626825u, /* telesto */
    1197504024u, /* terra */
    3857626825u, /* tethys */
    2233542473u, /* thebe */
    81596567u, /* titan */
    3509176257u, /* titania */
    2631119796u, /* triton */
    269771423u, /* umbriel */
    3775006485u, /* uranus */
    2178457071u, /* venus */
    755648592u, /* vesta */
};

/* Phase 9 off-diagonal coupling table. */
const es_coupling_t es_couplings[] = {
    { .idx_a = 20, .idx_b = 38, .n_a = 5, .m_b = 2, .weight_rpd = -1188733LL }, /* Jupiter-Saturn 5:2 (Great Conjunction) */
    { .idx_a = 27, .idx_b = 34, .n_a = 3, .m_b = 2, .weight_rpd = -1322LL }, /* Neptune-Pluto 3:2 (orbital resonance) */
    { .idx_a = 18, .idx_b = 11, .n_a = 2, .m_b = 1, .weight_rpd = -7488LL }, /* Io-Europa 2:1 (Laplace pair 1) */
    { .idx_a = 11, .idx_b = 12, .n_a = 2, .m_b = 1, .weight_rpd = -9667LL }, /* Europa-Ganymede 2:1 (Laplace pair 2) */
    { .idx_a = 9, .idx_b = 8, .n_a = 2, .m_b = 1, .weight_rpd = -1LL }, /* Enceladus-Dione 2:1 (powers Enceladus tidal heating) */
    { .idx_a = 45, .idx_b = 16, .n_a = 4, .m_b = 3, .weight_rpd = -10LL }, /* Titan-Hyperion 4:3 (Hyperion chaotic rotation source) */
};

const size_t es_n_couplings = 6;
