"""Octonion algebra: the Cayley-Dickson-from-H multiplication table + L/R binders.

The foundational layer of the ``srmech.physics.qm`` so(8)/Spin(8) triality engine
(v0.5.0rc17). Octonions are the 8-dimensional real normed division algebra
``O`` obtained by doubling the quaternions ``H``; their multiplication
fixes a sign convention that, once chosen, IS the provenance of every
downstream object (the 28 so(8) generators, the order-3 triality
automorphism ``tau``, the ``Fix(tau) = g2`` keystone).

**0.9.0rc111 (issue #1234 Item 1c, re-raise of #863): the ODFT twiddle
family** — :func:`octonion_exp` / :func:`octonion_twiddle` /
:func:`octonion_exp_series_truncate`, the dim-8 mirror of the rc109
``srmech.physics.qm.quaternion`` foundation (same exactness convention, same same-rc C
peers ``srmech_octonion_exp`` / ``srmech_octonion_twiddle``). The twiddle
``exp(μθ) = cos θ·1 + sin θ·μ̂`` for a UNIT pure imaginary ``μ̂`` (``μ̂² =
−1``) lives in the commutative subalgebra ``ℝ[μ̂] ≅ ℂ`` — which is why the
one-sided ODFT inverts. **Alternativity (the Artin boundary, F378 made
precise):** ``𝕆`` is alternative — ``a(ax) = (aa)x`` and ``(xa)a = x(aa)``
— and by Artin's theorem every subalgebra generated by TWO elements is
associative. So everything the ONE-SIDED transform composes (twiddles on a
single axis ``μ`` against one sample ``x``) lives in the two-generator
subalgebra ``⟨μ, x⟩`` and associates EXACTLY; non-associativity bites only
at ≥3 independent generators (the two-sided form with distinct axes,
or a twiddle associated through a product of two samples) — verified
empirically in the rc111 test suite over the fixed table.

Per ``[[feedback_science_is_ssot_not_project]]``: each operation cites the
canonical octonion literature, **not** a project instantiation.

FIXED CONVENTION (Cayley-Dickson doubling ``R -> C -> H -> O``):

- doubling rule:  ``(a, b) * (c, d) = (a*c - conj(d)*b, d*a + b*conj(c))``
- conjugation:    ``conj((a, b)) = (conj(a), -b)``; ``conj(scalar) = scalar``

The 480 sign-ambiguous conventions collapse to ONE the moment these two
generative rules are fixed (no free per-pair sign choices remain). That
determinism is what :func:`octonion_table_attestation` content-addresses
(``response_sha256`` over the int8 table bytes): *same convention -> same
``tau`` reproducibly*. The resulting unordered Fano lines are
``{1,2,3} {1,4,5} {1,6,7} {2,4,6} {2,5,7} {3,4,7} {3,5,6}`` — bit-for-bit
identical to Baez (2002) §2.

A-N placement (per ``[[feedback_no_privileged_primitive_classes]]``):

- ``octonion_mult_table`` / ``octonion_table_attestation`` — **Class A**
  (content-addressing: the convention IS the provenance; the attestation is
  a SHA-256 over the table bytes).
- ``octonion_left_mult`` / ``octonion_right_mult`` — **Class M** (Clifford /
  HDC binding: ``L_a`` and ``R_a`` bind the 8-dim octonion space; the 7+7
  imaginary-unit binders are the ``14`` non-``g2`` directions of the ``28``).
- ``octonion_conjugate`` — **Class C** (chirality / orientation: conjugation
  flips the imaginary-axis sign).
- ``octonion_norm`` — **Class K + Class C** (the Class K pin-slot magnitude
  via ``srmech.cascade.magnitude`` composed with Class C sign-handling;
  **never** Python ``abs()`` per
  ``[[feedback_sign_handling_is_class_k_pin_slot_not_alu_abs]]``).
- ``octonion_exp`` / ``octonion_twiddle`` — **Class N** (Q61 cos/sin
  cascade) ∘ **Class C** (the ±μ orientation) ∘ **Class I** (the cyclic
  ``jk mod N`` twiddle index reduction) ∘ **Class M** (the axis scaling).
- ``octonion_exp_series_truncate`` — **Class N** (the exact rational
  series-truncate pair; the ``bignum_reference`` oracle tier).

Canonical SSoT:

- Baez, J.C. (2002) *The Octonions*, Bull. Amer. Math. Soc. 39, 145-205
  (arXiv:math/0105155) — Cayley-Dickson construction, the Fano plane,
  ``G2 = Aut(O)`` with Lie algebra ``Der(O)``, Spin(8) triality.
- Schafer, R.D. (1966) *An Introduction to Nonassociative Algebras*,
  Academic Press — the derivation ``D_{a,b}`` of a composition algebra.
- Boyle, L. (2020) *The Standard Model, The Exceptional Jordan Algebra, and
  Triality* (arXiv:2006.16265) — the SM-physics context (three generations
  related to SO(8) triality).
"""

from __future__ import annotations

import ctypes
import functools
from srmech.math.rational import sqrt as _rsqrt  # §22: scalar root via Class-N
from typing import List, Sequence, Tuple

from srmech import _native  # rc122: numpy-free native loop-op dispatch
from srmech.cascade import cd_conjugate as _cd_conjugate
from srmech.cascade import cd_norm_sq as _cd_norm_sq
from srmech.cascade import left_mult_matrix as _left_mult_matrix
from srmech.cascade import magnitude as _magnitude
from srmech.cascade import right_mult_matrix as _right_mult_matrix
# rc465 (`#T1188`): the exact-operand ADMISSION predicate is IMPORTED, not
# re-derived. It has exactly ONE definition in this tree — rc463 wrote it for
# einsum — and a second hand-rolled copy of a load-bearing type test is how two
# surfaces come to disagree about what "exact" means.
from srmech.cascade.matrix_cascades import _exact_leaf
from srmech.math.q import Q  # rc465: the exact-ℚ scalar carrier
from srmech.math.qmat import QMat  # rc465: the exact-ℚ 8×8 L_a / R_a carrier
from srmech.amsc.format import sha256_bytes as _sha256_bytes
from srmech.math.mat import Mat  # rc122: numpy-free 2-D carrier for L_a / R_a

# rc111 (the ODFT twiddle family): the Class-N Q61 trig cascade + the exact
# series-truncate tier — the same imports the rc109 qm.quaternion twiddle uses.
from srmech.math import rational as _rational
from srmech.math.rational import atan as _ratan
from srmech.math.rational import cos as _rcos
from srmech.math.rational import cos_series_truncate as _cos_series
from srmech.math.rational import sin as _rsin
from srmech.math.rational import sin_series_truncate as _sin_series

#: Octonion dimension (the real normed division algebra ``O``).
_DIM = 8

#: ctypes pointer alias for the native dim-8 loop-op marshalling (numpy-free).
_DBLP = ctypes.POINTER(ctypes.c_double)

#: The two generative rules that fix THE convention (their bytes are the
#: ``parser_rule_hash`` provenance — change a rule and the whole table /
#: ``tau`` change, which the content-addressed hash detects).
_DOUBLING_RULE = b"(a,b)*(c,d)=(a*c - conj(d)*b, d*a + b*conj(c))"
_CONJ_RULE = b"conj((a,b))=(conj(a),-b); conj(scalar)=scalar"

#: A FIXED ISO timestamp for the self-attestation. Deterministic on
#: purpose (NOT ``datetime.now()``) so the MCP surface is reproducible: the
#: attestation of a GENERATED constant must not change between calls.
_RETRIEVED_AT = "2026-05-29T00:00:00Z"

#: The 7 unordered Fano lines of the fixed convention (Baez 2002 §2). The
#: oriented ``+1`` structure constants ``e_i e_j = +e_k`` close along these.
_FANO_LINES: Tuple[Tuple[int, int, int], ...] = (
    (1, 2, 3), (1, 4, 5), (1, 6, 7),
    (2, 4, 6), (2, 5, 7),
    (3, 4, 7), (3, 5, 6),
)

#: Cascade-π at the float64 boundary (rc111) — the SAME Class-N derivation the
#: rc109 quaternion module uses (``4·atan(1)`` via the Q61 atan cascade,
#: projected once at import; the ×4 is an exact power of two). NO ``math.pi``.
_PI = 4.0 * float(_ratan(1.0))

#: 1/√3 and 1/√7 via the Class-N rational sqrt cascade (axis unit norms).
_S3 = 1.0 / float(_rsqrt(3.0))
_S7 = 1.0 / float(_rsqrt(7.0))


def _e8(axis: int) -> Tuple[float, ...]:
    """The unit basis axis ``e_axis`` as an 8-tuple (exact floats)."""
    return tuple(1.0 if i == axis else 0.0 for i in range(_DIM))


#: Named unit pure-imaginary octonion axes (``μ̂² = −1``). ``'i'``/``'j'``/
#: ``'k'`` alias ``'e1'``/``'e2'``/``'e3'`` (the ℍ ⊂ 𝕆 rung — the SAME axes
#: the quaternion twiddle names); ``'e4'..'e7'`` are the extra octonion axes;
#: ``'ijk'`` is the quaternion body diagonal ``(e1+e2+e3)/√3``; ``'diagonal'``
#: is the equal-weight octonion axis ``(Σ_{a=1..7} e_a)/√7`` (the coupling
#: axis, F436).
_MU_AXES = {
    "i": _e8(1), "j": _e8(2), "k": _e8(3),
    "e1": _e8(1), "e2": _e8(2), "e3": _e8(3), "e4": _e8(4),
    "e5": _e8(5), "e6": _e8(6), "e7": _e8(7),
    "ijk": (0.0, _S3, _S3, _S3, 0.0, 0.0, 0.0, 0.0),
    "diagonal": (0.0, _S7, _S7, _S7, _S7, _S7, _S7, _S7),
}

#: The native uint32 twiddle-index bound (documented parity contract: the
#: pure path enforces the same ceiling so native == pure everywhere).
_TWIDDLE_N_MAX = 2 ** 32

# (The twiddle-family ctypes marshalling reuses the `_DBLP` pointer alias
# defined above for the loop-op dispatch.)


@functools.lru_cache(maxsize=1)
def _build_mult_table() -> Tuple[Tuple[Tuple[int, ...], ...], ...]:
    """Generate the ``(8, 8, 8)`` int8 structure-constant tensor (cached).

    rc10: built from the Cayley-Dickson basis cocycle ``e_i·e_j = sign·e_{i⊕j}``
    via :func:`srmech.cascade.cd_basis_product` — the C primitive
    ``srmech_cd_basis_product`` when native is present, its pure-Python loop
    otherwise. Same fixed convention as the module docstring's generative rules
    (``_DOUBLING_RULE`` / ``_CONJ_RULE``); the int8 bytes are **identical** to the
    prior numpy build, so the content-address in
    :func:`octonion_table_attestation` (a SHA-256 over the table) is unchanged.

    rc122 (numpy-free): the tensor is a nested tuple of ints in ``{-1, 0, +1}``
    (``Mat`` is 2-D only, so the 8×8×8 rank-3 tensor stays nested Python — the
    same precedent as ``gauge``'s structure constants). Built exactly once and
    memoised as an IMMUTABLE nested tuple; :func:`octonion_mult_table` hands
    callers a fresh mutable nested-list COPY so the cache can never be mutated.
    """
    from srmech.cascade import cd_basis_product as _cd_basis_product
    table = [[[0] * _DIM for _ in range(_DIM)] for _ in range(_DIM)]
    for i in range(_DIM):
        for j in range(_DIM):
            idx, sign = _cd_basis_product(_DIM, i, j)
            table[i][j][idx] = int(sign)
    return tuple(tuple(tuple(row) for row in plane) for plane in table)


def octonion_mult_table() -> List[List[List[int]]]:
    """The ``(8, 8, 8)`` int8 structure-constant tensor ``C``.

    ``e_i * e_j = sum_k C[i][j][k] e_k`` under the fixed Cayley-Dickson-from-H
    convention (see module docstring). ``e_0`` is the identity;
    ``e_1^2 = ... = e_7^2 = -e_0``; the off-diagonal imaginary products
    anticommute. Built from the Cayley-Dickson basis cocycle
    (:func:`srmech.cascade.cd_basis_product`; the native
    ``srmech_cd_basis_product`` when present). The generation is memoised
    (:func:`_build_mult_table`); each call returns a fresh mutable copy (two
    calls are entry-identical but independent).

    Class A (content-addressing): the table is the MPR-attested constant
    that :func:`octonion_table_attestation` content-addresses.

    rc122 (numpy-free): returns a nested ``list`` (``Mat`` is 2-D only — a
    rank-3 tensor stays nested Python); index it ``C[i][j][k]`` (NOT ``C[i, j, k]``).

    Canonical SSoT: Baez (2002) §2 (the Fano-plane multiplication table).

    Returns:
        ``8×8×8`` nested ``list[list[list[int]]]``; ``C[i][j][k]`` is the ``e_k``
        coefficient of ``e_i * e_j`` (entries in ``{-1, 0, +1}``).
    """
    return [[list(row) for row in plane] for plane in _build_mult_table()]


def _table_int8_bytes() -> bytes:
    """C-order int8 serialization of the structure-constant tensor.

    Bit-identical to the prior numpy ``int8`` ``tobytes()`` serialization: 512
    bytes, one signed two's-complement byte per entry in C (row-major i, j, k)
    order (``-1 -> 0xFF``, ``0 -> 0x00``, ``+1 -> 0x01`` via ``v & 0xFF``). This keeps
    the :func:`octonion_table_attestation` ``response_sha256`` unchanged
    (Class A content-address) across the rc122 numpy-free flip.
    """
    table = _build_mult_table()
    out = bytearray(_DIM * _DIM * _DIM)
    pos = 0
    for i in range(_DIM):
        for j in range(_DIM):
            row = table[i][j]
            for k in range(_DIM):
                out[pos] = row[k] & 0xFF  # two's-complement signed byte; no abs()
                pos += 1
    return bytes(out)


def octonion_table_attestation() -> dict:
    """MPR v1 self-attestation dict for the structure-constant table.

    A self-attestation for a GENERATED constant (NOT a fetched datum): the
    convention IS the provenance, so ``response_sha256`` content-addresses
    the table's int8 bytes via :func:`srmech.amsc.format.sha256_bytes`
    (Class A; **no** new ``hashlib.sha256`` per the C-library discipline).
    Returned as a plain MPR-shaped ``dict`` (NOT run through the strict
    ``format.validate_mpr_record`` — that validator targets fetched data
    with on-disk TOML descriptors; a generated-constant self-attestation
    has no such descriptor file). ``retrieved_at`` is a FIXED ISO string so
    the MCP surface is reproducible.

    Class A (content-addressing): the attestation IS a SHA-256 fingerprint.

    Canonical SSoT: Baez (2002), Bull. Amer. Math. Soc. 39, 145-205
    (arXiv:math/0105155).

    Returns:
        A plain ``dict`` with ``mpr_version``, ``data``, ``data_schema_id``,
        ``attestation`` (incl. ``response_sha256`` = ``sha256_bytes`` of the
        table), and ``rendering`` keys.
    """
    response_sha256 = _sha256_bytes(_table_int8_bytes())
    parser_rule_hash = _sha256_bytes(_DOUBLING_RULE + b"\n" + _CONJ_RULE)
    descriptor_hash = _sha256_bytes(
        b"srmech/physics/qm/octonion.py::cayley_dickson_from_H"
    )
    return {
        "mpr_version": "1.0",
        "data": {
            "convention": "cayley_dickson_from_H",
            "basis_order": "e0..e7",
            "fano_triples": [list(line) for line in _FANO_LINES],
        },
        "data_schema_id": "srmech://schema/octonion_structure_constants",
        "attestation": {
            # Baez is OA on arXiv; a paywalled-only DOI is rejected per
            # [[feedback_paywalled_doi_cannot_be_attested]] — so no source_doi.
            "source_doi": None,
            "source_url": "https://arxiv.org/abs/math/0105155",
            "license": "CC0",
            "retrieved_at": _RETRIEVED_AT,
            "response_sha256": response_sha256,
            "parser_version": "srmech 0.5.0",
            "parser_rule_hash": parser_rule_hash,
            "collector_descriptor_path": "srmech/physics/qm/octonion.py",
            "collector_descriptor_hash": descriptor_hash,
        },
        "rendering": {
            "name": "Octonion multiplication table (Cayley-Dickson from H)",
            "purpose": "Fixed sign convention for the so(8)/triality engine",
            "cite_as": (
                "Baez, J.C. (2002) The Octonions, Bull. Amer. Math. Soc. 39, "
                "145-205 (arXiv:math/0105155)"
            ),
        },
    }


def _as_octonion(v: Sequence[float], op: str) -> List[float]:
    """Coerce ``v`` to a plain ``list[float]`` of length 8.

    Accepts any 1-D sequence (list / tuple / ndarray); a 2-D / wrong-length
    input raises the same ``ValueError`` the prior numpy ``asarray(...).shape``
    check produced. The ``Mat`` refusal lives one level up, in
    :func:`_operand_leaves`, which is the single admission point every op on
    this surface passes through — see the ⚠️ there for why the guard cannot sit
    here."""
    try:
        out = [float(c) for c in v]
    except TypeError as exc:  # 0-D scalar / non-iterable
        raise ValueError(f"{op}: a must be an 8-vector; got {v!r}") from exc
    if len(out) != _DIM:
        raise ValueError(f"{op}: a must be an 8-vector; got length {len(out)}")
    return out


def _operand_leaves(v, op: str, noun: str = "a"):
    """Materialise a 1-D operand ONCE so the exactness read cannot consume it,
    and REFUSE a ``Mat`` here — this is the single admission point.

    ⚠️ **The refusal moved here in rc465-fix (`#T1188`), and the reason is that
    a pass-through IS an admission.** As first shipped this read
    ``if isinstance(v, Mat): return v`` and left the rejection to
    :func:`_as_octonion` further down. Behaviourally that raised the same
    ``ValueError`` — but ``tests/coercion_boundary.py`` derives what an op
    ACCEPTS from its ``isinstance`` guards, and its documented rule is that a
    guard whose body does not raise is an ACCEPTANCE. So the shipped registry
    measured ``octonion_left_mult`` / ``_right_mult`` / ``_conjugate`` /
    ``_norm`` (and, through the shared helper,
    ``srmech.physics.qm.triality.triality_apply``) as ACCEPTING ``Mat`` while
    declaring only ``HV``, and ``tests/test_declared_type_honesty_rc363.py``
    went red at ``CEIL_WIDE_UNDECLARED_OPS = 0``. The instrument was right
    about the source; the source was wrong about the boundary.

    Raising here makes the guard a REFUSAL in both readings, and it fixes a
    second defect in the same move: ``triality_apply`` does not call
    :func:`_as_octonion` at all, so a ``Mat`` operand reached its
    ``[float(v) for v in leaves]`` and escaped as a bare ``TypeError``
    (measured: ``float() argument must be a string or a real number, not
    'list'``) against a docstring that documents ``ValueError``.
    """
    if isinstance(v, Mat):
        raise ValueError(
            f"{op}: {noun} must be an 8-vector; got a Mat {v.shape}")
    try:
        return list(v)
    except TypeError:
        return v


def _exact_component(c):
    """The EXACT-ℚ reading of ONE operand component, or ``None``.

    rc465-fix (`#T1188`) — :func:`~srmech.cascade.matrix_cascades._exact_leaf`
    plus the ``(num, den)`` PAIR, because the pair is what this surface's own
    shipped prose, its declared wire type ``HV | Sequence[int | Q]`` and its MCP
    encoding hint all promise, and it was the one spelling of the three that
    did not work. Measured before the fix:
    ``octonion_conjugate([(7, 3), 0, 0, 0, 0, 0, 0, 0])`` raised
    ``a must be an 8-vector`` — the operand IS an 8-vector; the rejected thing
    was the component type, so the message named the wrong contract too.

    ``(num, den)`` means a 2-element integer pair everywhere else in this
    package (:func:`srmech.math.q.to_q`, ``QMat.from_rows``,
    ``srmech/apokatastasis/modular_forms_ring.py`` spells it out), so this
    reading is the package's, not a new one. rc463's shared ``_exact_leaf`` is
    deliberately NOT changed: its contract is the einsum admission gate and a
    2-tuple there is a SHAPE, not a scalar.
    """
    if isinstance(c, (tuple, list)) and len(c) == 2             and isinstance(c[0], int) and not isinstance(c[0], bool)             and isinstance(c[1], int) and not isinstance(c[1], bool)             and c[1] != 0:
        return Q(int(c[0]), int(c[1]))
    return _exact_leaf(c)


def _exact_octonion(v):
    """The EXACT-ℚ reading of an 8-vector operand, or ``None``.

    rc465 (`#T1188`) — **the whole-operand admission gate**, over the imported
    rc463 scalar predicate :func:`~srmech.cascade.matrix_cascades._exact_leaf`
    (a TYPE test: ``2.0`` is a float the caller ELECTED and stays on the float
    carrier even though it happens to be integral). ONE float component
    anywhere sends the entire call down the float route, because mixing
    carriers mid-computation is the defect rather than the cure — the rc463
    ``_exact_nd`` rule, applied at dim 8.

    ⚠️ **The length check is NOT here, and that is deliberate.** A wrong-length
    operand returns ``None`` and falls through to :func:`_as_octonion`, which
    raises the documented ``ValueError`` — so the arity contract is
    CARRIER-INDEPENDENT and an 8-vector rule cannot be quietly relaxed for
    exact callers. ``tests/test_declared_raises_execution_rc434.py`` drives the
    float half of that and ``tests/test_octonion_exact_carrier_rc465.py`` the
    exact half.
    """
    if not isinstance(v, list) or len(v) != _DIM:
        return None
    out = []
    for c in v:
        q = _exact_component(c)
        if q is None:
            return None
        out.append(q)
    return out


def _loop_op_native_ready(symbol: str) -> bool:
    """True iff the native lib is loaded AND exports ``symbol``."""
    return bool(
        _native.HAS_NATIVE and _native.LIB is not None
        and hasattr(_native.LIB, symbol)
    )


def _try_native_loop_op(symbol: str, a: List[float]) -> List[List[float]]:
    """Dispatch a dim-8 loop operator (``srmech_loop_{left,right}_op_f64``) to the
    C peer, returning the ``8x8`` result as a nested ``list`` — or ``None`` to
    signal the numpy-free table fallback. Marshals through ctypes only (no numpy):
    the native flat output is row-major ``out[k*8 + j]`` = ``M[k][j]``."""
    if not _loop_op_native_ready(symbol):
        return None
    Arr = ctypes.c_double * _DIM
    MatC = ctypes.c_double * (_DIM * _DIM)
    c_a = Arr(*(float(v) for v in a))
    c_out = MatC()
    rc = getattr(_native.LIB, symbol)(
        ctypes.cast(c_a, _DBLP), ctypes.c_size_t(_DIM), ctypes.cast(c_out, _DBLP)
    )
    if rc != _native.SRMECH_OK:
        return None
    return [[float(c_out[k * _DIM + j]) for j in range(_DIM)] for k in range(_DIM)]


def octonion_left_mult(a: Sequence[int | Q | Tuple[int, int] | float]) -> Mat | QMat:
    """Left-multiplication matrix ``L_a`` (``x -> a * x``) as an ``8x8`` real ``Mat``.

    Column ``j`` is ``a * e_j``; ``L_a[k, j] = sum_i a_i C[i, j, k]``. For an
    imaginary unit ``e_i`` (``i >= 1``) the matrix ``L_{e_i}`` is already
    antisymmetric, so it sits directly in ``so(8)`` (one of the 7 L-type
    coset directions of the ``28``).

    Class M (Clifford / HDC binding).

    Canonical SSoT: Baez (2002) §2.3-2.4 (left/right multiplication and the
    bimodule structure underlying triality).

    **THE CARRIER IS THE OPERAND'S, NOT THE OP'S** (rc465, `#T1188`). An operand
    whose every component is exact (``int`` / ``Q`` / a
    ``numerator``-``denominator`` pair) returns an exact-ℚ ``QMat``, computed
    through :func:`srmech.cascade.left_mult_matrix` — the C-composed
    ``srmech_cd_mult`` / ``srmech_cd_qbasis`` route. **Float is the caller's own
    request**: one float component anywhere sends the whole call down the f64
    route below, and ``QMat.to_mat()`` projects an exact result on demand. There
    is no ``exact=`` keyword, exactly as there is none on ``einsum`` / ``kron``
    — the operand already says which carrier was asked for.

    ⚠️ **Through rc464 this rounded silently.** It coerced with
    ``[float(c) for c in v]`` at the entry, before any arithmetic, so
    ``octonion_left_mult([2**53+1, 0, …])[0, 0]`` returned
    ``9007199254740992.0`` — off by one, with no exception, no warning, no
    status and no accuracy statement, while
    :func:`srmech.cascade.left_mult_matrix` computed the same object exactly one
    import away. It escaped rc463's silent-demotion gate on exactly ONE
    conjunct — a signature-declared ``Sequence[float]`` — which is R2
    shielding: a type annotation standing in for an accuracy contract, on the
    rung rc463's own honesty ladder rates "WEAK, nothing enforces it".

    **The two routes are the SAME matrix**, and that is measured rather than
    asserted: ``tests/test_octonion_exact_carrier_rc465.py`` drives the 8 basis
    vectors and 12 random integer 8-vectors through this module's table and
    through ``cascade.left_mult_matrix`` — 0 mismatches. That is also the first
    execution of the convention claim below, which had been prose since rc122
    and is now load-bearing.

    rc122 (numpy-free): the FLOAT route dispatches to the C-backed
    ``srmech_loop_left_op_f64`` (native when present; bit-identical numpy-free
    table fallback otherwise) and returns a real ``Mat``, **accurate to
    round-off** — every component is truncated to a 53-bit significand on entry.
    ``L_a[k][j] = sum_i a_i C[i][j][k]`` is bit-identical to the per-basis binds
    ``loop_left_op`` column-stacks (same Cayley-Dickson-from-H convention).

    Args:
        a: An 8-vector octonion (components ``(a_0, ..., a_7)``); exact
            (``int`` / ``Q`` / ``(num, den)``) or ``float``.

    Returns:
        ``8x8`` exact-ℚ ``QMat`` ``L_a`` for an exact operand; ``8x8`` real
        ``Mat`` for a float one.

    Raises:
        ValueError: if ``a`` is not an 8-vector (on EITHER carrier).
    """
    a = _operand_leaves(a, "octonion_left_mult")
    exact = _exact_octonion(a)
    if exact is not None:
        return QMat.from_rows(_left_mult_matrix(exact))
    a = _as_octonion(a, "octonion_left_mult")
    native = _try_native_loop_op("srmech_loop_left_op_f64", a)
    if native is not None:
        return Mat.from_rows(native, is_complex=False)
    table = _build_mult_table()
    rows = [[sum(a[i] * table[i][j][k] for i in range(_DIM)) for j in range(_DIM)]
            for k in range(_DIM)]
    return Mat.from_rows(rows, is_complex=False)


def octonion_right_mult(a: Sequence[int | Q | Tuple[int, int] | float]) -> Mat | QMat:
    """Right-multiplication matrix ``R_a`` (``x -> x * a``) as an ``8x8`` real ``Mat``.

    Column ``j`` is ``e_j * a``; ``R_a[k, j] = sum_i a_i C[j, i, k]``. For an
    imaginary unit ``e_i`` (``i >= 1``) the matrix ``R_{e_i}`` is already
    antisymmetric (the other 7 R-type coset directions of the ``28``).

    Class M (Clifford / HDC binding).

    Canonical SSoT: Baez (2002) §2.3-2.4.

    **THE CARRIER IS THE OPERAND'S, NOT THE OP'S** (rc465, `#T1188`) — the
    :func:`octonion_left_mult` rule verbatim, one hand over. An exact operand
    returns an exact-ℚ ``QMat`` via :func:`srmech.cascade.right_mult_matrix`;
    one float component anywhere routes the whole call to the f64 peer below;
    ``QMat.to_mat()`` is the on-demand projection. Measured equal on both routes
    over the 8 basis vectors and 12 random integer 8-vectors.

    rc122 (numpy-free): the FLOAT route dispatches to the C-backed
    ``srmech_loop_right_op_f64`` (native when present; bit-identical numpy-free
    table fallback otherwise) and returns a real ``Mat``, **accurate to
    round-off** — every component is truncated to a 53-bit significand on entry.
    ``R_a[k][j] = sum_i a_i C[j][i][k]``.

    Args:
        a: An 8-vector octonion; exact (``int`` / ``Q`` / ``(num, den)``) or
            ``float``.

    Returns:
        ``8x8`` exact-ℚ ``QMat`` ``R_a`` for an exact operand; ``8x8`` real
        ``Mat`` for a float one.

    Raises:
        ValueError: if ``a`` is not an 8-vector (on EITHER carrier).
    """
    a = _operand_leaves(a, "octonion_right_mult")
    exact = _exact_octonion(a)
    if exact is not None:
        return QMat.from_rows(_right_mult_matrix(exact))
    a = _as_octonion(a, "octonion_right_mult")
    native = _try_native_loop_op("srmech_loop_right_op_f64", a)
    if native is not None:
        return Mat.from_rows(native, is_complex=False)
    table = _build_mult_table()
    rows = [[sum(a[i] * table[j][i][k] for i in range(_DIM)) for j in range(_DIM)]
            for k in range(_DIM)]
    return Mat.from_rows(rows, is_complex=False)


def octonion_conjugate(x: Sequence[int | Q | Tuple[int, int] | float]) -> List[float] | List[Q]:
    """Octonion conjugate ``conj(x) = (x_0, -x_1, ..., -x_7)``.

    Flips the sign of the seven imaginary axes (the scalar axis is fixed).
    Class C (chirality / orientation).

    Canonical SSoT: Baez (2002) §2.1 (conjugation and the norm form).

    **THE CARRIER IS THE OPERAND'S, NOT THE OP'S** (rc465, `#T1188`). An exact
    operand returns ``list[Q]`` through :func:`srmech.cascade.cd_conjugate` —
    the exact-ℚ C peer ``srmech_cd_qconjugate``, one import away since rc159. A
    float operand keeps the float route. No ``exact=`` keyword: the operand says
    which carrier was asked for.

    ⚠️ **Through rc464 a sign flip changed the value.** This op performs NO
    arithmetic at all — it negates seven components — and
    ``octonion_conjugate([2**53+1, 0, …])[0]`` still came back
    ``9007199254740992.0``, because ``[float(c) for c in v]`` ran at the entry.
    That is the ``einsum("ij->ji")`` witness in a different module: the cleanest
    possible demonstration that the defect is the CARRIER, not the algorithm.

    rc122: the Class-C imaginary-axis sign flip is a plain list comprehension
    (``-x_i`` for ``i >= 1``; no ``abs()``) on **both** routes. The float route
    returns ``list[float]`` and is **accurate to round-off** — its components
    are truncated to a 53-bit significand on entry.

    Args:
        x: An 8-vector octonion; exact (``int`` / ``Q`` / ``(num, den)``) or
            ``float``.

    Returns:
        The 8-vector conjugate: ``list[Q]`` for an exact operand,
        ``list[float]`` for a float one.

    Raises:
        ValueError: if ``x`` is not an 8-vector (on EITHER carrier).
    """
    x = _operand_leaves(x, "octonion_conjugate")
    exact = _exact_octonion(x)
    if exact is not None:
        return list(_cd_conjugate(exact))
    x = _as_octonion(x, "octonion_conjugate")
    return [x[0]] + [-x[i] for i in range(1, _DIM)]


def octonion_norm(x: Sequence[int | Q | Tuple[int, int] | float]) -> float | Q:
    """Octonion norm ``sqrt(sum x_i^2)`` (Class K + Class C; never abs()).

    The norm form of the composition algebra. The sum-of-squares is reduced
    to a Python float, passed through the **scalar** Class K pin-slot
    magnitude — but read the SCOPE line below first.

    **SCOPE — this is the DEFINITE 𝕆, and the coordinate form is correct only
    there** (named rc352, `#T1001`). ``Σ xᵢ²`` equals ``Re(x·x̄)`` because this
    module's product is :func:`octonion_mult_table`'s, whose imaginary units
    all square to ``−1``. On **split-𝕆** four of them square to ``+1``, the
    norm form is the indefinite ``(4, 4)`` one, and this function would report
    a positive number for a genuine null vector. That is not a latent bug here
    — this module cannot construct a split algebra — but it IS the same
    substitution :func:`srmech.cascade.inertia_signature` exists to avoid.
    For a twist, use ``cd_norm_sq(x, gammas=…)`` or read ``Re(x·x̄)`` through
    :func:`srmech.cascade.table_product`.

    The sum-of-squares is passed through the **scalar** Class K pin-slot
    magnitude (:func:`srmech.cascade.magnitude` — the cascade-honest
    replacement for ``abs()`` per
    ``[[feedback_sign_handling_is_class_k_pin_slot_not_alu_abs]]``), then the
    Class-N ``rational.sqrt``. ``magnitude`` is SCALAR-ONLY, so the reduction
    to a scalar happens FIRST.

    Class K + Class C.

    rc122 (numpy-free): the sum-of-squares is a pure-Python ``sum`` over the
    coerced ``list[float]`` (no numpy reduction).

    Canonical SSoT: Baez (2002) §2.1 (``N(x) = x conj(x)``, the norm form).

    **THE CARRIER IS THE OPERAND'S, NOT THE OP'S** (rc465, `#T1188`) — and here
    the honest statement differs from its three siblings, because a square root
    is not a rational function. An exact operand takes the exact route: ``Σ xᵢ²``
    through :func:`srmech.cascade.cd_norm_sq` (the C peer
    ``srmech_cd_qnorm_sq``), the Class-K pin-slot magnitude, then the Class-N
    :func:`srmech.math.rational.sqrt`, returning a ``Q``. The radicand is exact
    and the root is EXACT WHEN IT LANDS ON THE CLASS-N DYADIC GRID — an integer
    root, or one whose reduced denominator is a power of two. MEASURED:
    ``sqrt(Q(25, 1)) == 5``, ``sqrt(Q(9, 16)) == 3/4``, ``sqrt(Q(1, 4)) == 1/2``;
    but ``sqrt(Q(25, 49))`` is ``25734855013545691/36028797018963968``, **not**
    ``5/7``. A RATIONAL root with an odd denominator does not land on the nose,
    so ``|Q(1, 3)| != Q(1, 3)``. Off the grid the ``Q`` is that root **accurate
    to** ``2**-54`` relative, which is a bound the caller can read here BEFORE
    calling — the whole difference between this and what rc464 shipped. A float operand keeps the float route and its terminal float lift.

    In rc463's vocabulary the other three ops are an exact CARRIER and this one
    is an exact ROUTE with a declared bound. Both senses of "exact" live in this
    package; conflating them is how a silent demotion becomes a quieter one
    rather than a fixed one.

    ⚠️ **Through rc464 this rounded the operand before it was squared**, so
    ``octonion_norm([2**53+1, 0, …])`` returned ``9007199254740992.0`` for a
    vector whose norm is exactly ``9007199254740993``.

    rc122 (numpy-free): the float route's sum-of-squares is a pure-Python
    ``sum`` over the coerced ``list[float]`` (no numpy reduction), **accurate to
    round-off**.

    Args:
        x: An 8-vector octonion; exact (``int`` / ``Q`` / ``(num, den)``) or
            ``float``.

    Returns:
        The non-negative Euclidean norm: an exact-ℚ ``Q`` for an exact operand
        (exact on the Class-N dyadic grid — an integer root or a power-of-two
        denominator; otherwise that root to ``2**-54`` relative), a ``float``
        for a float one.

    Raises:
        ValueError: if ``x`` is not an 8-vector (on EITHER carrier).
    """
    x = _operand_leaves(x, "octonion_norm")
    exact = _exact_octonion(x)
    if exact is not None:
        # The SAME three-step cascade as the float route below, on the exact
        # carrier: the Class-K pin-slot (magnitude is type-preserving over Q
        # since rc362) then the Class-N root. Never abs().
        return _rsqrt(_magnitude(_cd_norm_sq(exact)))
    x = _as_octonion(x, "octonion_norm")
    # Reduce to a SCALAR float first (cascade.magnitude raises on a sequence),
    # then the Class K pin-slot magnitude, then the square root. No abs().
    sum_sq = sum(xi * xi for xi in x)
    return float(_rsqrt(_magnitude(sum_sq)))


# ────────────────────────────────────────────────────────────────────────
# The ODFT twiddle family (0.9.0rc111; issue #1234 Item 1c, re-raise of
# #863) — the dim-8 mirror of the rc109 qm.quaternion foundation. Same-rc
# C peers: srmech_octonion_exp / srmech_octonion_twiddle (byte-exact).
# ────────────────────────────────────────────────────────────────────────


def _native_ready(symbol: str) -> bool:
    """True iff the native lib is loaded AND exports ``symbol``.
    The twiddle-family readiness gate (the loop-op gate above is separate so
    each family can be force-pured independently in tests)."""
    return bool(
        _native.HAS_NATIVE and _native.LIB is not None
        and hasattr(_native.LIB, symbol)
    )


def _resolve_mu8(mu, op: str) -> List[float]:
    """Resolve ``mu`` to a UNIT pure-imaginary 8-vector ``μ̂`` (``μ̂[0] == 0``,
    ``‖μ̂‖ = 1`` ⟹ ``μ̂² = −1``) — resolved exactly ONCE per public call so the
    native and pure paths consume the identical floats (the rc109
    one-resolution parity contract, at dim 8).

    Accepts a named axis (``'i'``/``'j'``/``'k'`` == ``'e1'``/``'e2'``/
    ``'e3'``, ``'e4'``..``'e7'``, ``'ijk'``, ``'diagonal'`` — exact table
    values) or a 4-/8-sequence pure-imaginary vector (a 4-sequence is an
    ℍ ⊂ 𝕆 axis, zero-extended), normalised via the Class-N
    :func:`srmech.math.rational.sqrt` cascade (never libm)."""
    if isinstance(mu, str):
        if mu in _MU_AXES:
            return list(_MU_AXES[mu])
        raise ValueError(
            f"{op}: mu must be one of {sorted(_MU_AXES)} or a unit "
            f"pure-imaginary 4-/8-vector; got {mu!r}"
        )
    if isinstance(mu, Mat):
        raise ValueError(f"{op}: mu must be a 4-/8-vector; got a Mat {mu.shape}")
    try:
        v = [float(c) for c in mu]
    except TypeError as exc:  # 0-D scalar / non-iterable
        raise ValueError(f"{op}: mu must be a 4-/8-vector; got {mu!r}") from exc
    if len(v) == 4:
        v = v + [0.0, 0.0, 0.0, 0.0]
    if len(v) != _DIM:
        raise ValueError(
            f"{op}: a general mu must have 4 (ℍ ⊂ 𝕆) or 8 components; "
            f"got length {len(v)}"
        )
    if v[0] != 0.0:
        raise ValueError(f"{op}: a general mu must be pure-imaginary (e0 == 0)")
    norm_sq = sum(c * c for c in v[1:])
    if norm_sq == 0.0:
        raise ValueError(f"{op}: mu must be a non-zero pure-imaginary vector")
    inv = 1.0 / float(_rsqrt(float(norm_sq)))
    return [0.0] + [v[i] * inv for i in range(1, _DIM)]


def _try_native_exp(theta: float, mu: List[float]) -> List[float]:
    """Dispatch ``exp(μθ)`` to ``srmech_octonion_exp`` (``μ`` already unit),
    returning the 8-vector ``list[float]`` — or ``None`` for the pure path."""
    if not _native_ready("srmech_octonion_exp"):
        return None
    Arr = ctypes.c_double * _DIM
    c_mu = Arr(*(float(v) for v in mu))
    c_out = Arr()
    rc = _native.LIB.srmech_octonion_exp(
        ctypes.c_double(theta), ctypes.cast(c_mu, _DBLP),
        ctypes.c_size_t(_DIM), ctypes.cast(c_out, _DBLP)
    )
    if rc != _native.SRMECH_OK:
        return None
    return [float(c_out[i]) for i in range(_DIM)]


def _exp_resolved(theta: float, mu: List[float]) -> List[float]:
    """The exp core over an ALREADY-RESOLVED unit ``μ̂`` (never re-normalises —
    the one-resolution parity contract): native ``srmech_octonion_exp`` when
    present, else the pure Q61 cascade (``rational.{cos,sin}`` projected to
    float once, then the axis scaling) — byte-exact either way."""
    native = _try_native_exp(theta, mu)
    if native is not None:
        return native
    c = float(_rcos(theta))
    s = float(_rsin(theta))
    return [c] + [s * mu[i] for i in range(1, _DIM)]


def octonion_exp(theta: float, mu="i") -> List[float]:
    """The octonion Euler formula ``exp(μθ) = cos θ·1 + sin θ·μ̂`` — the ODFT
    twiddle at the float64 boundary (0.9.0rc111; the dim-8 mirror of
    :func:`srmech.physics.qm.quaternion.quaternion_exp`).

    ``μ̂`` is a UNIT pure imaginary (``μ̂² = −1``), so ``exp(μθ)`` is a UNIT
    octonion living in the commutative subalgebra ``ℝ[μ̂] ≅ ℂ`` — which is
    exactly why the one-sided ODFT is invertible (the geometric-series
    orthogonality runs inside ``ℝ[μ̂]``, and by Artin's theorem the
    two-generator subalgebra ``⟨μ̂, x⟩`` is ASSOCIATIVE, so the same-axis
    round-trip composition is exact despite 𝕆's non-associativity).
    Properties (tested): ``‖exp(μθ)‖ = 1``; ``exp(μθ₁)·exp(μθ₂) =
    exp(μ(θ₁+θ₂))`` for the SAME axis; ``conj(exp(μθ)) = exp(−μθ)``;
    ``exp(μ·2π/N)^N = 1`` (the N-th roots of unity the DFT needs — see
    :func:`octonion_twiddle`).

    Exactness convention (the rc109 three tiers, at dim 8): trig is the Q61
    Class-N cascade (``rational.{cos,sin}``; native ``srmech_{cos,sin}_q61``)
    projected to float ONCE; the exact-rational tier is
    :func:`octonion_exp_series_truncate`; the exact-Q61 equal-weight-axis
    tier is :func:`srmech.cascade.hypercomplex_exp` (``k_axes=7``).
    Dispatches to the same-rc C peer ``srmech_octonion_exp`` (byte-exact
    pure fallback).

    Class N (Q61 cos/sin) ∘ Class C (the ±μ orientation) ∘ Class M (the axis
    scaling); no ``abs()``, no libm.

    Args:
        theta: The rotation angle θ (radians), finite.
        mu: The axis ``μ̂`` — a named axis (``'i'``/``'j'``/``'k'`` ==
            ``'e1'``/``'e2'``/``'e3'``, ``'e4'``..``'e7'``, ``'ijk'``,
            ``'diagonal'``; exact) or a pure-imaginary 4-/8-sequence
            (normalised via the Class-N sqrt cascade). Default ``'i'``.

    Returns:
        The unit octonion ``[cos θ, sin θ·μ̂₁, …, sin θ·μ̂₇]`` as a
        ``list[float]``.

    Raises:
        ValueError: non-finite ``theta``; ``mu`` not a valid axis.
    """
    th = float(theta)
    if not _rational._is_finite(th):
        raise ValueError("octonion_exp: theta must be finite")
    mu_hat = _resolve_mu8(mu, "octonion_exp")
    return _exp_resolved(th, mu_hat)


def octonion_exp_series_truncate(
    theta_num: int,
    theta_den: int,
    num_terms: int,
    axis: int = 1,
) -> Tuple[Tuple[int, int], ...]:
    """EXACT-rational ``exp(e_axis·θ)`` for a RATIONAL angle ``θ = p/q`` — the
    series-truncate tier of the ODFT twiddle (the dim-8 mirror of
    :func:`srmech.physics.qm.quaternion.quaternion_exp_series_truncate`).

    Composes the Class-N calculus series
    :func:`srmech.math.rational.cos_series_truncate` /
    :func:`srmech.math.rational.sin_series_truncate` (Taylor partial sums to
    ``num_terms``, exact bignum ``(num, den)`` rationals) with an
    exactly-representable basis axis ``μ̂ = e_axis`` (``axis ∈ {1, …, 7}`` —
    the only unit octonion axes with exact rational components). Returns the
    8 exact pairs ``(cos at slot 0, sin at slot axis, (0, 1) elsewhere)``.
    The unit property ``cos² + sin² = 1`` holds in the ``num_terms → ∞``
    limit (the truncation residue is the caller's precision dial).

    π is NOT rational — a ``2πjk/N`` twiddle angle enters this tier only as
    a caller-chosen rational approximant (e.g. ``best_rational`` over the π
    cascade digits); the float64 projection of that boundary is
    :func:`octonion_twiddle`.

    Class N (rational series-truncate). Pure exact-bignum (the
    ``bignum_reference`` tier — the arbitrary-precision oracle of the Q61 /
    float paths).

    Args:
        theta_num: Angle numerator ``p`` (radians as ``p/q``).
        theta_den: Angle denominator ``q`` (nonzero).
        num_terms: Taylor terms ``N`` (see the series-truncate contracts).
        axis: The basis axis ``e_axis``, 1..7. Default 1.

    Returns:
        An 8-tuple of exact ``(num, den)`` pairs: slot 0 = truncated cos,
        slot ``axis`` = truncated sin, the other slots ``(0, 1)``.

    Raises:
        ValueError: ``axis`` not in {1..7}; series-contract violations
            propagate from the underlying truncates.
    """
    if axis not in (1, 2, 3, 4, 5, 6, 7):
        raise ValueError(
            f"octonion_exp_series_truncate: axis must be an imaginary basis "
            f"index 1..7; got {axis!r}"
        )
    c_pair = _cos_series(theta_num, theta_den, num_terms)
    s_pair = _sin_series(theta_num, theta_den, num_terms)
    out: List[Tuple[int, int]] = [tuple(c_pair)] + [(0, 1)] * (_DIM - 1)
    out[axis] = tuple(s_pair)
    return tuple(out)


def _try_native_twiddle(j: int, k: int, n_points: int, sigma: int,
                        mu: List[float]) -> List[float]:
    """Dispatch the whole twiddle to ``srmech_octonion_twiddle`` (``μ``
    already unit; ``j``/``k`` already reduced mod ``n_points``) — or ``None``
    to signal the pure mirror."""
    if not _native_ready("srmech_octonion_twiddle"):
        return None
    Arr = ctypes.c_double * _DIM
    c_mu = Arr(*(float(v) for v in mu))
    c_out = Arr()
    rc = _native.LIB.srmech_octonion_twiddle(
        ctypes.c_uint32(j), ctypes.c_uint32(k), ctypes.c_uint32(n_points),
        ctypes.c_int32(sigma), ctypes.cast(c_mu, _DBLP),
        ctypes.c_size_t(_DIM), ctypes.cast(c_out, _DBLP)
    )
    if rc != _native.SRMECH_OK:
        return None
    return [float(c_out[i]) for i in range(_DIM)]


def _twiddle_resolved(j_red: int, k_red: int, n_points: int, sigma: int,
                      mu_hat: List[float]) -> List[float]:
    """The twiddle core over an ALREADY-RESOLVED unit ``μ̂`` and ALREADY-REDUCED
    indices (``j_red``/``k_red`` < ``n_points``) — never re-normalises μ̂ (the
    one-resolution parity contract). Shared by :func:`octonion_twiddle` and
    the rc111 ``cascade.octonion_dft`` composed path so both consume the
    identical floats the C peers see. Native ``srmech_octonion_twiddle`` when
    present; the pure mirror follows the C float-op order exactly."""
    native = _try_native_twiddle(j_red, k_red, n_points, sigma, mu_hat)
    if native is not None:
        return native
    # Pure mirror of the C peer — identical float-op order (parity contract).
    r = (j_red * k_red) % n_points
    two_pi = 2.0 * _PI
    frac = float(r) / float(n_points)
    theta = float(sigma) * two_pi * frac
    return _exp_resolved(theta, mu_hat)


def octonion_twiddle(j: int, k: int, n_points: int, *,
                     mu="i", sigma: int = -1) -> List[float]:
    """The ODFT twiddle factor ``exp(σ·μ·2πjk/N)`` — the DFT-facing form of
    :func:`octonion_exp`, with π and the index reduction handled natively
    (0.9.0rc111; the dim-8 mirror of
    :func:`srmech.physics.qm.quaternion.quaternion_twiddle`).

    The angle is ``σ·2π·((j·k) mod N)/N``: the index product is reduced in
    the cyclic group Z_N FIRST (Class I — exact, and the reduction keeps the
    projected angle in one period), then π enters ONCE as the Class-N
    ``4·atan(1)`` cascade at the float64 boundary (never ``math.pi``).
    ``σ = −1`` (default) is the forward-DFT orientation (matching
    ``cascade.octonion_dft``); ``σ = +1`` the inverse. Twiddle closure
    (tested): ``octonion_twiddle(j, k, N)`` for ``jk ≡ 0 (mod N)`` is the
    identity, and ``exp(μ·2π/N)^N = 1``.

    Dispatches to the same-rc C peer ``srmech_octonion_twiddle`` (byte-exact
    pure mirror otherwise). Class I (cyclic index) ∘ N (π cascade + Q61
    trig) ∘ C (σ orientation) ∘ M (axis scaling).

    Args:
        j: Frequency index (non-negative int).
        k: Sample index (non-negative int).
        n_points: The DFT length ``N`` (``1 ≤ N < 2³²`` — the native uint32
            parity bound, enforced identically on the pure path).
        mu: The axis ``μ̂`` (same forms as :func:`octonion_exp`). Default ``'i'``.
        sigma: ``−1`` forward (default) or ``+1`` inverse.

    Returns:
        The unit-octonion twiddle as a ``list[float]`` (8 components).

    Raises:
        ValueError: bad ``j``/``k``/``n_points``/``sigma``/``mu``.
    """
    j = int(j)
    k = int(k)
    n_points = int(n_points)
    if j < 0 or k < 0:
        raise ValueError(
            f"octonion_twiddle: j and k must be non-negative; got {j}, {k}")
    if not (1 <= n_points < _TWIDDLE_N_MAX):
        raise ValueError(
            f"octonion_twiddle: n_points must be in [1, 2**32); got {n_points}")
    if sigma not in (1, -1):
        raise ValueError(
            f"octonion_twiddle: sigma must be +1 or -1; got {sigma!r}")
    mu_hat = _resolve_mu8(mu, "octonion_twiddle")
    j_red = j % n_points
    k_red = k % n_points
    return _twiddle_resolved(j_red, k_red, n_points, sigma, mu_hat)


__all__ = [
    "octonion_conjugate",
    "octonion_exp",
    "octonion_exp_series_truncate",
    "octonion_left_mult",
    "octonion_mult_table",
    "octonion_norm",
    "octonion_right_mult",
    "octonion_table_attestation",
    "octonion_twiddle",
]
