"""
PlatformIO Pre-Build Script
Generates src/CMakeLists.txt based on build environment type

This script runs before each build and generates the appropriate CMakeLists.txt:
- Modular builds: Include all module files (main.c + tasks + hardware + system)
- Test builds: Include only the test file

This solves the "multiple definition of app_main" error when building test environments.
"""

Import("env")
import os

# Get the current build environment name
build_env = env["PIOENV"]

# Define which environments use modular architecture
MODULAR_BUILDS = ["xiao_esp32c6", "xiao_esp32c6_production", "xiao_esp32c6_testing", "xiao_esp32c6_ble_no_nvs", "xiao_esp32c6_prototype"]

# Define source file mapping for test builds
source_map = {
    "hbridge_test": "../test/hbridge_test.c",
    "hbridge_pwm_test": "../test/hbridge_pwm_test.c",
    "ledc_blink_test": "../test/ledc_blink_test.c",
    "button_deepsleep_test": "../test/button_deepsleep_test.c",
    "ws2812b_test": "../test/ws2812b_test.c",
    "single_device_demo_test": "../test/single_device_demo_test.c",
    "battery_voltage_test": "../test/battery_voltage_test.c",
    "minimal_battery_voltage_test": "../test/minimal_battery_voltage_test.c",
    "single_device_battery_bemf_test": "../test/single_device_battery_bemf_test.c",
    "single_device_battery_bemf_queued_test": "../test/single_device_battery_bemf_queued_test.c",
    "single_device_demo_jpl_queued": "../test/single_device_demo_jpl_queued.c",
    "single_device_ble_gatt_test": "../test/single_device_ble_gatt_test.c",
    "minimal_ble_test": "../test/minimal_ble_test.c",
    "minimal_wifi_test": "../test/minimal_wifi_test.c",
    # Add future test environments here
}

# CMakeLists.txt template for MODULAR builds (all module files)
MODULAR_CMAKE_TEMPLATE = """# EMDR Bilateral Stimulation Device - Main Component
# Component-level CMakeLists.txt for ESP-IDF
#
# This tells ESP-IDF how to build the src/ directory
# Modular architecture with separate task and hardware modules
# AUTO-GENERATED by scripts/select_source.py - DO NOT EDIT MANUALLY

idf_component_register(
    SRCS
        # Main application entry point
        "main.c"

        # Task modules (state machines)
        "motor_task.c"
        "ble_task.c"
        "button_task.c"

        # Hardware control modules
        "battery_monitor.c"
        "backemf.c"
        "motor_control.c"
        "led_control.c"
        "status_led.c"

        # System modules
        "ble_manager.c"
        "nvs_manager.c"
        "power_manager.c"
        "time_sync.c"
        "time_sync_task.c"

        # Command-and-Control modules (AD028)
        "command_protocol.c"
        "role_manager.c"

        # Pattern Playback modules (AD047)
        "zone_config.c"
        "pattern_playback.c"

    INCLUDE_DIRS
        "."

    REQUIRES
        # FreeRTOS and ESP system
        freertos
        esp_system
        esp_common
        esp_timer

        # Hardware drivers
        driver          # GPIO, LEDC, ADC, RMT

        # Storage
        nvs_flash

        # Bluetooth
        bt              # NimBLE stack

        # Power management
        esp_pm

        # LED strip encoder (for WS2812B)
        led_strip
)
"""

# CMakeLists.txt template for TEST builds (single test file only)
TEST_CMAKE_TEMPLATE = """# EMDR Bilateral Stimulation Device - Test Build
# Component-level CMakeLists.txt for ESP-IDF
#
# This tells ESP-IDF how to build the test/ directory file
# Test build: Single standalone test file (no modular dependencies)
# AUTO-GENERATED by scripts/select_source.py - DO NOT EDIT MANUALLY

idf_component_register(
    SRCS
        # Test file (standalone, includes its own app_main)
        "{source_file}"

    INCLUDE_DIRS
        "."

    REQUIRES
        # FreeRTOS and ESP system
        freertos
        esp_system
        esp_common
        esp_timer

        # Hardware drivers
        driver          # GPIO, LEDC, ADC, RMT

        # Storage
        nvs_flash

        # Bluetooth
        bt              # NimBLE stack

        # Power management
        esp_pm

        # LED strip encoder (for WS2812B)
        led_strip
)
"""

# Path to src/CMakeLists.txt
cmake_path = os.path.join(env["PROJECT_DIR"], "src", "CMakeLists.txt")

# Generate appropriate CMakeLists.txt based on build type
if build_env in MODULAR_BUILDS:
    # Modular build - use all module files
    cmake_content = MODULAR_CMAKE_TEMPLATE
    print(f"[BUILD] Generating MODULAR CMakeLists.txt for {build_env}")
else:
    # Test build - use only test file
    source_file = source_map.get(build_env, "main.c")
    cmake_content = TEST_CMAKE_TEMPLATE.format(source_file=source_file)
    print(f"[BUILD] Generating TEST CMakeLists.txt for {build_env}: {source_file}")

# Write the generated CMakeLists.txt
with open(cmake_path, 'w') as f:
    f.write(cmake_content)

print(f"[BUILD] CMakeLists.txt generation complete")
