"""Codegen: emit the C17 tables (bodies, omega_diag, initial phases,
couplings, cosine LUT) from the canonical Python research modules.

Reads from ../../research/{bodies, laplacian, bip_instrument}.py and
emits ../src/es_bodies.c, ../src/es_laplacian.c, ../src/es_cosine_lut.c.

Run after any change to the research modules:

    python emit_c_tables.py

The output is a deterministic C source — same Python research code
=> same C tables => same SHAs. The c17/ tree carries a manifest.json
sibling to the Python wheel's so consumers can verify the C tables
came from a known research-tree commit.
"""

from __future__ import annotations

import hashlib
import json
import math
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_C17_ROOT = _HERE.parent
_PY_RESEARCH = _C17_ROOT.parents[1] / "research"

# Make the Python research modules importable.
sys.path.insert(0, str(_C17_ROOT.parents[1]))

from research.bodies import BODIES                              # noqa: E402
from research.bip_instrument import (                           # noqa: E402
    EphemerisBIPInstrument,
    MODULO,
    K_BITS,
    COSINE_LUT_SIZE,
    COSINE_LUT_AMP,
    REFERENCE_JD,
)


_CATEGORY_TO_C = {
    "star":     "ES_CATEGORY_STAR",
    "planet":   "ES_CATEGORY_PLANET",
    "moon":     "ES_CATEGORY_MOON",
    "asteroid": "ES_CATEGORY_ASTEROID",
}


# Header preamble for every emitted file. The "DO NOT EDIT" line is
# load-bearing — manual edits would diverge from the Python SSOT.
_PREAMBLE = """\
/*
 * AUTO-GENERATED by emit_c_tables.py from
 * ../../../research/{bodies,laplacian,bip_instrument}.py.
 *
 * DO NOT EDIT. To regenerate:
 *
 *     cd ../codegen && python emit_c_tables.py
 *
 * Schema and rationale: ../include/ephemerides_spectral.h
 */

#include <stdint.h>
#include <stddef.h>

#include "ephemerides_spectral.h"

"""


def _emit_bodies(path: Path) -> None:
    sorted_names = sorted(BODIES.keys())
    rows = []
    for name in sorted_names:
        b = BODIES[name]
        cat_c = _CATEGORY_TO_C[b.category]
        # Ensure name fits in the 16-byte C field including NUL.
        if len(name) >= 16:
            raise ValueError(
                f"body name {name!r} >= 16 chars, won't fit in es_body_t.name"
            )
        rows.append(
            f'    {{ .name = "{name}",'
            f' .period_days = {b.period_days!r},'
            f' .mass_earth = {b.mass_earth!r},'
            f' .category = {cat_c} }},'
        )
    body_count = len(sorted_names)
    body_compile_assert = (
        f"_Static_assert(ES_N_BODIES == {body_count}, "
        f'"body count mismatch — re-run emit_c_tables.py and rebuild");'
    )
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(_PREAMBLE)
        f.write(body_compile_assert + "\n\n")
        f.write("const es_body_t es_bodies[ES_N_BODIES] = {\n")
        f.write("\n".join(rows) + "\n")
        f.write("};\n")


def _emit_laplacian(path: Path) -> None:
    """Emit omega_diag, initial_phases, couplings, n_couplings.

    Builds an EphemerisBIPInstrument once with the default kernel —
    initial_phases come from skyfield calibration at REFERENCE_JD.
    Embedded targets at runtime use these constants directly; they
    have no skyfield dependency.
    """
    inst = EphemerisBIPInstrument(D=2**16, kernel="de421")  # kernel-agnostic for these tables
    sorted_names = sorted(BODIES.keys())

    # Sanity: instrument's body order must match the bodies table.
    assert list(inst.body_names) == sorted_names, (
        "Body name ordering drift between BODIES dict and instrument"
    )

    omega_rows = []
    init_rows = []
    for i, name in enumerate(sorted_names):
        omega_rows.append(f"    {int(inst.omega_diag[i])}, /* {name} */")
        init_rows.append(f"    {int(inst.initial_phases_int[i])}u, /* {name} */")

    # Couplings — v0.1.0 wires only the J-S 5:2 entry. Future versions
    # add Neptune-Pluto 3:2, Io-Europa 1:2, etc. via the same machinery.
    couplings = []
    if "jupiter" in inst.body_to_idx and "saturn" in inst.body_to_idx:
        idx_j = inst.body_to_idx["jupiter"]
        idx_s = inst.body_to_idx["saturn"]
        weight_rpd = inst._get_scaled_coupling("jupiter", "saturn")
        couplings.append({
            "idx_a": idx_j,
            "idx_b": idx_s,
            "n_a": 5,
            "m_b": 2,
            "weight_rpd": weight_rpd,
            "label": "Jupiter-Saturn 5:2",
        })

    coupling_rows = []
    for cp in couplings:
        coupling_rows.append(
            f"    {{ .idx_a = {cp['idx_a']}, .idx_b = {cp['idx_b']},"
            f" .n_a = {cp['n_a']}, .m_b = {cp['m_b']},"
            f" .weight_rpd = {cp['weight_rpd']}LL }}, /* {cp['label']} */"
        )

    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(_PREAMBLE)
        f.write("/* Diagonal frequencies (residues/day, signed int64). */\n")
        f.write("const int64_t es_omega_diag[ES_N_BODIES] = {\n")
        f.write("\n".join(omega_rows) + "\n")
        f.write("};\n\n")
        f.write("/* Initial phase residues at REFERENCE_JD = J2000.0 (uint32). */\n")
        f.write("const uint32_t es_initial_phases[ES_N_BODIES] = {\n")
        f.write("\n".join(init_rows) + "\n")
        f.write("};\n\n")
        f.write("/* Phase 9 off-diagonal coupling table. */\n")
        f.write("const es_coupling_t es_couplings[] = {\n")
        if coupling_rows:
            f.write("\n".join(coupling_rows) + "\n")
        else:
            f.write("    /* (none) */\n")
        f.write("};\n\n")
        f.write(f"const size_t es_n_couplings = {len(couplings)};\n")


def _emit_cosine_lut(path: Path) -> None:
    """Emit es_cosine_lut[1024] in Q1.14, computed at codegen time
    using float math; runtime is pure integer table lookup.
    """
    values = [
        round(math.cos(2.0 * math.pi * k / COSINE_LUT_SIZE) * COSINE_LUT_AMP)
        for k in range(COSINE_LUT_SIZE)
    ]
    rows = []
    for chunk_start in range(0, COSINE_LUT_SIZE, 8):
        row = ", ".join(f"{v:>6}" for v in values[chunk_start:chunk_start + 8])
        rows.append(f"    {row},")
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(_PREAMBLE)
        f.write(
            f"_Static_assert(ES_COSINE_LUT_SIZE == {COSINE_LUT_SIZE}, "
            '"LUT size mismatch — re-run emit_c_tables.py and rebuild");\n\n'
        )
        f.write("const int32_t es_cosine_lut[ES_COSINE_LUT_SIZE] = {\n")
        f.write("\n".join(rows) + "\n")
        f.write("};\n")


def _sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> None:
    src = _C17_ROOT / "src"
    src.mkdir(parents=True, exist_ok=True)

    bodies_path = src / "es_bodies.c"
    laplacian_path = src / "es_laplacian.c"
    lut_path = src / "es_cosine_lut.c"

    print("emit es_bodies.c       ...", end=" ")
    _emit_bodies(bodies_path)
    print("ok")
    print("emit es_laplacian.c    ...", end=" ")
    _emit_laplacian(laplacian_path)
    print("ok")
    print("emit es_cosine_lut.c   ...", end=" ")
    _emit_cosine_lut(lut_path)
    print("ok")

    # Sibling to the Python wheel's _data/manifest.json: SHAs of the
    # emitted C tables so embedded consumers can verify.
    manifest = {
        "package": "ephemerides-spectral-c17",
        "version": "0.1.0",
        "reference_jd": REFERENCE_JD,
        "k_bits": K_BITS,
        "modulo": int(MODULO),
        "n_bodies": len(BODIES),
        "cosine_lut_size": COSINE_LUT_SIZE,
        "cosine_lut_amp": COSINE_LUT_AMP,
        "files": {
            p.name: {"size_bytes": p.stat().st_size, "sha256": _sha256(p)}
            for p in [bodies_path, laplacian_path, lut_path]
        },
    }
    manifest_path = _C17_ROOT / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"emit manifest.json     ... ok ({len(manifest['files'])} files)")


if __name__ == "__main__":
    main()
