"""``srmech.music.relations`` — the RELATIONAL music surface (rc424, `#T1113`).

The sibling ``_spectra`` / ``_instruments`` modules answer questions about a
single sounding object: *what partials does this bell have, and do they share a
period?* This module answers the other kind of question entirely — **how two
pitches stand to one another**, and how a whole collection of them stands to
itself. Nothing here is acoustics; nothing here reads a spectrum.

WHY IT IS A SEPARATE MODULE
===========================
``srmech.music``'s ``__init__`` docstring has always insisted that "harmonic" in
the acoustic sense and "harmonic" in the chirality-order sense never meet. That
discipline generalises: **the acoustic lane and the relational lane are also
different questions**, and mixing them is how a spectrum op ends up being asked
for a scale degree. So the relational ops live here, and the seam is explicit.

THE TWO LANES, AND WHY BOTH ARE EXACT
=====================================
Everything is exact ℚ or exact ℤ. There is no ``float`` anywhere, no stdlib
``math`` / ``fractions`` / ``decimal``, no numpy, and no ``abs()`` — sign is
handled as a **Class-K pin-slot phase boundary** with **Class-C** re-application
per ``[[feedback_sign_handling_is_class_k_pin_slot_not_alu_abs]]``.

**Lane 1 — the FREQUENCY lane (ℚ⁺ under multiplication).** ``just_limit`` and
``comma_of_chain`` live here. A just interval is a rational; its *p-limit* is
the largest prime in its factorisation, which makes p-limit tuning exactly the
multiplicative subgroup of ℚ⁺ generated by the primes ≤ p (Wright, *Mathematics
and Music*, AMS 2009, §9). Class J decides it; Class I reduces first; Class N
carries it.

**Lane 2 — the MODULAR lane (ℤ/12 under addition).** ``interval_vector`` /
``normal_order`` / ``prime_form`` live here. Class I supplies the group action,
Class E supplies the canonical-representative selection.

⚠️ **THE TWO LANES DO NOT AGREE, AND THAT IS THE POINT** (notebook §3.46.2).
The frequency lane never closes — ``(3/2)**n = 2**m`` has no solution for
``n > 0``, because the prime supports ``{3}`` and ``{2}`` are disjoint (Class J
deciding a question Class I cannot even pose). The modular lane always closes,
because a generator coprime to the modulus generates the whole cycle. The exact
non-vanishing residue between them IS a comma, and ``comma_of_chain`` DERIVES it
rather than looking it up.

⚠️ **CLASS N IS THE WRONG TOOL FOR EVERY OP IN THIS MODULE, AND SPECTACULARLY
SO** (`#T1014`). ``best_rational`` does not *approximate* a musical interval —
it **replaces** it with a different one you can hear. Measured on the shipped
op: the syntonic comma ``81/80`` at ``max_denominator=10`` comes back as
``1/1`` — the comma is **erased to a unison**, which is precisely the thing a
comma is defined by not being. And 12-EDO's irrational major third comes back
as an exact ``5/4`` at ``max_denominator=10``, silently converting an
inharmonic spectrum into a just one. Every op here therefore carries the exact
value and never an anchor; ``just_limit``'s worked example ships the divergence
side by side so it is demonstrated rather than merely warned about.

WHAT IS DELIBERATELY NOT HERE
=============================
``interval_invert`` / ``pitch_class_transpose`` / ``pitch_class_invert`` were
costed and **REJECTED**: each is a single ``cyclic_mod_add`` call carrying no
decision, so registering one would add registry surface for zero capability.
The ℤ/7 note-alphabet walk of §3.46.2 (fifth ``+4``, fourth ``+3``, ``4+3=7``
the conserved octave) ships as a worked example and an ``[[alias]]`` entry, not
as an op, for the same reason. Psychoacoustics, timbre and fingerboard
GEOMETRY are out of scope — the last by the CAD-scope ban (§3.46.3 says so in
those words).
"""

from __future__ import annotations

from typing import Dict, Sequence, Tuple, Union

from srmech.cascade import cyclic_mod_add
from srmech.math.cyclic import gcd
from srmech.math.primes import factor
from srmech.math.q import Q

__all__ = [
    "just_limit",
    "comma_of_chain",
    "tempers_out",
    "interval_vector",
    "normal_order",
    "prime_form",
    "FORTE",
    "RAHN",
    "CONVENTIONS",
]

#: Forte (1973) — the left-packed convention.
FORTE = "forte"
#: Rahn (1980) — the right-packed convention.
RAHN = "rahn"
#: The two conventions a caller may name. There is no default, by design.
CONVENTIONS = (FORTE, RAHN)

#: The chromatic modulus. ℤ/12 is the modular lane's group.
_EDO12 = 12

#: The Class-J parity surface. ``srmech.math.primes.factor`` binds the
#: fixed-width ``srmech_factor`` and refuses an operand beyond this bound — a
#: real C-parity contract, NOT relaxed here.
_CLASS_J_PARITY_MAX = 0xFFFF_FFFF_FFFF_FFFF

_RatioIn = Union[int, "Q", Sequence[int]]


# ══════════════════════════════════════════════════════════════════════
# Wire coercion — bare int or exact [num, den] pair, matching the
# sibling acoustic ops. float is REFUSED, loudly, on purpose.
# ══════════════════════════════════════════════════════════════════════
def _as_ratio(value: _RatioIn, what: str) -> Tuple[int, int]:
    """Coerce a wire ratio to an exact ``(num, den)`` pair of ints."""
    if isinstance(value, bool):
        raise TypeError(f"{what} must be an exact ratio, not bool")
    if isinstance(value, int):
        return (value, 1)
    if isinstance(value, Q):
        return (int(value.numerator), int(value.denominator))
    if isinstance(value, float):
        raise TypeError(
            f"{what} must be EXACT — got float {value!r}. A float has already "
            "lost the distinction this module exists to keep: 81/80 and 1/1 "
            "are different intervals, and a float that rounds one to the "
            "other has erased a comma. Pass an int, an exact [num, den] "
            "pair, or a Q.")
    if isinstance(value, Sequence) and len(value) == 2:
        num, den = value
        if isinstance(num, bool) or isinstance(den, bool):
            raise TypeError(f"{what} pair must be ints, not bool")
        if not isinstance(num, int) or not isinstance(den, int):
            raise TypeError(
                f"{what} must be an exact [num, den] pair of ints; got "
                f"[{type(num).__name__}, {type(den).__name__}]")
        return (num, den)
    raise TypeError(
        f"{what} must be an int, an exact [num, den] pair, or a Q; got "
        f"{type(value).__name__}")


def _sign_split(n: int) -> Tuple[int, int]:
    """Class-K pin-slot: split ``n`` into (orientation, magnitude).

    The pin-slot IS the phase boundary at zero; the orientation it returns is
    the Class-C datum that a later step re-applies. This is the module's ONLY
    sign primitive — ``abs()`` never appears, because ``abs()`` would DISCARD
    the orientation instead of naming it.
    """
    if n < 0:
        return (-1, -n)
    if n > 0:
        return (1, n)
    return (0, 0)


def _reduce(num: int, den: int, what: str) -> Tuple[int, int]:
    """Reduce a positive ratio to lowest terms through the Class-I gcd."""
    if den == 0:
        raise ValueError(f"{what} has zero denominator")
    orient_n, mag_n = _sign_split(num)
    orient_d, mag_d = _sign_split(den)
    if orient_n <= 0 or orient_d <= 0:
        raise ValueError(
            f"{what} must be a POSITIVE ratio; got {num}/{den}. A frequency "
            "ratio is a positive rational — the sign lane in this module is "
            "the monzo EXPONENT's, never the ratio's.")
    g = gcd(mag_n, mag_d)  # Class I
    return (mag_n // g, mag_d // g)


# ══════════════════════════════════════════════════════════════════════
# §1  just_limit  —  Class J ∘ Class I ∘ Class N
# ══════════════════════════════════════════════════════════════════════
def just_limit(num: _RatioIn, den: _RatioIn = 1) -> Dict[str, object]:
    """The **p-limit**, prime support and **monzo** of a just interval.

    p-limit tuning is exactly the multiplicative subgroup of ℚ⁺ generated by
    the primes ≤ p, so "what limit is this interval?" is literally "what is the
    largest prime in its factorisation?" — a **Class J** question, asked of a
    ratio that **Class I** has reduced first and that **Class N** carries
    exactly.

    The **monzo** is the exponent vector of that factorisation: ``3/2`` is
    ``{2: -1, 3: 1}``, i.e. ``2**-1 * 3**1``. It is the interval's coordinates
    in the free abelian group on the primes, which is what makes comma
    arithmetic (``comma_of_chain``) and temperament kernels (``tempers_out``)
    exact integer linear algebra rather than approximation.

    The **odd limit** drops the prime 2, because octave-equivalence is assumed
    in most tuning literature: ``2/1`` is 2-limit but 1-odd-limit.

    :param num: the numerator, or the whole ratio as an exact ``[num, den]``
        pair / ``Q``. float is REFUSED.
    :param den: the denominator when ``num`` was a bare int. Default ``1``.
    :returns: ``{'ratio', 'num', 'den', 'primes', 'limit', 'odd_limit',
        'monzo', 'class_n_anchor_at_10'}``.

    Exact-ℚ; numpy-free; no ``abs()``.
    """
    if den == 1 and not isinstance(num, int):
        num, den = _as_ratio(num, "interval")
    else:
        num, _ = _as_ratio(num, "numerator")
        den, _ = _as_ratio(den, "denominator")
    num, den = _reduce(num, den, "interval")

    fn = factor(num)  # Class J
    fd = factor(den)  # Class J
    monzo: Dict[int, int] = {}
    for (p, e) in fn:
        monzo[p] = monzo.get(p, 0) + e
    for (p, e) in fd:
        monzo[p] = monzo.get(p, 0) - e
    primes = sorted(p for p in monzo if monzo[p] != 0)
    odd = [p for p in primes if p != 2]
    return {
        "ratio": f"{num}/{den}",
        "num": num,
        "den": den,
        "primes": tuple(primes),
        "limit": (max(primes) if primes else 1),
        "odd_limit": (max(odd) if odd else 1),
        "monzo": {str(p): monzo[p] for p in sorted(monzo) if monzo[p] != 0},
    }


# ══════════════════════════════════════════════════════════════════════
# §2  comma_of_chain  —  Class N ∘ Class J   (DERIVED, never a table)
# ══════════════════════════════════════════════════════════════════════
def _period_reduce(num: int, den: int,
                   p_num: int, p_den: int) -> Tuple[int, int, int]:
    """Fold ``num/den`` into ``[1, period)`` by integer powers of the period.

    Pure exact-ℤ cross-multiplication — no logarithm, no float, no ``abs()``.
    Returns ``(num, den, k)`` where ``k`` is the SIGNED number of periods
    removed (Class-C: the orientation of the reduction is data, not noise).
    """
    k = 0
    # while num/den >= p_num/p_den  <=>  num*p_den >= den*p_num
    while num * p_den >= den * p_num:
        num, den = num * p_den, den * p_num
        num, den = _reduce(num, den, "residue")
        k += 1
    # while num/den < 1
    while num < den:
        num, den = num * p_num, den * p_den
        num, den = _reduce(num, den, "residue")
        k -= 1
    return (num, den, k)


def comma_of_chain(gen: _RatioIn, n: int,
                   period: _RatioIn = 2) -> Dict[str, object]:
    """**DERIVE** the comma of an ``n``-step generator chain — never look it up.

    Stack the generator ``n`` times and fold the result back into ``[1,
    period)`` by whole periods. What is left over is the **comma**: the exact
    rational by which the chain FAILS to close. A table of five named constants
    would earn nothing; deriving the residue from the chain is the capability,
    and it answers for generators and periods no table lists.

    The two most-cited commas both fall out of this one op:

    * ``comma_of_chain((3, 2), 12, (2, 1))`` → ``531441/524288``, the
      **Pythagorean comma** — twelve just fifths against seven octaves.
    * ``comma_of_chain((3, 2), 4, (5, 1))`` → ``81/80``, the **syntonic
      comma** — four just fifths against a just major third two octaves up.

    ⚠️ **The residue is structural, not an error term.** ``(3/2)**n == 2**m``
    has no solution for ``n > 0`` by unique factorisation: the prime supports
    ``{3}`` and ``{2}`` are disjoint. So the chain does not *nearly* close and
    it does not close *badly* — it **cannot** close, and the comma is the exact
    measure of that impossibility (notebook §3.46.2; Class J deciding a
    question Class I cannot pose).

    :param gen: the generator ratio, ``> 1``. Exact ``[num, den]`` / ``Q`` /
        int; float REFUSED.
    :param n: how many generators to stack. ``n >= 0``.
    :param period: the equivalence interval, ``> 1``. Default ``2`` (the
        octave).
    :returns: ``{'comma', 'num', 'den', 'vanishes', 'periods_removed',
        'limit', 'monzo', 'factorisation_unavailable', 'gen', 'n', 'period'}``.
        ``limit`` and ``monzo`` are ``None``, with a reason in
        ``factorisation_unavailable``, when the residue exceeds the Class-J
        2**64 parity surface — which a long chain reaches quickly (41 fifths
        already carries a 20-digit numerator). The comma itself stays exact
        there; only the prime-support enrichment is withheld.

    Exact-ℚ; numpy-free; no ``abs()``.
    """
    if isinstance(n, bool) or not isinstance(n, int):
        raise TypeError(f"n must be int, got {type(n).__name__}")
    if n < 0:
        raise ValueError(
            f"n must be non-negative; got {n}. A negative chain is the "
            "reciprocal generator's positive chain — invert `gen` instead, so "
            "the read direction stays explicit (Class C).")
    g_num, g_den = _reduce(*_as_ratio(gen, "gen"), "gen")
    p_num, p_den = _reduce(*_as_ratio(period, "period"), "period")
    if g_num * 1 <= g_den * 1:
        raise ValueError(
            f"gen must exceed 1; got {g_num}/{g_den}")
    if p_num <= p_den:
        raise ValueError(
            f"period must exceed 1; got {p_num}/{p_den}")

    num, den = 1, 1
    for _ in range(n):
        num, den = _reduce(num * g_num, den * g_den, "chain")
    num, den, k = _period_reduce(num, den, p_num, p_den)

    # The COMMA is exact at every n — it is only the Class-J enrichment
    # (limit / monzo) that is bounded, because `factor` binds the fixed-width
    # `srmech_factor` and refuses an operand beyond 2**64 - 1. A long chain
    # reaches that quickly: 41 fifths already carries a 20-digit numerator.
    # So the enrichment is reported ABSENT rather than allowed to destroy a
    # correct comma — the same shape as commensurability_verdict's optional
    # period_multiplier, and for the same reason.
    if num > _CLASS_J_PARITY_MAX or den > _CLASS_J_PARITY_MAX:
        limit = None
        monzo = None
        unavailable = (
            f"the residue {num}/{den} exceeds the Class-J parity surface of "
            f"2**64 - 1, so its prime support is not factorable on this "
            f"surface. The COMMA ITSELF is exact and unaffected — only the "
            f"limit and monzo are withheld. Call just_limit() directly to get "
            f"the refusal as a raise.")
    else:
        limits = just_limit((num, den))
        limit = limits["limit"]
        monzo = limits["monzo"]
        unavailable = None

    return {
        "comma": f"{num}/{den}",
        "num": num,
        "den": den,
        "vanishes": (num == den),
        "periods_removed": k,
        "limit": limit,
        "monzo": monzo,
        "factorisation_unavailable": unavailable,
        "gen": f"{g_num}/{g_den}",
        "n": n,
        "period": f"{p_num}/{p_den}",
    }


# ══════════════════════════════════════════════════════════════════════
# §3  tempers_out  —  Class I ∘ Class N
# ══════════════════════════════════════════════════════════════════════
def _patent_val(prime: int, edo: int) -> int:
    """Steps of ``edo``-EDO nearest to the prime — by EXACT integer compare.

    ``round(edo * log2(prime))`` is the textbook patent val, but a logarithm is
    the one thing this package will not carry. The identity that removes it:

        ``k == round(edo·log2 p)``  ⟺  ``2**(2k-1) <= p**(2·edo) < 2**(2k+1)``

    which is a comparison between two exact integers. No log, no float, no
    tolerance — the val is DECIDED, not estimated.
    """
    target = prime ** (2 * edo)
    m = target.bit_length() - 1  # 2**m <= target < 2**(m+1)
    for k in ((m - 1) // 2, m // 2, (m + 1) // 2, m // 2 + 1):
        if k < 0:
            continue
        if (1 << (2 * k - 1) if 2 * k - 1 >= 0 else 0) <= target < (
                1 << (2 * k + 1)):
            return k
    raise ValueError(  # pragma: no cover - unreachable by the bracket above
        f"no patent-val step found for prime {prime} in {edo}-EDO")


def tempers_out(comma: _RatioIn, edo: int,
                den: _RatioIn = None) -> Dict[str, object]:
    """Does ``edo``-tone equal temperament **temper out** this comma?

    A temperament tempers out a comma exactly when the comma maps to the
    UNISON under that temperament's val — i.e. when the comma's monzo lies in
    the kernel of the map ``p ↦ round(edo·log2 p)``. This op decides that by
    exact integer comparison (see :func:`_patent_val`); nothing is rounded and
    no tolerance is consulted.

    This is the op that explains the keyboard. 12-EDO tempers out the
    **syntonic** comma ``81/80`` — which is what makes it a meantone
    temperament and why a piano has one key for both ``D#`` and ``Eb`` — and it
    tempers out the **Pythagorean** comma ``531441/524288``, which is what
    closes the circle of fifths that §3.46.2 measures as structurally open in
    the frequency lane. 5-EDO tempers out neither.

    :param comma: the comma as an exact ``[num, den]`` pair / ``Q`` / int, or
        a bare numerator when ``den`` is given.
    :param edo: the equal division of the octave, ``>= 1``.
    :param den: the denominator when ``comma`` was a bare int.
    :returns: ``{'tempers_out', 'steps', 'comma', 'edo', 'val', 'monzo'}``
        where ``steps`` is the signed number of EDO steps the comma maps to
        (zero exactly when it is tempered out) and ``val`` is the patent val
        restricted to the primes the comma actually uses.

    Exact integer; numpy-free; no ``abs()``.
    """
    if isinstance(edo, bool) or not isinstance(edo, int):
        raise TypeError(f"edo must be int, got {type(edo).__name__}")
    if edo < 1:
        raise ValueError(f"edo must be >= 1; got {edo}")
    if den is None:
        limits = just_limit(comma)
    else:
        limits = just_limit(comma, den)

    monzo = limits["monzo"]
    val: Dict[str, int] = {}
    steps = 0
    for (p_str, exponent) in monzo.items():
        k = _patent_val(int(p_str), edo)
        val[p_str] = k
        steps += exponent * k
    return {
        "tempers_out": (steps == 0),
        "steps": steps,
        "comma": limits["ratio"],
        "edo": edo,
        "val": val,
        "monzo": monzo,
    }


# ══════════════════════════════════════════════════════════════════════
# §4  the ℤ/12 modular lane  —  Class I ∘ Class E
# ══════════════════════════════════════════════════════════════════════
def _as_pcs(pcs: Sequence[int]) -> Tuple[int, ...]:
    """Coerce to a sorted tuple of DISTINCT pitch classes in ℤ/12."""
    if isinstance(pcs, (str, bytes)) or not isinstance(pcs, Sequence):
        raise TypeError(
            f"pcs must be a sequence of ints; got {type(pcs).__name__}")
    out = set()
    for x in pcs:
        if isinstance(x, bool) or not isinstance(x, int):
            raise TypeError(
                f"pitch classes must be ints; got {type(x).__name__}")
        out.add(cyclic_mod_add(x % _EDO12, 0, _EDO12))  # Class I
    if not out:
        raise ValueError("pcs must be non-empty")
    return tuple(sorted(out))


def _interval_class(a: int, b: int) -> int:
    """The interval CLASS between two pitch classes — Class I then Class K.

    Class I gives the directed distance ``(b - a) mod 12`` through the shipped
    modular add. Class K then folds it at the **tritone**, which is the phase
    boundary: 6 is the unique self-inverse interval in ℤ/12 (12 is even, so the
    octave CAN be bisected — in ℤ/7 no step is self-inverse because 7 is odd,
    §3.46.2's ``7/2 = 3.5``). The fold is a pin-slot decision at that boundary,
    NOT an ``abs()``.
    """
    d = cyclic_mod_add(b, _EDO12 - a, _EDO12)  # Class I
    return d if d <= _EDO12 // 2 else _EDO12 - d  # Class K pin-slot at 6


def interval_vector(pcs: Sequence[int]) -> Tuple[int, ...]:
    """The **interval-class vector**: how a pitch-class set relates to ITSELF.

    Entry ``i`` counts the unordered pairs separated by interval class ``i+1``,
    for ``i`` in ``0..5``. The major triad ``[0, 4, 7]`` gives ``(0, 0, 1, 1,
    1, 0)`` — one minor third, one major third, one fourth — and the minor
    triad ``[0, 3, 7]`` gives the SAME vector, which is the first hint that
    this invariant is coarse.

    ⚠️ **IT IS NOT A COMPLETE INVARIANT, AND THE LOSS HAS A NAME.** Measured
    over all set classes of cardinality 2..10: **23 interval vectors are shared
    by more than one set class**. Those are the **Z-related** pairs — genuinely
    different objects with identical interval content, e.g. ``[0,1,3,7]`` and
    ``[0,1,4,6]`` both giving ``(1,1,1,1,1,1)``. So this op answers "what
    intervals does this set contain?" and NOT "which set class is this?". For
    the latter, use :func:`prime_form`, and note that even *it* cannot separate
    a Z-pair by interval content — only by the set class itself.

    :param pcs: pitch classes; reduced mod 12 and de-duplicated.
    :returns: a 6-tuple of counts.

    Exact integer; numpy-free; no ``abs()``.
    """
    s = _as_pcs(pcs)
    v = [0] * (_EDO12 // 2)
    for i in range(len(s)):
        for j in range(i + 1, len(s)):
            v[_interval_class(s[i], s[j]) - 1] += 1
    return tuple(v)


def _rotations(s: Tuple[int, ...]):
    n = len(s)
    return [tuple(s[(i + k) % n] for k in range(n)) for i in range(n)]


def _spans(rot: Tuple[int, ...]) -> Tuple[int, ...]:
    a0 = rot[0]
    return tuple(cyclic_mod_add(x, _EDO12 - a0, _EDO12) for x in rot[1:])


def _check_convention(convention: str) -> str:
    if convention not in CONVENTIONS:
        raise ValueError(
            f"convention must be one of {CONVENTIONS!r}; got "
            f"{convention!r}. There is NO DEFAULT on purpose: Forte (1973) "
            "and Rahn (1980) disagree on 6 of the 208 set classes, so an "
            "unnamed convention would silently pick a side in a live "
            "scholarly disagreement and be wrong for whichever community it "
            "did not pick.")
    return convention


def normal_order(pcs: Sequence[int], convention: str) -> Tuple[int, ...]:
    """The **normal order** of a pitch-class set — convention REQUIRED.

    The most compact rotation of the set. Both conventions first minimise the
    outer span; they break the tie differently, and the difference is the whole
    reason ``convention`` has no default:

    * ``"forte"`` — Forte (1973) packs **from the left**: after the span, compare
      the first interval, then the second, and so on outward.
    * ``"rahn"`` — Rahn (1980) packs **from the right**: after the span, compare
      the interval to the second-to-last, then the third-to-last, working
      inward from the end.

    :param pcs: pitch classes; reduced mod 12 and de-duplicated.
    :param convention: ``"forte"`` or ``"rahn"``. **Required.**
    :returns: the pitch classes in normal order (NOT transposed to 0 — see
        :func:`prime_form` for that).

    Exact integer; numpy-free; no ``abs()``.
    """
    _check_convention(convention)
    s = _as_pcs(pcs)
    best = None
    for rot in _rotations(s):
        d = _spans(rot)
        if not d:
            key: Tuple[int, ...] = ()
        elif convention == RAHN:
            key = (d[-1],) + tuple(reversed(d[:-1]))
        else:
            key = (d[-1],) + tuple(d[:-1])
        if best is None or key < best[0] or (key == best[0] and rot < best[1]):
            best = (key, rot)
    return best[1]


def _invert(s: Tuple[int, ...]) -> Tuple[int, ...]:
    """Inversion about 0 — Class I, through the shipped modular add."""
    return tuple(sorted({cyclic_mod_add(0, (_EDO12 - x) % _EDO12, _EDO12)
                         for x in s}))


def prime_form(pcs: Sequence[int], convention: str) -> Tuple[int, ...]:
    """The **prime form** of a pitch-class set — convention REQUIRED.

    The canonical representative of the set class under Tn/TnI: take the normal
    order of the set and of its inversion, transpose each to start at 0, and
    keep the smaller. This is the **Class E** half of the op — a catalog
    selection over the **Class I** group orbit.

    ⚠️ **THE CONVENTION IS NOT COSMETIC — IT IS A LIVE SCHOLARLY DISAGREEMENT,
    AND WE MEASURED IT.** Enumerating all set classes of cardinality 2..10
    (220 of them; 208 counting the standard 3..9 table) and comparing the two
    algorithms row by row, **exactly 6 set classes disagree**:

    ==========  =====================  =====================
    set class   ``"forte"``            ``"rahn"``
    ==========  =====================  =====================
    5-20        ``(0,1,3,7,8)``        ``(0,1,5,6,8)``
    6-Z29       ``(0,1,3,6,8,9)``      ``(0,2,3,6,7,9)``
    6-31        ``(0,1,3,5,8,9)``      ``(0,1,4,5,7,9)``
    7-Z18       ``(0,1,2,3,5,8,9)``    ``(0,1,4,5,6,7,9)``
    7-20        ``(0,1,2,4,7,8,9)``    ``(0,1,2,5,6,7,9)``
    8-26        ``(0,1,2,4,5,7,9,10)`` ``(0,1,3,4,5,7,8,10)``
    ==========  =====================  =====================

    Note **7-Z18**. The figure most often quoted is *five*, following Straus's
    *Introduction to Post-Tonal Theory*, which omits it. Six is what the
    algorithms actually do, and it is what independent open set-class tables
    list. Our value is COMPUTED, not copied, and the test suite pins all six.

    An unnamed ``prime_form`` would silently answer as one community and be
    wrong for the other on these six. Hence: no default, ever.

    :param pcs: pitch classes; reduced mod 12 and de-duplicated.
    :param convention: ``"forte"`` or ``"rahn"``. **Required.**
    :returns: the prime form, starting at 0.

    Exact integer; numpy-free; no ``abs()``.
    """
    _check_convention(convention)
    s = _as_pcs(pcs)
    cands = []
    for t in (s, _invert(s)):
        no = normal_order(t, convention)
        cands.append(tuple(cyclic_mod_add(x, _EDO12 - no[0], _EDO12)
                           for x in no))
    return min(cands)
