/* srmech_responsion_registry.c - GENERATED by c/tools/gen_responsion_registry.py.
 * DO NOT EDIT BY HAND. Regenerate with:
 *   python3 tools/regen_all.py            (from docs/srmech/python)
 *
 * rc347: this line named the raw generator plus a `>` redirect, which was
 * exactly trap 2 the runner removed - forget the redirect and the table
 * goes to the terminal, nothing changes, exit 0. The runner also fixes the
 * ORDER this file depends on. rc346 left it stale on purpose to keep its
 * own zero-delta signal clean; rc347 already moves these bytes.
 *
 * Source of truth: srmech.introspect.responsion_schema._pure_responsion_schema()
 * (the F929 dispatch reduce-back rows + their verbatim _OPEN_HINTS
 * residues + the continuous response-function ops). The 0.9.0rc225
 * RESPONSION (stored-relationship) introspection registry -- the k=3
 * EDGE face binding the rc184 tool registry (verbs) and the rc205
 * carrier registry (nouns) -- as a const data table (JPL-clean:
 * const arrays, no dynamic init, no malloc). The accessors + the
 * canonical JSON assembler live in srmech_responsion_schema.c.
 * Entries are in byte-sorted edge-key order == the
 * json.dumps(sort_keys=True) key order the hash-ratchet compares
 * against; each entry_json fragment is baked pre-canonical (compact,
 * sorted keys, ensure_ascii -> pure ASCII).
 *
 * Edges: 23; responsions: 25.
 */

#include "srmech.h"

/* MSVC C4125 ("decimal digit terminates octal escape sequence") is a
 * STYLE nag on the baked \NNN octal escapes (the C standard caps an
 * octal escape at 3 digits, so a following decimal digit is
 * unambiguous; gcc/clang stay silent). Generated pure-DATA table ->
 * suppress locally (compiled bytes identical; the hash-ratchet is
 * unaffected). */
#ifdef _MSC_VER
#pragma warning(disable : 4125)
#endif

/* The responsion registry, in byte-sorted edge-key order (== the
 * canonical JSON key order the hash-ratchet compares against). */
const srmech_responsion_entry_t srmech_responsion_registry_table[] = {
    {
        "srmech.amsc.apagodu_zeilberger.apagodu_zeilberger|TriPoly",
        "srmech.amsc.apagodu_zeilberger.apagodu_zeilberger",
        "TriPoly",
        1u,
        "[{\"answers_with\":\"the minimal-order annihilating recurrence for the 'sums of sums' \\u03a3_{j,k} F(n,j,k) (Apagodu\\u2013Zeilberger creative telescoping)\",\"carrier\":\"TriPoly\",\"curvature\":\"flat\",\"kind\":\"closed_form\",\"operator\":\"srmech.amsc.apagodu_zeilberger.apagodu_zeilberger\",\"regime\":\"discrete_algebraic\",\"status\":\"verified\"}]",
        327u,
    },
    {
        "srmech.amsc.cascade.the_one|One",
        "srmech.amsc.cascade.the_one",
        "One",
        1u,
        "[{\"answers_with\":\"the One S(\\u03c3,\\u03b8) \\u2014 the (1,3,7,3)-partition Klein-4 generator, verified by its own structural invariants (partition + plane-counts + n1_is_sigma_only)\",\"carrier\":\"One\",\"curvature\":\"curved\",\"kind\":\"closed_form\",\"operator\":\"srmech.amsc.cascade.the_one\",\"regime\":\"discrete_algebraic\",\"status\":\"verified\"}]",
        332u,
    },
    {
        "srmech.amsc.coupling.resonant_spectrum|Mat",
        "srmech.amsc.coupling.resonant_spectrum",
        "Mat",
        1u,
        "[{\"answers_with\":\"the resonant eigenspectrum payload of the coupling Laplacian \\u2014 the reduction EXISTS iff L is bit-exact real-symmetric (the spectral theorem's own hypothesis, rc224); the eigenvalues are the operand, never the verdict\",\"carrier\":\"Mat\",\"curvature\":\"curved\",\"kind\":\"closed_form\",\"operator\":\"srmech.amsc.coupling.resonant_spectrum\",\"regime\":\"discrete_algebraic\",\"status\":\"verified\"}]",
        402u,
    },
    {
        "srmech.amsc.dispatch.infer|BiPoly",
        "srmech.amsc.dispatch.infer",
        "BiPoly",
        1u,
        "[{\"answers_with\":\"a definite/indefinite hypergeometric sum the telescope reducers did not close \\u2014 try the multivariate (sums-of-sums) or q-hypergeometric \\u03a3 sub-rows, or a higher-order creative-telescoping\",\"carrier\":\"BiPoly\",\"curvature\":\"flat\",\"kind\":\"open_sustain\",\"operator\":\"srmech.amsc.dispatch.infer\",\"regime\":\"discrete_algebraic\",\"status\":\"open\"}]",
        363u,
    },
    {
        "srmech.amsc.dispatch.infer|EllMonomial",
        "srmech.amsc.dispatch.infer",
        "EllMonomial",
        2u,
        "[{\"answers_with\":\"a root-system elliptic multisum beyond the A\\u2099 (Milne) elliptic Jackson reach \\u2014 a D\\u2099/BC\\u2099 (other root-system) elliptic multisum, a higher-genus theta multisum, or the m \\u2265 2 elliptic Kajihara TRANSFORMATION (Rosengren math/0305379 Thm 3.1, of which the shipped Eq-6 summation is the m = 1 case). (The A\\u2099 per-call PROOF ships with the row: the constructive closed form is verified via the complete multi-variable elliptic is_zero over the C(N+n\\u22121, n\\u22121)-composition simplex, up to the measured feasibility cap; larger sums return the build-verified constructive form with verified=None.)\",\"carrier\":\"EllMonomial\",\"curvature\":\"flat\",\"kind\":\"open_sustain\",\"operator\":\"srmech.amsc.dispatch.infer\",\"regime\":\"discrete_algebraic\",\"status\":\"open\"},{\"answers_with\":\"a root-system elliptic multisum beyond the C\\u2099 elliptic Jackson reach \\u2014 the A\\u2099 (type-A / Milne) elliptic multisum row now ships (rc227 \\u2014 tag row='sigma_elliptic_an'); the remaining frontier is a D\\u2099/BC\\u2099 (other root-system) elliptic multisum or a higher-genus theta multisum. (The exact per-call PROOF of the C\\u2099 reduction ships at rc101: the constructive closed form is verified via the rc98/rc99 complete multi-variable elliptic is_zero, up to a term-count feasibility cap; larger sums return the build-verified constructive form with verified=None.)\",\"carrier\":\"EllMonomial\",\"curvature\":\"flat\",\"kind\":\"open_sustain\",\"operator\":\"srmech.amsc.dispatch.infer\",\"regime\":\"discrete_algebraic\",\"status\":\"open\"}]",
        1548u,
    },
    {
        "srmech.amsc.dispatch.infer|EllRatio",
        "srmech.amsc.dispatch.infer",
        "EllRatio",
        1u,
        "[{\"answers_with\":\"an elliptic-hypergeometric sum beyond the very-well-poised \\u2088\\u03c9\\u2087 / \\u2081\\u2080E\\u2089 Frenkel\\u2013Turaev reach \\u2014 the multivariate C\\u2099 elliptic Jackson row (now shipped \\u2014 tag row='sigma_elliptic_multivar') or a higher-genus theta reduction row\",\"carrier\":\"EllRatio\",\"curvature\":\"flat\",\"kind\":\"open_sustain\",\"operator\":\"srmech.amsc.dispatch.infer\",\"regime\":\"discrete_algebraic\",\"status\":\"open\"}]",
        440u,
    },
    {
        "srmech.amsc.dispatch.infer|Mat",
        "srmech.amsc.dispatch.infer",
        "Mat",
        1u,
        "[{\"answers_with\":\"directed / signed (magnetic) Laplacian spectral row, or a non-self-adjoint pencil generalized-eigenproblem reducer\",\"carrier\":\"Mat\",\"curvature\":\"curved\",\"kind\":\"open_sustain\",\"operator\":\"srmech.amsc.dispatch.infer\",\"regime\":\"discrete_algebraic\",\"status\":\"open\"}]",
        280u,
    },
    {
        "srmech.amsc.dispatch.infer|One",
        "srmech.amsc.dispatch.infer",
        "One",
        1u,
        "[{\"answers_with\":\"a higher Cayley\\u2013Dickson rung (sedenion S(\\u03c3,\\u03b8)) or a non-division-algebra cyclic-group reduction\",\"carrier\":\"One\",\"curvature\":\"curved\",\"kind\":\"open_sustain\",\"operator\":\"srmech.amsc.dispatch.infer\",\"regime\":\"discrete_algebraic\",\"status\":\"open\"}]",
        276u,
    },
    {
        "srmech.amsc.dispatch.infer|QBiPoly",
        "srmech.amsc.dispatch.infer",
        "QBiPoly",
        1u,
        "[{\"answers_with\":\"a q-hypergeometric sum beyond the q-Gosper / q-WZ reach \\u2014 the elliptic-hypergeometric (\\u2088\\u03c9\\u2087 / \\u2081\\u2080E\\u2089) sub-row (now shipped) or a multibasic q-multisum reducer\",\"carrier\":\"QBiPoly\",\"curvature\":\"flat\",\"kind\":\"open_sustain\",\"operator\":\"srmech.amsc.dispatch.infer\",\"regime\":\"discrete_algebraic\",\"status\":\"open\"}]",
        358u,
    },
    {
        "srmech.amsc.dispatch.infer|TriPoly",
        "srmech.amsc.dispatch.infer",
        "TriPoly",
        1u,
        "[{\"answers_with\":\"multivariate 'sums of sums' beyond the (n,j,k) Apagodu\\u2013Zeilberger reach \\u2014 a higher-arity TriPoly\\u207a creative-telescoping or a multibasic-q multisum reducer\",\"carrier\":\"TriPoly\",\"curvature\":\"flat\",\"kind\":\"open_sustain\",\"operator\":\"srmech.amsc.dispatch.infer\",\"regime\":\"discrete_algebraic\",\"status\":\"open\"}]",
        336u,
    },
    {
        "srmech.amsc.elliptic_jackson.multivariate_elliptic_jackson|EllMonomial",
        "srmech.amsc.elliptic_jackson.multivariate_elliptic_jackson",
        "EllMonomial",
        1u,
        "[{\"answers_with\":\"the closed-form theta-quotient product of the balanced C\\u2099 elliptic Jackson n-fold sum (Rosengren Thm 2.1; per-call proof when in-budget, build-verified constructive form beyond the feasibility cap)\",\"carrier\":\"EllMonomial\",\"curvature\":\"flat\",\"kind\":\"closed_form\",\"operator\":\"srmech.amsc.elliptic_jackson.multivariate_elliptic_jackson\",\"regime\":\"discrete_algebraic\",\"status\":\"verified\"}]",
        409u,
    },
    {
        "srmech.amsc.elliptic_jackson_an.multivariate_elliptic_jackson_an|EllMonomial",
        "srmech.amsc.elliptic_jackson_an.multivariate_elliptic_jackson_an",
        "EllMonomial",
        1u,
        "[{\"answers_with\":\"the closed-form theta-quotient of the A\\u2099 (type-A / Milne) elliptic Jackson simplex sum (Rosengren math/0305379 Eq. 6; per-call proof when in-budget, build-verified constructive form beyond the feasibility cap)\",\"carrier\":\"EllMonomial\",\"curvature\":\"flat\",\"kind\":\"closed_form\",\"operator\":\"srmech.amsc.elliptic_jackson_an.multivariate_elliptic_jackson_an\",\"regime\":\"discrete_algebraic\",\"status\":\"verified\"}]",
        427u,
    },
    {
        "srmech.amsc.elliptic_wz_certificate.elliptic_wz_certificate|EllRatio",
        "srmech.amsc.elliptic_wz_certificate.elliptic_wz_certificate",
        "EllRatio",
        1u,
        "[{\"answers_with\":\"the elliptic-WZ connection-coefficient PROOF of the very-well-poised \\u2088\\u03c9\\u2087 / \\u2081\\u2080E\\u2089 Frenkel\\u2013Turaev summation, closed form cf(n) (verified via the exact ThetaSum.is_zero decision)\",\"carrier\":\"EllRatio\",\"curvature\":\"flat\",\"kind\":\"closed_form\",\"operator\":\"srmech.amsc.elliptic_wz_certificate.elliptic_wz_certificate\",\"regime\":\"discrete_algebraic\",\"status\":\"verified\"}]",
        414u,
    },
    {
        "srmech.amsc.gosper.gosper|Poly",
        "srmech.amsc.gosper.gosper",
        "Poly",
        1u,
        "[{\"answers_with\":\"the Gosper rational-certificate antidifference \\u2014 the indefinite hypergeometric closed form (a non-None certificate IS the verification)\",\"carrier\":\"Poly\",\"curvature\":\"flat\",\"kind\":\"closed_form\",\"operator\":\"srmech.amsc.gosper.gosper\",\"regime\":\"discrete_algebraic\",\"status\":\"verified\"}]",
        307u,
    },
    {
        "srmech.amsc.laplacian.ground_state_flux_response|Mat",
        "srmech.amsc.laplacian.ground_state_flux_response",
        "Mat",
        1u,
        "[{\"answers_with\":\"\\u03bb_min(\\u03a6) \\u2014 the magnetic ground state as a function of flux (the F1007 flux shadow), over the magnetic-Laplacian Mat built internally from the edge list\",\"carrier\":\"Mat\",\"curvature\":\"curved\",\"kind\":\"response_curve\",\"operator\":\"srmech.amsc.laplacian.ground_state_flux_response\",\"regime\":\"continuous_spectral\",\"status\":\"verified\"}]",
        361u,
    },
    {
        "srmech.amsc.laplacian.heat_trace|Mat",
        "srmech.amsc.laplacian.heat_trace",
        "Mat",
        1u,
        "[{\"answers_with\":\"\\u0398(t) = Tr(e^{\\u2212tL}) = \\u03a3\\u2096 e^{\\u2212t\\u00b7\\u03bb\\u2096} \\u2014 the read-independent spectral summary (the trace of the propagator)\",\"carrier\":\"Mat\",\"curvature\":\"flat\",\"kind\":\"trace\",\"operator\":\"srmech.amsc.laplacian.heat_trace\",\"regime\":\"continuous_spectral\",\"status\":\"verified\"}]",
        316u,
    },
    {
        "srmech.amsc.laplacian.propagate|Mat",
        "srmech.amsc.laplacian.propagate",
        "Mat",
        1u,
        "[{\"answers_with\":\"e^{\\u2212zL}\\u00b7u0 \\u2014 the named EPH surface (responsion kind='propagator' subsumes it as its time-domain member)\",\"carrier\":\"Mat\",\"curvature\":\"curved\",\"kind\":\"propagator\",\"operator\":\"srmech.amsc.laplacian.propagate\",\"regime\":\"continuous_spectral\",\"status\":\"verified\"}]",
        292u,
    },
    {
        "srmech.amsc.laplacian.responsion|Mat",
        "srmech.amsc.laplacian.responsion",
        "Mat",
        2u,
        "[{\"answers_with\":\"e^{\\u2212zL}\\u00b7u0 \\u2014 the time-domain member (arg(z) the coherence dial: real \\u2192 thermal, imaginary \\u2192 coherent, between \\u2192 partial)\",\"carrier\":\"Mat\",\"curvature\":\"curved\",\"kind\":\"propagator\",\"operator\":\"srmech.amsc.laplacian.responsion\",\"regime\":\"continuous_spectral\",\"status\":\"verified\"},{\"answers_with\":\"(zI\\u2212L)^{-1}\\u00b7u0 \\u2014 the frequency/energy-domain Green's function, the LAPLACE TRANSFORM of the propagator (per eigenmode e^{\\u2212z\\u00b7\\u03bb} \\u27f7 1/(z\\u2212\\u03bb)); poles at spec(L)\",\"carrier\":\"Mat\",\"curvature\":\"curved\",\"kind\":\"resolvent\",\"operator\":\"srmech.amsc.laplacian.responsion\",\"regime\":\"continuous_spectral\",\"status\":\"verified\"}]",
        698u,
    },
    {
        "srmech.amsc.q_gosper.q_gosper|QPoly",
        "srmech.amsc.q_gosper.q_gosper",
        "QPoly",
        1u,
        "[{\"answers_with\":\"the q-Gosper rational q-antidifference certificate \\u2014 the indefinite q-hypergeometric closed form\",\"carrier\":\"QPoly\",\"curvature\":\"flat\",\"kind\":\"closed_form\",\"operator\":\"srmech.amsc.q_gosper.q_gosper\",\"regime\":\"discrete_algebraic\",\"status\":\"verified\"}]",
        273u,
    },
    {
        "srmech.amsc.q_wz_certificate.q_wz_certificate|QBiPoly",
        "srmech.amsc.q_wz_certificate.q_wz_certificate",
        "QBiPoly",
        1u,
        "[{\"answers_with\":\"the q-WZ identity PROOF certificate (accepted only when its own verified flag is True)\",\"carrier\":\"QBiPoly\",\"curvature\":\"flat\",\"kind\":\"closed_form\",\"operator\":\"srmech.amsc.q_wz_certificate.q_wz_certificate\",\"regime\":\"discrete_algebraic\",\"status\":\"verified\"}]",
        276u,
    },
    {
        "srmech.amsc.q_zeilberger.q_zeilberger|QBiPoly",
        "srmech.amsc.q_zeilberger.q_zeilberger",
        "QBiPoly",
        1u,
        "[{\"answers_with\":\"the minimal-order q-creative-telescoping recurrence annihilating the definite q-sum\",\"carrier\":\"QBiPoly\",\"curvature\":\"flat\",\"kind\":\"closed_form\",\"operator\":\"srmech.amsc.q_zeilberger.q_zeilberger\",\"regime\":\"discrete_algebraic\",\"status\":\"verified\"}]",
        265u,
    },
    {
        "srmech.amsc.wz_certificate.wz_certificate|BiPoly",
        "srmech.amsc.wz_certificate.wz_certificate",
        "BiPoly",
        1u,
        "[{\"answers_with\":\"the WZ identity PROOF certificate R(n,k) (accepted only when its own verified flag is True)\",\"carrier\":\"BiPoly\",\"curvature\":\"flat\",\"kind\":\"closed_form\",\"operator\":\"srmech.amsc.wz_certificate.wz_certificate\",\"regime\":\"discrete_algebraic\",\"status\":\"verified\"}]",
        276u,
    },
    {
        "srmech.amsc.zeilberger.zeilberger|BiPoly",
        "srmech.amsc.zeilberger.zeilberger",
        "BiPoly",
        1u,
        "[{\"answers_with\":\"the minimal-order creative-telescoping recurrence annihilating \\u03a3_k F(n,k)\",\"carrier\":\"BiPoly\",\"curvature\":\"flat\",\"kind\":\"closed_form\",\"operator\":\"srmech.amsc.zeilberger.zeilberger\",\"regime\":\"discrete_algebraic\",\"status\":\"verified\"}]",
        255u,
    },
};

const size_t srmech_responsion_registry_len =
    sizeof(srmech_responsion_registry_table) / sizeof(srmech_responsion_registry_table[0]);
