r"""R-RBS-SNN-ACROSS — the sharpened question: how does the FIBRATED k=7 couple multiple synapses & neurons, and
does the fibration view show anything DIFFERENT vs the k=7-NATIVE view? Yes — three things the flat view hides.

k=7-NATIVE (F487): the neuron + 7 synapses = one octonion; couple ≤7 → octonion, reversible; the 7 synapses are
FLAT — equivalent slots, no internal role. That is all the native view says about coupling multiple synapses.

FIBRATION ((4:3) = base S⁴ + fiber S³) reveals what the flat view CANNOT see:
  (a) ROLE SPLIT — the 3 fiber synapses CLOSE (a recurrent quaternion loop); the 4 base synapses DON'T (they
      point out = feedforward). So 3 of every neuron's ≤7 couplings are RECURRENT, 4 are FEEDFORWARD.
  (b) GAUGE / MANY-TO-ONE — fiber·base ⊆ base: the fiber (phase) moves the content AROUND WITHIN the base while
      the base POINT (the content identity) is invariant. Many fiber-phases share ONE base point → one content,
      many phases → the F490 "one marking, many readers" is now PREDICTED by the Hopf quotient, not just observed.
  (c) CONTENT REGENERATES PATTERN — base·base → fiber: the relations (pattern) EMERGE from content interactions;
      the fiber isn't a stored 8th thing, it's generated by how the 4 content-couplings combine.

Across neurons the coupling (the hand/conjugate) PRESERVES the split → recursive (4:3):(4:3) (F128); and the fiber
is GAUGE over the base → it can DROP without losing content (= "sentences with the content but missing the
pattern"; the held thought is always whole — the projection quotients the fiber). srmech 0.7.4 (exact octonion).
"""
import srmech
from srmech.amsc.cascade import cayley_dickson as cd

FIBER = [1, 2, 3]          # the quaternion ℍ (S³) — RECURRENT loop / PATTERN / relations / chirality / phase
BASE = [4, 5, 6, 7]        # the coset ℍe4 (S⁴) — FEEDFORWARD / CONTENT / the things
ix = lambda i, j: cd.cd_basis_product(8, i, j)[0]


def in_span(vec, slots):
    return all(vec[i] == 0 for i in range(8) if i not in slots and i != 0)


def main():
    print(f"=== R-RBS-SNN-ACROSS — fibration vs k=7-native: what coupling multiple synapses/neurons reveals  (srmech {srmech.__version__}) ===\n")

    print("k=7-NATIVE view (F487): 7 synapses → 1 octonion, reversible; the 7 are FLAT (equivalent slots).")
    print("  coupling multiple synapses = 'bind 7 into 1'. No internal role. ← this is all the native view sees.\n")

    print("FIBRATION view reveals THREE things the flat k=7 cannot see:")
    # (a) role split — recurrent vs feedforward
    fiber_closes = all(ix(a, b) in FIBER for a in FIBER for b in FIBER if a != b)
    base_closes = all(ix(a, b) in BASE for a in BASE for b in BASE if a != b)
    print(f"  (a) ROLE SPLIT — fiber {{e1,e2,e3}} closes (a RECURRENT loop): {fiber_closes};  base {{e4..e7}} closes: {base_closes}")
    print(f"      → 3 of every neuron's ≤7 couplings are RECURRENT, 4 are FEEDFORWARD (k=7-native: 7 identical).")
    # (b) gauge / many-to-one — fiber acts within base
    gauge = all(ix(f, b) in BASE for f in FIBER for b in BASE)
    orbit = {b: ix(1, b) for b in BASE}
    print(f"  (b) GAUGE / MANY-TO-ONE — fiber·base ⊆ base (the fiber phase moves content WITHIN the base): {gauge}")
    print(f"      e1 permutes the base {orbit} — many phases, ONE base point → 'one marking, many readers' (F490) PREDICTED.")
    # (c) content regenerates pattern — base·base → fiber
    regen = all(ix(a, b) in FIBER for a in BASE for b in BASE if a != b)
    print(f"  (c) CONTENT REGENERATES PATTERN — base·base → fiber (e4·e5={ix(4,5)}, e5·e6={ix(5,6)}): {regen}")
    print(f"      → the pattern (relations) EMERGES from content interactions; the fiber is generated, not stored.\n")

    # across-coupling preserves the split → recursive (4:3):(4:3)
    cf = cd.cd_conjugate([0, 2, -3, 1, 0, 0, 0, 0])     # a PATTERN (fiber)
    cb = cd.cd_conjugate([0, 0, 0, 0, 5, -2, 4, 1])     # a CONTENT (base)
    split_preserved = in_span(cf, FIBER) and in_span(cb, BASE)
    print(f"ACROSS neurons: the coupling (the hand/conjugate) PRESERVES the split (fiber→fiber, base→base): {split_preserved}")
    print(f"  → INPUT (synapses) (4:3) and OUTPUT (targets) (4:3) bound by a split-preserving coupling = recursive (4:3):(4:3) (F128).\n")

    # the phenomenology: the fiber is GAUGE → droppable without losing content
    things = {4: "the cat", 5: "the mouse", 6: "the garden", 7: "at noon"}        # base = content
    rel = {1: "chased", 2: "in", 3: "(past)"}                                     # fiber = pattern
    def render(vec):
        content = [things[i] for i in BASE if vec[i] != 0]
        pat = [rel[i] for i in FIBER if vec[i] != 0]
        if len(pat) == 3:
            return f"{content[0].capitalize()} {pat[0]} {content[1]} {pat[1]} {content[2]} {content[3]}."
        if not pat:
            return " . ".join(content) + " ."                                     # content, PATTERN missing
        return f"{content[0].capitalize()} {content[1]} {pat[0]}? {content[2]} {content[3]}."  # scrambled
    full = [0, 1, 1, 1, 1, 1, 1, 1]
    drop = [v if i in (0, *BASE) else 0 for i, v in enumerate(full)]              # gauge fiber dropped
    mism = [v if i in (0, *BASE, 1) else 0 for i, v in enumerate(full)]           # hand mismatch (partial fiber)
    print("the fiber is GAUGE over the base → it can drop WITHOUT losing the content (the held thought stays whole):")
    print(f"  phase tracked   : {render(full)}")
    print(f"  phase DROPPED   : {render(drop)}     ← content whole, PATTERN missing ('sentences with missing parts')")
    print(f"  hand MISMATCH   : {render(mism)}\n")

    ok = fiber_closes and not base_closes and gauge and regen and split_preserved
    print("VERDICT — does fibration show anything DIFFERENT from k=7-native? YES, three things:")
    print(f"  1. ROLE SPLIT: 3 recurrent (the fiber loop) + 4 feedforward (the base) — coupling multiple synapses")
    print(f"     is NOT 7-flat; it is a recurrent core wrapped by feedforward content. (k=7-native: all 7 alike.)")
    print(f"  2. GAUGE / MANY-TO-ONE: the fiber (phase) moves content within one base point → many neurons share")
    print(f"     one content at different phases → the F490 divergence is PREDICTED by the Hopf quotient, not just seen.")
    print(f"  3. CONTENT→PATTERN: base·base → fiber — relations EMERGE from content coupling (the pattern is generated).")
    print(f"  Consequence (the phenomenology, as STRUCTURE): the fiber is GAUGE → droppable; 'missing parts' = the")
    print(f"  dropped pattern, content always whole; a hand-mismatch = wrong pattern, right content. Favored not")
    print(f"  privileged (F398); framework reads structure, hands the ND-chirality/dyspraxia question to the expert (F282). checks: {ok}")


if __name__ == "__main__":
    main()
