r"""R-RBS-LM-WIKITOMES (F746) — the PERSISTENT GENOME CODE PATH for the already-encoded big-wiki RBS-HDC instrument:
save it as a MULTI-TOME source = the Möbius / bi-axial-Möbius BOOKSHELF OF 14.

This does NOT re-encode wiki. The instrument is already built: `enwiki_kernel_256.json` (the Class-L co-occurrence
kernel over 300k streamed enwiki articles — edges + weights + vocab + spectrum, CC-BY-SA attested, F640). Per the
STANDING RULE F584: the kernel is the on-disk SSoT; the loop-bookshelf of tomes is LATENT in it and regenerated by
cheap HDC (tome routing = a free atan2 read-out of two eigenvector columns, F542 — no corpus re-read, no re-encode).

WHAT THIS ADDS: the genome persistence path that materializes that latent shelf as a saved MULTI-TOME genome:
  1. load the kernel; rebuild the 256-node weighted Laplacian (Class-L) and eigendecompose -> V  (cheap; deterministic
     from the stored edges; this is the "build once" — not a re-encode of the corpus).
  2. ROUTE each vocab word to one of NT=14 tomes by atan2(V[:,2], V[:,1]) (F542; the_one's 14 = local recall, F540).
  3. build the genome as 14 TOME-chromosomes (the bookshelf of 14) and genome_save it (the rc149 persistent path).
  4. load it back + navigate: route a word -> its tome; the Möbius SEAM = conjugation (Class-K sign-flip, F544/F594:
     negate the imaginary band, fix the real anchor) pairs each tome with its mirror; BI-AXIAL = 28 = 14 × 2 (the
     γ₅ / iω₇ chirality-dual, F158/F174) — every tome has its conjugate-mirror partner across the seam.

A LOOP bookshelf, not a flat circle (F544): the 14 tomes are cyclically adjacent AND conjugation-paired across the
half-twist — that is what makes it a Möbius. Persisted OUTSIDE the repo (the kernel + genome are big, attested data).

Run:  /tmp/srmech_rc149/venv/bin/python3 docs/srmech/rbs_lm_research/R-RBS-LM-WIKITOMES_...py
No abs() (sign-handling = Class-K via srmech); no CAD; research-subtree scaffold. srmech 0.7.5rc149.
"""
import json
from pathlib import Path
import srmech
from srmech.amsc import genome as g, hdc, laplacian as L
from srmech.amsc.format import sha256_raw, write_ndjson, read_ndjson, MPRRecord
from srmech import calculus

KERNEL = Path.home() / "corpora" / "wikipedia" / "enwiki_kernel_256.json"
OUTDIR = Path.home() / "corpora" / "wikipedia" / "wiki_tomes_genome"          # the persisted multi-tome source
SIDECAR = OUTDIR / "tomes.ndjson"                                             # MPR: each tome's renderable word list
DIM, NT = 64, 14                                                              # leaf dim; the bookshelf of 14 (the_one)
ONE = hdc.klein4_random(DIM, seed=0)
PI = 2.0 * calculus.atan2(1.0, 0.0)                                           # π = 2·atan2(1,0), srmech-native
def _leaf(t): return hdc.klein4_random(DIM, seed=int.from_bytes(sha256_raw(t.encode())[:4], "big"))


def route_to_tomes(kernel):
    """Cheap, no re-encode: rebuild the Class-L Laplacian from the stored edges, eigendecompose, route by atan2."""
    vocab = kernel["vocab"]
    n = len(vocab)
    edges = [tuple(e) for e in kernel["edge_list"]]
    weights = [float(w) for w in kernel["edge_weights"]]
    lap = L.dense_laplacian(n, edges, weights)                               # Class-L
    _evals, V = L.symmetric_eigendecompose(lap)                              # V columns = eigenvectors (modes)
    c1 = [V[i, 1] for i in range(n)]                                         # mode 1 (skip mode 0 = constant)
    c2 = [V[i, 2] for i in range(n)]                                         # mode 2
    tome_of, angle = [], []
    for i in range(n):
        a = calculus.atan2(c2[i], c1[i])                                    # [-π, π] — the latent circle (F542)
        angle.append(a)
        tome_of.append(int((a + PI) / (2.0 * PI) * NT) % NT)
    return vocab, tome_of, angle


def build_and_save():
    kernel = json.loads(KERNEL.read_text())
    vocab, tome_of, angle = route_to_tomes(kernel)
    tomes = {b: [] for b in range(NT)}
    for w, b in zip(vocab, tome_of):
        tomes[b].append(w)
    chromosomes, payload = [], []
    for b in range(NT):
        words = tomes[b]
        if not words:
            continue                                                        # an empty shelf slot (some of 14 fill)
        lab = f"tome_{b:02d}"
        chromosomes.append((lab, [(w, [_leaf(f"{lab}/{w}")]) for w in words]))
        payload.append((lab, b, words))
    strand = g.genome(chromosomes=chromosomes, the_one=ONE)
    OUTDIR.mkdir(parents=True, exist_ok=True)
    g.genome_save(strand, str(OUTDIR), ONE, [lab for lab, _ in chromosomes])  # THE PERSISTENT MULTI-TOME PATH
    # MPR sidecar: each tome's word list, carrying the kernel's CC-BY-SA attestation (no re-encode -> same provenance)
    att = kernel.get("attestation", {})
    rows = [MPRRecord(mpr_version="1.0",
                      data={"kernel": "wiki_tomes", "key": lab, "tome": b, "words": words},
                      data_schema_id="rbslm://schema/siona_wiki_tomes/v1",
                      attestation={"source_url": att.get("source_url", "https://dumps.wikimedia.org/enwiki/"),
                                   "license": att.get("license", "CC-BY-SA-4.0"),
                                   "retrieved_at": att.get("retrieved_at", "2026-06-06T00:00:00Z"),
                                   "response_sha256": sha256_raw((",".join(words)).encode()).hex(),
                                   "parser_version": f"srmech {srmech.__version__}",
                                   "derived_from": "enwiki_kernel_256.json (Class-L eigvec atan2 routing; no re-encode)"},
                      rendering={"name": f"wiki_tome:{lab}", "purpose": "wiki tome (Class-L spectral bookshelf)",
                                 "cite_as": "Wikipedia (enwiki dump), CC-BY-SA"})
            for lab, b, words in payload]
    write_ndjson(SIDECAR, rows)
    return len(vocab), len([1 for b in range(NT) if tomes[b]]), tome_of, angle, vocab


def mobius_mirror_tome(angle_of_word):
    """The Möbius seam: conjugation negates the imaginary band (F544/F594) -> angle -> -angle -> the mirror tome."""
    return int((-angle_of_word + PI) / (2.0 * PI) * NT) % NT


def main():
    print(f"=== R-RBS-LM-WIKITOMES — persist the encoded wiki instrument as the Möbius bi-axial bookshelf of {NT} "
          f"(srmech {srmech.__version__}) ===\n")
    n, filled, tome_of, angle, vocab = build_and_save()
    print(f"loaded the ENCODED instrument (enwiki_kernel_256.json): {n} vocab; NO re-encode — rebuilt V from stored "
          f"edges, routed by atan2(V[:,2],V[:,1]).")
    print(f"persisted MULTI-TOME genome -> {OUTDIR}  ({filled} of {NT} tomes filled)\n")

    cat = g.genome_catalog(str(OUTDIR), the_one=ONE)
    print("the persisted bookshelf (genome_catalog, reloaded from disk):")
    for c in cat["chromosomes"]:
        sample = [w for w, _ in g.genome_genes(str(OUTDIR), c["label"], the_one=ONE)][:6]
        print(f"    {c['label']}  ({c['leaf_count']:3d} words)  e.g. {', '.join(sample)}")

    print("\n--- navigate: route a word -> its tome, + its Möbius conjugate-mirror tome (the bi-axial 28=14×2 seam) ---")
    vi = {w: i for i, w in enumerate(vocab)}
    for w in ("water", "war", "science", "music", "god", "city"):
        if w in vi:
            b = tome_of[vi[w]]
            mb = mobius_mirror_tome(angle[vi[w]])
            print(f"    '{w}': tome_{b:02d}  ⟷ conjugate-mirror tome_{mb:02d}  (γ₅ half-twist seam)")
    print("\nVERDICT: the already-encoded wiki instrument is now a PERSISTED multi-tome genome — the bookshelf of 14.")
    print("  No re-encode (F584/F542): the kernel is the SSoT, the 14-tome loop-shelf is the latent atan2 routing,")
    print("  materialized + genome_save'd. Möbius seam = conjugation (Class-K, F544/F594); bi-axial = 28 = 14×2 (F158).")


if __name__ == "__main__":
    main()
