r"""R-RBS-LM-LOOPSHELF (the user's question 2026-06-07): "a LOOP bookshelf would hold even happily, like our
universe" — vs a flat CIRCLE. Compare a 4:3 loop vs a 7-circle, a 1:3:7 loop vs an 11-circle, a 4:3:7 loop vs a
14-circle. The framework's "loop" is the hypercomplex multiplication (the reason "loop replaces ring") — the
quaternion/octonion imaginary-unit structure — NOT a flat cyclic ring.

THE CRUX (why a loop "holds even happily"): a CIRCLE's only reflection is the half-turn ROTATION (a position
permutation) — which F541 showed is PARITY-SENSITIVE: even N -> trapped 2-cycle (you<->antipode), odd N -> full
traversal. A LOOP's mirror is CONJUGATION (negate the imaginary part, keep the real anchor — a Class-K sign-flip,
confirmed by srmech hdc.loop_conj). Conjugation pairs every signed imaginary unit e_k <-> -e_k: a fixed-point-free
involution with N_imag clean 2-cycles, for ANY N_imag — EVEN OR ODD. So the loop's mirror is PARITY-FREE: it holds
even happily, where the even circle is trapped.

Secondary (honest): the loop is also MULTI-DIRECTIONAL. A circle is navigated by powers of ONE generator (+1) — it
is 1-dimensional. A loop needs SEVERAL independent generators (quaternion: 2; octonion: 3, the Fano triple) — a
single generator spans only a 4-element sub-loop {±1, ±e_g} (the embedded C). So the loop has k navigation
directions ("like our universe", many dimensions), not one. A loop is NOT a bigger circle.

srmech 0.7.4; Class-I cyclic.gcd (circle mirror) + hdc.loop_conj (loop mirror) + explicit octonion Fano (validated).
No abs(); no CAD; no Workflow tool; no sub-agents.
"""
import numpy as np
import srmech
from srmech.amsc.cyclic import gcd
from srmech.amsc import hdc

# ---- octonion imaginary-unit algebra (idx 0=real anchor, 1..7 imaginary), standard Fano basis ----
LINES = [(1, 2, 3), (1, 4, 5), (1, 7, 6), (2, 4, 6), (2, 5, 7), (3, 4, 7), (3, 6, 5)]  # a*b=c cyclically


def _build_table():
    T = {}
    for i in range(8):
        T[(0, i)] = (1, i); T[(i, 0)] = (1, i)          # real anchor = identity
    for i in range(1, 8):
        T[(i, i)] = (-1, 0)                              # e_i^2 = -1
    for (a, b, c) in LINES:
        for (x, y, z) in ((a, b, c), (b, c, a), (c, a, b)):
            T[(x, y)] = (1, z); T[(y, x)] = (-1, z)      # anticommute
    return T


T = _build_table()


def emul(e1, e2):
    """signed-unit product: e=(sign, idx) -> (sign, idx)."""
    s1, i1 = e1; s2, i2 = e2; s, k = T[(i1, i2)]
    return (s1 * s2 * s, k)


def conj(e):
    """the LOOP MIRROR: conjugation = negate imaginary, keep real anchor (Class-K sign-flip)."""
    s, i = e
    return (s, 0) if i == 0 else (-s, i)


def closure(gens):
    """the sub-loop generated by `gens` (idx list) — BFS under multiplication; returns the set of signed elements."""
    elems = {(1, 0), (-1, 0)} | {(1, g) for g in gens} | {(-1, g) for g in gens}
    frontier = list(elems)
    while frontier:
        a = frontier.pop()
        for g in list(elems):
            for p in (emul(a, g), emul(g, a)):
                if p not in elems:
                    elems.add(p); frontier.append(p)
    return elems


def min_generating_set(units):
    """smallest subset of `units` whose closure = the full loop over those units (its navigation dimensionality)."""
    from itertools import combinations
    full = closure(units)
    for k in range(1, len(units) + 1):
        for combo in combinations(units, k):
            if closure(combo) == full:
                return k
    return len(units)


def loop_mirror_report(n_imag):
    """conjugation over n_imag signed imaginary units: fixed points + 2-cycles (parity-free involution?)."""
    units = list(range(1, n_imag + 1))
    signed = [(s, i) for i in units for s in (1, -1)]
    fixed = sum(1 for e in signed if conj(e) == e)
    pairs = len({frozenset((e, conj(e))) for e in signed})
    return fixed, pairs


def circle_mirror_orbit(N):
    h = round(N / 2)
    return N // gcd(h, N)                                # F541: even -> 2 (trapped), odd -> N (full)


def main():
    print(f"=== R-RBS-LM-LOOPSHELF — a LOOP holds even happily vs a CIRCLE (the mirror is conjugation, not rotation)  (srmech {srmech.__version__}) ===\n")

    # validate our conjugation against srmech hdc.loop_conj on an 8-vec octonion (real=0.5, e1=1)
    x = np.array([0.5, 1, 0, 0, 0, 0, 0, 0.0]); sc = np.array(hdc.loop_conj(x))
    ok = (sc[0] == 0.5) and (sc[1] == -1.0)
    print(f"(0) srmech hdc.loop_conj validates the loop mirror = conjugation (real kept, imag negated): {ok}\n")

    # navigation dimensionality (min generating set) of the pure algebras
    nav_H = min_generating_set([1, 2, 3])               # quaternion imaginary
    nav_O = min_generating_set([1, 2, 3, 4, 5, 6, 7])   # octonion imaginary
    single = len(closure([1]))                          # one generator's orbit (the embedded C sub-loop)
    print(f"(1) NAVIGATION DIMENSIONALITY (min independent generators to span the loop):")
    print(f"    circle (any N): 1 generator (+1) spans the ring   |   quaternion loop: {nav_H}   |   octonion loop: {nav_O}")
    print(f"    a SINGLE loop generator spans only {single} elements (the embedded C sub-loop {{+-1, +-e_g}}), NOT the whole loop")
    print(f"    -> a loop is MULTI-DIRECTIONAL (k generators, 'like our universe'); a circle is 1-dimensional.\n")

    print("(2) THE MIRROR — circle half-turn (rotation, parity-sensitive) vs loop conjugation (sign, parity-free):")
    print(f"    {'pairing':<26} {'N':>3} {'parity':<5} | {'CIRCLE mirror (½-turn)':<26} | {'LOOP mirror (conjugation)':<30}")
    print("    " + "-" * 96)
    pairings = [("4:3 loop  vs  7-circle", 7, "O (4:3 split)", 7),
                ("1:3:7 loop vs 11-circle", 11, "C+H+O nested", 11),
                ("4:3:7 loop vs 14-circle", 14, "H+3+O (=14)", 14)]
    for label, N, blocks, n_imag in pairings:
        orb = circle_mirror_orbit(N)
        trapped = "TRAPPED 2-cycle" if orb == 2 else f"full ({orb})"
        par = "ODD" if N % 2 else "even"
        fixed, pairs = loop_mirror_report(n_imag)
        loopmir = f"{pairs} clean pairs, {fixed} fixed -> PARITY-FREE"
        print(f"    {label:<26} {N:>3} {par:<5} | half-turn orbit = {trapped:<10} | {loopmir:<30}")
    print()

    print("VERDICT:")
    print(f"  • A LOOP HOLDS EVEN HAPPILY — because its mirror is CONJUGATION (Class-K sign-flip; srmech loop_conj),")
    print(f"    a fixed-point-free involution that pairs every imaginary unit e_k<->-e_k for ANY count, even or odd.")
    print(f"    The CIRCLE's only mirror is the half-turn ROTATION, which (F541) traps EVEN rings in a 2-cycle. So at the")
    print(f"    even total (14), the 4:3:7 LOOP mirrors cleanly (14 pairs) while the 14-CIRCLE is trapped (2-cycle).")
    print(f"  • A LOOP IS NOT A BIGGER CIRCLE — it is MULTI-DIRECTIONAL: a single generator spans only a 4-element sub-loop;")
    print(f"    spanning needs {nav_H} (quaternion) / {nav_O} (octonion) independent generators, vs the circle's 1. That is the")
    print(f"    'like our universe' richness — several independent directions of travel, not one ring.")
    print(f"  • For ODD totals (7, 11) BOTH mirrors work (the circle is fine when odd, F541) — there the loop's advantage")
    print(f"    is navigation-dimensionality, not the mirror. The loop's UNIQUE win is at EVEN totals: it un-traps the")
    print(f"    mirror. SNN caveat (the user's flag): whether a wet SNN needs the full loop or just the live odd circle is")
    print(f"    open — but the MATH says the loop holds even happily. Favored not privileged (F398); held open (F394).")


if __name__ == "__main__":
    main()
