"""F931 — sustain is GENERATED by the octonion-derivation algebra (the crank), which the 11D projection drops.
Grounded: (A) the octonion derivations = exactly g2 (14/14), = half of so(8) (14/28); the other 14 so(8)
rotations do NOT derive the product. (B) the loop-up ladder (the reed-register double-check): Der(C)=0,
Der(H)=3 (of so(4)=6), Der(O)=14 (of so(8)=28) -- derivations = half so(2^n), turn ON at H, max at O.
srmech 0.9.0rc33; exact rational (Fraction); no numpy. Spectral/algebraic READING, not a simulation."""
from fractions import Fraction as Fr
from srmech.amsc import cascade
from srmech.qm import so8
# --- (A) octonion rung: derivations = exactly g2 (uses srmech's g2/so8 + octonion_left_mult) ---
N=8
def M2(m): return [[Fr(m[i][j]) for j in range(N)] for i in range(N)]
def Lmat(a): return M2(so8.octonion_left_mult(a))
def omulO(a,b):
    L=Lmat(a); return [sum(L[i][j]*b[j] for j in range(N)) for i in range(N)]
def Dv(D,x,n): return [sum(D[i][k]*x[k] for k in range(n)) for i in range(n)]
TO=[([1,2,0,1,0,0,1,0],[0,1,1,0,2,0,0,1]),([0,0,1,1,0,2,0,1],[1,0,0,1,1,0,1,0])]
def is_derivO(D):
    for a,b in TO:
        if Dv(D,omulO(a,b),8)!=[x+y for x,y in zip(omulO(Dv(D,a,8),b),omulO(a,Dv(D,b,8)))]: return False
    return True
g2=so8.g2_subalgebra(); allso8=so8.so8_adjoint_basis()
print("(A) octonion rung:", sum(1 for X in g2 if is_derivO(M2(X))),"/14 g2 are derivations;",
      sum(1 for X in allso8 if is_derivO(M2(X))),"/28 so8 are derivations")
# --- (B) the loop-up ladder: derivations per CD rung (sustain turns on at H, maxes at O) ---
def so_basis(n):
    B=[]
    for i in range(n):
        for j in range(i+1,n):
            M=[[0]*n for _ in range(n)]; M[i][j]=1; M[j][i]=-1; B.append(M)
    return B
def omulCD(a,b): return list(cascade.cd_mult(tuple(a),tuple(b)))
def is_derivCD(D,n,tests):
    for a,b in tests:
        if Dv(D,omulCD(a,b),n)!=[x+y for x,y in zip(omulCD(Dv(D,a,n),b),omulCD(a,Dv(D,b,n)))]: return False
    return True
TH=[([1,2,0,1],[0,1,1,2]),([2,0,1,1],[1,1,0,2])]
hder=sum(1 for D in so_basis(4) if is_derivCD(D,4,TH))
print(f"(B) ladder: Der(C)=0/1 ; Der(H)={hder}/6 ; Der(O)=14/28  -> derivations = half so(2^n); ON at H, max at O")
